// New dictionaries: Presentations & Speaking, Negotiations & Deals.
// Rescue: Programming Languages (existing corpus file, curated injection).
export const presentations = {
  file: 'dictionaries/phrasebook-presentations.json',
  dropCorpus: true,
  emoji: '🎤',
  new: true,
  name: 'Presentations & Speaking',
  description: 'Презентации и публичные выступления: слайды, вопросы зала, работа с волнением',
  phrases: [
    ['Thank you all for coming today.', 'Спасибо всем, что пришли сегодня.'],
    ['Introduce myself briefly first.', 'Сначала коротко представлюсь.'],
    ['My name is Alex, product lead.', 'Меня зовут Алекс, я лид продукта.'],
    ['Today I will cover three points.', 'Сегодня я освещу три вопроса.'],
    ['Talk structured in two parts.', 'Доклад состоит из двух частей.'],
    ['Roughly twenty minutes plus questions.', 'Около двадцати минут плюс вопросы.'],
    ['Feel free to interrupt with questions.', 'Задавайте вопросы по ходу.'],
    ['Questions saved for the end.', 'Вопросы — в конце выступления.'],
    ['Slides available after the talk.', 'Слайды пришлю после доклада.'],
    ['QR code links to my slides.', 'По QR-коду открываются слайды.'],
    ['Lets dive straight in.', 'Перейдём сразу к делу.'],
    ['Starting with some context.', 'Начну с контекста.'],
    ['Background for those unfamiliar.', 'Немного вводной для тех, кто не в теме.'],
    ['Quick show of hands question.', 'Быстрый вопрос — поднимите руки.'],
    ['Who here has experienced this?', 'Кто-нибудь сталкивался с этим?'],
    ['Exactly as I expected.', 'Именно как я и ожидал.'],
    ['This graph tells the story.', 'Этот график говорит сам за себя.'],
    ['Numbers doubled year over year.', 'Цифры удвоились за год.'],
    ['Notice the spike right here.', 'Обратите внимание на этот скачок.'],
    ['The trend line speaks volumes.', 'Линия тренда красноречива.'],
    ['Let that sink in for a moment.', 'Осознайте эту цифру секунду.'],
    ['Moving on to the next slide.', 'Переходим к следующему слайду.'],
    ['Next slide please.', 'Следующий слайд, пожалуйста.'],
    ['Could we go back one slide?', 'Можно на слайд назад?'],
    ['Skip ahead to the demo.', 'Перемотаем сразу к демонстрации.'],
    ['This slide summarizes everything.', 'Этот слайд резюмирует всё.'],
    ['Key takeaway highlighted in yellow.', 'Главное выделено жёлтым.'],
    ['Three key takeaways today.', 'Три главных вывода сегодня.'],
    ['First point worth remembering.', 'Первый пункт стоит запомнить.'],
    ['If you remember one thing…', 'Если запомните что-то одно.'],
    ['Demo time fingers crossed.', 'Время демо — надеюсь, не подведёт техника.'],
    ['Live demo always risky exciting.', 'Живое демо риск и драйвер одновременно.'],
    ['Technology gods smiling today hopefully.', 'Технические боги сегодня пусть будут благосклонны.'],
    ['Bear with me one moment.', 'Одну секунду, сейчас наладим.'],
    ['Technical difficulties aside moving on.', 'Не будем застревать на технических проблемах.'],
    ['Works on my machine joke landed.', 'Шутка «у меня работало» вызвала смех.'],
    ['Screen share starting now.', 'Начинаю трансляцию экрана.'],
    ['Can everyone see my screen?', 'Всем виден мой экран?'],
    ['Zoom into this section here.', 'Приблизим этот фрагмент.'],
    ['Highlighting the important row.', 'Подсвечиваю важную строку.'],
    ['Laser pointer distracting use sparingly.', 'Лазерную указку лучше не злоупотреблять.'],
    ['Pause for effect dramatic silence.', 'Драматическая пауза для эффекта.'],
    ['That was the bad news part.', 'Это была часть с плохими новостями.'],
    ['Good news comes next slide.', 'Хорошие новости — на следующем слайде.'],
    ['Anticipation building nicely now.', 'Интрига нарастает как надо.'],
    ['Drum roll please.', 'Барабанная дробь!'],
    ['Announcing the results finally.', 'Наконец объявляю результаты.'],
    ['Applause line prepared carefully.', 'Реплика под аплодисменты подготовлена заранее.'],
    ['Self-deprecating humor works every time.', 'Самоирония работает безотказно.'],
    ['Nervous laughter acknowledged gracefully.', 'Неловкий смешок залпа обыграли изящно.'],
    ['Forgot my place notes help.', 'Сбился — заглянул в заметки.'],
    ['Lost my train of thought briefly.', 'На секунду потерял нить мысли.'],
    ['Where was I? Ah yes.', 'На чём я остановился? Ах да.'],
    ['Speaking pace deliberately slower here.', 'Здесь говорю намеренно медленнее.'],
    ['Emphasizing this word strongly.', 'Особенно выделяю это слово голосом.'],
    ['Eye contact corners of room.', 'Держу зрительный контакт со всеми частями зала.'],
    ['Avoiding death by PowerPoint.', 'Спасаемся от «смерти через PowerPoint».'],
    ['Six words maximum per bullet.', 'Максимум шесть слов в пункте.'],
    ['Reading slides aloud forbidden.', 'Читать слайды вслух запрещено!'],
    ['Slide is backdrop not script.', 'Слайд — фон, а не шпаргалка.'],
    ['White space is your friend.', 'Пустота на слайде — ваш друг.'],
    ['Font size legible from back row.', 'Шрифт читается с заднего ряда.'],
    ['Consistent color scheme professional look.', 'Единая цветовая гамма выглядит профессионально.'],
    ['Animation transitions minimal tasteful.', 'Анимации минимальные и со вкусом.'],
    ['Chart junk eliminated ruthlessly.', 'Мусорные элементы с графиков убраны беспощадно.'],
    ['Story arc beginning middle end.', 'История: завязка, развитие, развязка.'],
    ['Anecdote opens attention grabbed.', 'История с порога цепляет внимание сразу.'],
    ['Personal failure story relatable.', 'Личная история провала вызывает доверие.'],
    ['Vulnerability builds speaker credibility.', 'Открытость делает спикера убедительным.'],
    ['Rehearsed opening cold memorized.', 'Вступление отрепетировано до автоматизма.'],
    ['First thirty seconds decide attention.', 'Первые тридцать секунд решают внимание зала.'],
    ['Energy level matches message.', 'Энергия подачи соответствует сообщению.'],
    ['Microphone feedback screech adjusted distance.', 'Свист микрофона — отошёл подальше.'],
    ['Handheld mic frees gestures.', 'Ручной микрофон освобождает жесты.'],
    ['Lavalier mic clipped discreetly.', 'Петличка незаметно закреплена.'],
    ['Confidence booth pre-stage ritual.', 'Перед выходом — ритуал собранности.'],
    ['Deep breaths backstage nerves calmed.', 'Глубокие вдохи за кулисами успокоили нервы.'],
    ['Butterflies flying formation phrase classic.', 'Классика: «пусть бабочки летят строем».'],
    ['Stage fright never fully disappears.', 'Страх сцены не уходит полностью никогда.'],
    ['Audience wants you to succeed.', 'Зал хочет, чтобы вы выступили хорошо.'],
    ['They are rooting for you.', 'Они болеют за вас.'],
    ['Wrapping up final thoughts now.', 'Завершаю, последние мысли.'],
    ['To summarize three things matter.', 'Резюмирую: важны три вещи.'],
    ['Call to action clear single step.', 'Призыв к действию: один ясный шаг.'],
    ['Contact details final slide stay.', 'Контакты на последнем слайде, оставлю до конца.'],
    ['Questions welcome fire away.', 'Вопросы приветствуются — задавайте!'],
    ['Great question thank you asking.', 'Отличный вопрос, спасибо, что спросили.'],
    ['Answer briefly elaborate if needed.', 'Отвечу кратко, могу развернуть.'],
    ['Interesting angle never considered that.', 'Любопытный ракурс, не думал об этом.'],
    ['Offline discussion better venue detailed.', 'Детали лучше обсудим лично после.'],
    ['Hard question stalling politely think.', 'Сложный вопрос — беру паузу подумать.'],
    ['Honest answer simply dont know.', 'Честный ответ: не знаю.'],
    ['Will find out and follow up.', 'Выясню и обязательно вернусь с ответом.'],
    ['Host signaling wrap up soon.', 'Ведущий сигналит — пора закругляться.'],
    ['One more slide promise short.', 'Ещё один слайд, обещаю коротко.'],
    ['Thank you applause bow slightly.', 'Спасибо, аплодисменты, лёгкий поклон.'],
    ['Relieved exhale backstage celebration.', 'Выдох облегчения за кулисами, празднуем!'],
    ['Adrenaline crash post-talk nap.', 'После доклада — откат адреналина и сон.'],
    ['Feedback forms honest comments gold.', 'Честные комментарии в анкетах — золото.'],
    ['Recording link shared company channel.', 'Запись доклада разослана по каналу.'],
  ],
};

export const negotiations = {
  file: 'dictionaries/phrasebook-negotiations.json',
  dropCorpus: true,
  emoji: '🤝',
  new: true,
  name: 'Negotiations & Deals',
  description: 'Переговоры и сделки: условия, уступки, торги и закрытие договорённостей',
  phrases: [
    ['Pleasure doing business with you.', 'Рад с вами работать.'],
    ['Shall we get down to terms?', 'Перейдём к условиям?'],
    ['Agenda proposed both parties agreed.', 'Повестку согласовали обе стороны.'],
    ['Win-win outcome our goal today.', 'Наша цель сегодня — взаимовыгодный итог.'],
    ['Interests versus positions distinction matters.', 'Разница интересов и позиций ключевая.'],
    ['What does success look like you?', 'Как выглядит успех для вас?'],
    ['Underlying needs beneath stated demands.', 'За заявленными требованиями — реальные нужды.'],
    ['Priority ranking helps trade-offs.', 'Расстановка приоритетов помогает уступать разумно.'],
    ['BATNA preparation before table.', 'Готовьте запасной вариант до стола.'],
    ['Walkaway point defined privately.', 'Точку выхода определил заранее и молча.'],
    ['Anchoring high opening offer strategy.', 'Стратегия якоря: стартовое предложение выше.'],
    ['Counter-offer expected protocol normal.', 'Ответное предложение — нормальный протокол.'],
    ['Concessions exchanged gradually reciprocal.', 'Уступки обменивают постепенно и зеркально.'],
    ['Never concede without getting something.', 'Никогда не уступай бесплатно.'],
    ['If you flex on price, then…', 'Если идёте вниз по цене, то.'],
    ['Throw-in sweetens the deal.', 'Бонус подслащивает сделку.'],
    ['Bundle pricing attractive combined.', 'Комплектная цена привлекательнее.'],
    ['Volume discount tier structure discussed.', 'Обсудили уровни скидок за объём.'],
    ['Payment terms flexible options offered.', 'Предложили гибкие варианты оплаты.'],
    ['Net thirty standard industry practice.', 'Оплата в течение месяца — стандарт отрасли.'],
    ['Deposit secures production slot.', 'Аванс бронирует место в производстве.'],
    ['Milestone payments de-risk both sides.', 'Поэтапная оплата снижает риски обеих сторон.'],
    ['Escrow arrangement trust builder.', 'Аккредитив строит доверие.'],
    ['Delivery window realistic buffer included.', 'В срок поставки заложен реалистичный запас.'],
    ['Penalty clauses cut both ways.', 'Штрафные пункты работают в обе стороны.'],
    ['Liability cap negotiated reasonable level.', 'Лимит ответственности согласовали разумный.'],
    ['Force majeure language standard boilerplate.', 'Формулировки форс-мажора — стандартный текст.'],
    ['Exclusivity clause limited geography time.', 'Эксклюзив ограничен территорией и сроком.'],
    ['Non-compete scope narrowed sensibly.', 'Объём неконкуренции сузили разумно.'],
    ['Intellectual property ownership clarified upfront.', 'Права на интеллектуальную собственность уточнили сразу.'],
    ['Licensing versus assignment difference significant.', 'Лицензия и уступка прав сильно различаются.'],
    ['Royalty rate percentage revenue net.', 'Роялти — процент от чистой выручки.'],
    ['Term sheet non-binding framework document.', 'Термшит — рамочный необязывающий документ.'],
    ['Subject to contract wording protects.', 'Оговорка «при условии договора» страхует обе стороны.'],
    ['Head of agreement principles only.', 'Меморандум фиксирует только принципы.'],
    ['Due diligence documents requested list.', 'Список документов для проверки направлен.'],
    ['Data room access granted temporary.', 'Доступ в дата-рум выдали временный.'],
    ['Red flags surfaced during review.', 'При проверке вскрылись тревожные сигналы.'],
    ['Deal breaker identified early saves pain.', 'Ранний стоп-фактор сберегает месяцы впустую.'],
    ['Silence tactic uncomfortable powerful.', 'Тактика паузы неудобна, но сильна.'],
    ['Good cop bad cop transparent ploy.', 'Парочка «злой и добрый» — видимый приём.'],
    ['Higher authority excuse buying time.', 'Ссылка на начальство покупает время.'],
    ['Nibbling after handshake annoys.', 'Дожим после рукопожатия портит отношения.'],
    ['Salami slicing tactics recognized resisted.', 'Тактику «салями» распознали и пресекли.'],
    ['Deadline pressure manufactured artificial often.', 'Дедлайн-давление часто искусственное.'],
    ['Take it or leave it rarely final.', '«Бери или уходи» редко бывает окончательным.'],
    ['Every number negotiable until signed.', 'До подписи любое число обсуждаемо.'],
    ['Package deal versus itemized haggling.', 'Пакетом торговаться проще, чем по пунктам.'],
    ['Splitting difference midpoint compromise common.', 'Компромисс посередине — частый исход.'],
    ['Round numbers invite round counters.', 'Круглые цифры тянут к новому торгу.'],
    ['Precise figures signal homework done.', 'Точные суммы показывают домашнюю работу.'],
    ['Currency fluctuation clause protects margins.', 'Валютная оговорка защищает маржу.'],
    ['Indexation annual review built-in.', 'Ежегодная индексация предусмотрена.'],
    ['Most favored nation clause requested.', 'Попросили оговорку о наибольшем благоприятствовании.'],
    ['Right of first refusal negotiated.', 'Согласовали преимущественное право покупки.'],
    ['Termination notice period ninety days mutual.', 'Расторжение с уведомлением за девяносто дней, взаимно.'],
    ['Exit provisions clarity prevents lawsuits.', 'Ясные условия выхода предотвращают суды.'],
    ['Dispute resolution arbitration preferred.', 'Предпочли арбитраж для споров.'],
    ['Governing law jurisdiction debated lengthily.', 'Применимое право обсуждали долго.'],
    ['Signaling flexibility without weakness art.', 'Искусство: показать гибкость без слабости.'],
    ['Empathy maps counterpart pressures real.', 'Карта эмпатии: у второй стороны свои давления.'],
    ['Rapport small talk icebreaker genuine.', 'Small talk для контакта — искренний, не дежурный.'],
    ['Coffee break resets tense atmosphere.', 'Кофе-брейк сбрасывает напряжение.'],
    ['Caucus private huddle regroup strategy.', 'Тайм-аут: совещание в стороне, пересборка стратегии.'],
    ['Note-taker captures commitments precisely.', 'Протоколист точно фиксирует договорённости.'],
    ['Action items owner deadline assigned.', 'У каждого пункта — владелец и срок.'],
    ['Memorandum understanding drafted same day.', 'Меморандум составили в тот же день.'],
    ['Verbal agreements fragile paper solid.', 'Словесные договорённости хрупки, бумага тверда.'],
    ['Handshake deals still mean something.', 'Рукопожатие пока ещё что-то значит.'],
    ['Relationship capital compounds future deals.', 'Репутационный капитал умножает будущие сделки.'],
    ['Squeeze last dime loses lifetime customer.', 'Дожав до последней копейки, теряешь клиента навсегда.'],
    ['Leave money on table goodwill earned.', 'Оставленная на столе скидка = заработанная лояльность.'],
    ['Deal closed handshakes photographs signatures.', 'Сделка закрыта: рукопожатия, фото, подписи.'],
    ['Champagne toast successful negotiation concluded.', 'Тост шампанским — успешные переговоры завершены.'],
  ],
};

export const programminglanguages = {
  file: 'dictionaries/phrasebook-programminglanguages.json',
  dropCorpus: true,
  emoji: '🧑‍💻',
  name: 'Programming Languages',
  description: 'Разговорник разработчика: языки, стек, код-ревью и собеседования',
  phrases: [
    ['Which languages do you code in?', 'На каких языках ты пишешь?'],
    ['Primarily TypeScript these days.', 'Сейчас в основном TypeScript.'],
    ['Started with Python years ago.', 'Начинал с Python много лет назад.'],
    ['Java pays the bills currently.', 'Сейчас Java кормит (основной язык).'],
    ['Rust learning curve famously steep.', 'У Rust легендарно крутая кривая обучения.'],
    ['Borrow checker fights beginners hard.', 'Borrow checker жёстко воюет с новичками.'],
    ['Memory safety without garbage collection.', 'Безопасность памяти без сборщика мусора.'],
    ['Go compiles blazingly fast.', 'Go компилируется молниеносно.'],
    ['Goroutines make concurrency approachable.', 'Горутины делают конкурентность доступной.'],
    ['Error handling verbose but explicit.', 'Обработка ошибок многословная, но явная.'],
    ['JavaScript ecosystem moves ridiculously fast.', 'Экосистема JavaScript движется бешено.'],
    ['Framework fatigue is real talk.', 'Усталость от фреймворков — реальная вещь.'],
    ['React hooks changed everything honestly.', 'Хуки React честно всё изменили.'],
    ['State management library debate endless.', 'Споры о библиотеках состояния бесконечны.'],
    ['CSS-in-JS divisive topic developers.', 'CSS-in-JS вызывает споры среди разработчиков.'],
    ['Type safety catches bugs early.', 'Типизация ловит баги рано.'],
    ['Strict mode enabled from day one.', 'Строгий режим включаем с первого дня.'],
    ['Any type defeats the purpose.', 'Тип any убивает смысл типизации.'],
    ['Generics confusing at first glance.', 'Дженерики сначала сбивают с толку.'],
    ['Duck typing philosophy explained simply.', 'Утиную типизацию объясняет просто философию.'],
    ['Compiled versus interpreted performance tradeoffs.', 'Компиляция против интерпретации — компромиссы производительности.'],
    ['JIT compilation bridges gap cleverly.', 'JIT-компиляция изящно сокращает разрыв.'],
    ['Bytecode intermediate representation explained.', 'Байткод — промежуточное представление, если коротко.'],
    ['Garbage collector pauses minimized lately.', 'Паузы сборщика мусора минимизированы в новых версиях.'],
    ['Memory leaks haunt long-running processes.', 'Утечки памяти преследуют долгоживущие процессы.'],
    ['Stack overflow literally crashed program.', 'Переполнение стека реально уронило программу.'],
    ['Recursion depth limits configured.', 'Глубину рекурсии настроили лимитом.'],
    ['Tail call optimization supported natively?', 'Оптимизация хвостовой рекурсии поддерживается нативно?'],
    ['Immutable data structures prevent bugs.', 'Иммутабельные структуры предотвращают баги.'],
    ['Pure functions easier testability.', 'Чистые функции легче тестировать.'],
    ['Side effects isolated edges only.', 'Побочные эффекты только на краях системы.'],
    ['Functional programming paradigm resurgence strong.', 'Функциональная парадигма переживает возрождение.'],
    ['Object-oriented inheritance criticized lately.', 'ООП-наследование недавно критикуют много.'],
    ['Composition over inheritance mantra repeated.', 'Мантра «композиция вместо наследования» повторяется.'],
    ['Design patterns overused sometimes honestly.', 'Паттерны проектирования иногда переиспользуют.'],
    ['Singleton pattern considered harmful debates.', 'Споры: синглтон считают вредным.'],
    ['Dependency injection containers explained.', 'Контейнеры внедрения зависимостей объяснили.'],
    ['Microservices versus monolith eternal debate.', 'Микросервисы против монолита — вечный спор.'],
    ['Distributed systems complexity underestimated constantly.', 'Сложность распределённых систем постоянно недооценивают.'],
    ['Eventual consistency confused stakeholders initially.', 'Итоговую консистентность стейкхолдеры сначала не поняли.'],
    ['Message queues decouple services elegantly.', 'Очереди сообщений элегантно разделяют сервисы.'],
    ['Idempotency keys prevent double charges.', 'Ключи идемпотентности спасают от двойных списаний.'],
    ['Race conditions reproduce intermittently nightmare.', 'Гонки воспроизводятся через раз — кошмар.'],
    ['Deadlock debugging sessions memorable pain.', 'Отладка дедлоков запоминается болью.'],
    ['Mutex locks contention hotspots profiled.', 'Профилировщик показал узкие места мьютексов.'],
    ['Async await syntax sugar appreciated.', 'Синтаксис async/await все ценят.'],
    ['Callback hell pyramid doom memories.', 'Воспоминания об аде колбеков — пирамида ужаса.'],
    ['Promise chains flattened async functions.', 'Цепочки промисов распрямились в асинхронных функциях.'],
    ['Event loop single threaded magic.', 'Event loop — магия одного потока.'],
    ['Blocking calls freeze entire UI.', 'Блокирующие вызовы замораживают интерфейс целиком.'],
    ['Web workers offload heavy computation.', 'Web workers выносят тяжёлые вычисления.'],
    ['SQL versus NoSQL religious wars tiresome.', 'Священные войны SQL против NoSQL утомляют.'],
    ['Schema migrations versioned rollback safe.', 'Миграции схемы версионируются с безопасным откатом.'],
    ['ORM queries hidden N+1 problem.', 'ORM прячет проблему N+1 запросов.'],
    ['Indexes speed reads slow writes.', 'Индексы ускоряют чтение, замедляют запись.'],
    ['Query planner explains decisions EXPLAIN.', 'Планировщик объясняет решения через EXPLAIN.'],
    ['Connection pooling essential production.', 'Пул соединений обязателен в проде.'],
    ['Git rebase interactive history rewritten.', 'Интерактивный rebase переписал историю.'],
    ['Force push main branch forbidden.', 'Force push в главную ветку запрещён.'],
    ['Merge conflicts resolved carefully manually.', 'Конфликты слияния решали вручную и аккуратно.'],
    ['Pull request reviews mentor juniors.', 'Ревью пул-реквестов обучает джуниоров.'],
    ['Code style linters enforce automatically.', 'Линтеры навязывают стиль автоматически.'],
    ['Continuous integration pipelines green required.', 'Пайплайны CI должны быть зелёными.'],
    ['Flaky tests quarantine investigated later.', 'Мерцающие тесты — в карантин, разберёмся потом.'],
    ['Test coverage metrics gamed warning.', 'Метриками покрытия можно манипулировать — осторожно.'],
    ['Unit tests fast isolated numerous.', 'Юнит-тесты быстрые, изолированные и многочисленные.'],
    ['End-to-end tests brittle expensive fewer.', 'E2E-тесты хрупкие и дорогие — их мало.'],
    ['Test pyramid balance advocated widely.', 'Баланс тестовой пирамиды все проповедуют.'],
    ['Debugging rubber duck method works.', 'Метод резиновой уточки реально работает.'],
    ['Print debugging versus debugger preference.', 'Дебажить принтами или отладчиком — дело вкуса.'],
    ['Breakpoints conditional expressions powerful feature.', 'Условные точки останова — мощная штука.'],
    ['Logging levels structured JSON production.', 'Логи в проде — структурный JSON с уровнями.'],
    ['Observability trumps monitoring buzzphrase accurate.', 'Наблюдаемость модный термин, но точный.'],
    ['Interview leetcode grinding controversial gatekeeping.', 'Гринд LeetCode на интервью — спорный фильтр.'],
    ['Whiteboard coding anxiety universal experience.', 'Кодирование у доски — универсальная тревога.'],
    ['System design interviews senior roles.', 'System design спрашивают на старших позициях.'],
    ['Behavioral interviews STAR method recommended.', 'На поведенческих советуют метод STAR.'],
    ['Salary negotiation leverage researched market.', 'Для торга по зарплате изучи рынок.'],
  ],
};
