// Batch 1: hotel & short-term rental deep fills.
export const topups = {
  hotel: [
    ['Reservation under Ivanov, two adults.', 'Бронь на фамилию Иванов, двое взрослых.'],
    ['Confirmation email on my phone.', 'Подтверждение брони в моём телефоне.'],
    ['Is the room ready early?', 'Номер готов раньше срока?'],
    ['We only need it for one night.', 'Нам нужен номер всего на одну ночь.'],
    ['Two adults and one child.', 'Двое взрослых и один ребёнок.'],
    ['Crib ready before we arrive?', 'Кроватка будет готова к нашему приезду?'],
    ['Rollaway bed for the third guest.', 'Дополнительную раскладную кровать для третьего гостя.'],
    ['Accessible room with roll-in shower.', 'Номер для маломобильных с душевой без бортика.'],
    ['Ground floor preferred for luggage.', 'Предпочитаем первый этаж из-за чемоданов.'],
    ['Do windows open or is it sealed?', 'Окна открываются или наглухо запечатаны?'],
    ['Blackout curtains essential for me.', 'Для меня важны светонепроницаемые шторы.'],
    ['Twin beds instead of a double.', 'Две отдельные кровати вместо одной двойной.'],
    ['Honeymoon suite surprise for my wife.', 'Сьют для молодожёнов — сюрприз для жены.'],
    ['Champagne delivered at eight, discreetly.', 'Шампанское доставьте в восемь, незаметно.'],
    ['Flowers in the room for her birthday.', 'Цветы в номер ко дню её рождения.'],
    ['Handwritten welcome note appreciated.', 'Рукописная приветственная открытка — приятно.'],
    ['Turn-down service in the evening?', 'Вечерняя подготовка номера ко сну есть?'],
    ['Turndown with chocolates, lovely touch.', 'Вечерняя уборка с шоколадом — милая деталь.'],
    ['Slippers and bathrobe sizes?', 'Есть тапочки и халаты по размерам?'],
    ['Extra blanket in the wardrobe found.', 'Нашли дополнительное одеяло в шкафу.'],
    ['Umbrella stand by the entrance.', 'Подставка для зонтов у входа.'],
    ['Complimentary water bottles daily.', 'Бесплатные бутылки воды каждый день.'],
    ['Fruit plate replenished nightly.', 'Фруктовую тарелку пополняют каждый вечер.'],
    ['Minibar prices listed clearly.', 'Цены мини-бара указаны понятно.'],
    ['Kettle plus tea selection provided.', 'Чайник и набор чаёв прилагаются.'],
    ['Instant noodles in the drawer, handy.', 'Лапша быстрого приготовления в ящике — удобно.'],
    ['Coffee machine capsules complimentary.', 'Капсулы для кофемашины бесплатные.'],
    ['Room service menu under the door.', 'Меню обслуживания номеров подсунули под дверь.'],
    ['Breakfast in bed possible?', 'Можно завтрак в постель?'],
    ['Continental breakfast until ten.', 'Континентальный завтрак до десяти.'],
    ['Omelette station at breakfast.', 'Станция омлетов на завтраке.'],
    ['Freshly squeezed juice extra charge.', 'Свежевыжатый сок за отдельную плату.'],
    ['Gluten-free bread on request.', 'Безглютеновый хлеб по запросу.'],
    ['Early breakfast box for flights.', 'Сухой паёк на завтрак для ранних рейсов.'],
    ['Grab-and-go bag ordered tonight.', 'Заказал пакет с завтраком навынос на завтра.'],
    ['Lunch available by the pool?', 'Обед подают у бассейна?'],
    ['Pool towels exchanged daily.', 'Полотенца для бассейна меняют ежедневно.'],
    ['Pool opens at what time?', 'Во сколько открывается бассейн?'],
    ['Kids pool heated year-round.', 'Детский бассейн подогревается круглый год.'],
    ['Swim-up bar looks inviting.', 'Бар у воды так и манит.'],
    ['Sunbeds reserved with towels?', 'Шезлонги занимают полотенцами?'],
    ['Gym towel station stocked.', 'Полотенца в спортзале всегда есть.'],
    ['Personal training session booked.', 'Записался на персональную тренировку.'],
    ['Could you move my spa appointment to four?', 'Перенесите мою спа-процедуру на четыре, пожалуйста.'],
    ['Massage therapist highly recommended.', 'Массажиста очень рекомендуют.'],
    ['Sauna rules posted inside.', 'Правила сауны висят внутри.'],
    ['The hot tub jets are not working.', 'Струи в джакузи не работают.'],
    ['Steam room temperature perfect.', 'Температура в парной идеальная.'],
    ['Beauty salon appointments downstairs.', 'Салон красоты записывается внизу.'],
    ['Hairdryer too weak, another please.', 'Фен слабоват, дайте другой, пожалуйста.'],
    ['Laundry service same-day?', 'Химчистка обслуживает в тот же день?'],
    ['Shirts pressed and hung.', 'Рубашки погладили и повесили.'],
    ['Dry cleaning list attached.', 'Список вещей в химчистку прилагается.'],
    ['Stain removal worked miracles.', 'Выведение пятен сработало чудом.'],
    ['Sewing kit in the drawer.', 'Набор для шитья в ящике.'],
    ['Shoe shine service complimentary.', 'Чистка обуви бесплатно.'],
    ['Business center computers free.', 'Компьютеры бизнес-центра бесплатные.'],
    ['Meeting room projector booked.', 'Проектор в переговорной забронирован.'],
    ['Flip chart markers restocked.', 'Маркеры для флипчарта пополнили.'],
    ['Coffee break catering arranged.', 'Кофе-брейк организован.'],
    ['Conference package includes lunch.', 'Конференц-пакет включает обед.'],
    ['Delegate badges printed overnight.', 'Бейджи делегатов напечатали за ночь.'],
    ['Airport pickup confirmed for six.', 'Трансфер из аэропорта подтверждён на шесть.'],
    ['Driver holding a name sign.', 'Водитель держит табличку с именем.'],
    ['Shuttle runs every thirty minutes.', 'Шаттл ходит каждые тридцать минут.'],
    ['Last shuttle at eleven p.m.', 'Последний шаттл в одиннадцать вечера.'],
    ['Taxi rank two minutes walk.', 'Стоянка такси в двух минутах пешком.'],
    ['City tour desk in lobby.', 'Стойка экскурсий в лобби.'],
    ['Booked the old town walking tour.', 'Забронировал пешую экскурсию по старому городу.'],
    ['Tickets are cheaper sold here.', 'Билеты здесь продают дешевле.'],
    ['Beware of unofficial guides outside.', 'Осторожно: снаружи неофициальные гиды.'],
    ['Concierge reserved museum entries.', 'Консьерж забронировал вход в музеи.'],
    ['Skip-the-line tickets worth it.', 'Билеты без очереди того стоят.'],
    ['Restaurant fully booked, but the concierge fixed it.', 'Ресторан переполнен, но консьерж всё устроил.'],
    ['Late-night pharmacy directions given.', 'Подсказали дорогу к ночной аптеке.'],
    ['Doctor called to the room quickly.', 'Врача быстро вызвали прямо в номер.'],
    ['Housekeeping skipped today, thanks.', 'Уборку сегодня пропустите, спасибо.'],
    ['Do not disturb sign left up.', 'Табличку «не беспокоить» не снял.'],
    ['Towels on floor mean replace.', 'Полотенца на полу означают «заменить».'],
    ['Eco program asks to reuse towels.', 'В экологичной программе просят использовать полотенца повторно.'],
    ['Lights keycard slot saves energy.', 'Свет включается картой-ключом (экономия).'],
    ['Balcony furniture wiped down.', 'Мебель на балконе протёрли.'],
    ['View of rooftops charming at sunset.', 'Вид на крыши очарователен на закате.'],
    ['Construction noise next door!', 'Соседняя стройка шумит!'],
    ['Earplugs offered at reception.', 'На ресепшене предложили беруши.'],
    ['Room change processed swiftly.', 'Переселение оформили оперативно.'],
    ['Apologized with fruit basket upgrade.', 'Извинились фруктовой корзиной и апгрейдом.'],
    ['Air freshener scent too strong.', 'Ароматизатор слишком душный.'],
    ['Reported the carpet stains right away.', 'Сразу сообщили о пятнах на ковре.'],
    ['Charged accidentally for minibar water.', 'Случайно списали воду из мини-бара.'],
    ['Charge reversed without fuss.', 'Списание отменили без вопросов.'],
    ['Final bill itemized clearly.', 'Итоговый счёт детализирован понятно.'],
    ['City tax added per person.', 'Городской сбор добавили за каждого человека.'],
    ['Paying the rate difference in cash.', 'Разницу в цене оплачу наличными.'],
    ['Card preauthorization released later.', 'Блокировка по карте спадает позже.'],
    ['Invoice emailed to accounting.', 'Счёт отправили почтой в бухгалтерию.'],
    ['Loyalty points credited post-stay.', 'Бонусные баллы начислят после выезда.'],
    ['Member rate matched online price.', 'Членскую цену сравняли с онлайн-тарифом.'],
    ['Elite status perks honored.', 'Привилегии элитного статуса учли.'],
    ['Late checkout granted till two.', 'Поздний выезд разрешили до двух.'],
    ['Half day rate for evening flight.', 'Полдневный тариф под вечерний рейс.'],
    ['Feedback form filled honestly.', 'Анкету заполнил честно.'],
    ['Would stay again without hesitation.', 'Остался бы снова без раздумий.'],
    ['Already rebooked for next summer!', 'Уже забронировал на следующее лето!'],
  ],

  airbnb: [
    ['Host greeted us personally at arrival.', 'Хозяин лично встретил нас по приезде.'],
    ['Local tips taped to the fridge.', 'Местные советы приклеены к холодильнику.'],
    ['Welcome basket with wine waiting.', 'Нас ждала корзина с вином.'],
    ['Neighborhood guidebook updated recently.', 'Гид по району недавно обновляли.'],
    ['Metro map pinned above the desk.', 'Карта метро приколота над столом.'],
    ['Grocery store two blocks away.', 'Продуктовый магазин в двух кварталах.'],
    ['Bakery downstairs sells out early.', 'Пекарня внизу распродаётся рано.'],
    ['The best coffee spot is around the block.', 'Лучшая кофейня — за углом.'],
    ['Farmers market on Saturdays nearby.', 'Фермерский рынок по субботам рядом.'],
    ['Laundromat coin-operated downstairs.', 'Прачечная самообслуживания внизу, монеты.'],
    ['Drying rack on the balcony.', 'Сушилка для белья на балконе.'],
    ['Iron hidden in bedroom closet.', 'Утюг спрятан в шкафу спальни.'],
    ['Wi-Fi router restarted remotely by host.', 'Хозяин удалённо перезагрузил роутер.'],
    ['Backup hotspot code provided.', 'Дали код резервной точки доступа.'],
    ['Streaming accounts were signed out before us.', 'Из стриминговых аккаунтов вышли до нашего приезда.'],
    ['Smart TV needs host account.', 'Смарт-ТВ требует аккаунт хозяина.'],
    ['Bluetooth speaker paired instantly.', 'Колонка подключилась мгновенно.'],
    ['Universal adapters in kitchen drawer.', 'Переходники для розеток в кухонном ящике.'],
    ['Blackout blinds in both bedrooms.', 'Блэкаут-шторы в обеих спальнях.'],
    ['Mattress firmer than expected.', 'Матрас жёстче, чем ожидали.'],
    ['Pillows swapped for softer ones.', 'Подушки поменяли на помягче.'],
    ['Duvet cover freshly laundered.', 'Пододеяльник свежевыстиранный.'],
    ['Heater timer set for mornings.', 'Таймер обогревателя настроен на утро.'],
    ['Hot water takes a minute to arrive.', 'Горячая вода идёт с минутной задержкой.'],
    ['Water pressure strong upstairs.', 'Напор воды наверху сильный.'],
    ['Drain gurgles but works fine.', 'Слив булькает, но работает исправно.'],
    ['Lightbulb replaced within an hour.', 'Лампочку заменили в течение часа.'],
    ['Smoke detector battery chirping.', 'Пищит батарейка датчика дыма.'],
    ['Fire extinguisher under the sink.', 'Огнетушитель под раковиной.'],
    ['First aid kit bathroom shelf.', 'Аптечка на полке в ванной.'],
    ['Emergency numbers laminated by phone.', 'Экстренные номера заламинированы у телефона.'],
    ['Building intercom code shared.', 'Код домофона прислали заранее.'],
    ['Elevator occasionally out of service.', 'Лифт иногда не работает.'],
    ['Fifth floor walk-up warning noted.', 'Предупреждение: пятый этаж без лифта.'],
    ['Dragging luggage up the stairs is painful.', 'Тащить чемоданы по лестнице — мучение.'],
    ['Host carried the heaviest suitcase up.', 'Хозяин занёс самый тяжёлый чемодан наверх.'],
    ['Street parking permit included.', 'Разрешение на уличную парковку включено.'],
    ['Garage remote on the keyring.', 'Пульт гаража на связке ключей.'],
    ['Charging spot for electric car.', 'Есть место зарядки электромобиля.'],
    ['Bike storage in the courtyard shed.', 'Велосипеды хранят в сарае во дворе.'],
    ['Two bikes lent free of charge.', 'Два велосипеда дали бесплатно.'],
    ['Helmet straps adjustable, safe.', 'Ремни шлемов регулируются, безопасно.'],
    ['Rooftop terrace view stunning.', 'Вид с крыши-террасы потрясающий.'],
    ['Sunset photos from the balcony.', 'Фото заката сделали с балкона.'],
    ['A neighbor waters the plants weekly.', 'Сосед поливает растения раз в неделю.'],
    ['There is a cat living downstairs.', 'Этажом ниже живёт кот.'],
    ['Allergic guests warned beforehand.', 'Аллергикам предупреждают заранее.'],
    ['Checkout instructions followed exactly.', 'Инструкции выезда выполнили точно.'],
    ['Left a thank-you note behind.', 'Оставили благодарственную записку.'],
    ['Review posted with five stars.', 'Отставили отзыв на пять звёзд.'],
    ['Photos attached to honest review.', 'К честному отзыву приложили фото.'],
    ['Rebooking same place next trip.', 'Забронировали то же место на следующую поездку.'],
    ['Shared listing link with friends.', 'Скинули друзьям ссылку на объявление.'],
    ['Host replied thanking warmly.', 'Хозяин тепло поблагодарил в ответ.'],
    ['Discount code for returning guests.', 'Код скидки для вернувшихся гостей.'],
    ['Referral bonus applied automatically.', 'Реферальный бонус применился автоматически.'],
  ],
};
