// Curated real-speech phrases: tech support, social media chat, dating.
export const digital = {
  techsupport: {
    file: 'dictionaries/phrasebook-technologyinternet.json',
    emoji: '💻',
    description: 'Техника и интернет: проблемы, поддержка, настройка',
    phrases: [
      ['My computer won’t turn on.', 'Мой компьютер не включается.'],
      ['The screen went black.', 'Экран погас (почернел).'],
      ['It keeps freezing on me.', 'Он постоянно зависает.'],
      ['The app keeps crashing.', 'Приложение постоянно вылетает.'],
      ['My laptop is running so slowly.', 'Мой ноутбук так медленно работает.'],
      ['I think I have a virus.', 'Кажется, у меня вирус.'],
      ['A weird pop-up appeared.', 'Появилось странное всплывающее окно.'],
      ['Have you tried restarting it?', 'Вы пробовали перезагрузить его?'],
      ['Try turning it off and on again.', 'Попробуйте выключить и снова включить.'],
      ['Did you check the cable?', 'Ты проверил кабель?'],
      ['Check if it’s plugged in properly.', 'Проверь, плотно ли он подключён.'],
      ['Update the app to the latest version.', 'Обновите приложение до последней версии.'],
      ['Clear your browser cache.', 'Очистите кеш браузера.'],
      ['Restart your router, that usually helps.', 'Перезапустите роутер, это обычно помогает.'],
      ['The Wi-Fi keeps dropping.', 'Wi-Fi постоянно пропадает.'],
      ['There’s no internet connection.', 'Нет подключения к интернету.'],
      ['The internet is down again.', 'Интернет опять не работает.'],
      ['What’s the Wi-Fi password here?', 'Какой здесь пароль от Wi-Fi?'],
      ['Could you share the hotspot?', 'Раздай точку доступа, пожалуйста.'],
      ['I’m out of mobile data.', 'У меня закончился мобильный интернет.'],
      ['My phone fell in water!', 'Мой телефон упал в воду!'],
      ['Put it in rice, quick!', 'Засыпь его рисом, быстро!'],
      ['The battery drains too fast.', 'Батарея слишком быстро садится.'],
      ['My storage is full.', 'Моя память заполнена.'],
      ['Delete some old photos to free up space.', 'Удали старые фото, чтобы освободить место.'],
      ['Back up everything to the cloud.', 'Скопируйте всё в облачное хранилище.'],
      ['I lost all my files!', 'Я потерял все свои файлы!'],
      ['Do you have a backup?', 'Есть резервная копия?'],
      ['I forgot my password.', 'Я забыл свой пароль.'],
      ['Reset my password, please.', 'Сбросьте мой пароль, пожалуйста.'],
      ['I got locked out of my account.', 'Меня заблокировали из моего аккаунта.'],
      ['Someone hacked my account!', 'Мой аккаунт взломали!'],
      ['Change your password immediately.', 'Немедленно смените пароль.'],
      ['Enable two-factor authentication.', 'Включите двухфакторную аутентификацию.'],
      ['Never share your PIN with anyone.', 'Никогда никому не сообщайте свой PIN-код.'],
      ['That email is a phishing scam.', 'Это письмо — фишинговая мошенническая рассылка.'],
      ['Don’t click on suspicious links.', 'Не нажимайте на подозрительные ссылки.'],
      ['Download the installer from the official site only.', 'Скачивайте установщик только с официального сайта.'],
      ['Accept the license agreement and click Next.', 'Примите лицензионное соглашение и нажмите «Далее».'],
      ['Scroll down and press Enter.', 'Прокрутите вниз и нажмите Enter.'],
      ['Save changes before closing.', 'Сохраните изменения перед закрытием.'],
      ['Take a screenshot and send it to me.', 'Сделайте скриншот и отправьте мне.'],
      ['Send me a screenshot of the error.', 'Пришлите мне скриншот ошибки.'],
      ['It’s working now, thanks a lot!', 'Теперь работает, большое спасибо!'],
      ['Thanks, that solved the problem!', 'Спасибо, это решило проблему!'],
    ],
  },

  chat: {
    file: 'dictionaries/phrasebook-socialmediachat.json',
    emoji: '📱',
    description: 'Чаты и соцсети: переписка, реакции, живой сленг сообщений',
    phrases: [
      ['Hey! What’s up?', 'Привет! Как дела / что нового?'],
      ['Not much, you?', 'Да ничего особенного, а у тебя?'],
      ['You there?', 'Ты тут?'],
      ['You around?', 'Ты на месте? Можешь ответить?'],
      ['Give me a sec.', 'Дай мне секунду.'],
      ['BRB — be right back.', 'BRB — скоро вернусь.'],
      ['Sorry, was away from my phone.', 'Извини, отходил от телефона.'],
      ['Just saw your message.', 'Только что увидел твоё сообщение.'],
      ['Didn’t get any notification!', 'Мне не пришло уведомление!'],
      ['Typing…', 'Печатает.'],
      ['Sent you a photo, check it out.', 'Отправил тебе фото, глянь.'],
      ['Look what I just found!', 'Посмотри, что я только что нашёл!'],
      ['This is hilarious 😂', 'Это умора 😂'],
      ['LOL!', 'Очень смешно (ржу не могу)!'],
      ['OMG, no way!', 'О боже, да ладно!'],
      ['No wayyy!', 'Не может быть!'],
      ['That’s awesome!', 'Вот это круто!'],
      ['Congrats!! So happy for you!', 'Поздравляю!! Так рад за тебя!'],
      ['Sending you hugs 🤗', 'Обнимаю тебя 🤗'],
      ['Miss you already.', 'Уже скучаю.'],
      ['Call me when you’re free.', 'Позвони, когда будешь свободен.'],
      ['Can’t talk right now, texting.', 'Не могу говорить сейчас, пишу сообщения.'],
      ['In a meeting, text me later.', 'На совещании, напиши позже.'],
      ['On my way!', 'Уже еду!'],
      ['Running late, sorry!', 'Опаздываю, извини!'],
      ['Where are you?', 'Где ты?'],
      ['We’re at the entrance.', 'Мы у входа.'],
      ['Save me a seat!', 'Займи мне место!'],
      ['Order for me too, please.', 'Закажи и за меня, пожалуйста.'],
      ['Same as usual.', 'Как обычно.'],
      ['Sounds good to me.', 'Меня устраивает.'],
      ['Works for me 👍', 'Мне подходит 👍'],
      ['Deal.', 'По рукам.'],
      ['Kk.', 'Окей-окей.'],
      ['Got it, thanks.', 'Принял, спасибо.'],
      ['Copy that.', 'Принято.'],
      ['Will do.', 'Будет сделано.'],
      ['My bad 🙈', 'Виноват 🙈'],
      ['Oops, wrong chat!', 'Ой, не в тот чат!'],
      ['Wrong window, sorry!', 'Не туда написал, извините!'],
      ['Who is this?', 'Кто это?'],
      ['New phone, who dis?', 'Новый телефон, кто это пишет? (шутл.)'],
      ['How did we meet again?', 'Как мы познакомились, напомни?'],
      ['Add me to the group chat.', 'Добавь меня в групповой чат.'],
      ['Mute this group, too many messages.', 'Отключи уведомления этой группы, слишком много сообщений.'],
      ['Stop spamming!', 'Хватит спамить!'],
      ['Read but no reply? Really?', 'Прочитал и не ответил? Серьёзно?'],
      ['Seen zoned again 😅', 'Опять прочитали и проигнорировали 😅'],
      ['Double texting much?', 'Пишешь дважды подряд, не стесняешься? (шутл.)'],
      ['Ghosting people is rude.', 'Игнорировать людей (пропасть без ответа) — грубо.'],
      ['Post the pics, tag me!', 'Выкладывай фото, отметь меня!'],
      ['Tagged you in the album.', 'Отметил тебя в альбоме.'],
      ['Your story cracked me up.', 'Твоя сторис меня рассмешила.'],
      ['Liked and subscribed!', 'Лайкнул и подписался!'],
      ['Follow me back?', 'Подпишись взаимно?'],
      ['DM me the details.', 'Напиши детали в личку.'],
      ['Slide into my DMs.', 'Пишите мне в личные сообщения.'],
      ['This pic needs no filter.', 'Этому фото фильтры не нужны.'],
      ['Delete this immediately 😳', 'Немедленно удали это 😳'],
      ['Screenshot taken before you deleted it!', 'Скрин сделан до того, как ты удалил!'],
      ['Gotta go, ttyl!', 'Мне пора, поговорим позже!'],
      ['Good night, talk tomorrow.', 'Спокойной ночи, созвонимся завтра.'],
    ],
  },

  dating: {
    file: 'dictionaries/phrasebook-romancedating.json',
    emoji: '💘',
    description: 'Свидания и отношения: знакомство, комплименты, приглашения',
    phrases: [
      ['Would you like to go out sometime?', 'Может, как-нибудь сходим куда-нибудь?'],
      ['Are you seeing anyone?', 'У тебя кто-то есть?'],
      ['Are you single?', 'Ты свободна?'],
      ['I’d love to take you out for dinner.', 'Я бы с удовольствием сводил тебя на ужин.'],
      ['Can I buy you a drink?', 'Можно угостить тебя напитком?'],
      ['Shall we say Saturday evening?', 'Договоримся на субботний вечер?'],
      ["I had a really nice time tonight.", 'Сегодня вечером мне было очень приятно.'],
      ['When can I see you again?', 'Когда я смогу увидеть тебя снова?'],
      ['Text me when you get home safe.', 'Напиши, когда доберёшься домой.'],
      ['You look stunning tonight.', 'Ты сегодня потрясающе выглядишь.'],
      ['Your smile is beautiful.', 'У тебя красивая улыбка.'],
      ['You have such a warm personality.', 'У тебя такой тёплый характер.'],
      ['I feel like I can talk to you about anything.', 'Кажется, я могу говорить с тобой о чём угодно.'],
      ['What are you passionate about?', 'Чем ты увлечена по-настоящему?'],
      ['Tell me more about yourself.', 'Расскажи о себе подробнее.'],
      ['What makes you laugh?', 'Что заставляет тебя смеяться?'],
      ['Do you believe in love at first sight?', 'Ты веришь в любовь с первого взгляда?'],
      ['This might sound cheesy, but…', 'Это может прозвучать банально, но.'],
      ['I’ve never felt this way about anyone.', 'Я никогда ни к кому не испытывал таких чувств.'],
      ['I think about you a lot.', 'Я часто о тебе думаю.'],
      ['You make me happy.', 'С тобой я счастлив.'],
      ['Being with you feels easy.', 'С тобой всё легко и просто.'],
      ['I like you more than I should admit.', 'Ты нравишься мне больше, чем я готов признать.'],
      ['Will you be my girlfriend?', 'Будешь моей девушкой?'],
      ['I love you.', 'Я люблю тебя.'],
      ['I love you too.', 'Я тоже люблю тебя.'],
      ['I’m falling for you.', 'Я влюбляюсь в тебя.'],
      ['You mean the world to me.', 'Ты для меня весь мир.'],
      ['Let’s take things slow.', 'Давай не будем торопить события.'],
      ['I need some time to think.', 'Мне нужно время подумать.'],
      ['Where is this relationship going?', 'К чему движутся наши отношения?'],
      ['Are we exclusive now?', 'Мы теперь пара без других отношений?'],
      ['Let’s move in together.', 'Давай съедемся (будем жить вместе).'],
      ['Meet my parents this weekend?', 'Познакомишься с моими родителями в выходные?'],
      ['I miss you like crazy.', 'Я безумно по тебе скучаю.'],
      ['Distance means nothing when you mean everything.', 'Расстояние ничего не значит, когда ты значишь всё.'],
      ['Video call tonight?', 'Видеозвонок сегодня вечером?'],
      ['Save me a dance.', 'Пригласи меня на танец.'],
      ['May I have this dance?', 'Можно вас на этот танец?'],
      ['Hold my hand.', 'Возьми меня за руку.'],
      ['Come closer.', 'Подойди ближе.'],
      ['You give the best hugs.', 'Ты лучше всех обнимаешь.'],
      ['I want to spend my life with you.', 'Я хочу провести с тобой всю жизнь.'],
      ['Marry me!', 'Выходи за меня!'],
      ['She said yes!', 'Она сказала да!'],
      ['We’re engaged!', 'Мы обручились!'],
      ['Save the date — the wedding is June first!', 'Отметьте дату — свадьба первого июня!'],
      ['Best wishes to the happy couple!', 'Лучшие пожелания счастливой паре!'],
    ],
  },
};
