// Curated real-speech phrases: greetings, small talk, opinions, requests, invitations.
// Format: ['English phrase', 'Русский перевод']
export const everyday = {
  smalltalk: {
    file: 'dictionaries/phrasebook-smalltalkbasics.json',
    emoji: '💬',
    description: 'Приветствия, знакомство, разговоры ни о чём — база живого общения',
    phrases: [
      ['Hi! How are you?', 'Привет! Как дела?'],
      ["Hi! How's it going?", 'Привет! Как жизнь?'],
      ['Good morning!', 'Доброе утро!'],
      ['Good afternoon!', 'Добрый день!'],
      ['Good evening!', 'Добрый вечер!'],
      ["How've you been?", 'Как ты поживаешь?'],
      ['Long time no see!', 'Сто лет не виделись!'],
      ["It's so good to see you!", 'Как же я рад тебя видеть!'],
      ['What have you been up to?', 'Чем занимался всё это время?'],
      ['How was your weekend?', 'Как прошли выходные?'],
      ['It was great, thanks. And yours?', 'Отлично, спасибо. А твои?'],
      ['How is your family?', 'Как твоя семья?'],
      ["How's work going?", 'Как дела на работе?'],
      ['Same old, same old.', 'Всё по-старому.'],
      ["Can't complain.", 'Пожаловаться не на что.'],
      ["It's nice to meet you.", 'Приятно познакомиться.'],
      ["Nice to meet you too.", 'Мне тоже приятно познакомиться.'],
      ["I don't think we've met. I'm Alex.", 'Кажется, мы не знакомы. Я Алекс.'],
      ['What is your name?', 'Как вас зовут?'],
      ['Sorry, what was your name again?', 'Извините, как вас зовут, повторите?'],
      ['Where are you from?', 'Откуда вы?'],
      ["I'm from Russia. And you?", 'Я из России. А вы?'],
      ['How long have you lived here?', 'Давно вы здесь живёте?'],
      ['About three years now.', 'Уже года три.'],
      ['Do you like it here?', 'Вам здесь нравится?'],
      ["Yes, it's a great place to live.", 'Да, здесь замечательно жить.'],
      ['What do you do for a living?', 'Чем вы занимаетесь?'],
      ["I'm a software engineer. What about you?", 'Я инженер-программист. А вы?'],
      ['That sounds interesting!', 'Звучит интересно!'],
      ['How did you two meet?', 'Как вы познакомились?'],
      ['Are you here on business or on holiday?', 'Вы здесь по делам или в отпуске?'],
      ['Is this your first time here?', 'Вы здесь впервые?'],
      ['Have you been here before?', 'Вы раньше здесь бывали?'],
      ['Do you come here often?', 'Вы часто сюда заходите?'],
      ['Beautiful weather today, isn’t it?', 'Прекрасная погода сегодня, не правда ли?'],
      ['Can you believe this heat?', 'Можешь представить эту жару?'],
      ['They say it’s going to rain tomorrow.', 'Говорят, завтра будет дождь.'],
      ['Did you catch the game last night?', 'Смотрел матч вчера вечером?'],
      ['Have you seen any good movies lately?', 'Смотрел в последнее время какие-нибудь хорошие фильмы?'],
      ['Any plans for the weekend?', 'Есть планы на выходные?'],
      ['Nothing special, just relaxing.', 'Ничего особенного, просто отдыхаю.'],
      ['How do you usually spend your free time?', 'Как вы обычно проводите свободное время?'],
      ['What kind of music do you like?', 'Какую музыку вы любите?'],
      ["I listen to almost everything, honestly.", 'Честно говоря, слушаю почти всё.'],
      ['Do you speak English?', 'Вы говорите по-английски?'],
      ['A little bit. Do you speak Russian?', 'Немного. Вы говорите по-русски?'],
      ['Could you speak a little slower, please?', 'Не могли бы вы говорить помедленнее?'],
      ['Could you repeat that, please?', 'Повторите, пожалуйста.'],
      ["I didn't quite catch that.", 'Я не совсем расслышал.'],
      ['Sorry, I didn’t get your number.', 'Извините, я не запомнил ваш номер телефона.'],
      ['Here, let me give you my number.', 'Вот, дам вам свой номер.'],
      ['Add me on WhatsApp.', 'Добавьте меня в WhatsApp.'],
      ['It was really nice talking to you.', 'Было очень приятно поговорить.'],
      ["I'd better get going.", 'Мне уже пора идти.'],
      ['Sorry, I have to run.', 'Извините, мне нужно бежать.'],
      ['Talk to you later!', 'Созвонимся позже!'],
      ['See you soon!', 'До скорой встречи!'],
      ['See you tomorrow!', 'До завтра!'],
      ['Take care!', 'Береги себя!'],
      ['Have a good one!', 'Хорошего дня!'],
      ['Have a great day!', 'Отличного дня!'],
      ['Have a nice evening!', 'Хорошего вечера!'],
      ['Good night, sleep well.', 'Спокойной ночи, сладких снов.'],
      ['Say hi to your family for me.', 'Передавай привет семье.'],
      ['Give my best to Anna.', 'Передавай привет Анне.'],
      ['We should catch up sometime.', 'Надо как-нибудь увидеться.'],
      ["Let's keep in touch!", 'Будем на связи!'],
      ['Drop me a line sometime.', 'Напишите мне как-нибудь.'],
      ['Welcome! Come on in.', 'Добро пожаловать! Заходите.'],
      ['Make yourself at home.', 'Будьте как дома.'],
      ['Would you like something to drink?', 'Хотите что-нибудь выпить?'],
      ['Coffee would be great, thanks.', 'Кофе был бы отлично, спасибо.'],
      ['Help yourself.', 'Угощайтесь.'],
      ['Are you hungry?', 'Вы голодны?'],
      ['I’m starving!', 'Я умираю с голоду!'],
      ["I've heard a lot about you.", 'Я много о вас слышал.'],
      ['Finally we meet in person!', 'Наконец-то мы встретились лично!'],
      ['Small world!', 'Как тесен мир!'],
      ['What a coincidence!', 'Какое совпадение!'],
      ["You haven't changed a bit!", 'Ты совсем не изменился!'],
      ['Congratulations!', 'Поздравляю!'],
      ['Happy birthday!', 'С днём рождения!'],
      ['Happy New Year!', 'С Новым годом!'],
      ['Merry Christmas!', 'С Рождеством!'],
      ['Enjoy your meal!', 'Приятного аппетита!'],
      ['Bon appétit!', 'Приятного аппетита!'],
      ['Cheers!', 'За здоровье! / Спасибо!'],
      ['Bless you!', 'Будь здоров!'],
      ['Get well soon!', 'Поправляйся скорее!'],
      ['Good luck!', 'Удачи!'],
      ['Fingers crossed!', 'Держу кулачки!'],
    ],
  },

  opinions: {
    file: 'dictionaries/phrasebook-opinionsarguments.json',
    emoji: '🗣️',
    description: 'Как выразить мнение, согласиться или возразить в живом разговоре',
    phrases: [
      ['What do you think?', 'Что вы думаете?'],
      ['What do you think about it?', 'Что вы об этом думаете?'],
      ["What's your opinion on this?", 'Каково ваше мнение по этому поводу?'],
      ['In my opinion, it’s a good idea.', 'По моему мнению, это хорошая идея.'],
      ['In my view, he’s absolutely right.', 'На мой взгляд, он совершенно прав.'],
      ['Personally, I think it’s overrated.', 'Лично я считаю, что это переоценено.'],
      ['If you ask me, it’s not worth it.', 'Если хотите знать моё мнение, это того не стоит.'],
      ['The way I see it, we have two options.', 'Как я это вижу, у нас два варианта.'],
      ['As far as I’m concerned, the deal is off.', 'Что касается меня, сделка отменяется.'],
      ['It seems to me that you’re right.', 'Мне кажется, что вы правы.'],
      ['I’d say it depends on the situation.', 'Я бы сказал, это зависит от ситуации.'],
      ['To be honest, I don’t like it.', 'Честно говоря, мне это не нравится.'],
      ['Frankly speaking, I disagree.', 'Откровенно говоря, я не согласен.'],
      ['To be fair, she did warn us.', 'Справедливости ради, она нас предупреждала.'],
      ['I totally agree with you.', 'Я полностью с вами согласен.'],
      ['I couldn’t agree more.', 'Полностью согласен, не могу не согласиться.'],
      ['Absolutely!', 'Абсолютно верно!'],
      ['Exactly!', 'Именно так!'],
      ["That's exactly what I meant.", 'Это именно то, что я имел в виду.'],
      ["You're absolutely right.", 'Вы совершенно правы.'],
      ['Fair enough.', 'Справедливо. / Ладно, убедили.'],
      ['Good point.', 'Верное замечание.'],
      ['That makes sense.', 'Это логично.'],
      ['I see your point, but…', 'Я понимаю вашу мысль, но.'],
      ["I see what you mean, however…", 'Я понимаю, о чём вы, однако.'],
      ["I'm afraid I disagree.", 'Боюсь, я не согласен.'],
      ["I don't think so.", 'Я так не думаю.'],
      ['Not really.', 'Не совсем. / Не особо.'],
      ["That's not how I see it.", 'Я вижу это иначе.'],
      ["I beg to differ.", 'Позвольте не согласиться.'],
      ['On the contrary.', 'Напротив.'],
      ['That’s partly true, but…', 'Отчасти это правда, но.'],
      ['I see it differently.', 'Я смотрю на это иначе.'],
      ['Well, it depends.', 'Ну, смотря по обстоятельствам.'],
      ['There are two sides to every story.', 'У всякой истории две стороны.'],
      ["Let's agree to disagree.", 'Оставим каждый при своём мнении.'],
      ['Are you sure about that?', 'Вы уверены в этом?'],
      ['Are you serious?', 'Вы серьёзно?'],
      ['Really? Why do you say that?', 'Правда? Почему вы так говорите?'],
      ['What makes you think so?', 'Почему вы так решили?'],
      ['Where did you get that idea?', 'Откуда у вас такая мысль?'],
      ["That's ridiculous!", 'Это нелепо!'],
      ["You must be joking!", 'Да вы шутите!'],
      ['No way!', 'Не может быть!'],
      ['I find that hard to believe.', 'Мне трудно в это поверить.'],
      ['Believe it or not.', 'Хотите верьте, хотите нет.'],
      ['As far as I know, yes.', 'Насколько я знаю, да.'],
      ['If I’m not mistaken…', 'Если я не ошибаюсь.'],
      ['Correct me if I’m wrong, but…', 'Поправьте меня, если я ошибаюсь, но.'],
      ['From my point of view…', 'С моей точки зрения.'],
      ['Generally speaking, yes.', 'Вообще говоря, да.'],
      ['By and large, people are honest.', 'В целом люди честны.'],
      ["Let's look at it from another angle.", 'Давайте посмотрим на это под другим углом.'],
      ['On the one hand… on the other hand…', 'С одной стороны... с другой стороны.'],
      ['All things considered, it went well.', 'Учитывая всё, прошло хорошо.'],
      ["When it comes to money, I'm careful.", 'Когда речь идёт о деньгах, я осторожен.'],
      ['Speaking of which…', 'Кстати говоря.'],
      ['That reminds me…', 'Это напоминает мне.'],
    ],
  },

  requests: {
    file: 'dictionaries/phrasebook-requestspermissions.json',
    emoji: '🙋',
    description: 'Вежливые просьбы, разрешения и одолжения — как просят носители',
    phrases: [
      ['Excuse me, could you help me?', 'Извините, не могли бы вы помочь мне?'],
      ['Could you do me a favor?', 'Не могли бы вы оказать мне услугу?'],
      ['Can you help me for a second?', 'Можешь помочь мне секунду?'],
      ['Would you mind helping me?', 'Не могли бы вы помочь мне?'],
      ['Could you give me a hand with this?', 'Не могли бы вы помочь мне с этим?'],
      ['Could you pass me the salt, please?', 'Передайте мне соль, пожалуйста.'],
      ['Could you hold this for a moment?', 'Не могли бы вы подержать это минуту?'],
      ['Would you mind opening the window?', 'Вы не против открыть окно?'],
      ['Do you mind if I sit here?', 'Вы не против, если я сяду здесь?'],
      ['Mind if I smoke?', 'Вы не против, если я закурю?'],
      ['May I come in?', 'Можно войти?'],
      ['May I ask you something?', 'Можно вас кое о чём спросить?'],
      ['Can I ask a quick question?', 'Можно задать быстрый вопрос?'],
      ['Could I borrow your pen?', 'Можно одолжить вашу ручку?'],
      ['Could I use your phone for a minute?', 'Можно воспользоваться вашим телефоном минутку?'],
      ['Is it okay if I take this chair?', 'Ничего, если я возьму этот стул?'],
      ['Would it be all right if I came late?', 'Можно, я приду попозже?'],
      ['Would you be able to pick me up at six?', 'Ты мог бы забрать меня в шесть?'],
      ['I was wondering if you could drive me home.', 'Не мог бы ты отвезти меня домой?'],
      ['Could you possibly stay a bit longer?', 'Ты не могла бы остаться чуть подольше?'],
      ['Could you keep an eye on my bag?', 'Не могли бы вы присмотреть за моей сумкой?'],
      ['Could you watch my stuff for a minute?', 'Присмотрите за моими вещами минутку?'],
      ['Please, help yourself.', 'Пожалуйста, угощайтесь.'],
      ['Go ahead.', 'Давайте. / Пожалуйста (делайте).'],
      ['Sure, no problem.', 'Конечно, без проблем.'],
      ['Of course!', 'Конечно!'],
      ['Certainly.', 'Разумеется.'],
      ['By all means.', 'Ради бога, конечно.'],
      ['No worries, take your time.', 'Не переживайте, не торопитесь.'],
      ["I'm sorry, I'm afraid I can't.", 'Извините, боюсь, что не могу.'],
      ["I'd love to, but I'm busy tonight.", 'С удовольствием, но я занят сегодня вечером.'],
      ['Unfortunately, I can’t make it.', 'К сожалению, я не смогу прийти.'],
      ["I wish I could, but I can't.", 'Хотел бы, да не могу.'],
      ['Ask someone else, please.', 'Попроси кого-нибудь другого, пожалуйста.'],
      ['Sorry, it slipped my mind.', 'Извините, я забыла об этом.'],
      ['I completely forgot, forgive me.', 'Я совершенно забыла, простите.'],
      ['Thank you so much, you saved my life!', 'Большое спасибо, ты спас мне жизнь!'],
      ['Thanks a lot, I owe you one.', 'Спасибо большое, я у тебя в долгу.'],
      ['I really appreciate it.', 'Я очень ценю это.'],
      ['That’s very kind of you.', 'Это очень добро с вашей стороны.'],
      ['You’re a lifesaver!', 'Ты меня выручил!'],
      ['Don’t mention it.', 'Не стоит благодарности.'],
      ['Anytime.', 'Всегда пожалуйста.'],
      ['No problem at all.', 'Да не за что.'],
      ['My pleasure.', 'С удовольствием (помог вам).'],
      ['Could you do one more thing for me?', 'Могли бы вы сделать для меня ещё кое-что?'],
      ['One last thing, I promise.', 'Последняя просьба, обещаю.'],
      ['Sorry to bother you again, but…', 'Извините за беспокойство, но.'],
      ['Sorry for the trouble.', 'Извините за беспокойство.'],
      ['Thanks for your patience.', 'Спасибо за терпение.'],
      ['Would you mind waiting outside?', 'Подождите снаружи, вас не затруднит?'],
      ['Could you speak up a little?', 'Не могли бы вы говорить погромче?'],
      ['Could you write that down for me?', 'Не могли бы вы записать это для меня?'],
      ['Could you show me on the map?', 'Можете показать мне на карте?'],
      ['Just a moment, please.', 'Одну минуту, пожалуйста.'],
      ['Hang on a second.', 'Подожди секундочку.'],
    ],
  },

  invitations: {
    file: 'dictionaries/phrasebook-offersinvitations.json',
    emoji: '🤝',
    description: 'Приглашения, планы с друзьями, предложение помощи',
    phrases: [
      ['What are you doing tonight?', 'Что ты делаешь сегодня вечером?'],
      ['Are you free on Friday?', 'Ты свободна в пятницу?'],
      ['Do you have any plans for Saturday?', 'У тебя есть планы на субботу?'],
      ['Would you like to grab a coffee?', 'Хочешь выпить кофе?'],
      ['Fancy a cup of coffee?', 'Не хочешь чашечку кофе?'],
      ["Let's grab lunch sometime.", 'Давай как-нибудь пообедаем вместе.'],
      ['How about dinner at my place?', 'Как насчёт ужина у меня дома?'],
      ['Would you like to join us?', 'Не хотите присоединиться к нам?'],
      ['We’d love to have you over.', 'Мы будем рады видеть вас у себя.'],
      ['Come over whenever you like.', 'Заходи, когда захочешь.'],
      ['Why don’t we go for a walk?', 'Может, пойдём прогуляемся?'],
      ['Shall we dance?', 'Танцуешь со мной?'],
      ['Do you feel like watching a movie?', 'Хочешь посмотреть фильм?'],
      ["I was wondering if you'd like to come.", 'Может быть, ты хочешь прийти?'],
      ['You should totally come with us!', 'Тебе точно стоит пойти с нами!'],
      ["I'd love to!", 'С удовольствием!'],
      ["Sounds great, I'm in!", 'Звучит здорово, я за!'],
      ["Count me in!", 'Записывай и меня!'],
      ["I wouldn't miss it for the world!", 'Ни за что бы это не пропустил!'],
      ["I'm afraid I can't make it.", 'Боюсь, я не смогу прийти.'],
      ["I'd love to, but I already have plans.", 'С радостью, но у меня уже есть планы.'],
      ['Maybe some other time?', 'Может быть, в другой раз?'],
      ['Rain check?', 'Перенесём на другой день?'],
      ["Let's play it by ear.", 'Давай решим по ходу дела.'],
      ["I'll let you know by tomorrow.", 'Я скажу тебе завтра до конца дня.'],
      ['What time works for you?', 'Какое время тебе подходит?'],
      ['Does seven o’clock suit you?', 'Семь часов вам удобно?'],
      ['Where shall we meet?', 'Где встретимся?'],
      ["Let's meet at the main entrance.", 'Давай встретимся у главного входа.'],
      ["I'll text you the address.", 'Я пришлю тебе адрес сообщением.'],
      ["Don't be late!", 'Не опаздывай!'],
      ["I'll be there in ten minutes.", 'Буду через десять минут.'],
      ['I’m on my way.', 'Я уже еду.'],
      ['Running five minutes late, sorry!', 'Опаздываю на пять минут, извини!'],
      ['Something has come up.', 'У меня появились неотложные дела.'],
      ['Can we reschedule?', 'Можно перенести нашу встречу?'],
      ['Can we push our meeting to next week?', 'Можно перенести встречу на следующую неделю?'],
      ['Shall we say eight o’clock?', 'Договорились на восемь?'],
      ['Perfect, see you then!', 'Отлично, до встречи!'],
      ['Would you like some more cake?', 'Хотите ещё торта?'],
      ['Just a little, please.', 'Немножко, пожалуйста.'],
      ['No, thank you, I’m full.', 'Нет, спасибо, я сыт.'],
      ['Can I get you anything?', 'Могу вам что-нибудь принести?'],
      ['Let me get that for you.', 'Позвольте, я вам это поднесу.'],
      ['Shall I open the window?', 'Мне открыть окно?'],
      ['Should I call a taxi for you?', 'Мне вызвать вам такси?'],
      ['Do you need a ride?', 'Тебя подвезти?'],
      ['I’ll walk you out.', 'Я провожу вас.'],
      ['Make yourselves comfortable.', 'Располагайтесь.'],
      ['Stay for dinner!', 'Останьтесь на ужин!'],
      ['You’re welcome to stay the night.', 'Можете остаться на ночь.'],
      ['It’s getting late, I should go.', 'Уже поздно, мне пора.'],
      ['Already leaving? Stay a bit longer!', 'Уже уходишь? Посиди ещё немного!'],
      ['Thanks for having me!', 'Спасибо за приглашение!'],
      ['Thanks for a lovely evening!', 'Спасибо за чудесный вечер!'],
      ['Come again soon!', 'Приходите ещё!'],
      ['Safe trip home!', 'Добраться домой без происшествий!'],
      ['Text me when you get home.', 'Напиши мне, когда будешь дома.'],
    ],
  },
};
