// Curated real-speech phrases: advice, apologies, compliments, feelings, time & dates.
export const everyday2 = {
  advice: {
    file: 'dictionaries/phrasebook-advicesuggestions.json',
    emoji: '💡',
    description: 'Советы и рекомендации — как их дают и принимают в реальной речи',
    phrases: [
      ['What should I do?', 'Что мне делать?'],
      ['What would you do in my place?', 'Что бы вы сделали на моём месте?'],
      ['Any advice?', 'Есть какой-нибудь совет?'],
      ['What do you suggest?', 'Что вы посоветуете?'],
      ['You should see a doctor.', 'Тебе следует показаться врачу.'],
      ["You'd better hurry up.", 'Тебе лучше поторопиться.'],
      ['If I were you, I’d apologize.', 'На твоём месте я бы извинился.'],
      ['If I were you, I wouldn’t do it.', 'На твоём месте я бы этого не делал.'],
      ['I strongly recommend this restaurant.', 'Я очень рекомендую этот ресторан.'],
      ['Take my advice and get some rest.', 'Послушайся моего совета и отдохни.'],
      ['Trust me on this one.', 'Поверь мне на слово.'],
      ['Take it from me.', 'Поверь моему опыту.'],
      ['Why don’t you talk to her about it?', 'Почему бы тебе не поговорить с ней об этом?'],
      ['Have you tried turning it off and on?', 'Пробовал выключить и включить?'],
      ['It might be worth calling first.', 'Возможно, стоит сначала позвонить.'],
      ['You might want to double-check.', 'Вам, возможно, стоит перепроверить.'],
      ['Be careful with that.', 'Будь осторожен с этим.'],
      ['Watch out!', 'Осторожно!'],
      ['Look out below!', 'Осторожно, сверху падает!'],
      ['Don’t touch it, it’s hot!', 'Не трогай, горячо!'],
      ['Whatever you do, don’t panic.', 'Что бы ни случилось, не паникуй.'],
      ['Just take it easy.', 'Просто не переживай.'],
      ['Relax, everything will be fine.', 'Расслабься, всё будет хорошо.'],
      ['Don’t worry, it’s going to be okay.', 'Не волнуйся, всё будет хорошо.'],
      ['Calm down and think it over.', 'Успокойся и хорошо всё обдумай.'],
      ['Sleep on it.', 'Отложи решение на утро.'],
      ['Give it a try.', 'Попробуйте.'],
      ['It can’t hurt to ask.', 'Спросить никогда не вредно.'],
      ['Better safe than sorry.', 'Лучше перестраховаться.'],
      ['When in doubt, ask.', 'Если сомневаешься — спроси.'],
      ['Practice makes perfect.', 'Практика ведёт к совершенству.'],
      ['Rome wasn’t built in a day.', 'Рим не сразу строился.'],
      ['Slow and steady wins the race.', 'Тише едешь — дальше будешь.'],
      ['Don’t put all your eggs in one basket.', 'Не клади все яйца в одну корзину.'],
      ['Actions speak louder than words.', 'Дела говорят громче слов.'],
      ['That’s a good idea.', 'Это хорошая идея.'],
      ['Good thinking!', 'Здорово придумано!'],
      ['That might work.', 'Это может сработать.'],
      ["I'll think about it.", 'Я подумаю над этим.'],
      ['Let me sleep on it.', 'Дайте мне подумать до завтра.'],
      ['Thanks for the tip!', 'Спасибо за совет!'],
      ['I’ll keep that in mind.', 'Я учту это.'],
      ['Noted.', 'Принято. / Учтено.'],
      ['Point taken.', 'Замечание принято.'],
      ["I'll take that under advisement.", 'Я приму это к сведению.'],
    ],
  },

  apologies: {
    file: 'dictionaries/phrasebook-apologiesforgiveness.json',
    emoji: '🙏',
    description: 'Извинения и прощение — от лёгкого «извини» до серьёзных ситуаций',
    phrases: [
      ['Sorry!', 'Извините!'],
      ["I'm so sorry.", 'Мне так жаль. / Простите, пожалуйста.'],
      ["I'm terribly sorry.", 'Я страшно извиняюсь.'],
      ['Excuse me.', 'Извините (чтобы привлечь внимание).'],
      ['Pardon me.', 'Простите меня.'],
      ['Sorry for keeping you waiting.', 'Извините, что заставил вас ждать.'],
      ["Sorry I'm late.", 'Извините за опоздание.'],
      ['Sorry, my fault entirely.', 'Извините, это полностью моя вина.'],
      ['My bad.', 'Виноват. / Моя ошибка.'],
      ['Oops, sorry about that.', 'Ой, прошу прощения.'],
      ["Sorry, I didn't mean to.", 'Прости, я не хотел.'],
      ["I didn't do it on purpose.", 'Я сделал это не нарочно.'],
      ['It was an accident.', 'Это был несчастный случай.'],
      ["I didn't mean to hurt you.", 'Я не хотел тебя обидеть.'],
      ['Please forgive me.', 'Прошу прощения.'],
      ['Can you ever forgive me?', 'Ты когда-нибудь сможешь меня простить?'],
      ['How can I make it up to you?', 'Чем я могу загладить свою вину?'],
      ["I owe you an apology.", 'Я должен перед тобой извиниться.'],
      ['I want to apologize for yesterday.', 'Хочу извиниться за вчера.'],
      ['I take back what I said.', 'Я беру свои слова назад.'],
      ['I shouldn’t have said that.', 'Зря я это сказал.'],
      ['That came out wrong, sorry.', 'Это прозвучало не так, как я хотел, извини.'],
      ['I regret my words.', 'Сожалею о сказанном.'],
      ['I feel terrible about it.', 'Мне ужасно неловко за это.'],
      ['It won’t happen again.', 'Больше этого не повторится.'],
      ['I promise it won’t happen again.', 'Обещаю, это больше не повторится.'],
      ['No harm done.', 'Ничего страшного.'],
      ['It’s all right.', 'Всё в порядке.'],
      ["It's fine, really.", 'Всё нормально, правда.'],
      ['No worries.', 'Всё в порядке, не переживай.'],
      ['Never mind.', 'Не обращайте внимания.'],
      ['Forget about it.', 'Забудьте об этом.'],
      ['These things happen.', 'Такое бывает.'],
      ['It could happen to anyone.', 'Это может случиться с каждым.'],
      ['Apology accepted.', 'Извинение принято.'],
      ['I forgive you.', 'Я тебя прощаю.'],
      ["Let's forget the whole thing.", 'Давай забудем обо всём этом.'],
      ['Truce?', 'Мир?'],
      ['Are we good?', 'Мы в расчёте? / Всё между нами в порядке?'],
      ["We're good.", 'Всё в порядке.'],
      ['Excuse me, coming through.', 'Извините, разрешите пройти.'],
      ['Excuse me, is this seat taken?', 'Извините, это место занято?'],
      ['Sorry to interrupt, but…', 'Извините, что перебиваю, но.'],
      ['Sorry to bother you.', 'Извините за беспокойство.'],
      ['Forgive the mess.', 'Простите за беспорядок.'],
      ['Excuse my French.', 'Простите за мой крепкий язык.'],
      ['Sorry, you were saying?', 'Извините, вы что-то говорили?'],
      ['Go ahead, sorry.', 'Говорите, извините (перебил).'],
    ],
  },

  compliments: {
    file: 'dictionaries/phrasebook-complimentspraise.json',
    emoji: '🌟',
    description: 'Комплименты и похвала — искренние фразы для живого общения',
    phrases: [
      ['You look great today!', 'Ты сегодня прекрасно выглядишь!'],
      ['I love your dress!', 'Мне очень нравится твоё платье!'],
      ['Nice haircut!', 'Классная стрижка!'],
      ['Have you been working out?', 'Ты что, ходишь в спортзал?'],
      ['You’ve lost weight, haven’t you?', 'Ты похудел, разве нет?'],
      ['That color suits you.', 'Этот цвет вам идёт.'],
      ['This suits you perfectly.', 'Это вам идеально подходит.'],
      ['You have excellent taste.', 'У вас отличный вкус.'],
      ['Your English is very good!', 'У вас очень хороший английский!'],
      ['You speak English fluently.', 'Вы свободно говорите по-английски.'],
      ['Wow, impressive!', 'Ух ты, впечатляет!'],
      ['That’s amazing!', 'Это потрясающе!'],
      ['You did a great job!', 'Ты отлично справился!'],
      ['Well done!', 'Молодец! Отлично сделано!'],
      ['Keep up the good work!', 'Продолжай в том же духе!'],
      ['I’m proud of you.', 'Я тобой горжусь.'],
      ['You nailed it!', 'Ты сделал это блестяще!'],
      ['Brilliant idea!', 'Блестящая идея!'],
      ['What a talented person you are!', 'Какой же ты талантливый человек!'],
      ['You’re a natural.', 'У тебя врождённый талант.'],
      ['You have a gift for this.', 'У тебя талант к этому.'],
      ['This is delicious! Did you cook it yourself?', 'Это восхитительно! Вы сами готовили?'],
      ['Your cooking is out of this world.', 'Твоя готовка — нечто невероятное.'],
      ['The food was superb.', 'Еда была превосходной.'],
      ['What a beautiful home!', 'Какой красивый дом!'],
      ['You have such a cozy place.', 'У тебя такой уютный дом.'],
      ['Great photo! Where was it taken?', 'Отличное фото! Где оно сделано?'],
      ['Thank you, that’s very kind of you to say.', 'Спасибо, это очень мило с вашей стороны.'],
      ['Oh, thank you! That means a lot.', 'Ой, спасибо! Это много для меня значит.'],
      ['Thanks, you just made my day.', 'Спасибо, ты осчастливил меня.'],
      ['You’re too kind.', 'Вы слишком добры.'],
      ['You flatter me.', 'Вы меня льстите.'],
      ['Coming from you, that means a lot.', 'Для вас это особенно приятно слышать.'],
      ['Likewise!', 'Взаимно!'],
      ['Right back at you!', 'И вам того же!'],
      ['Stop it, you’re making me blush.', 'Хватит, у меня уже румянец.'],
      ['You deserve it.', 'Вы это заслужили.'],
      ['You’ve earned it.', 'Ты этого добился.'],
      ['Hats off to you!', 'Снимаю перед вами шляпу!'],
      ['My respect!', 'Моё уважение!'],
      ['Outstanding performance!', 'Великолепное выступление!'],
      ['What a show!', 'Что за представление!'],
      ['Encore! Encore!', 'Браво! Ещё раз!'],
      ['That deserves a round of applause.', 'Это заслуживает аплодисментов.'],
    ],
  },

  feelings: {
    file: 'dictionaries/phrasebook-feelingsemotions.json',
    emoji: '😊',
    description: 'Как рассказать о своих чувствах и эмоциях по-английски',
    phrases: [
      ['How are you feeling?', 'Как вы себя чувствуете?'],
      ["I'm fine, thanks.", 'Спасибо, хорошо.'],
      ["I'm doing great!", 'У меня всё прекрасно!'],
      ["I'm feeling a bit down today.", 'Сегодня я немного подавлен.'],
      ['Not so great, to be honest.', 'Не очень, если честно.'],
      ["I've had a rough day.", 'У меня был тяжёлый день.'],
      ["I'm exhausted.", 'Я совершенно вымотался.'],
      ['I’m worn out.', 'Я выбился из сил.'],
      ["I'm so happy for you!", 'Я так рад за тебя!'],
      ["I'm thrilled!", 'Я в восторге!'],
      ["I'm over the moon!", 'Я на седьмом небе от счастья!'],
      ['This is a dream come true.', 'Это сбывшаяся мечта.'],
      ['I couldn’t be happier.', 'Я не мог бы быть счастливее.'],
      ["I'm really excited about it.", 'Я очень рад этому.'],
      ["I can't wait!", 'Жду не дождусь!'],
      ["I'm looking forward to it.", 'С нетерпением жду этого.'],
      ["I'm nervous about tomorrow.", 'Я нервничаю из-за завтрашнего дня.'],
      ['I have butterflies in my stomach.', 'У меня мандраж. / У меня мурашки от волнения.'],
      ['I’m scared stiff.', 'Я застыл от страха.'],
      ['It gives me goosebumps.', 'От этого у меня мурашки.'],
      ["I'm worried sick.", 'Я места себе не нахожу от беспокойства.'],
      ["I'm anxious about the results.", 'Я тревожусь из-за результатов.'],
      ["I'm furious!", 'Я вне себя от ярости!'],
      ["I'm fed up with this!", 'Мне это надоело!'],
      ['That drives me crazy!', 'Это сводит меня с ума!'],
      ["I've had enough!", 'С меня хватит!'],
      ['I lost my temper.', 'Я вышел из себя.'],
      ['I flew off the handle.', 'Я вспыхнул.'],
      ['I’m annoyed with him.', 'Он меня раздражает.'],
      ["He gets on my nerves.", 'Он действует мне на нервы.'],
      ["I'm upset about what happened.", 'Я расстроен тем, что произошло.'],
      ["I'm heartbroken.", 'У меня разбито сердце.'],
      ['I feel blue today.', 'Сегодня мне грустно.'],
      ['I miss you so much.', 'Я так по тебе скучаю.'],
      ['I miss those days.', 'Скучаю по тем временам.'],
      ["I'm disappointed in myself.", 'Я разочарован в себе.'],
      ['What a relief!', 'Какое облегчение!'],
      ["I'm so relieved.", 'Я так успокоилась.'],
      ['Phew! That was close.', 'Фух! Это было близко.'],
      ["I'm ashamed of myself.", 'Мне стыдно за себя.'],
      ['Shame on you!', 'Как тебе не стыдно!'],
      ["I'm embarrassed.", 'Мне неловко.'],
      ['I felt like a fool.', 'Я чувствовал себя глупцом.'],
      ['I’m jealous, but in a good way.', 'Я завидую, но по-доброму.'],
      ['There’s no point in envying others.', 'Завидовать другим бессмысленно.'],
      ['I feel lonely sometimes.', 'Иногда мне одиноко.'],
      ['Cheer up!', 'Не унывай!'],
      ["Come on, cheer up!", 'Да ладно, повеселее!'],
      ['Things will get better.', 'Всё наладится.'],
      ['Every cloud has a silver lining.', 'Нет худа без добра.'],
      ['Look on the bright side.', 'Смотри на вещи позитивнее.'],
      ["Don't beat yourself up.", 'Не кори себя.'],
      ['Pull yourself together!', 'Возьми себя в руки!'],
      ['Get a grip!', 'Соберись!'],
      ['Take a deep breath.', 'Сделай глубокий вдох.'],
    ],
  },

  timedates: {
    file: 'dictionaries/phrasebook-timedates.json',
    emoji: '🕒',
    description: 'Время, даты и договорённости о встречах — живые разговорные формулы',
    phrases: [
      ['What time is it?', 'Который час?'],
      ['Do you have the time?', 'Вы не подскажете, который час?'],
      ["It's half past three.", 'Сейчас полчетвертого.'],
      ["It's quarter to five.", 'Сейчас без четверти пять.'],
      ["It's ten past six.", 'Сейчас десять минут седьмого.'],
      ["It's noon already.", 'Уже полдень.'],
      ["It's almost midnight.", 'Почти полночь.'],
      ['My watch is slow.', 'Мои часы отстают.'],
      ['My watch is ten minutes fast.', 'Мои часы спешат на десять минут.'],
      ['What day is it today?', 'Какой сегодня день?'],
      ['What’s the date today?', 'Какое сегодня число?'],
      ["Today's Monday, June fifth.", 'Сегодня понедельник, пятое июня.'],
      ['What month is it?', 'Какой сейчас месяц?'],
      ['See you on Monday!', 'До понедельника!'],
      ['I’ll be back next week.', 'Я вернусь на следующей неделе.'],
      ['See you in an hour.', 'Увидимся через час.'],
      ['Call me in twenty minutes.', 'Позвони мне минут через двадцать.'],
      ['How long will it take?', 'Сколько это займёт времени?'],
      ['It won’t take long.', 'Это долго не займёт.'],
      ['It takes about an hour by train.', 'На поезде это занимает около часа.'],
      ['I need some more time.', 'Мне нужно ещё немного времени.'],
      ['There’s no rush.', 'Никакой спешки.'],
      ['Take your time.', 'Не торопитесь.'],
      ['Time flies!', 'Время летит!'],
      ['Where did the time go?', 'Куда ушло время?'],
      ['We’re running out of time.', 'У нас кончается время.'],
      ['We still have plenty of time.', 'У нас ещё куча времени.'],
      ['Time is up.', 'Время вышло.'],
      ['In due time.', 'В своё время.'],
      ['Sooner or later.', 'Рано или поздно.'],
      ['From time to time.', 'Время от времени.'],
      ['Once in a while.', 'Время от времени.'],
      ['All in good time.', 'Всему своё время.'],
      ['Better late than never.', 'Лучше поздно, чем никогда.'],
      ['Are we still on for tonight?', 'Мы всё ещё встречаемся сегодня вечером?'],
      ['Is seven still good for you?', 'Семь часов всё ещё удобно?'],
      ['Can we meet a bit earlier?', 'Можем встретиться пораньше?'],
      ['Could we move our appointment?', 'Можно перенести нашу встречу?'],
      ['I’d like to book an appointment.', 'Я хотел бы записаться на приём.'],
      ['What times do you have available?', 'Какое время у вас свободно?'],
      ['Does Tuesday work for you?', 'Вторник вам подходит?'],
      ['Tuesday works perfectly.', 'Вторник подходит идеально.'],
      ['I’m available any day except Sunday.', 'Я свободен в любой день, кроме воскресенья.'],
      ['Mornings are better for me.', 'Для меня лучше утро.'],
      ['Let’s set a date.', 'Давайте назначим дату.'],
      ['Mark your calendar.', 'Отметь это в календаре.'],
      ['Save the date!', 'Сохраните эту дату!'],
      ['I’ll put it in my calendar.', 'Я добавлю это в свой календарь.'],
      ['What’s the deadline?', 'Какой срок сдачи?'],
      ['By when do you need it?', 'К какому сроку это нужно?'],
      ['As soon as possible, please.', 'Как можно скорее, пожалуйста.'],
      ['Within two weeks.', 'В течение двух недель.'],
      ['At the latest by Friday.', 'Крайний срок — пятница.'],
    ],
  },
};
