// Fill-up for five thin phrasebooks (part B): toolshardware,
// officestationery, mythologyfolklore, videogamesshootersaction,
// hobbiesgardening. Each topic targets >=100 curated entries.
// Emojis are copied verbatim from the current manifest rows on purpose:
// the build rewrites manifest emoji from topic.emoji.

export const toolshardware = {
  file: 'dictionaries/phrasebook-toolshardware.json',
  emoji: '🧰',
  description: 'Фразы об инструментах и оснастке: дрели, крепёж, измерения, мастерская. Для ремонта и поделок своими руками.',
  phrases: [
    ['Pass me the screwdriver with the flat head.', 'Подай мне отвёртку с плоским жалом.'],
    ['The Phillips head strips easily if you rush.', 'Крестовое шлиц легко срывается, если торопиться.'],
    ['Turn it clockwise to tighten, counterclockwise to loosen.', 'По часовой — затягивать, против — откручивать.'],
    ['This bolt needs a ten millimetre socket.', 'Этот болт требует головку на десять миллиметров.'],
    ['Socket sets save trips back to the toolbox.', 'Наборы головок избавляют от ходьбы к ящику с инструментами.'],
    ['The ratchet clicks when it reaches torque.', 'Трещотка щёлкает при достижении момента.'],
    ['An adjustable wrench slips under real pressure.', 'Разводной ключ проскальзывает под серьёзной нагрузкой.'],
    ['Ring spanners grip better than open ends.', 'Кольцевые ключи держат лучше рожковых.'],
    ['Hex keys live in every furniture flatpack.', 'Шестигранники живут в каждой плоской упаковке мебели.'],
    ['The allen key rounded off halfway through assembly.', 'Шестигранник округлился посреди сборки.'],
    ['Pliers grip, cutters cut, never confuse their jobs.', 'Пассатижи держат, кусачки режут — не путайте их работу.'],
    ['Needle nose pliers reach into tight corners.', 'Длинногубцы достают в узких местах.'],
    ['Locking pliers clamp like a third hand.', 'Струбцины-пассатижи работают как третья рука.'],
    ['Wire strippers gauge insulation perfectly every time.', 'Стрипперы каждый раз идеально снимают изоляцию.'],
    ['Crimping lugs requires the right die size.', 'Обжим наконечников требует правильного размера матрицы.'],
    ['The drill bit wandered across the tile surface.', 'Сверло ушло в сторону по плитке.'],
    ['Mark your drill points with a centre punch first.', 'Размечайте точки сверления кернером заранее.'],
    ['Masonry bits hammer through brick effortlessly.', 'Буры по бетону проходят кирпич без усилий.'],
    ['Drill pilot holes before driving screws near edges.', 'Сверлите направляющие отверстия перед шурупами у краёв.'],
    ['The clutch setting prevents overdriving screws.', 'Регулировка муфты не даёт перетянуть шурупы.'],
    ['Impact drivers eat long deck screws for breakfast.', 'Гайковёрт щёлкает длинные саморезы как орешки.'],
    ['Counterbore the holes so heads sit flush.', 'Зенкуйте отверстия, чтобы шляпки сидели заподлицо.'],
    ['Hole saws cut circles where spade bits tear.', 'Коронки режут круги там, где перки рвут.'],
    ['Step drills enlarge holes in thin metal neatly.', 'Ступенчатые свёрла аккуратно расширяют дырки в тонком металле.'],
    ['Clamp your workpiece before anything else.', 'Закрепите заготовку струбциной прежде всего остального.'],
    ['You can never own too many clamps.', 'Струбцин много не бывает.'],
    ['The vice grips the bench and the bench grips everything.', 'Тиски держат верстак, а верстак держит всё.'],
    ['Measure twice, cut once, regret neither.', 'Семь раз отмерь, один отрежь — и ни о чём не жалей.'],
    ['The tape measure hook slides to account for its thickness.', 'Зацеп рулетки двигается, учитывая собственную толщину.'],
    ['Combination squares check ninety degrees instantly.', 'Комбинированные угольники мгновенно проверяют прямой угол.'],
    ['A centred spirit level bubble means truly level.', 'Пузырёк уровня в центре значит ровно.'],
    ['Laser levels project lines across whole rooms.', 'Лазерные уровни проецируют линии через всю комнату.'],
    ['Calipers measure inside, outside and depth.', 'Штангенциркуль меряет внутри, снаружи и глубину.'],
    ['Digital calipers switch between millimetres and inches.', 'Цифровой штангенциркуль переключает миллиметры и дюймы.'],
    ['Feeler gauges set spark plug gaps precisely.', 'Щупы точно выставляют зазоры свечей.'],
    ['The stud finder beeped twice above the fireplace.', 'Детектор каркаса дважды пискнул над камином.'],
    ['Studs sit sixteen inches apart in most walls.', 'Стойки каркаса стоят обычно в шестнадцати дюймах друг от друга.'],
    ['Anchor plugs hold screws where studs hide away.', 'Дюбели держат шурупы там, где нет стоек.'],
    ['Toggle bolts carry heavy shelves on drywall.', 'Анкеры-бабочки держат тяжёлые полки на гипсокартоне.'],
    ['Wood screws need clearance in the top piece.', 'Шурупам по дереву нужен зазор в верхней детали.'],
    ['Machine threads pair with nuts or tapped holes.', 'Машинная резьба работает с гайками или нарезными отверстиями.'],
    ['Thread pitch matters more than diameter sometimes.', 'Шаг резьбы иногда важнее диаметра.'],
    ['Blue threadlocker keeps bolts from backing out.', 'Синий фиксатор резьбы не даёт болтам откручиваться.'],
    ['Never use red threadlocker unless you mean forever.', 'Красный фиксатор используйте, только если хотите навсегда.'],
    ['Washers distribute load and stop pull-through.', 'Шайбы распределяют нагрузку и не дают продавить.'],
    ['Lock washers bite into surfaces under vibration.', 'Пружинные шайбы впиваются в поверхность от вибрации.'],
    ['Nylon insert nuts never loosen from shaking.', 'Самоконтрящиеся гайки с нейлоном не откручиваются от тряски.'],
    ['Rivets join metal where welding cannot reach.', 'Заклёпки соединяют металл там, куда сварка не дотянется.'],
    ['The rivet gun snaps each mandrel satisfyingly.', 'Заклёпочник со щелчком откусывает каждую оправку.'],
    ['Epoxy fills gaps that fasteners cannot.', 'Эпоксидка заполняет щели, недоступные крепежу.'],
    ['Two part adhesives demand exact mixing ratios.', 'Двухкомпонентные клеи требуют точной пропорции смешивания.'],
    ['Sand the surface before gluing anything seriously.', 'Шлифуйте поверхность перед любой серьёзной склейкой.'],
    ['Degrease with alcohol before applying tape.', 'Обезжирьте спиртом перед наклейкой ленты.'],
    ['Double sided tape holds surprisingly heavy mirrors.', 'Двусторонний скотч держит на удивление тяжёлые зеркала.'],
    ['The utility knife blade snapped mid-cut.', 'Лезвие канцелярского ножа сломалось посреди реза.'],
    ['Snap off blades stay sharp segment by segment.', 'Сегментные лезвия остаются острыми сегмент за сегментом.'],
    ['Handsaws cut straight only with practice.', 'Ручные пилы режут прямо только с практикой.'],
    ['Hacksaw blade tension matters more than speed.', 'Натяжение полотна ножовки важнее скорости.'],
    ['Mitre boxes guide perfect angle cuts.', 'Стусло ведёт пилу под идеальным углом.'],
    ['Forty-five degree cuts meet into clean corners.', 'Резы под сорок пять градусов сходятся в чистый угол.'],
    ['Chisels shave wood only when razor sharp.', 'Стамески строгают дерево только будучи острее бритвы.'],
    ['Sharpening stones reward ten patient minutes.', 'Точильные камни награждают десять минут терпения.'],
    ['Dull tools cause more injuries than sharp ones.', 'Тупой инструмент калечит чаще острого.'],
    ['Planes leave gossamer shavings when tuned right.', 'Рубанки оставляют паутинную стружку при правильной настройке.'],
    ['Rasps shape curves where planes refuse.', 'Рашпили формуют кривые там, где рубанк бессилен.'],
    ['Files cut in one direction only.', 'Напильники режут только в одну сторону.'],
    ['Wire brushes strip rust before painting.', 'Щётки по металлу снимают ржавчину перед покраской.'],
    ['Primer seals bare metal against moisture.', 'Грунт защищает голый металл от влаги.'],
    ['Masking tape lines crisp paint borders.', 'Малярный скотч даёт чёткие границы краски.'],
    ['Drop cloths protect floors from splatter.', 'Укрывные плёнки защищают полы от брызг.'],
    ['The soldering iron idles at three hundred degrees.', 'Паяльник держит триста градусов в простое.'],
    ['Tin the tip before every joint.', 'Лудите жало перед каждой пайкой.'],
    ['Flux cleans oxidation so solder flows.', 'Флюс очищает окислы, и припой растекается.'],
    ['Cold joints crack under the slightest flex.', 'Холодная пайка трескается от малейшего изгиба.'],
    ['Heat shrink tubing insulates connections professionally.', 'Термоусадка изолирует соединения как профессионал.'],
    ['Multimeters test voltage continuity and resistance.', 'Мультиметры проверяют напряжение, целостность и сопротивление.'],
    ['Always test your multimeter on a known source first.', 'Сначала проверьте мультиметр на известном источнике.'],
    ['Turn off the breaker before touching any wiring.', 'Выключите автомат перед любыми работами с проводкой.'],
    ['Voltage testers light up near live wires.', 'Индикаторы напряжения загораются возле проводов под током.'],
    ['Insulated handles rated for a thousand volts exist for reasons.', 'Изолированные рукоятки на тысячу вольт существуют не просто так.'],
    ['Ladders lean at a four to one angle safely.', 'Лестницы безопасно стоят под углом четыре к одному.'],
    ['Safety glasses cost less than emergency rooms.', 'Защитные очки дешевле приёмного покоя.'],
    ['Ear protection matters around impact drivers.', 'Защита ушей важна рядом с гайковёртами.'],
    ['Dust masks filter particles your lungs resent.', 'Респираторы задерживают пыль, которую лёгкие не любят.'],
    ['Gloves improve grip but snag near spinning bits.', 'Перчатки улучшают хват, но цепляются за вращающееся сверло.'],
    ['Magnetic trays keep small parts from vanishing.', 'Магнитные лотки не дают мелочам исчезать.'],
    ['Every project loses one screw to the carpet gods.', 'Каждый проект жертвует один шуруп богам ковра.'],
    ['Organise drawers by size or surrender to chaos.', 'Разложите ящики по размерам или сдайтесь хаосу.'],
    ['Tool rolls travel lighter than full boxes.', 'Инструментальные рулоны легче полноценных ящиков.'],
    ['Rust prevention wipes extend tool lifespans for years.', 'Салфетки от ржавчины продлевают жизнь инструментов на годы.'],
    ['Quality tools hurt once at purchase, cheap ones hurt forever.', 'Хороший инструмент болит один раз при покупке, дешёвый — вечно.'],
    ['Borrowed tools return cleaner than borrowed.', 'Чужие инструменты возвращают чище, чем брали.'],
    ['The workshop rule says put it back where it lives.', 'Правило мастерской: кладите инструмент туда, где он живёт.'],
    ['Half of DIY is knowing which job to refuse.', 'Половина ремонта — знать, какую работу не браться делать.'],
    ['Call a professional before water finds the ceiling below.', 'Зовите мастера, пока вода не нашла потолок снизу.'],
    ['The torque wrench clicks at target tightness.', 'Динамометрический ключ щёлкает при нужной затяжке.'],
    ['Over-torqued bolts stretch and never trust again.', 'Перетянутые болты тянутся и больше не доверяют.'],
    ['Torque specs live in manuals nobody reads first.', 'Моменты затяжки прописаны в мануалах, которые никто не читает заранее.'],
    ['Penetrating oil loosens rusted bolts overnight.', 'Проникающая смазка отмачивает ржавые болты за ночь.'],
    ['Heat the nut, cool the bolt, then persuade gently.', 'Грейте гайку, охладите болт, потом мягко уговаривайте.'],
    ['Broken extractors dig out snapped studs slowly.', 'Экстракторы выкручивают сломанные шпильки медленно.'],
    ['Left handed drill bits sometimes back broken bolts out.', 'Свёрла с левой спиралью иногда выворачивают сломанные болты.'],
  ],
};

export const officestationery = {
  file: 'dictionaries/phrasebook-officestationery.json',
  emoji: '🖇️',
  description: 'Фразы про офис и канцелярию: бумаги, ручки, печать, организация рабочего места. Для офисной работы и учёбы.',
  phrases: [
    ['Could you lend me a pen for a second?', 'Не одолжишь ручку на секунду?'],
    ['This pen writes smoother than it has any right to.', 'Эта ручка пишет плавнее, чем имеет право.'],
    ['Ballpoints skip on glossy paper annoyingly.', 'Шариковые ручки раздражающе прерываются на глянцевой бумаге.'],
    ['Gel pens bleed through thin notebook pages.', 'Гелевые ручки просвечивают через тонкие страницы.'],
    ['Fountain pens demand good paper and patience.', 'Перьевые ручки требуют хорошей бумаги и терпения.'],
    ['My handwriting deteriorates without lined paper.', 'Без линованной бумаги мой почерк разваливается.'],
    ['The printer jammed again on page forty-seven.', 'Принтер снова зажевал бумагу на сорок седьмой странице.'],
    ['Remove the jammed sheet by pulling slowly upward.', 'Достайте застрявший лист, медленно вытягивая вверх.'],
    ['We are out of toner again before the deadline.', 'У нас опять кончился тонер перед дедлайном.'],
    ['Shake the cartridge gently to revive fading prints.', 'Слегка встряхните картридж, чтобы оживить бледную печать.'],
    ['Double-sided printing halves our paper budget.', 'Двусторонняя печать вдвое экономит бюджет бумаги.'],
    ['Draft mode saves ink for internal documents.', 'Черновой режим экономит чернила для внутренних документов.'],
    ['The scanner feeds crooked unless you align the guides.', 'Сканер тянет криво, если не выставить направляющие.'],
    ['Scan to PDF keeps pages searchable through OCR.', 'Сканирование в PDF делает страницы доступными для поиска.'],
    ['Shredders handle staples but not spiral bindings.', 'Шреддеры пережёвывают скобы, но не спирали.'],
    ['Cross-cut shredding protects documents better than strips.', 'Перекрёстное шредирование защищает документы лучше полосок.'],
    ['Staple removers deserve more appreciation honestly.', 'Антистеплер честно заслуживает больше признания.'],
    ['Heavy duty staples bind fifty pages comfortably.', 'Крупные скобы спокойно сшивают пятьдесят страниц.'],
    ['Paper clips come in two philosophies, regular and jumbo.', 'Скрепки бывают двух философий: обычные и большие.'],
    ['Binder clips grip stacks no clip dares to.', 'Зажимы для бумаг берут такие стопки, какие другим не снились.'],
    ['Rubber bands perish into sticky strings within a year.', 'Резинки за год превращаются в липкие нитки.'],
    ['Highlighter ink fades after a decade in storage.', 'Маркер выцветает за десятилетие хранения.'],
    ['Yellow highlights the main idea, green means examples.', 'Жёлтый выделяет главное, зелёный — примеры.'],
    ['Colour coding notes saved my exam preparation.', 'Цветовая маркировка конспектов спасла мою подготовку к экзамену.'],
    ['Sticky notes migrate onto every monitor eventually.', 'Стикеры в итоге расползаются по всем мониторам.'],
    ['Sticky note adhesive fails on dusty surfaces.', 'Клей стикеров не держит на пыльных поверхностях.'],
    ['Index tabs mark chapters in thick binders.', 'Табы-разделители отмечают главы в толстых папках.'],
    ['Laminating pouches protect frequently handled sheets.', 'Пакеты для ламинирования защищают часто используемые листы.'],
    ['The laminator needs two minutes to warm up.', 'Ламинатору нужно две минуты на прогрев.'],
    ['Guillotine cutters slice stacks in one pass.', 'Гильотины режут стопки одним движением.'],
    ['Rotary trimmers score photos without tearing.', 'Роликовые резаки режут фото без задиров.'],
    ['Window envelopes align addresses automatically.', 'Конверты с окошком сами выставляют адрес.'],
    ['Registered mail requires signatures upon delivery.', 'Для заказного письма нужна подпись при получении.'],
    ['The mailroom sorts internal envelopes by floor.', 'В канцелярии внутренние конверты сортируют по этажам.'],
    ['Whiteboards ghost if you leave markers on too long.', 'На маркерных досках остаются следы, если не стирать долго.'],
    ['Dry erase markers squeak on dirty boards.', 'Маркеры скрипят по грязной доске.'],
    ['Flip charts stand ready for brainstorming sessions.', 'Флипчарты наготове для мозговых штурмов.'],
    ['Push pins hold schedules on cork boards.', 'Кнопки-гвоздики держат расписания на пробковых досках.'],
    ['Magnets pin diagrams to whiteboard frames.', 'Магниты крепят схемы к раме доски.'],
    ['The hole punch collects confetti nobody empties.', 'Дырокол копит конфетти, которые никто не вытряхивает.'],
    ['Reinforcement rings rescue torn punch holes.', 'Наклейки-усилители спасают порванные отверстия.'],
    ['Archival folders survive decades in storage boxes.', 'Архивные папки переживают десятилетия в коробках.'],
    ['Label the spine or lose the folder forever.', 'Подписывайте корешок, иначе потеряете папку навсегда.'],
    ['Alphabetical filing beats chronological for retrieval.', 'Алфавитный порядок находит документы быстрее хронологического.'],
    ['The archive room smells of dust and forgotten deadlines.', 'В архиве пахнет пылью и забытыми дедлайнами.'],
    ['Retention policies decide what gets shredded when.', 'Политика хранения решает, что и когда уничтожать.'],
    ['Sign here, initial there, date everywhere.', 'Подпись здесь, инициалы там, дата везде.'],
    ['Blue ink distinguishes originals from photocopies.', 'Синие чернила отличают оригиналы от ксерокопий.'],
    ['Notarised copies require embossed seals.', 'Нотариальные копии требуют выпуклой печати.'],
    ['Date stamps save writing today thrice daily.', 'Датеры спасают от троекратного написания сегодняшнего числа.'],
    ['Correction fluid dries faster than regrets fade.', 'Замазка сохнет быстрее, чем забываются сожаления.'],
    ['Erasable pens rewrite history until heated.', 'Стираемые ручки переписывают историю до нагрева.'],
    ['Mechanical pencils click through leads endlessly.', 'Механические карандаши бесконечно щёлкают грифелями.'],
    ['HB hardness suits general writing best.', 'Твёрдость HB лучше всего подходит для письма.'],
    ['Sketch artists prefer softer grades for shading.', 'Художники любят мягкие грифели за штриховку.'],
    ['Kneaded erasers lift graphite without residue.', 'Клячки поднимают графит без следов.'],
    ['Rulers wobble unless pressed firmly.', 'Линейки виляют, если их не прижать крепко.'],
    ['Set squares draw angles rulers dream about.', 'Угольники рисуют углы, о которых линейки мечтают.'],
    ['Compasses circle homework margins precisely.', 'Циркули точно очерчивают поля домашних заданий.'],
    ['Protractors measure angles students argue about.', 'Транспортиры измеряют углы, о которых спорят студенты.'],
    ['Calculators replaced log tables but not understanding.', 'Калькуляторы заменили таблицы логарифмов, но не понимание.'],
    ['Scientific calculators hide functions behind shift keys.', 'Научные калькуляторы прячут функции за клавишей Shift.'],
    ['Spare batteries live in the drawer of necessity.', 'Запасные батарейки живут в ящике необходимости.'],
    ['Desk organisers corral pens into actual order.', 'Органайзеры загоняют ручки в подобие порядка.'],
    ['Drawer dividers end the stationery avalanche.', 'Разделители прекращают лавину канцелярии.'],
    ['Order supplies before the fiscal year freezes budgets.', 'Заказывайте поставки до заморозки бюджета на конец года.'],
    ['Bulk buying staples costs pennies per thousand.', 'Оптом скрепки стоят гроши за тысячу.'],
    ['Inventory sheets track who borrowed the good scissors.', 'Ведомости следят, кто взял хорошие ножницы.'],
    ['Good scissors disappear into gift wrapping emergencies.', 'Хорошие ножницы исчезают в упаковочных авралах.'],
    ['Paper cutter blades dull against staple surprises.', 'Лезвия резаков тупятся о незамеченные скобы.'],
    ['Recycled paper feeds smoother than expected.', 'Переработанная бумага идёт через принтер лучше ожидаемого.'],
    ['Notebooks pile up faster than projects finish.', 'Блокноты копятся быстрее, чем заканчиваются проекты.'],
    ['One notebook per project or chaos multiplies.', 'Один блокнот на проект, иначе хаос множится.'],
    ['Meeting minutes capture decisions, not conversations.', 'Протоколы фиксируют решения, а не разговоры.'],
    ['Action items get owners and dates immediately.', 'Задачи сразу получают ответственных и сроки.'],
    ['Agendas printed beforehand keep meetings honest.', 'Распечатанные заранее повестки делают встречи честнее.'],
    ['Name tents prevent awkward pointing during introductions.', 'Бейджи-таблички спасают от неловкого тыканья при знакомстве.'],
    ['Business card holders spare pockets from bent corners.', 'Визитницы берегут карманы от загнутых уголков.'],
    ['Letter openers feel delightfully old fashioned.', 'Ножи для писем приятно ощущаются старомодно.'],
    ['Envelope moisteners beat tongue sealing hygienically.', 'Увлажнители конвертов гигиеничнее заклейки языком.'],
    ['Postage meters weigh letters before surprises arrive.', 'Почтовые машины взвешивают письма до неприятных сюрпризов.'],
    ['Courier pouches travel between branches nightly.', 'Курьерские сумки ездят между филиалами каждую ночь.'],
    ['Fax machines survive purely out of institutional stubbornness.', 'Факсы живут исключительно на институциональном упрямстве.'],
    ['Typewriters click romantically in museum corners now.', 'Печатные машинки теперь романтично щёлкают в музейных углах.'],
    ['Carbon paper taught generations about copies.', 'Копирка научила поколения понимать, что такое копии.'],
    ['Ergonomic pens save wrists during marathon signing.', 'Эргономичные ручки берегут запястья при марафонском подписании.'],
    ['Wrist rests make spreadsheets survivable.', 'Подставки для запястий делают таблицы переносимыми.'],
    ['Monitor risers align screens with eyes properly.', 'Подставки монитора выставляют экран на уровень глаз.'],
    ['Footrests fix chairs built for taller people.', 'Подставки для ног исправляют стулья, сделанные для более высоких.'],
    ['A tidy desk signals either discipline or an empty calendar.', 'Аккуратный стол говорит либо о дисциплине, либо о пустом календаре.'],
    ['Stationery lovers find joy in blank pages.', 'Любители канцелярии находят радость в чистых страницах.'],
    ['The first page of any notebook deserves better handwriting.', 'Первая страница блокнота заслуживает лучшего почерка.'],
    ['Paper weight numbers confuse everyone except printers.', 'Плотность бумаги путает всех, кроме принтеров.'],
    ['Eighty gsm sheets feed reliably through office machines.', 'Листы восемьдесят граммов идут через офисную технику без капризов.'],
    ['Cardstock jams cheap printers every single time.', 'Картон застревает в дешёвых принтерах каждый раз.'],
    ['A4 versus Letter formats betray international travellers.', 'Форматы A4 и Letter подставляют международных путешественников.'],
    ['Binder rings snap shut on careless fingers.', 'Кольца скоросшивателя защёлкиваются на неосторожных пальцах.'],
    ['Plastic sleeves protect frequently referenced recipes.', 'Пластиковые файлы берегут часто используемые рецепты.'],
    ['Tab dividers colour code projects across departments.', 'Разделители размечают проекты по цветам между отделами.'],
    ['Sticky flags mark pages without committing ink.', 'Флажки помечают страницы без чернил.'],
    ['Rubber finger tips speed page flipping dramatically.', 'Напальчники резко ускоряют перелистывание.'],
    ['Book stands hold cookbooks open at stubborn pages.', 'Подставки держат поваренные книги на упрямых страницах.'],
    ['Desk pads cushion wrists and hide old stains.', 'Планшеты на стол смягчают запястья и прячут старые пятна.'],
    ['Chair mats glide rolling chairs over carpet.', 'Коврики под кресло катают колёсные стулья по ковру.'],
    ['Cable clips route charger wires along desk edges.', 'Клипсы ведут провода зарядок вдоль края стола.'],
    ['Whiteboard markers dry uncapped within days.', 'Маркеры высыхают без крышки за считанные дни.'],
    ['Permanent marker accidents call for alcohol wipes.', 'Последствия перманентного маркера лечатся спиртовыми салфетками.'],
    ['Envelope windows misalign when inserts shift.', 'Окошки конвертов съезжают, если вкладка сместилась.'],
    ['Return address stamps save winter card marathons.', 'Штампы обратного адреса спасают зимние марафоны открыток.'],
  ],
};

export const mythologyfolklore = {
  file: 'dictionaries/phrasebook-mythologyfolklore.json',
  emoji: '🦄',
  description: 'Фразы о мифологии и фольклоре: боги, легенды, сказания, символы. Для чтения мифов и культурных бесед.',
  phrases: [
    ['Every culture explains thunder somehow.', 'Каждая культура как-то объясняет гром.'],
    ['Zeus ruled Olympus with temper and lightning.', 'Зевс правил Олимпом с помощью грозы и характера.'],
    ['Hera punished his infidelities creatively.', 'Гера творчески мстила за его измены.'],
    ['Prometheus stole fire and paid eternally for it.', 'Прометей украл огонь и платил за это вечно.'],
    ['Odysseus took ten years to sail home.', 'Одиссей добирался домой десять лет.'],
    ['The Trojan Horse remains history most famous ruse.', 'Троянский конь остаётся самой знаменитой хитростью в истории.'],
    ['Sirens sang sailors onto the rocks.', 'Сирены пением вели моряков на скалы.'],
    ['Icarus ignored his father and melted his wings.', 'Икар ослушался отца и расплавил крылья.'],
    ['Medusa turned onlookers into stone.', 'Медуза обращала смотрящих в камень.'],
    ['Perseus won by reflection rather than force.', 'Персей победил отражением, а не силой.'],
    ['Heracles completed twelve labours as penance.', 'Геракл совершил двенадцать подвигов во искупление.'],
    ['Achilles strength hid one vulnerable heel.', 'В силе Ахиллеса таилась одна уязвимая пятка.'],
    ['Norse gods knew their doom in advance.', 'Скандинавские боги знали свою гибель заранее.'],
    ['Odin traded an eye for wisdom.', 'Один отдал глаз за мудрость.'],
    ['Thor lifts a hammer worth lifting.', 'Тор поднимает молот, который стоит того.'],
    ['Loki tricks first and apologises never.', 'Локи сначала хитрит и никогда не извиняется.'],
    ['Ragnarok ends the world and begins another.', 'Рагнарёк заканчивает мир и начинает новый.'],
    ['Yggdrasil connects nine worlds through its branches.', 'Иггдрасиль соединяет девять миров своими ветвями.'],
    ['Ravens bring Odin news every morning.', 'Вороны приносят Одину новости каждое утро.'],
    ['Valhalla feasts await the brave fallen.', 'В Вальхалле пиршества ждут храбрых павших.'],
    ['Egyptian gods judged hearts against a feather.', 'Египетские боги взвешивали сердца против пера.'],
    ['Anubis guided souls through the underworld.', 'Анубис проводил души через загробный мир.'],
    ['Ra sailed the sun across the sky daily.', 'Ра ежедневно вёз солнце через небо.'],
    ['The Nile flooded because Isis wept, legends say.', 'Нил разливался от слёз Исиды, говорят легенды.'],
    ['The Sphinx asked riddles with deadly stakes.', 'Сфинкс загадывал загадки ценой жизни.'],
    ['Gilgamesh sought immortality and found wisdom instead.', 'Гильгамеш искал бессмертие, а нашёл мудрость.'],
    ['Flood stories appear across a dozen traditions.', 'Истории потопа встречаются в десятке традиций.'],
    ['Hindu epics run longer than any western saga.', 'Индуистские эпосы длиннее любых западных саг.'],
    ['Krishna advised duty without attachment to results.', 'Кришна советовал исполнять долг без привязанности к плодам.'],
    ['Shiva dances destruction into creation.', 'Шива танцем превращает разрушение в созидание.'],
    ['Ganesha removes obstacles before journeys begin.', 'Ганеша убирает препятствия перед началом пути.'],
    ['The Monkey King rebelled against heaven itself.', 'Царь обезьян восстал против самого неба.'],
    ['Journey narratives shape half the worlds folklore.', 'Сюжет странствия лежит в половине мирового фольклора.'],
    ['Dragons guard treasure in Europe and bring rain in Asia.', 'В Европе драконы сторожат сокровища, в Азии приносят дождь.'],
    ['Phoenixes rebuild themselves from their own ashes.', 'Фениксы возрождаются из собственного пепла.'],
    ['Medieval lore insisted only maidens could catch unicorns.', 'Средневековые поверья настаивали: единорога ловит лишь дева.'],
    ['Mermaids lured with beauty and drowned without mercy.', 'Русалки манили красотой и топили без пощады.'],
    ['Vampires fear daylight and uninvited entry both.', 'Вампиров страшен и дневной свет, и вход без приглашения.'],
    ['Werewolf tales explained the madness of full moons.', 'Истории об оборотнях объясняли безумие полнолуния.'],
    ['Ghosts linger over unfinished business, all stories agree.', 'Призраки остаются из-за незавершённых дел — так согласны все истории.'],
    ['Banshee wails foretold deaths in Irish folklore.', 'Стоны банши предвещали смерть в ирландском фольклоре.'],
    ['Leprechauns allegedly guard gold at rainbow ends.', 'Лепреконы якобы стерегут золото у конца радуги.'],
    ['Fairies demanded respect and occasionally stole children.', 'Феи требовали уважения и порой похищали детей.'],
    ['Changelings explained babies who cried differently.', 'Подменышами объясняли младенцев с непривычным плачем.'],
    ['House spirits rewarded cleanliness and punished rudeness.', 'Домовые награждали за чистоту и наказывали за грубость.'],
    ['The domovoi lived behind the stove in Slavic homes.', 'Домовой жил за печью в славянских избах.'],
    ['Baba Yaga hut walks on chicken legs.', 'Изба Бабы-Яги ходит на курьих ножках.'],
    ['Koschei hid his death inside a needle.', 'Кощей спрятал смерть в игле.'],
    ['Firebird feathers begin quests and complicate them.', 'Перо Жар-птицы начинает поход и усложняет его.'],
    ['Vasilisa outwitted the witch with kindness and skulls.', 'Василиса перехитрила ведьму добротой и черепами.'],
    ['Urban legends thrive on friend of a friend sources.', 'Городские легенды процветают на историях «знакомого знакомого».'],
    ['Alligators in sewers swam from tabloids into folklore.', 'Аллигаторы в канализации приплыли из жёлтой прессы в фольклор.'],
    ['Chain letters threatened luck and promised riches.', 'Письма счастья грозили неудачей и обещали богатство.'],
    ['Campfire stories grow taller with every retelling.', 'Истории у костра растут с каждым пересказом.'],
    ['Local legends mark every old bridge and well.', 'У каждого старого моста и колодца есть своя легенда.'],
    ['Founding myths flatter cities into destinies.', 'Мифы об основании льстят городам, превращая их в судьбы.'],
    ['Romulus killed Remus over a city line.', 'Ромул убил Рема из-за городской черты.'],
    ['Creation myths answer questions children ask first.', 'Мифы о творении отвечают на первые вопросы детей.'],
    ['Trickster tales teach rules by breaking them.', 'Сказки о трикстерах учат правилам, нарушая их.'],
    ['Coyote stories laugh at cleverness gone wrong.', 'Истории о Койоте смеются над умом не в ту сторону.'],
    ['Anansi carried stories from heaven in a clay pot.', 'Ананси принёс сказки с небес в глиняном горшке.'],
    ['Raven stole the sun for the first people.', 'Ворон украл солнце для первых людей.'],
    ['Thunderbirds battled water monsters above the plains.', 'Гром-птицы сражались с водяными чудищами над прериями.'],
    ['Quetzalcoatl promised return and changed history anyway.', 'Кетцалькоатль обещал вернуться и невольно изменил историю.'],
    ['Myths encode seasons, stars and harvests.', 'Мифы кодируют времена года, звёзды и урожаи.'],
    ['Constellation stories map heroes onto the sky.', 'Созвездия расселяют героев по небу.'],
    ['Orion hunts across winter skies worldwide.', 'Орион охотится в зимнем небе по всему миру.'],
    ['The Big Dipper doubles as a drinking gourd in songs.', 'Большая Медведица в песнях служит ещё и ковшом.'],
    ['Folk heroes outsized their historical originals.', 'Фольклорные герои больше своих исторических прототипов.'],
    ['Paul Bunyan logged forests with one blue ox.', 'Пол Баньян валил леса с одним синим быком.'],
    ['Robin Hood robbed rich coaches on forest roads.', 'Робин Гуд грабил богатые кареты на лесных дорогах.'],
    ['Outlaws become folk heroes when laws feel unjust.', 'Разбойники становятся народными героями, когда законы кажутся несправедливыми.'],
    ['Proverbs compress folklore into portable wisdom.', 'Пословицы спрессовывают фольклор в переносную мудрость.'],
    ['Riddles sharpened wits at long winter evenings.', 'Загадки оттачивали умы долгими зимними вечерами.'],
    ['Lullabies smuggle old fears into soft melodies.', 'Колыбельные проносят древние страхи сквозь нежные мелодии.'],
    ['Wedding rituals borrow fertility symbols shamelessly.', 'Свадебные обряды бесстыдно заимствуют символы плодородия.'],
    ['Harvest festivals thank whatever provided the harvest.', 'Праздники урожая благодарят того, кто послал урожай.'],
    ['Masked processions scare winters back into hiding.', 'Маскарадные шествия пугают зиму обратно в укрытие.'],
    ['Carved pumpkins originally guarded against wandering spirits.', 'Резные тыквы изначально стерегли от блуждающих духов.'],
    ['Mistletoe meant peace between enemies in older customs.', 'Омела в старых обычаях значила мир между врагами.'],
    ['Amulets trade fear for something to hold.', 'Амулеты меняют страх на то, что можно держать в руках.'],
    ['Evil eye beads decorate cradles and dashboards alike.', 'Глазки от сглаза украшают и колыбели, и торпеды машин.'],
    ['Crossroads carry supernatural weight everywhere.', 'Перекрёстки везде имеют сверхъестественный вес.'],
    ['Thresholds deserve respect in half the worlds tales.', 'Порог требует уважения в половине мировых сказок.'],
    ['Mirrors face walls in houses of mourning.', 'Зеркала завешивают в домах скорби.'],
    ['Salt spilled over shoulders undoes small bad lucks.', 'Просыпанную соль бросают через плечо от мелких бед.'],
    ['Knocking on wood hedges every confident sentence.', 'Стук по дереву подстраховывает каждую самоуверенную фразу.'],
    ['Wishes on falling stars arrive unverified.', 'Желания под падающими звёздами исполняются без гарантий.'],
    ['Birthday candles demand secrecy and lung capacity.', 'Свечки на торте требуют секретности и объёма лёгких.'],
    ['Fortune cookies invented tradition newer than the telephone.', 'Печенье с предсказаниями моложе телефона, хотя притворяется традицией.'],
    ['Tarot decks read narratives more than futures.', 'Карты таро читают скорее сюжеты, чем будущее.'],
    ['Palm readers find lifelines wherever hands differ.', 'Хироманты находят линии жизни на любых ладонях.'],
    ['Superstition survives because being wrong costs nothing.', 'Суеверия живут, потому что ошибка ничего не стоит.'],
    ['Scholars collect variants of the same tale worldwide.', 'Учёные собирают варианты одних и тех же сказаний по всему миру.'],
    ['Comparative mythology finds brothers under different names.', 'Сравнительная мифология находит братьев под разными именами.'],
    ['Joseph Campbell called it the heros journey.', 'Джозеф Кэмпбелл назвал это путешествием героя.'],
    ['Retellings keep old gods employed in new novels.', 'Пересказы дают старым богам работу в новых романах.'],
    ['Mythology survives because humans never stop asking why.', 'Мифология выжила, потому что люди не перестают спрашивать почему.'],
    ['Epic poetry began as memory before writing existed.', 'Эпическая поэзия началась как память, ещё до письменности.'],
    ['Bards carried genealogies inside rhymed verses.', 'Барды носили родословные в рифмованных строках.'],
    ['Homer asked the muse for help out loud.', 'Гомер вслух просил музу о помощи.'],
    ['Invocation openings still echo in fantasy prologues.', 'Зачины-призывы всё ещё звучат в прологах фэнтези.'],
    ['Kalevala verses built Finnish identity from songs.', 'Калевала строила финскую идентичность из песен.'],
    ['National epics surface whenever identities need anchors.', 'Национальные эпосы всплывают, когда идентичности нужны якоря.'],
    ['Beowulf monsters mirror the fears of their age.', 'Чудовища Беовульфа отражают страхи своей эпохи.'],
    ['Grendel envied joy he could never join.', 'Грендель завидовал радости, к которой не мог присоединиться.'],
  ],
};

export const videogamesshootersaction = {
  file: 'dictionaries/phrasebook-videogamesshootersaction.json',
  emoji: '🔫',
  description: 'Фразы из шутеров и экшен-игр: матч, команда, тактика, стриминг. Для геймеров и игровых чатов.',
  phrases: [
    ['Enemy spotted near the north exit.', 'Противник замечен у северного выхода.'],
    ['Cover me while I reload.', 'Прикрой, я перезаряжаюсь.'],
    ['I am pushing the objective now.', 'Я иду на точку сейчас.'],
    ['Hold this angle and wait for them.', 'Держи этот угол и жди их.'],
    ['Flanking around through the basement.', 'Обхожу через подвал.'],
    ['Two enemies left on the scoreboard.', 'На табло осталось двое противников.'],
    ['Reload behind cover, not in the open.', 'Перезаряжайся за укрытием, а не на открытом.'],
    ['Headshot through the smoke, lucky shot.', 'Хедшот сквозь дым — повезло.'],
    ['Their sniper is watching mid lane.', 'Их снайпер следит за центром карты.'],
    ['Smoke grenade out, move through quickly.', 'Дымовая граната брошена, быстро идём.'],
    ['Flashbang incoming, look away.', 'Светошумовая летит, отвернись.'],
    ['Defuse the bomb before the timer ends.', 'Разминируй бомбу до конца таймера.'],
    ['Plant is down, defend the site.', 'Бомба установлена, защищаем точку.'],
    ['Rotate to B, they are stacking A.', 'Переходи на B, они стекуются на A.'],
    ['Save your utility for the retake.', 'Береги гранаты для ретейка.'],
    ['Economy round, we buy pistols only.', 'Экономический раунд, покупаем только пистолеты.'],
    ['Full buy next round, save what you have.', 'Полная закупка в следующем раунде, сохраняй оружие.'],
    ['Drop me a weapon at spawn.', 'Скинь мне оружие на респавне.'],
    ['Nice clutch, one versus three.', 'Красивый клатч, один против трёх.'],
    ['That was pure luck, admit it.', 'Это была чистая удача, признай.'],
    ['My ping spiked right at the worst moment.', 'Пинг подскочил в худший момент.'],
    ['Lag cost us the whole round.', 'Лаг стоил нам всего раунда.'],
    ['Hit registration feels off tonight.', 'Регистрация попаданий сегодня хромает.'],
    ['Aim down sights before peeking corners.', 'Целься через прицел, прежде чем выглядывать из-за угла.'],
    ['Pre-aim common angles to win duels.', 'Забирай углы с заранее наведённым прицелом.'],
    ['Crosshair placement wins more fights than reflexes.', 'Правильное положение прицела выигрывает больше дуэлей, чем реакция.'],
    ['Strafe while shooting to dodge headshots.', 'Стрейфься во время стрельбы, чтобы уходить от хедшотов.'],
    ['Counter strafing stops movement for accurate shots.', 'Контрстрейф останавливает движение для точного выстрела.'],
    ['Spray control separates ranks more than aim.', 'Контроль отдачи разделяет ранги сильнее, чем аим.'],
    ['Tap fire at range, spray up close.', 'На дистанции стреляй одиночными, вблизи — очередями.'],
    ['Recoil patterns climb then drift sideways.', 'Отдача сначала идёт вверх, потом уводит вбок.'],
    ['Learn the recoil pattern in practice range.', 'Выучи паттерн отдачи на тренировочном полигоне.'],
    ['Sound cues reveal footsteps through walls.', 'Звук выдаёт шаги сквозь стены.'],
    ['Walk quietly when they listen for runners.', 'Иди тихо, когда они слушают бегущих.'],
    ['Crouch walking silences footsteps almost completely.', 'Шаги почти полностью замолкают на корточках.'],
    ['Use headphones, speakers hide directions.', 'Играй в наушниках — колонки прячут направление.'],
    ['Team composition needs a healer badly.', 'Нашему составу отчаянно нужен хилер.'],
    ['Ultimate abilities ready in thirty seconds.', 'Ультимейты будут готовы через тридцать секунд.'],
    ['Combo your ultimate with mine.', 'Соедини свой ультимейт с моим.'],
    ['Focus fire the support first.', 'Сначала сфокусируйте урон на поддержке.'],
    ['Peel for our sniper, he is getting dived.', 'Прикройте снайпера, на него прыгают.'],
    ['Spawn camping ruins casual matches.', 'Кемпинг респавна портит казуальные матчи.'],
    ['Teabagging says more about you than your skill.', 'Тибэгинг говорит о вас больше, чем ваш скилл.'],
    ['GG WP, that was a clean match.', 'Хорошая игра, чистый матч.'],
    ['Report that player for team killing.', 'Пожалуйтесь на игрока за тимкилл.'],
    ['Toxic chat mutes improve my winrate honestly.', 'Мут токсичного чата честно улучшает мой винрейт.'],
    ['Ranked season resets next week.', 'Рейтинговый сезон сбрасывается на следующей неделе.'],
    ['Placement matches decide your starting rank.', 'Матчи плейсментов определяют стартовый ранг.'],
    ['Smurfs ruin low rank lobbies.', 'Смурфы портят лобби низких рангов.'],
    ['Matchmaking put us against a five stack.', 'Подбор игроков выставил нас против пятёрки друзей.'],
    ['Battle pass tiers grind faster with challenges.', 'Боевой пропуск качается быстрее через задания.'],
    ['Daily challenges expire in four hours.', 'Ежедневные задания истекают через четыре часа.'],
    ['Skin market prices fluctuate like stocks.', 'Цены на скины колеблются как биржевые котировки.'],
    ['That knife skin cost more than my monitor.', 'Тот скин ножа стоил дороже моего монитора.'],
    ['Cosmetics change nothing but confidence everything.', 'Косметика не меняет ничего, кроме уверенности — всё.'],
    ['DLC maps split the player base again.', 'Карточки DLC снова разделили комьюнити.'],
    ['Patch notes nerfed my main weapon.', 'Патчноуты занерфили моё основное оружие.'],
    ['The meta shifted after the balance patch.', 'Мета сменилась после патча баланса.'],
    ['Speedrunners beat this campaign in forty minutes.', 'Спидраннеры проходят эту кампанию за сорок минут.'],
    ['Difficulty settings exist, use them proudly.', 'Уровни сложности существуют — пользуйся ими с гордостью.'],
    ['Checkpoint saves rescued my three hour progress.', 'Чекпоинты спасли мои три часа прогресса.'],
    ['Quick time events interrupt cutscenes annoyingly.', 'QTE раздражающе прерывают катсцены.'],
    ['Boss fight phase two adds new attack patterns.', 'Во второй фазе босс добавляет новые атаки.'],
    ['Learn the dodge timing before attacking.', 'Выучи тайминг уворота, прежде чем атаковать.'],
    ['Parry windows feel generous in this game.', 'Окна парирования в этой игре щедрые.'],
    ['Stealth missions fail loudly within seconds.', 'Стелс-миссии громко проваливаются за секунды.'],
    ['Alerted guards remember your last position.', 'Встревоженные охранники помнят последнюю позицию.'],
    ['Open world games drown players in icons.', 'Опенворлд игры топят игроков в иконках.'],
    ['Fast travel unlocks after discovering towers.', 'Быстрое перемещение открывается после захвата башен.'],
    ['Side quests outshine main stories sometimes.', 'Побочные квесты иногда затмевают основной сюжет.'],
    ['New game plus carries gear into harder runs.', 'Новая игра плюс переносит снаряжение в сложный заход.'],
    ['Frame drops hit during explosion heavy scenes.', 'Просадки кадров случаются в сценах со взрывами.'],
    ['Uncapped frame rates tear on older monitors.', 'Незаблокированный фреймрейт рвёт картинку на старых мониторах.'],
    ['Field of view settings widen survival odds.', 'Расширенный FOV повышает шансы на выживание.'],
    ['Motion sickness fades with higher FOV values.', 'Укачивание проходит при большем поле зрения.'],
    ['Controller aim assist sparks eternal debates.', 'Ассист прицеливания на геймпаде порождает вечные споры.'],
    ['Keyboard and mouse players dominate crossplay lobbies.', 'Клавомышь доминирует в кроссплейных лобби.'],
    ['Sensitivity settings take weeks to settle.', 'Чувствительность подбирается неделями.'],
    ['Lower sensitivity favours precision over flicks.', 'Низкая чувствительность любит точность, а не резкие движения.'],
    ['Streaming overlays hide health bars from viewers.', 'Стрим-оверлеи прячут полоски здоровья от зрителей.'],
    ['Chat backscreens show donations during clutch moments.', 'Экран чата показывает донаты в моменты клатчей.'],
    ['Clip that play before it disappears.', 'Записывай этот момент, пока он не исчез.'],
    ['Highlights compile themselves into weekly videos.', 'Хайлайты сами собираются в недельные видео.'],
    ['Esports casters hype crowd reactions professionally.', 'Комментаторы киберспорта профессионально разгоняют реакции толпы.'],
    ['LAN tournaments eliminate every excuse except skill.', 'LAN-турниры убирают все отговорки, кроме скилла.'],
    ['Practice routines beat raw talent eventually.', 'Тренировочные рутины со временем побеждают сырой талант.'],
    ['Aim trainers warm up wrists before ranked.', 'Аим-тренажёры разогревают запястье перед рейтингом.'],
    ['Deathmatch warms reflexes better than bots.', 'Дезматч греет рефлексы лучше ботов.'],
    ['Reviewing replays exposes habits you never noticed.', 'Разбор реплеев вскрывает привычки, которых вы не замечали.'],
    ['Take breaks, tilt loses more games than lag.', 'Делайте паузы — тильт проигрывает больше матчей, чем лаг.'],
    ['One more game means five more games.', '«Ещё одна игра» значит «ещё пять игр».'],
    ['Sleep beats grinding ranks at two in the morning.', 'Сон важнее гринда рангов в два часа ночи.'],
    ['Bunny hopping carries momentum across old maps.', 'Распрыжка несёт импульс через старые карты.'],
    ['Rocket jumps trade health for shortcuts.', 'Ракетные прыжки меняют здоровье на короткие пути.'],
    ['Movement shooters reward mastery of slides and dashes.', 'В подвижных шутерах мастерство слайдов и рывков решает.'],
    ['Wall running rewrites map routes entirely.', 'Бег по стенам полностью переписывает маршруты карт.'],
    ['Head glitching abuses cover geometry shamelessly.', 'Хедглейтинг бесстыдно использует геометрию укрытий.'],
    ['Peekers advantage favours whoever moves first.', 'Преимущество выглядывающего на стороне того, кто двигается первым.'],
    ['Pre-firing corners catches holders off guard.', 'Выстрел в угол до появления застаёт держащих врасплох.'],
    ['Jump shots land where enemies never expect.', 'Прыжковые выстрелы ложатся там, где их не ждут.'],
    ['Quick switching cancels reload animations faster.', 'Быстрая смена оружия отменяет анимацию перезарядки.'],
    ['Weapon loadouts balance range against mobility.', 'Лоадауты балансируют дальность против мобильности.'],
    ['Shotguns dominate stairwells and doorways.', 'Дробовики правят лестницами и дверными проёмами.'],
    ['Sniper glints betray positions across whole maps.', 'Блеск прицела снайпера выдаёт позицию через всю карту.'],
    ['Quick scoping turns snipers into aggressive duelists.', 'Куикскоп превращает снайпера в агрессивного дуэлянта.'],
    ['Hardcore modes remove HUDs and second chances.', 'Хардкорные режимы убирают интерфейс и вторые шансы.'],
    ['Friendly fire teaches trigger discipline painfully.', 'Огонь по своим больно учит дисциплине спускового крючка.'],
    ['Spectator mode doubles as free coaching.', 'Режим наблюдателя работает как бесплатный коучинг.'],
    ['Kill cams reveal exactly where you were outplayed.', 'Killcam показывает, где именно вас переиграли.'],
    ['Score streaks reward survival over aggression.', 'Серии очков награждают выживание, а не агрессию.'],
    ['Objective players win matches stat screens forget.', 'Игроки на цели выигрывают матчи, которых не видно в таблице.'],
  ],
};

export const hobbiesgardening = {
  file: 'dictionaries/phrasebook-hobbiesgardening.json',
  emoji: '🪴',
  description: 'Фразы о садоводстве: растения, уход, грядки, семена. Для дачи, сада и цветников.',
  phrases: [
    ['The tomatoes finally ripened this week.', 'Помидоры наконец созрели на этой неделе.'],
    ['Water deeply but not too often.', 'Поливайте глубоко, но не слишком часто.'],
    ['Morning watering beats evening watering for leaves.', 'Утренний полив полезнее для листьев вечернего.'],
    ['Mulch keeps moisture in and weeds out.', 'Мульча держит влагу и не пускает сорняки.'],
    ['Compost transforms kitchen scraps into black gold.', 'Компост превращает кухонные отходы в чёрное золото.'],
    ['Turn the compost pile every couple of weeks.', 'Переворачивайте компостную кучу раз в пару недель.'],
    ['Worms in the soil mean healthy ground.', 'Черви в земле значат здоровую почву.'],
    ['Test your soil pH before planting anything fussy.', 'Проверьте кислотность почвы перед посадкой капризных растений.'],
    ['Acid loving blueberries sulk in alkaline beds.', 'Голубика любит кислую почву и дуется в щелочных грядках.'],
    ['Crop rotation prevents soil exhaustion.', 'Севооборот спасает почву от истощения.'],
    ['Never plant tomatoes where potatoes grew last year.', 'Не сажайте помидоры там, где в прошлом году рос картофель.'],
    ['Legumes feed nitrogen back into the soil.', 'Бобовые возвращают азот в землю.'],
    ['Hardening off seedlings takes a patient week.', 'Закаливание рассады занимает терпеливую неделю.'],
    ['Seedlings stretch leggy toward insufficient light.', 'Рассада вытягивается от нехватки света.'],
    ['Grow lights rescue February seed trays.', 'Фитолампы спасают февральские лотки с рассадой.'],
    ['Label your seedlings or guess forever.', 'Подписывайте рассаду или гадайте вечно.'],
    ['Thin the seedlings so survivors thrive.', 'Прореживайте всходы, чтобы выжившие крепли.'],
    ['Pruning shears need sharpening every spring.', 'Секатор нужно точить каждую весну.'],
    ['Cut just above an outward facing bud.', 'Режьте чуть выше почки, смотрящей наружу.'],
    ['Deadheading spent blooms forces new flowers.', 'Удаление отцветших бутонов гонит новые цветы.'],
    ['Roses forgive clumsy pruning surprisingly often.', 'Розы удивительно часто просят неуклюжую обрезку.'],
    ['Late frost nipped my peach blossoms again.', 'Поздний заморозок опять прихватил персиковый цвет.'],
    ['Frost blankets save tender plants overnight.', 'Укрывные полотна спасают нежные растения за ночь.'],
    ['Harden your heart and thin the carrot rows.', 'Будьте тверды и проредите ряды моркови.'],
    ['Weeds pull easiest after rain.', 'Сорняки легче всего выдёргиваются после дождя.'],
    ['Mulching now saves weeding later.', 'Замульчируйте сейчас — меньше прополки потом.'],
    ['Groundcover plants crowd out invaders naturally.', 'Почвопокровные естественным образом теснят захватчиков.'],
    ['Slugs devoured my seedlings overnight.', 'Слизни съели мою рассаду за ночь.'],
    ['Beer traps catch slugs humanely enough.', 'Пивные ловушки ловят слизней достаточно гуманно.'],
    ['Copper tape repels snails off raised beds.', 'Медная лента отпугивает улиток с высоких грядок.'],
    ['Aphids farm ants and ants farm aphids.', 'Тля доит муравьёв, а муравьи пасут тлю.'],
    ['Ladybugs devour aphids by the hundreds.', 'Божьи коровки пожирают тлю сотнями.'],
    ['Neem oil handles most soft bodied pests.', 'Нимовое масло справляется с большинством мягкотелых вредителей.'],
    ['Beneficial insects need alternatives to poison.', 'Полезным насекомым нужна альтернатива яду.'],
    ['Pollinator flowers feed the bees that feed you.', 'Цветы для опылителей кормят пчёл, которые кормят вас.'],
    ['No bees means no zucchini, simple arithmetic.', 'Нет пчёл — нет кабачков, простая арифметика.'],
    ['Hand pollination works with a small paintbrush.', 'Ручное опыление работает маленькой кисточкой.'],
    ['Greenhouse humidity breeds mildew if unventilated.', 'Влажность в теплице плодит мучнистую росу без проветривания.'],
    ['Open the greenhouse doors before noon heat.', 'Открывайте теплицу до полуденной жары.'],
    ['Tomatoes crack from irregular watering schedules.', 'Помидоры трескаются от нерегулярного полива.'],
    ['Cucumbers drink more than any other crop here.', 'Огурцы пьют больше всех культур на этом участке.'],
    ['Zucchini overwhelms gardens and neighbours alike.', 'Кабачки заваливают и сады, и соседей.'],
    ['Lock your car during zucchini season.', 'Закрывайте машину в сезон кабачков.'],
    ['Herbs thrive on neglect and sunshine.', 'Травы процветают на пренебрежении и солнце.'],
    ['Basil pinches back into bushy shapes.', 'Базилик отщипыванием становится пышным кустиком.'],
    ['Mint invades everything unless potted separately.', 'Мята захватывает всё, если не посадить её отдельно.'],
    ['Rosemary hates wet feet in winter.', 'Розмарин ненавидит мокрые корни зимой.'],
    ['Perennials return like old friends each spring.', 'Многолетники возвращаются каждую весну как старые друзья.'],
    ['Divide overcrowded perennials in autumn.', 'Делите заросшие многолетники осенью.'],
    ['Bulbs plant pointy side up in autumn holes.', 'Луковицы сажают острым концом вверх в осенние лунки.'],
    ['Squirrels relocate tulip bulbs as a hobby.', 'Белки пересаживают тюльпановые луковицы как хобби.'],
    ['Daffodils naturalise into cheerful drifts.', 'Нарциссы дичают в весёлые полянки.'],
    ['Spring cleanup waits until pollinators wake.', 'Весеннюю уборку откладывают, пока не проснутся опылители.'],
    ['Leaf litter shelters overwintering butterflies.', 'Опавшие листья укрывают зимующих бабочек.'],
    ['Raised beds warm earlier than ground soil.', 'Высокие грядки прогреваются раньше открытой земли.'],
    ['Vertical gardening multiplies tiny balconies.', 'Вертикальное озеленение умножает крошечные балконы.'],
    ['Container gardening demands daily summer watering.', 'Контейнерное садоводство требует ежедневного летнего полива.'],
    ['Drainage holes matter more than pretty pots.', 'Дренажные отверстия важнее красивых горшков.'],
    ['Overwatering kills more houseplants than drought.', 'Перелив убивает комнатные растения чаще засухи.'],
    ['Stick a finger in the soil before every watering.', 'Проверяйте почву пальцем перед каждым поливом.'],
    ['Yellowing leaves whisper overwatering confessions.', 'Желтеющие листья шепчутся о переливе.'],
    ['Repot rootbound plants into slightly larger homes.', 'Пересаживайте растения с оплётёнными корнями чуть в большие горшки.'],
    ['Terracotta breathes, plastic holds water longer.', 'Терракота дышит, пластик дольше держит воду.'],
    ['Propagation turns one pothos into fifteen gifts.', 'Размножение превращает одно растение в пятнадцать подарков.'],
    ['Water roots grow differently than soil roots.', 'Водные корни растут иначе, чем земляные.'],
    ['Monstera fenestrations appear with maturity and light.', 'Разрезы монстеры появляются со зрелостью и светом.'],
    ['Dust blocks light, wipe broad leaves monthly.', 'Пыль блокирует свет — протирайте широкие листья ежемесячно.'],
    ['Rotating pots keeps growth even toward windows.', 'Поворачивайте горшки для ровного роста к окну.'],
    ['South windows scorch shade lovers.', 'Южные окна обжигают тенелюбивые растения.'],
    ['Humidity trays fake tropical comfort cheaply.', 'Поддоны с влажностью дёшево имитируют тропики.'],
    ['Grouping plants raises local humidity naturally.', 'Группировка растений естественно повышает влажность вокруг.'],
    ['Fertilise weakly weekly during growing season.', 'Подкармливайте слабым раствором еженедельно в сезон роста.'],
    ['Flush salts from pots every few months.', 'Промывайте соли из горшков каждые несколько месяцев.'],
    ['Pruning fear kills more bonsai than neglect.', 'Страх обрезки губит бонсай чаще заброшенности.'],
    ['Bonsai patience measures decades not weekends.', 'Бонсай измеряется десятилетиями, а не выходными.'],
    ['Wiring branches bends character into trunks.', 'Проволока вносит характер в стволы.'],
    ['Japanese gardens compose silence with stones.', 'Японские сады сочиняют тишину камнями.'],
    ['Rock gardens suit slopes nothing else wants.', 'Каменистые сады устраивают склоны, которые никто не хотел.'],
    ['Alpine plants hate wet winters more than cold.', 'Альпийцам мокрая зима страшнее холода.'],
    ['Wildflower meadows replace hungry lawns beautifully.', 'Луговые травы красиво заменяют прожорливые газоны.'],
    ['Lawns drink more than any vegetable bed.', 'Газоны пьют больше любой овощной грядки.'],
    ['Clover lawns feed bees and survive drought.', 'Клеверный газон кормит пчёл и переживает засуху.'],
    ['Grasscycling returns clippings as free fertiliser.', 'Мульчирование травы возвращает скошенное как бесплатное удобрение.'],
    ['Sharpen mower blades or grass tears brown.', 'Точите ножи газонокосилки, иначе трава рвётся и буреет.'],
    ['Fruit trees need winter pruning while dormant.', 'Плодовым деревьям нужна зимняя обрезка в покое.'],
    ['Thinning apples produces fewer but bigger fruit.', 'Прореживание яблок даёт меньше плодов, но крупнее.'],
    ['Grafting joins varieties onto hardy roots.', 'Прививка соединяет сорта с выносливыми корнями.'],
    ['Strawberries send runners like escape plans.', 'Земляника пускает усы как планы побега.'],
    ['Netting defends berries from birds better than scarecrows.', 'Сетка защищает ягоды от птиц лучше пугал.'],
    ['Raspberries fruit on canes of specific ages.', 'Малина плодоносит на побегах определённого возраста.'],
    ['Rhubarb leaves are poisonous, stalks are pie.', 'Листья ревеня ядовиты, черешки идут в пирог.'],
    ['Asparagus beds wait three years for first harvest.', 'Грядки спаржи ждут первого урожая три года.'],
    ['Patience is the heaviest tool in the shed.', 'Терпение — самый тяжёлый инструмент в сарае.'],
    ['Gardens teach failure gently and repeatedly.', 'Сады мягко и настойчиво учат терпеть неудачи.'],
    ['Every gardener buries a few plants as tuition.', 'Каждый садовод хоронит несколько растений как плату за обучение.'],
    ['Volunteer squash appeared where compost got dumped.', 'Тыква-самосёд выросла там, где вывалили компост.'],
    ['Gardening journals reveal patterns memory forgets.', 'Садовый дневник показывает закономерности, которые память забывает.'],
    ['Photograph the beds monthly to track changes.', 'Фотографируйте грядки ежемесячно, чтобы видеть перемены.'],
    ['Seed swaps spread varieties and friendships equally.', 'Обмен семенами распространяет сорта и дружбу одинаково.'],
    ['Heirloom seeds carry stories alongside flavours.', 'Семена наследуемых сортов несут истории вместе со вкусом.'],
    ['Hybrid seeds rarely reproduce true to type.', 'Гибридные семена редко повторяют родителей.'],
    ['Saving seeds closes the loop gloriously.', 'Свои семена красиво замыкают круг.'],
    ['Community gardens grow vegetables and neighbourhoods together.', 'Общественные сады растят овощи вместе с соседством.'],
    ['Garden tours judge lawns less than they think.', 'Садовые туры судят газоны меньше, чем им кажется.'],
    ['The best fertiliser is the gardener shadow, they say.', 'Лучшее удобрение — тень садовода, говорят они.'],
    ['Nothing tastes like a tomato still warm from sun.', 'Ничто не сравнится с помидором, ещё тёплым от солнца.'],
    ['Rain barrels catch roof water for dry weeks.', 'Дождевые бочки копят воду с крыши на сухие недели.'],
    ['Drip irrigation sips quietly where sprinklers waste.', 'Капельный полив пьёт тихо там, где спринклеры разбазаривают.'],
    ['Soaker hoses weep moisture along entire rows.', 'Поливальные шланги сочатся влагой вдоль целых рядов.'],
    ['Watering cans aim gentler than any hose nozzle.', 'Лейка льёт нежнее любой насадки шланга.'],
    ['Greywater from kitchens waters ornamentals happily.', 'Серая вода с кухни радует декоративные посадки.'],
    ['Succession sowing keeps salads coming all summer.', 'Повторные посевы держат салаты всё лето.'],
    ['Catch cropping squeezes harvests between seasons.', 'Промежуточные посевы впритык собирают урожаи между сезонами.'],
  ],
};
