// Fill-up for six thinnest phrasebooks (part A): artpainting,
// religionspirituality, sciencephysics, historyempires, technologygadgets,
// internetwebsites. Each topic targets >=100 curated entries.
// Emojis are copied verbatim from the current manifest rows on purpose:
// the build rewrites manifest emoji from topic.emoji.

export const artpainting = {
  file: 'dictionaries/phrasebook-artpainting.json',
  emoji: '🎨',
  description: 'Фразы о живописи и изобразительном искусстве: картины, стили, художники, выставки. Для галерей и разговора об искусстве.',
  phrases: [
    ['This painting catches my eye every time.', 'Эта картина каждый раз притягивает взгляд.'],
    ['What do you see in this abstract piece?', 'Что ты видишь в этой абстракции?'],
    ['The brushwork here is incredibly confident.', 'Мазки здесь невероятно уверенные.'],
    ['I prefer landscapes to portraits.', 'Я предпочитаю пейзажи портретам.'],
    ['The colours blend softly near the horizon.', 'У горизонта цвета сливаются мягко.'],
    ['Who painted this canvas?', 'Кто написал это полотно?'],
    ['This gallery opens a new exhibition every month.', 'Эта галерея открывает новую выставку каждый месяц.'],
    ['Even the frame is a work of art.', 'Даже рама здесь — произведение искусства.'],
    ['Watercolour punishes hesitation because you cannot hide a mistake.', 'Акварель наказывает за нерешительность — ошибку не скрыть.'],
    ['The still life looks simple until you try painting it.', 'Натюрморт выглядит простым, пока сам не попробуешь его написать.'],
    ['She works mostly with palette knives instead of brushes.', 'Она работает в основном мастихином, а не кистями.'],
    ['The underpainting shows through in the shadows.', 'Подмалёвок просвечивает в тенях.'],
    ['Glazing gives the sky that glowing depth.', 'Лессировка даёт небу это светящееся глубину.'],
    ['Impressionists painted light rather than objects.', 'Импрессионисты писали свет, а не предметы.'],
    ['Cubism breaks faces into geometric planes.', 'Кубизм разбивает лица на геометрические плоскости.'],
    ['Surrealism bends reality like a dream.', 'Сюрреализм изгибает реальность, как сон.'],
    ['This portrait captures her stubbornness perfectly.', 'Этот портрет идеально передаёт её упрямство.'],
    ['The artist left the background deliberately unfinished.', 'Художник нарочно оставил фон незавершённым.'],
    ['Notice how the shadows lead your eye to the doorway.', 'Заметь, как тени ведут взгляд к двери.'],
    ['My sketches stay loose because I overthink details.', 'Мои наброски остаются свободными, иначе я утону в деталях.'],
    ['Perspective drawing starts with the horizon line.', 'Перспектива начинается с линии горизонта.'],
    ['The vanishing point sits just off centre.', 'Точка схода лежит чуть сбоку от центра.'],
    ['Mixing complementary colours makes clean greys.', 'Смешение комплементарных цветов даёт чистые серые.'],
    ['Oil paint stays wet for days, which suits my pace.', 'Масло сохнет днями — это подходит моему темпу.'],
    ['Gouache dries matte and layers beautifully.', 'Гуашь высыхает матовой и красиво слоится.'],
    ['Acrylics dry too fast for blending large skies.', 'Акрил сохнет слишком быстро для больших растяжек неба.'],
    ['Stretching canvas properly saves cracks later.', 'Правильная натяжка холста избавит от трещин потом.'],
    ['Priming the canvas with gesso takes patience.', 'Грунтовка холста левкасом требует терпения.'],
    ['A limited palette actually simplifies colour decisions.', 'Ограниченная палитра упрощает выбор цветов.'],
    ['His early period looks nothing like his later work.', 'Его ранний период совсем не похож на поздние работы.'],
    ['The museum restored the varnish to its original clarity.', 'Музей восстановил лак до первоначальной прозрачности.'],
    ['Conservators cleaned centuries of grime off this panel.', 'Реставраторы сняли с этой доски века копоти.'],
    ['Cracked paint tells the story of bad storage.', 'Растрескавшаяся краска рассказывает о плохом хранении.'],
    ['This etching comes from a limited run of fifty.', 'Эта гравюра из тиража в пятьдесят оттисков.'],
    ['Lithography needs a completely different mindset than painting.', 'Литография требует совсем другого склада, чем живопись.'],
    ['Street art deserves the same analysis as gallery pieces.', 'Стрит-арт заслуживает того же разбора, что и галерейные работы.'],
    ['Murals change how a whole neighbourhood feels.', 'Муралы меняют ощущение целого района.'],
    ['The curator hung the small studies opposite the final canvas.', 'Куратор повесил этюды напротив итогового полотна.'],
    ['Audio guides ruin the silence I come to galleries for.', 'Аудиогиды разрушают тишину, ради которой я хожу в галереи.'],
    ['We queued an hour for the Vermeer exhibition.', 'Мы стояли час к выставке Вермеера.'],
    ['Photography is allowed without flash in this wing.', 'В этом крыле снимать можно без вспышки.'],
    ['The gift shop sells surprisingly good print reproductions.', 'В музейном магазине продают на удивление хорошие репродукции.'],
    ['I bought this print at the student degree show.', 'Я купил этот принт на выпускной выставке студентов.'],
    ['Commissioning a portrait costs less than you think.', 'Заказать портрет дешевле, чем кажется.'],
    ['The commission required three sittings and two revisions.', 'Над заказом было три сеанса и две правки.'],
    ['Art fairs overwhelm me within the first hour.', 'Арт-ярмарки утомляют меня уже через час.'],
    ['Collectors rarely explain why they buy what they buy.', 'Коллекционеры редко объясняют, почему покупают именно это.'],
    ['Provenance papers matter as much as the picture.', 'Документы происхождения важны не меньше самой картины.'],
    ['This study sold for ten times its estimate.', 'Этот этюд ушёл в десять раз дороже оценки.'],
    ['The auction catalogue notes restretching and minor inpainting.', 'В аукционном каталоге отмечены перетяжка и небольшая реставрация.'],
    ['Her studio smells of linseed oil and turpentine.', 'В её мастерской пахнет льняным маслом и скипидаром.'],
    ['North light keeps colours true through the day.', 'Северный свет сохраняет верность цвета весь день.'],
    ['I ruined a good canvas rushing the underdrawing.', 'Я испортил хороший холст, торопясь с рисунком.'],
    ['Charcoal smudges if you forget the fixative.', 'Уголь смазывается, если забыть про фиксатив.'],
    ['Contour drawing trains your eye faster than copying photos.', 'Рисунок контура тренирует глаз быстрее копирования фото.'],
    ['Gesture drawing captures movement in thirty seconds.', 'Набросок позы ловит движение за тридцать секунд.'],
    ['Value studies matter more than colour at this stage.', 'На этом этапе тональные эскизы важнее цвета.'],
    ['Warm light pushes forward, cool light recedes.', 'Тёплый свет выступает, холодный уходит вглубь.'],
    ['Cast shadows anchor objects to the ground plane.', 'Падающие тени привязывают предметы к плоскости.'],
    ['Reflected light in shadows keeps them alive.', 'Отражённый свет в тенях оставляет их живыми.'],
    ['The golden section hides in half the classics.', 'Золотое сечение прячется в половине классики.'],
    ['Rule of thirds is a crutch, but a useful one.', 'Правило третей — костыль, но полезный.'],
    ['Negative space shapes the composition as much as the subject.', 'Негативное пространство формирует композицию не меньше объекта.'],
    ['Rhythm in painting comes from repeated angles.', 'Ритм в живописи рождается из повторяющихся углов.'],
    ['This seascape conveys wind better than any photograph.', 'Эта марина передаёт ветер лучше любой фотографии.'],
    ['Botanical illustration demands almost scientific precision.', 'Ботаническая иллюстрация требует почти научной точности.'],
    ['Urban sketchers gather by the old bridge on Sundays.', 'Городские скетчеры собираются у старого моста по воскресеньям.'],
    ['Plein air painting teaches you to decide fast.', 'Работа на пленэре учит быстро принимать решения.'],
    ['The rain destroyed my paper halfway through the sketch.', 'Дождь уничтожил мою бумагу посреди наброска.'],
    ['Miniature painting tests patience like nothing else.', 'Миниатюра испытывает терпение как ничто другое.'],
    ['Icon painting follows strict canonical rules.', 'Иконопись следует строгим каноническим правилам.'],
    ['Fresco must be finished before the plaster dries.', 'Фреску нужно закончить, пока не высохла штукатурка.'],
    ['Tempera gives that unmistakable matte luminosity.', 'Темпера даёт неповторимое матовое свечение.'],
    ['Pastels sit on the surface and demand glass.', 'Пастель лежит на поверхности и требует стекла.'],
    ['Ink wash rewards bold single strokes.', 'Техника тушью награждает за смелые одиночные мазки.'],
    ['Collage lets me recycle failed drawings.', 'Коллаж позволяет спасти неудачные рисунки.'],
    ['Digital tablets mimic oils convincingly now.', 'Планшеты теперь убедительно имитируют масло.'],
    ['Nothing replaces the resistance of real bristles on canvas.', 'Но ничто не заменит сопротивление настоящей щетины на холсте.'],
    ['Colour theory finally clicked after mixing my own wheel.', 'Теория цвета встала на место, когда я смешал свой круг.'],
    ['Chroma and value are different conversations.', 'Насыщенность и тон — разные разговоры.'],
    ['Muted backgrounds make the focal colour sing.', 'Приглушённый фон заставляет главный цвет звучать.'],
    ['This nude study respects anatomy without stiffness.', 'Этот этюд обнажённой фигуры уважает анатомию без скованности.'],
    ['Hands are harder than faces, always.', 'Руки всегда сложнее лиц.'],
    ['Capturing likeness is ninety percent observation.', 'Сходство — это девяносто процентов наблюдения.'],
    ['The sitter fell asleep twice during the portrait.', 'Модель дважды заснула во время сеанса.'],
    ['Self-portraits honest up quickly.', 'Автопортреты быстро становятся честными.'],
    ['Art school taught me to defend every choice.', 'Художественная школа научила защищать каждое решение.'],
    ['Rejection letters from galleries make great bookmarks.', 'Отказы от галерей отлично работают закладками.'],
    ['Social media flattened taste into trends.', 'Соцсети превратили вкус в тренды.'],
    ['Still, a good painting stops the scroll every time.', 'И всё же хорошая картина останавливает ленту каждый раз.'],
    ['The docent explained the symbolism for twenty minutes.', 'Экскурсовод двадцать минут объяснял символику.'],
    ['Children ask the best questions about modern art.', 'Дети задают лучшие вопросы о современном искусстве.'],
    ['Is it art if nobody feels anything?', 'Это искусство, если никто ничего не чувствует?'],
    ['Craftsmanship earns my respect before concept does.', 'Мастерство завоёвывает моё уважение раньше концепции.'],
    ['This triptych reads left to right like a sentence.', 'Этот триптих читается слева направо, как предложение.'],
    ['The diptych hinges on the gap between panels.', 'Весь диптих держится на зазоре между створками.'],
    ['Installations photograph better than they feel in person.', 'Инсталляции фотогеничнее, чем они ощущаются вживую.'],
    ['Video art tests my patience unless the loop is short.', 'Видеоарт испытывает моё терпение, если цикл длинный.'],
    ['Performance art lives in memory, not in collections.', 'Перформанс живёт в памяти, а не в коллекциях.'],
    ['The retrospective traces forty years of doubt and daring.', 'Ретроспектива прослеживает сорок лет сомнений и смелости.'],
    ['I left the museum with a sketchbook full of notes.', 'Я вышел из музея с блокнотом полным заметок.'],
    ['Copy the masters to learn, never to pass off as yours.', 'Копируй мастеров, чтобы учиться, но не чтобы выдавать за своё.'],
    ['Every artist steals, then pays it back with interest.', 'Каждый художник заимствует, а потом возвращает с процентами.'],
    ['Talent opens the door, but only hours keep you in the room.', 'Талант открывает дверь, но в комнате удерживают только часы работы.'],
  ],
};

export const religionspirituality = {
  file: 'dictionaries/phrasebook-religionspirituality.json',
  emoji: '🙏',
  description: 'Фразы о религии и духовности: вера, практики, праздники, философские беседы. Для межкультурных разговоров.',
  phrases: [
    ['Do you celebrate any religious holidays?', 'Ты отмечаешь какие-нибудь религиозные праздники?'],
    ['Faith means different things to different people.', 'Вера значит разное для разных людей.'],
    ['The cathedral bells ring every hour.', 'Соборные колокола звонят каждый час.'],
    ['Visitors should dress modestly inside the temple.', 'Посетителям стоит одеваться скромно внутри храма.'],
    ['Shoes stay at the entrance of the mosque.', 'Обувь оставляют у входа в мечеть.'],
    ['The service begins at nine on Sunday mornings.', 'Служба начинается в девять в воскресенье утром.'],
    ['The choir sang so beautifully that people wept.', 'Хор пел так прекрасно, что люди плакали.'],
    ['Candles flicker along the entire altar.', 'Свечи мерцают вдоль всего алтаря.'],
    ['She lights a candle for her grandmother every visit.', 'Она ставит свечку за бабушку при каждом визите.'],
    ['The monk rises before dawn for meditation.', 'Монах поднимается до рассвета для медитации.'],
    ['Silence is part of the practice here.', 'Тишина — часть практики в этих местах.'],
    ['Pilgrims walk hundreds of kilometres on this route.', 'Паломники проходят сотни километров по этому маршруту.'],
    ['The pilgrimage ends at the steps of the basilica.', 'Паломничество заканчивается на ступенях базилики.'],
    ['Fasting teaches discipline more than hunger.', 'Пост учит дисциплине больше, чем голоду.'],
    ['We break the fast together at sunset.', 'Мы разговляемся вместе на закате.'],
    ['Ramadan shifts earlier every year on the calendar.', 'Рамадан каждый год сдвигается раньше по календарю.'],
    ['Easter is the most important feast for us.', 'Пасха — самый важный праздник для нас.'],
    ['Christmas Eve dinner starts when the first star appears.', 'Ужин в Сочельник начинается с первой звездой.'],
    ['The menorah burns for eight nights.', 'Менора горит восемь вечеров подряд.'],
    ['Diwali lights up the whole neighbourhood.', 'Дивали озаряет весь квартал.'],
    ['The imam delivered a sermon about patience.', 'Имам произнёс проповедь о терпении.'],
    ['The rabbi answered our questions for an hour.', 'Раввин целый час отвечал на наши вопросы.'],
    ['The priest blesses the fields every spring.', 'Священник освящает поля каждую весну.'],
    ['Their wedding included vows from both traditions.', 'На их свадьбе прозвучали обеты обеих традиций.'],
    ['Funerals here focus on celebrating a life.', 'Здесь на похоронах скорее празднуют жизнь человека.'],
    ['Grief needs ritual as much as words.', 'Горю нужны ритуалы не меньше, чем слова.'],
    ['The sacred text sits wrapped in cloth.', 'Священный текст завёрнут в ткань.'],
    ['Passages are chanted rather than read aloud.', 'Отрывки поют, а не читают вслух.'],
    ['Translation always loses something in scripture.', 'Перевод всегда что-то теряет в писании.'],
    ['Interpretations differ even within one community.', 'Толкования расходятся даже внутри одной общины.'],
    ['The elders gather to discuss the question.', 'Старейшины собираются обсудить этот вопрос.'],
    ['Doubt is welcome in honest conversation.', 'Сомнение приветствуется в честном разговоре.'],
    ['Agnostic does not mean indifferent.', 'Агностик — не значит равнодушный.'],
    ['He identifies as spiritual but not religious.', 'Он называет себя духовным, но не религиозным.'],
    ['Meditation calmed my mind more than arguments ever did.', 'Медитация успокоила мой разум сильнее любых споров.'],
    ['Breathing slowly is harder than it sounds.', 'Медленно дышать сложнее, чем кажется.'],
    ['The retreat bans phones for a whole week.', 'На ретрите запрещены телефоны всю неделю.'],
    ['Gratitude journaling changed my mornings.', 'Дневник благодарности изменил мои утра.'],
    ['Mindfulness simply means paying attention.', 'Осознанность — это просто внимание.'],
    ['The bell marks the beginning and end of sitting.', 'Колокольчик отмечает начало и конец сидячей медитации.'],
    ['Karma is often misunderstood as punishment.', 'Карму часто понимают как наказание, и зря.'],
    ['Reincarnation raises more questions than it answers for me.', 'Реинкарнация порождает для меня больше вопросов, чем ответов.'],
    ['The lotus grows out of mud, which is the whole point.', 'Лотос растёт из грязи — в этом и смысл.'],
    ['Their shrine overlooks the rice terraces.', 'Их алтарь смотрит на рисовые террасы.'],
    ['Offerings of fruit cover the small altar.', 'Маленький алтарь уставлен фруктовыми подношениями.'],
    ['Incense smoke curls toward the ceiling paintings.', 'Дым благовоний вьётся к потолочным росписям.'],
    ['The mosaic depicts scenes from the old testament.', 'Мозаика изображает сцены Ветхого Завета.'],
    ['Stained glass turns sunlight into stories.', 'Витражи превращают солнечный свет в истории.'],
    ['Icons are written, not painted, according to tradition.', 'По традиции иконы пишут, а не рисуют.'],
    ['The bell tower offers a view of the whole valley.', 'С колокольни видна вся долина.'],
    ['Sunday school taught us songs better than theology.', 'В воскресной школе нас учили песням лучше, чем теологии.'],
    ['Confirmation classes met every Thursday evening.', 'Занятия для конфирмации проходили каждый четверг вечером.'],
    ['Bar mitzvah preparations take years of study.', 'Подготовка к бар-мицве занимает годы учёбы.'],
    ['The mosque courtyard stays cool even in August.', 'Во дворе мечети прохладно даже в августе.'],
    ['Call to prayer echoes across the rooftops five times daily.', 'Призыв к молитве звучит над крышами пять раз в день.'],
    ['Wudu stations line the entrance hall.', 'У входа выстроены места для омовения.'],
    ['Sikh temples serve free meals to anyone who comes.', 'Сикхские храмы кормят бесплатно всех приходящих.'],
    ['Volunteering in the kitchen counts as worship there.', 'Работа на кухне считается служением.'],
    ['Interfaith dialogues start with listening, not debating.', 'Межрелигиозные диалоги начинаются со слушания, а не споров.'],
    ['We compared traditions and found more overlap than expected.', 'Мы сравнили традиции и нашли больше общего, чем ожидали.'],
    ['Respect costs nothing and opens every door.', 'Уважение ничего не стоит и открывает все двери.'],
    ['Ask before photographing any ceremony.', 'Спрашивай разрешения перед съёмкой любой церемонии.'],
    ['Some rituals are closed to outsiders, and that is fine.', 'Некоторые ритуалы закрыты для чужих, и это нормально.'],
    ['The spring festival celebrates renewal and forgiveness.', 'Весенний праздник посвящён обновлению и прощению.'],
    ['Processions wind through the old town carrying lanterns.', 'Процессии с фонарями петляют по старому городу.'],
    ['Pilgrims tie ribbons to the ancient tree.', 'Паломники вяжут ленточки на древнее дерево.'],
    ['The healing spring attracts believers and sceptics alike.', 'Целебный источник привлекает и верующих, и скептиков.'],
    ['Superstition and faith are not the same thing.', 'Суеверие и вера — не одно и то же.'],
    ['My grandmother prayed every night without fail.', 'Бабушка молилась каждый вечер без пропусков.'],
    ['Her rosary worn smooth from decades of use.', 'Её чётки отполированы десятилетиями использования.'],
    ['Prayer beads help some people focus.', 'Чётки помогают некоторым сосредоточиться.'],
    ['Chanting synchronises breathing and voice.', 'Пение мантр синхронизирует дыхание и голос.'],
    ['The gospel choir rehearsed late into the night.', 'Евангелический хор репетировал допоздна.'],
    ['Sufi whirling looks like prayer in motion.', 'Суфийское кружение похоже на молитву в движении.'],
    ['Gospel music carries sorrow and joy in the same verse.', 'В госпеле печаль и радость живут в одном куплете.'],
    ['The organ filled the nave with sound.', 'Орган наполнил неф звуком.'],
    ['Weddings in this church require months of preparation.', 'Свадьба в этой церкви требует месяцев подготовки.'],
    ['Baptisms happen on the first Sunday of the month.', 'Крещения проводят в первое воскресенье месяца.'],
    ['Godparents take their promises seriously here.', 'Крёстные здесь серьёзно относятся к обещаниям.'],
    ['Naming ceremonies differ wildly between cultures.', 'Церемонии наречения именем сильно различаются между культурами.'],
    ['Coming of age ceremonies mark responsibility, not just age.', 'Обряды взросления отмечают ответственность, а не только возраст.'],
    ['The monastery accepts guests for weekend stays.', 'Монастырь принимает гостей на выходные.'],
    ['Monastic life follows a strict schedule of prayer and work.', 'Монашеская жизнь подчинена строгому распорядку молитвы и труда.'],
    ['Vows of silence fascinate those of us who talk too much.', 'Обеты молчания завораживают таких болтунов, как я.'],
    ['The abbot greeted us with unexpected humour.', 'Настоятель встретил нас неожиданным юмором.'],
    ['Simple food tastes richer after a day of manual work.', 'Простая еда вкуснее после дня физического труда.'],
    ['Charity sits at the centre of every tradition I know.', 'Милосердие в центре каждой известной мне традиции.'],
    ['Doctrine divides, kindness rarely does.', 'Доктрины разделяют, доброта — почти никогда.'],
    ['History records wars fought over interpretations.', 'История помнит войны за толкования.'],
    ['Hopefully the next generation argues less and helps more.', 'Будем надеяться, следующее поколение будет меньше спорить и больше помогать.'],
    ['The cemetery paths are lined with century-old oaks.', 'Дорожки кладбища обрамлены вековыми дубами.'],
    ['Gravestone inscriptions preserve whole biographies in few words.', 'Надгробные надписи хранят целые биографии в нескольких словах.'],
    ['Remembrance matters to the living more than the dead.', 'Память нужна живым больше, чем умершим.'],
    ['Every faith wrestles with the same hard questions.', 'Каждая вера борется с одними и теми же трудными вопросами.'],
    ['Meaning is built, not found ready-made.', 'Смысл строят, а не находят готовым.'],
    ['The chapel stays open all night during exams week.', 'Часовня открыта всю ночь в экзаменационную неделю.'],
    ['Even atheists appreciate the architecture.', 'Даже атеисты ценят эту архитектуру.'],
    ['The tour covers five places of worship in one afternoon.', 'Экскурсия охватывает пять храмов за один день.'],
    ['Our guide explained each custom without judgement.', 'Гид объяснял каждый обычай без осуждения.'],
    ['Curiosity turned out to be the best passport.', 'Любопытство оказалось лучшим паспортом.'],
  ],
};

export const sciencephysics = {
  file: 'dictionaries/phrasebook-sciencephysics.json',
  emoji: '🔬',
  description: 'Фразы о физике и науке: материя, энергия, законы, эксперименты. Для учёбы и научно-популярных бесед.',
  phrases: [
    ['Gravity keeps our feet on the ground.', 'Гравитация держит наши ноги на земле.'],
    ['Energy cannot be created or destroyed, only converted.', 'Энергия не создаётся и не исчезает, а лишь переходит.'],
    ['Every action has an equal and opposite reaction.', 'Каждому действию есть равное противодействие.'],
    ['The experiment failed, which is still a result.', 'Эксперимент провалился, но это тоже результат.'],
    ['Always state your hypothesis before looking at the data.', 'Формулируй гипотезу до взгляда на данные.'],
    ['The control group keeps the comparison honest.', 'Контрольная группа делает сравнение честным.'],
    ['Repeat measurements reduce random error.', 'Повторные измерения снижают случайную погрешность.'],
    ['Correlation does not imply causation.', 'Корреляция не означает причинность.'],
    ['The sample size was too small to conclude anything.', 'Выборка слишком мала для выводов.'],
    ['Peer review exists to catch our mistakes.', 'Рецензирование существует, чтобы ловить наши ошибки.'],
    ['The paper was retracted after replication failed.', 'Статью отозвали, когда повторить результат не удалось.'],
    ['Publishing negative results helps everyone.', 'Публикация отрицательных результатов полезна всем.'],
    ['Light behaves as both wave and particle.', 'Свет ведёт себя и как волна, и как частица.'],
    ['The double slit experiment still bends my mind.', 'Опыт с двумя щелями по-прежнему ломает мне голову.'],
    ['Absolute zero equals minus two hundred seventy-three degrees Celsius.', 'Абсолютный нуль — это минус двести семьдесят три градуса Цельсия.'],
    ['Entropy always increases in a closed system.', 'Энтропия в замкнутой системе только растёт.'],
    ['A perpetual motion machine violates thermodynamics.', 'Вечный двигатель нарушает термодинамику.'],
    ['Speed of light sets the universal speed limit.', 'Скорость света задаёт предел скорости во Вселенной.'],
    ['Time dilation sounds like science fiction until GPS proves it daily.', 'Замедление времени звучит как фантастика, пока GPS не доказывает его ежедневно.'],
    ['Mass and weight are not synonyms.', 'Масса и вес — не синонимы.'],
    ['Your weight changes on the Moon, your mass does not.', 'На Луне меняется вес, но не масса.'],
    ['Acceleration is change in velocity over time.', 'Ускорение — это изменение скорости за время.'],
    ['Friction converts motion into heat.', 'Трение превращает движение в тепло.'],
    ['Momentum equals mass times velocity.', 'Импульс равен массе, умноженной на скорость.'],
    ['The pendulum swings with predictable regularity.', 'Маятник качается с предсказуемой регулярностью.'],
    ['Resonance shattered the bridge, not wind alone.', 'Мост разрушил резонанс, а не только ветер.'],
    ['Sound travels faster through water than air.', 'Звук быстрее распространяется в воде, чем в воздухе.'],
    ['Vacuum carries no sound at all.', 'В вакууме звук не распространяется вовсе.'],
    ['Static electricity builds up on dry winter days.', 'Статическое электричество копится сухими зимними днями.'],
    ['Opposite charges attract, like charges repel.', 'Разноимённые заряды притягиваются, одноимённые отталкиваются.'],
    ['Voltage drives current through resistance.', 'Напряжение гонит ток через сопротивление.'],
    ['Ohm law ties voltage, current and resistance together.', 'Закон Ома связывает напряжение, ток и сопротивление.'],
    ['Short circuits happen when current finds an easier path.', 'Короткое замыкание случается, когда ток находит лёгкий путь.'],
    ['Magnets always have two poles.', 'У магнита всегда два полюса.'],
    ['Cutting a magnet in half makes two smaller magnets.', 'Разрежьте магнит — получите два меньших магнита.'],
    ['Electromagnets switch on and off with current.', 'Электромагниты включаются и выключаются током.'],
    ['Induction chargers transfer power without contact.', 'Индукционные зарядки передают энергию без контакта.'],
    ['Radio waves carry signals across continents.', 'Радиоволны переносят сигналы через континенты.'],
    ['Microwaves excite water molecules to heat food.', 'Микроволны раскачивают молекулы воды, нагревая еду.'],
    ['X-rays pass through soft tissue but not bone.', 'Рентген проходит через мягкие ткани, но не кости.'],
    ['Ultraviolet light causes sunburn.', 'Ультрафиолет вызывает солнечные ожоги.'],
    ['Infrared cameras reveal heat signatures at night.', 'Инфракрасные камеры показывают тепловые следы ночью.'],
    ['Half-life measures radioactive decay rate.', 'Период полураспада измеряет скорость распада.'],
    ['Carbon dating reads ages from isotopes.', 'Радиоуглеродный анализ определяет возраст по изотопам.'],
    ['Nuclear fusion powers the Sun.', 'Солнце питает термоядерный синтез.'],
    ['Fusion produces less waste than fission.', 'Синтез даёт меньше отходов, чем деление.'],
    ['Chain reactions require critical mass.', 'Цепная реакция требует критической массы.'],
    ['Quantum entanglement links particles across distance.', 'Квантовая запутанность связывает частицы на расстоянии.'],
    ['Superposition means a particle holds multiple states at once.', 'Суперпозиция значит, что частица пребывает в нескольких состояниях сразу.'],
    ['Measurement itself disturbs the system.', 'Само измерение возмущает систему.'],
    ['Uncertainty is built into nature, not just our instruments.', 'Неопределённость заложена в природе, а не только в приборах.'],
    ['Semiconductors conduct under precise conditions.', 'Полупроводники проводят ток при точных условиях.'],
    ['Doping silicon changes its conductivity dramatically.', 'Легирование кремния резко меняет проводимость.'],
    ['Transistors switch billions of times per second.', 'Транзисторы переключаются миллиарды раз в секунду.'],
    ['Superconductors lose all electrical resistance when cooled.', 'Сверхпроводники теряют сопротивление при охлаждении.'],
    ['Plasma is the fourth state of matter.', 'Плазма — четвёртое состояние вещества.'],
    ['Liquid crystals flow like liquids but align like crystals.', 'Жидкие кристаллы текут как жидкости, но выстраиваются как кристаллы.'],
    ['Surface tension lets insects walk on water.', 'Благодаря поверхностному натяжению насекомые ходят по воде.'],
    ['Capillary action pulls water up thin tubes.', 'Капиллярность поднимает воду по тонким трубкам.'],
    ['Pressure doubles every ten metres underwater.', 'Каждые десять метров под водой давление удваивается.'],
    ['Archimedes shouted Eureka in his bathtub for a reason.', 'Архидед кричал «Эврика» в ванне не просто так.'],
    ['Density decides whether objects float or sink.', 'Плотность решает, плавает предмет или тонет.'],
    ['Ice floats because freezing expands water.', 'Лёд плавает, потому что вода при замерзании расширяется.'],
    ['Boiling point drops at high altitude.', 'Точка кипения падает на большой высоте.'],
    ['Evaporation cools whatever it leaves behind.', 'Испарение охлаждает то, что осталось.'],
    ['Convection currents stir the atmosphere.', 'Конвекционные потоки перемешивают атмосферу.'],
    ['Metals conduct heat quickly, which is why handles stay cool.', 'Металлы быстро проводят тепло, поэтому ручки остаются прохладными.'],
    ['Radiation transfers heat even through vacuum.', 'Излучение переносит тепло даже через вакуум.'],
    ['The greenhouse effect is basic physics, not opinion.', 'Парниковый эффект — базовая физика, а не мнение.'],
    ['Kinetic energy grows with the square of speed.', 'Кинетическая энергия растёт квадратично со скоростью.'],
    ['Potential energy waits in the stretched spring.', 'Потенциальная энергия ждёт в растянутой пружине.'],
    ['Work equals force times distance moved.', 'Работа равна силе, умноженной на перемещение.'],
    ['Power measures how fast work gets done.', 'Мощность измеряет быстроту совершения работы.'],
    ['Efficiency never reaches one hundred percent.', 'КПД никогда не достигает ста процентов.'],
    ['Waste heat escapes every engine.', 'Из каждого двигателя уходит тепло впустую.'],
    ['Levers trade distance for force.', 'Рычаги меняют расстояние на силу.'],
    ['Pulleys multiply lifting power cheaply.', 'Блоки дёшево умножают подъёмную силу.'],
    ['Gears change speed into torque.', 'Шестерни превращают скорость в крутящий момент.'],
    ['Centrifugal force pins you to the carousel wall.', 'Центробежная сила прижимает вас к стенке карусели.'],
    ['Orbits are endless falling around a planet.', 'Орбиты — это бесконечное падение вокруг планеты.'],
    ['Escape velocity equals eleven kilometres per second from Earth.', 'Вторая космическая скорость с Земли — одиннадцать километров в секунду.'],
    ['Tides follow the Moon more than the Sun.', 'Приливы зависят от Луны больше, чем от Солнца.'],
    ['Eclipses happen because of cosmic coincidence in sizes.', 'Затмения возможны благодаря космическому совпадению размеров.'],
    ['Telescopes collect light, they do not magnify alone.', 'Телескопы собирают свет, а не только увеличивают.'],
    ['Redshift reveals an expanding universe.', 'Красное смещение выдаёт расширение Вселенной.'],
    ['Cosmic microwave background is the oldest light we can detect.', 'Реликтовое излучение — древнейший доступный нам свет.'],
    ['Dark matter outweighs visible matter five to one.', 'Тёмная материя превосходит видимую в пять раз.'],
    ['Dark energy accelerates cosmic expansion.', 'Тёмная энергия ускоряет расширение Вселенной.'],
    ['Black holes bend light beyond escape.', 'Чёрные дыры искривляют свет так, что он не может вырваться.'],
    ['Nothing escapes the event horizon.', 'За горизонт событий не выбирается ничто.'],
    ['Spacetime curves around mass.', 'Пространство-время искривляется вокруг массы.'],
    ['Einstein published relativity as a patent clerk.', 'Эйнштейн опубликовал теорию относительности, будучи клерком в патентном бюро.'],
    ['Newton invented calculus partly to explain planetary motion.', 'Ньютон придумал анализ отчасти для объяснения движения планет.'],
    ['Curie carried test tubes of radium in her pockets.', 'Кюри носила пробирки с радием в карманах.'],
    ['Science advances one funeral at a time, someone joked.', 'Наука продвигается похоронами за похоронами, пошутил кто-то.'],
    ['A good experiment embarrasses the researcher first.', 'Хороший эксперимент сначала смущает самого исследователя.'],
    ['Models are maps, never the territory.', 'Модели — это карты, но не сама местность.'],
    ['Statistics can mislead when cherry-picked.', 'Статистика обманывает, если выбирать удобное.'],
    ['Show me the error bars before the headline.', 'Сначала покажите погрешности, потом заголовки.'],
    ['Extraordinary claims require extraordinary evidence.', 'Исключительные заявления требуют исключительных доказательств.'],
    ['The lab notebook matters more than memory.', 'Лабораторный журнал надёжнее памяти.'],
    ['Calibrate the instrument before trusting a single reading.', 'Калибруй прибор, прежде чем доверять хоть одному показанию.'],
    ['Safety goggles exist because someone lost an eye.', 'Защитные очки существуют, потому что кто-то потерял глаз.'],
    ['Curiosity is the only prerequisite for physics.', 'Для физики нужно только любопытство.'],
  ],
};

export const historyempires = {
  file: 'dictionaries/phrasebook-historyempires.json',
  emoji: '📜',
  description: 'Фразы об империях и великих эпохах: власть, войны, расцвет и падение государств. Для любителей истории.',
  phrases: [
    ['The Roman Empire lasted roughly five centuries in the west.', 'Западная Римская империя просуществовала около пяти веков.'],
    ['All roads famously led to Rome.', 'Все дороги, как известно, вели в Рим.'],
    ['Roman aqueducts still stand after two thousand years.', 'Римские акведуки стоят две тысячи лет.'],
    ['Legions marched on roads they built themselves.', 'Легионы шли по дорогам собственного строительства.'],
    ['Caesar crossed the Rubicon and broke the republic.', 'Цезарь перешёл Рубикон и сломал республику.'],
    ['The Senate declared emperors, then lost control of them.', 'Сенат возводил императоров, а потом терял над ними контроль.'],
    ['Constantinople bridged Europe and Asia for a thousand years.', 'Константинополь тысячу лет соединял Европу и Азию.'],
    ['Byzantine diplomacy outlived Byzantine armies.', 'Византийская дипломатия пережила византийские армии.'],
    ['Greek fire guarded the harbour walls.', 'Греческий огонь стражал стены гавани.'],
    ['The Ottomans conquered Constantinople in fourteen fifty-three.', 'Османы взяли Константинополь в тысяча четыреста пятьдесят третьем.'],
    ['Ottoman sultans ruled three continents at their peak.', 'Османские султаны на пике правили тремя континентами.'],
    ['The devshirme system raised officials from conquered families.', 'Система девширме растила чиновников из покорённых семей.'],
    ['Janissaries began as loyal slaves and ended as kingmakers.', 'Янычары начались верными рабами, а кончили вершителями судеб.'],
    ['Suleiman the Magnificent codified laws as eagerly as he waged war.', 'Сулейман Великолепный кодифицировал законы столь же охотно, как вёл войны.'],
    ['The Mongol Empire covered the largest contiguous land ever.', 'Монгольская империя была крупнейшим сплошным государством в истории.'],
    ['Genghis Khan united rival tribes through conquest and law.', 'Чингисхан объединил враждующие племена завоеванием и законом.'],
    ['Mongol couriers relayed messages across continents in days.', 'Монгольские гонцы доставляли сообщения через континенты за дни.'],
    ['The Silk Road flourished under Mongol protection.', 'Шёлковый путь расцвёл под монгольской защитой.'],
    ['Trade spread plagues as efficiently as silk.', 'Торговля разносила моры так же эффективно, как шёлк.'],
    ['Alexander built an empire faster than anyone could administer it.', 'Александр построил империю быстрее, чем смог ею управлять.'],
    ['His generals divided the conquests like an inheritance.', 'Его полководцы разделили завоевания, как наследство.'],
    ['Alexandria kept its library burning bright for centuries.', 'Александрия веками держала свою библиотеку горящей.'],
    ['The Persian Empire ran on roads and tolerance.', 'Персидская держава держалась на дорогах и веротерпимости.'],
    ['Royal couriers crossed the empire in a week.', 'Царские курьеры пересекали державу за неделю.'],
    ['Satraps governed provinces and paid tribute faithfully, usually.', 'Сатрапы управляли провинциями и платили дань исправно, обычно.'],
    ['The British Empire once governed a quarter of humanity.', 'Британская империя когда-то управляла четвертью человечества.'],
    ['The sun never set on territories spanning every ocean.', 'Солнце не заходило над владениями во всех океанах.'],
    ['Naval power made island empires possible.', 'Морская сила сделала островные империи возможными.'],
    ['Colonial administration often ruled through local elites.', 'Колониальные администрации часто правили через местных элит.'],
    ['Railways built for extraction reshaped continents anyway.', 'Железные дороги для вывоза ресурсов всё равно перекроили континенты.'],
    ['Independence movements learned nationalism from their rulers.', 'Движения за независимость переняли национализм у самих властителей.'],
    ['Decolonisation redrew maps faster than conquest had.', 'Деколонизация перекроила карты быстрее завоеваний.'],
    ['The Spanish Empire funded itself with American silver.', 'Испанская империя кормилась американским серебром.'],
    ['Silver inflation wrecked Spanish finances eventually.', 'Серебряная инфляция в итоге подкосила испанские финансы.'],
    ['Armadas sink, empires adapt or collapse.', 'Армады тонут, а империи адаптируются или гибнут.'],
    ['The Habsburgs married their way across Europe.', 'Габсбурги женились по всей Европе вместо войн.'],
    ['Bella gerant alii, tu felix Austria nube.', 'Пусть воюют другие, а ты, счастливая Австрия, выходи замуж.'],
    ['Empires of inheritance fracture among heirs predictably.', 'Наследственные империи предсказуемо дробятся между наследниками.'],
    ['The Austro-Hungarian compromise created a state of two crowns.', 'Австро-венгерский компромисс создал государство двух корон.'],
    ['Nationalism dissolved multinational empires within decades.', 'Национализм растворил многонациональные империи за считанные десятилетия.'],
    ['The Qing dynasty expanded into Central Asia aggressively.', 'Династия Цин агрессивно расширялась в Центральную Азию.'],
    ['The Opium Wars forced open Chinese ports.', 'Опиумные войны силой открыли китайские порты.'],
    ['Unequal treaties humiliated a proud civilisation.', 'Неравноправные договоры унизили гордую цивилизацию.'],
    ['The Meiji restoration industrialised Japan within a generation.', 'Реставрация Мэйдзи индустриализировала Японию за одно поколение.'],
    ['Japan defeated a European empire in nineteen oh five.', 'Япония победила европейскую державу в тысяча девятьсот пятом.'],
    ['Industrial capacity decided twentieth century wars.', 'Индустриальная мощь решала войны двадцатого века.'],
    ['Empires rose on bronze, then iron changed everything.', 'Империи вставали на бронзе, потом железо всё изменило.'],
    ['Assyria ruled through fear and deported populations.', 'Ассирия правила страхом и депортациями народов.'],
    ['Babylon fell in a single night, the chronicles claim.', 'Вавилон пал за одну ночь, утверждают хроники.'],
    ['Egypt endured pharaohs for three thousand years.', 'Египет выдержал три тысячи лет фараонов.'],
    ['The Rosetta stone unlocked hieroglyphs for everyone.', 'Розеттский камень открыл иероглифы для всех.'],
    ['Inca runners carried messages along mountain roads.', 'Инкские гонцы несли вести по горным дорогам.'],
    ['The Inca empire administered without writing or wheels.', 'Империя инков управлялась без письменности и колёс.'],
    ['Spanish conquistadors arrived seeking gold and found empires.', 'Испанские конкистадоры искали золото, а нашли империи.'],
    ['Smallpox conquered where armies struggled.', 'Оспа завоёвывала там, где вязли армии.'],
    ['The Mali empire grew rich on gold and salt trade.', 'Империя Мали разбогатела на торговле золотом и солью.'],
    ['Mansa Musa devalued Cairo simply by spending there.', 'Манса Муса обесценил Каир одной лишь щедростью.'],
    ['Timbuktu became synonymous with distant learning.', 'Тимбукту стал синонимом далёкой учёности.'],
    ['Empires tax trade routes more profitably than farms.', 'Империи облагают торговые пути выгоднее, чем фермы.'],
    ['Ports outgrow palaces in the long run.', 'Порты в итоге перерастают дворцы.'],
    ['Venice ruled a maritime empire without conquering land.', 'Венеция правила морской империей, не завоёвывая земли.'],
    ['The Venetian arsenal launched a ship a day at its peak.', 'Венецианский арсенал спускал корабль в день на пике.'],
    ['Hanseatic merchants bound northern Europe in trade leagues.', 'Ганзейские купцы связали Северную Европу торговыми союзами.'],
    ['Merchant republics elected doges and dukes cautiously.', 'Купеческие республики осторожно избирали дожей и герцогов.'],
    ['Empires standardise weights, coins and calendars.', 'Империи стандартизируют меры, монеты и календари.'],
    ['Standardisation quietly outlasts every army.', 'Стандартизация тихо переживает любую армию.'],
    ['Latin survived Rome as the language of learning.', 'Латынь пережила Рим как язык науки.'],
    ['Legal codes outlive the legislators who wrote them.', 'Правовые кодексы переживают своих законодателей.'],
    ['Justinian codified Roman law while plague raged.', 'Юстиниан кодифицировал римское право среди чумы.'],
    ['The Antonine plague weakened Rome at its height.', 'Антонинова чума ослабила Рим на самом подъёме.'],
    ['Climate shifts pushed steppe riders westward repeatedly.', 'Смены климата снова и снова гнали степных всадников на запад.'],
    ['Rivers birth capitals and betray them in floods.', 'Реки рождают столицы и предают их наводнениями.'],
    ['Frontiers cost more than conquests ever earn.', 'Границы стоят дороже, чем приносят завоевания.'],
    ['Overextension killed more empires than enemies did.', 'Чрезмерное расширение убило больше империй, чем враги.'],
    ['Reform comes late or never, rarely on time.', 'Реформы приходят поздно или никогда, редко вовремя.'],
    ['Decline takes generations, collapse takes winters.', 'Упадок длится поколениями, крах — одну зиму.'],
    ['Historians still argue why Rome fell.', 'Историки до сих пор спорят, почему пал Рим.'],
    ['Probably a hundred reasons and no single villain.', 'Вероятно, причин сотня, и ни одного единственного злодея.'],
    ['Archaeology rewrites textbooks every decade.', 'Археология переписывает учебники каждое десятилетие.'],
    ['Amateur diggers found the Sutton Hoo treasure.', 'Клад Саттон-Ху нашли любители.'],
    ['Museums display looted artefacts under growing scrutiny.', 'Музеи выставляют награбленные артефакты под всё большим вниманием.'],
    ['Repatriation debates reshape museum politics today.', 'Споры о возвращении реликвий меняют музейную политику сегодня.'],
    ['Empire means different things to rulers and ruled.', 'Империя значит разное для правящих и управляемых.'],
    ['Infrastructure outlives ideology.', 'Инфраструктура переживает идеологию.'],
    ['Aqueducts, roads and codes remain long after flags change.', 'Акведуки, дороги и кодексы остаются после смены флагов.'],
    ['History rhymes more than it repeats.', 'История скорее рифмуется, чем повторяется.'],
    ['Primary sources beat patriotic legends.', 'Первичные источники достовернее патриотических легенд.'],
    ['Read the victors and the vanquished, then compare notes.', 'Читайте и победителей, и побеждённых, затем сверяйте.'],
    ['Chronicles were written by survivors with agendas.', 'Хроники писали выжившие со своими задачами.'],
    ['Coins reveal empires that manuscripts forgot.', 'Монеты рассказывают об империях, забытых манускриптами.'],
    ['Border walls announce fear more than strength.', 'Пограничные стены говорят о страхе больше, чем о силе.'],
    ['Mercenaries defend territory, never loyalty.', 'Наёмники защищают территорию, но не проявляют верность.'],
    ['Succession crises topple thrones faster than invasions.', 'Кризисы престолонаследия валят троны быстрее вторжений.'],
    ['Every empire believes it will be the exception.', 'Каждая империя верит, что станет исключением.'],
    ['Maps in old atlases show ambitions, not realities.', 'Карты старых атласов показывают амбиции, а не реальность.'],
    ['Ruins attract tourists who would never salute the flag that built them.', 'Руины привлекают туристов, которые не salютовали бы флагу их построившему.'],
    ['Grandeur photographs well; governance rarely does.', 'Величие фотогенично, управление — почти никогда.'],
    ['Study empires to notice the patterns repeating today.', 'Изучайте империи, чтобы замечать повторяющиеся узоры сегодня.'],
    ['The Khmer empire raised Angkor from jungle clay.', 'Кхмерская империя воздвигла Анкор из джунглевой глины.'],
    ['Hydraulic cities rise and fall with their waterworks.', 'Гидравлические города встают и падают вместе с водопроводами.'],
    ['The Mali griots memorised king lists for centuries.', 'Малийские гриоты веками заучивали списки королей.'],
    ['Oral historians preserve what paper never recorded.', 'Устные историки хранят то, чего бумага не записала.'],
    ['Austrian archdukes collected crowns like stamps.', 'Австрийские эрцгерцоги коллекционировали короны как марки.'],
    ['Every imperial museum hides disputed provenance somewhere.', 'В каждом имперском музее прячется спорное происхождение.'],
    ['The Berlin conference divided Africa with rulers on maps.', 'Берлинская конференция разделила Африку линейками по картам.'],
    ['Borders drawn in European capitals still bleed today.', 'Границы, прочерченные в европейских столицах, кровоточат до сих пор.'],
    ['Gunpowder empires rose together and modernised apart.', 'Пороховые империи вставали вместе, а модернизировались порознь.'],
    ['Cannons breached walls that diplomacy had kept standing.', 'Пушки пробили стены, которые держала дипломатия.'],
    ['Court chroniclers flattered, exiled poets told truths.', 'Придворные летописцы льстили, а сосланные поэты говорили правду.'],
    ['Exile letters outlast court gazettes as sources.', 'Письма из ссылки переживают придворные газеты как источники.'],
    ['The Song dynasty invented paper money and market regulation.', 'Династия Сун изобрела бумажные деньги и регулирование рынков.'],
  ],
};

export const technologygadgets = {
  file: 'dictionaries/phrasebook-technologygadgets.json',
  emoji: '🔌',
  description: 'Фразы о гаджетах и технологиях: телефоны, настройки, покупки, поломки. Для техники в быту и на работе.',
  phrases: [
    ['My phone battery barely survives until lunch.', 'Батарея моего телефона едва доживает до обеда.'],
    ['Did you remember the charger?', 'Ты не забыл зарядку?'],
    ['This cable charges twice as fast as the old one.', 'Этот кабель заряжает вдвое быстрее старого.'],
    ['Fast charging heats the battery noticeably.', 'Быстрая зарядка заметно греет батарею.'],
    ['Battery health dropped below eighty percent.', 'Ёмкость батареи упала ниже восьмидесяти процентов.'],
    ['Replacing the battery costs less than a new phone.', 'Замена батареи дешевле нового телефона.'],
    ['The screen cracked but touch still works.', 'Экран треснул, но сенсор работает.'],
    ['Screen protectors save screens and sanity.', 'Защитные стёкла спасают экраны и нервы.'],
    ['The camera quality convinced me to upgrade.', 'Качество камеры убедило меня обновить телефон.'],
    ['Night mode photography changed everything.', 'Ночная съёмка изменила всё.'],
    ['Storage full again, time to delete something.', 'Память опять забита — пора что-то удалить.'],
    ['Cloud backups run automatically overnight.', 'Облачные резервные копии создаются автоматически ночью.'],
    ['I lost all my photos before learning about backups.', 'Я потерял все фото, прежде чем узнал про резервные копии.'],
    ['Two-factor authentication saved my account once already.', 'Двухфакторная защита уже раз спасла мой аккаунт.'],
    ['Update tonight, it fixes the security hole.', 'Обновись сегодня — залатают дыру в безопасности.'],
    ['The update bricked my tablet last year.', 'Прошлое обновление превратило планшет в кирпич.'],
    ['Restarting fixes eighty percent of problems.', 'Перезагрузка лечит восемьдесят процентов проблем.'],
    ['Have you tried turning it off and on again?', 'Вы пробовали выключить и включить?'],
    ['The warranty covers manufacturing defects for two years.', 'Гарантия покрывает заводские дефекты два года.'],
    ['Water damage voids the warranty immediately.', 'Последствия воды гарантию аннулируют сразу.'],
    ['This model is water resistant, not waterproof.', 'Эта модель водостойкая, но не водонепроницаемая.'],
    ['Headphone jacks disappeared and adapters multiplied.', 'Разъёмы для наушников исчезли, а переходники размножились.'],
    ['Wireless earbuds vanish into sofa cushions mysteriously.', 'Беспроводные наушники таинственно исчезают в диванных подушках.'],
    ['Noise cancelling makes flights bearable.', 'Шумоподавление делает перелёты терпимыми.'],
    ['The microphone picks up my voice clearly on calls.', 'Микрофон чётко передаёт голос в звонках.'],
    ['Bluetooth pairing fails at the worst moments.', 'Bluetooth отказывается сопрягаться в худший момент.'],
    ['Forget the device and pair again from scratch.', 'Забудьте устройство и подключите заново с нуля.'],
    ['Smart speakers listen for wake words only, supposedly.', 'Умные колонки слушают только активационную фразу, якобы.'],
    ['Smart plugs turn any lamp into automation.', 'Умные розетки превращают любую лампу в автоматизацию.'],
    ['The robot vacuum maps the flat and avoids stairs.', 'Робот-пылесос строит карту квартиры и боится лестниц.'],
    ['It got stuck under the bed again.', 'Он опять застрял под кроватью.'],
    ['Fitness trackers count steps whether you trust them or not.', 'Фитнес-браслеты считают шаги независимо от вашего доверия.'],
    ['Sleep tracking says I toss all night.', 'Трекер сна говорит, что я ворочаюсь всю ночь.'],
    ['Smartwatch battery lasts three days at best.', 'Батарея смарт-часов держится максимум три дня.'],
    ['Notifications buzz constantly unless you tame them.', 'Уведомления вибрируют без остановки, пока их не приручишь.'],
    ['Do not disturb mode is self-care.', 'Режим «не беспокоить» — это забота о себе.'],
    ['The keyboard keys started sticking after the spill.', 'Клавиши залипли после пролитого кофе.'],
    ['Mechanical keyboards last decades if maintained.', 'Механические клавиатуры живут десятилетия при уходе.'],
    ['External monitors double my productivity honestly.', 'Внешние мониторы честно удваивают продуктивность.'],
    ['The laptop fan screams during video calls.', 'Кулер ноутбука вопит во время видеозвонков.'],
    ['Thermal throttling slows everything down eventually.', 'Троттлинг со временем замедляет всё.'],
    ['Cleaning the vents lowered temperatures dramatically.', 'Чистка вентиляторов резко снизила температуры.'],
    ['SSD upgrades breathe new life into old laptops.', 'Апгрейд на SSD вдохнул жизнь в старый ноутбук.'],
    ['RAM shortage shows up as constant disk swapping.', 'Нехватка оперативки проявляется постоянной загрузкой с диска.'],
    ['The graphics card costs more than the rest of the PC.', 'Видеокарта стоит дороже остального компьютера.'],
    ['Cable management behind the desk is a losing battle.', 'Порядок в проводах под столом — проигрышная битва.'],
    ['Label your cables before regret teaches you why.', 'Подписывайте провода, пока не стало поздно.'],
    ['Universal serial bus became anything but universal.', 'USB давно перестал быть универсальным.'],
    ['Adapters for adapters, welcome to modern ports.', 'Переходники для переходников — добро пожаловать в мир современных портов.'],
    ['The drone camera stabilises gimbal and software combined.', 'Камера дрона стабилизируется подвесом вместе с софтом.'],
    ['Register your products to extend warranty coverage.', 'Регистрируйте покупки, чтобы продлить гарантию.'],
    ['Refurbished devices carry the same warranty sometimes.', 'Восстановленные устройства иногда получают ту же гарантию.'],
    ['Black Friday deals reward research, not impulse.', 'Чёрная пятница вознаграждает исследование, а не импульс.'],
    ['Read reviews from owners six months later.', 'Читайте отзывы владельцев спустя полгода.'],
    ['Spec sheets hide real world performance.', 'Характеристики скрывают реальную производительность.'],
    ['Megapixels stopped mattering years ago.', 'Мегапиксели перестали иметь значение годы назад.'],
    ['Processor generations matter more than clock speed.', 'Поколения процессоров важнее частоты.'],
    ['Compare benchmarks, not marketing slides.', 'Сравнивайте тесты производительности, а не маркетинговые слайды.'],
    ['The demo unit always runs smoother than yours will.', 'Демонстрационный образец всегда работает шустрее вашего.'],
    ['E-waste recycling bins accept old cables too.', 'Контейнеры для электроники принимают и старые провода.'],
    ['Donate working devices instead of hoarding drawers.', 'Отдавайте рабочие устройства, а не храните их в ящиках.'],
    ['Factory reset wipes everything, triple check first.', 'Сброс к заводским стирает всё — проверьте трижды.'],
    ['Remove accounts before selling any device.', 'Удалите аккаунты перед продажей устройства.'],
    ['Encryption protects data on lost phones.', 'Шифрование защищает данные на потерянных телефонах.'],
    ['Find my phone located it under the car seat.', 'Найти телефон определил его под сиденьем машины.'],
    ['Screen time reports are mildly horrifying.', 'Отчёты о времени экрана слегка пугают.'],
    ['Blue light filters supposedly improve sleep.', 'Синий свет, говорят, портит сон, а фильтры помогают.'],
    ['Wireless charging pads clutter the nightstand differently.', 'Беспроводные зарядки захламляют прикроватную тумбочку по-новому.'],
    ['Reverse charging tops up earbuds from the phone.', 'Обратная зарядка подзаряжает наушники от телефона.'],
    ['Dual SIM separates work from life nicely.', 'Две SIM-карты удобно разделяют работу и жизнь.'],
    ['eSIM activation took one QR code scan.', 'Активация eSIM заняла одно сканирование QR-кода.'],
    ['Roaming charges surprise even careful travellers.', 'Роуминг удивляет даже аккуратных путешественников.'],
    ['Offline maps saved us in the mountains.', 'Офлайн-карты спасли нас в горах.'],
    ['The stylus writes like pen on paper now.', 'Стилус теперь пишет как ручка по бумаге.'],
    ['Foldable screens crease where you fold them, obviously.', 'Гибкие экраны мнутся там, где складываются, естественно.'],
    ['Early adopters pay premium prices as beta testers.', 'Ранние последователи платят премиум как бета-тестеры.'],
    ['Wait for the second generation of anything foldable.', 'Ждите второе поколение всего, что складывается.'],
    ['The remote control lost itself somewhere again.', 'Пульт опять куда-то запропастился.'],
    ['Voice assistants misunderstand accents charmingly.', 'Голосовые ассистенты очаровательно путают акценты.'],
    ['Parental controls limit screen time by schedule.', 'Родительский контроль ограничивает экранное время по расписанию.'],
    ['Kids crack passwords faster than adults admit.', 'Дети взламывают пароли быстрее, чем взрослые признают.'],
    ['The projector turns any wall into a cinema.', 'Проектор превращает любую стену в кинотеатр.'],
    ['Portable power banks rescue dying phones daily.', 'Портативные аккумуляторы ежедневно спасают умирающие телефоны.'],
    ['Solar chargers trickle power on cloudy hikes.', 'Солнечные панели еле-еле заряжают в пасходный поход.'],
    ['Action cameras survive crashes that end phones.', 'Экшн-камеры переживают падения, убивающие телефоны.'],
    ['E-readers last weeks on one charge.', 'Электронные книги живут неделями на одном заряде.'],
    ['E-ink reads fine in direct sunlight.', 'Электронные чернила читаются на прямом солнце.'],
    ['The coffee machine connects to wifi, which says everything.', 'Кофемашина подключается к wi-fi, и это говорит обо всём.'],
    ['Not every appliance needs internet access.', 'Далеко не каждому прибору нужен интернет.'],
    ['Smart features become dumb liabilities offline.', 'Умные функции офлайн превращаются в глупые обузы.'],
    ['Compatibility beats specifications every purchase.', 'Совместимость важнее характеристик при каждой покупке.'],
    ['Keep the boxes until the return window closes.', 'Храните коробки, пока не закрылось окно возврата.'],
    ['Serial numbers live on receipts worth filing.', 'Серийные номера живут в чеках, которые стоит хранить.'],
    ['Insurance covers theft but not carelessness.', 'Страховка покрывает кражу, но не беспечность.'],
    ['Technology serves you the moment you stop serving it.', 'Техника служит вам, когда вы перестаёте служить ей.'],
    ['The tablet replaced my stack of printed manuals.', 'Планшет заменил мою стопку распечатанных инструкций.'],
    ['Stylus notes sync across devices instantly now.', 'Заметки стилусом мгновенно синхронизируются между устройствами.'],
    ['The keyboard dock turns tablets into laptops grudgingly.', 'Клавиатура-док неохотно превращает планшет в ноутбук.'],
    ['Hubs multiply one port into seven compromises.', 'Хабы размножают один порт в семь компромиссов.'],
    ['Thunderbolt docks cost as much as budget monitors.', 'Доки Thunderbolt стоят как бюджетные мониторы.'],
    ['Monitor arms reclaim desk space heroically.', 'Кронштейны мониторов героически возвращают место на столе.'],
    ['The webcam cover tape is a lifestyle now.', 'Плейнштейн на камере — уже образ жизни.'],
    ['Microphone quality matters more than camera resolution in meetings.', 'В созвонах качество микрофона важнее разрешения камеры.'],
    ['Noise gate plugins mute keyboard clatter automatically.', 'Гейт шума автоматически глушит стук клавиатуры.'],
    ['The presentation clicker batteries die mid-slide always.', 'Батарейки кликера всегда садятся посреди слайда.'],
    ['Presentation remotes work better with fresh batteries obviously.', 'Презентационные пульты лучше работают со свежими батарейками, очевидно.'],
    ['Cable testers save hours of blind debugging.', 'Тестеры кабелей экономят часы слепой отладки.'],
    ['Label printers justify themselves in any server closet.', 'Принтеры этикеток оправдывают себя в любой серверной.'],
  ],
};

export const internetwebsites = {
  file: 'dictionaries/phrasebook-internetwebsites.json',
  emoji: '🌐',
  description: 'Фразы об интернете и сайтах: браузер, аккаунты, поиск, безопасность в сети. Для повседневной онлайн-жизни.',
  phrases: [
    ['Clear your browser cache and reload the page.', 'Очистите кэш браузера и перезагрузите страницу.'],
    ['The website loads instantly on fibre but crawls on mobile data.', 'Сайт мгновенно грузится по оптоволокну и ползёт на мобильном интернете.'],
    ['Incognito mode hides history, not identity.', 'Режим инкогнито скрывает историю, но не личность.'],
    ['Cookies accepted without reading, as tradition demands.', 'Куки приняты без чтения, как велит традиция.'],
    ['Third party trackers follow you across sites.', 'Сторонние трекеры следят за вами между сайтами.'],
    ['Ad blockers pay for themselves in sanity.', 'Блокировщики рекламы окупаются спокойствием.'],
    ['Some sites refuse to load with blockers enabled.', 'Некоторые сайты отказываются грузиться с блокировщиком.'],
    ['Pop-ups multiply like weeds on shady pages.', 'Попапы плодятся как сорняки на сомнительных страницах.'],
    ['Check the address bar before entering passwords.', 'Проверяйте адресную строку перед вводом пароля.'],
    ['The padlock icon means encrypted, not trustworthy.', 'Значок замочка означает шифрование, а не надёжность.'],
    ['Phishing emails imitate urgency convincingly.', 'Фишинговые письма убедительно изображают срочность.'],
    ['Hover over links to preview the real destination.', 'Наводите курсор на ссылки, чтобы увидеть настоящий адрес.'],
    ['That domain spelled slightly wrong on purpose.', 'Домен специально написан чуть неправильно.'],
    ['Password managers generate and remember everything.', 'Менеджеры паролей генерируют и помнят всё.'],
    ['One password for everything risks everything.', 'Один пароль на всё ставит на карту всё.'],
    ['Password reset links expire within minutes.', 'Ссылки сброса пароля устаревают за минуты.'],
    ['Security questions guess easily from social media.', 'Ответы на секретные вопросы легко угадать по соцсетям.'],
    ['Enable two factor authentication everywhere it exists.', 'Включайте двухфакторную защиту везде, где она есть.'],
    ['Backup codes belong printed in a drawer.', 'Резервные коды должны лежать распечатанными в ящике.'],
    ['My account got locked after three failed attempts.', 'Мой аккаунт заблокировали после трёх неудачных попыток.'],
    ['Username available, finally a short one.', 'Имя пользователя свободно, наконец-то короткое.'],
    ['Email verification landed in spam as usual.', 'Письмо подтверждения улетело в спам, как обычно.'],
    ['Unsubscribe links legally must work.', 'Ссылки отписки обязаны работать по закону.'],
    ['Newsletter subscriptions breed faster than rabbits.', 'Подписки на рассылки плодятся быстрее кроликов.'],
    ['Search engines answer questions search engines trained us to ask.', 'Поисковики отвечают на вопросы, которым сами нас научили.'],
    ['Quotation marks narrow search results dramatically.', 'Кавычки резко сужают результаты поиска.'],
    ['Site colon search limits results to one website.', 'Поиск с оператором site ограничивает результаты одним сайтом.'],
    ['The first page of results is the only page of results.', 'Первая страница выдачи — единственная страница выдачи.'],
    ['Wiki articles cite sources at the bottom.', 'Вики-статьи указывают источники внизу.'],
    ['Verify quotes before sharing them anywhere.', 'Проверяйте цитаты, прежде чем делиться ими где-либо.'],
    ['Screenshots outlive deleted posts inconveniently.', 'Скриншоты переживают удалённые посты некстати.'],
    ['The internet remembers what you hope it forgot.', 'Интернет помнит то, что вы надеялись похоронить.'],
    ['Right click saves images but not permission.', 'Правый клик сохраняет картинки, но не разрешение.'],
    ['Copyright applies to memes too, technically.', 'Авторское право касается и мемов, технически.'],
    ['Creative Commons licenses explain what sharing allows.', 'Лицензии Creative Commons объясняют, что разрешено делиться.'],
    ['Streaming quality auto-adjusts to bandwidth.', 'Качество стриминга подстраивается под скорость соединения.'],
    ['Buffering spins forever right before the climax.', 'Буферизация крутится вечно прямо перед кульминацией.'],
    ['Downloads pause when laptops sleep unexpectedly.', 'Загрузки останавливаются, когда ноутбук внезапно засыпает.'],
    ['Upload speeds lag far behind downloads on home lines.', 'Исходящая скорость дома сильно отстаёт от входящей.'],
    ['Latency matters more than bandwidth for video calls.', 'Для видеозвонков задержка важнее пропускной способности.'],
    ['The router restart fixed the connection again.', 'Перезапуск роутера снова починил соединение.'],
    ['Public wifi networks deserve healthy suspicion.', 'Публичный wi-fi заслуживает здоровой подозрительности.'],
    ['VPNs encrypt traffic between you and trusted servers.', 'VPN шифрует трафик между вами и доверенными серверами.'],
    ['Free VPNs monetise something, find out what.', 'Бесплатные VPN на чём-то зарабатывают — выясните на чём.'],
    ['DNS translates names into addresses invisibly.', 'DNS незаметно переводит имена в адреса.'],
    ['Changing DNS providers sometimes speeds everything up.', 'Смена DNS-провайдера иногда ускоряет вообще всё.'],
    ['The comment section tested my faith in humanity again.', 'Комментарии снова проверили мою веру в человечество.'],
    ['Reply politely or not at all.', 'Отвечайте вежливо или никак.'],
    ['Trolls feed on attention, starve them politely.', 'Тролли питаются вниманием — голодом их морите вежливо.'],
    ['Forums archive answers search engines bury.', 'Форумы хранят ответы, которые поисковики хоронят.'],
    ['Read the thread before asking the answered question.', 'Читайте ветку, прежде чем задавать отвеченный вопрос.'],
    ['Documentation beats tutorials six months later.', 'Документация через полгода полезнее обучающих видео.'],
    ['APIs let websites talk to each other.', 'API позволяют сайтам разговаривать друг с другом.'],
    ['Rate limits throttle enthusiastic scripts.', 'Лимиты запросов усмиряют рьяные скрипты.'],
    ['Web scraping walks legal grey areas.', 'Парсинг сайтов ходит по серым юридическим зонам.'],
    ['Progressive web apps install like native ones.', 'Прогрессивные веб-приложения устанавливаются как нативные.'],
    ['Responsive design adapts layouts to screen sizes.', 'Адаптивный дизайн подстраивает вёрстку под размеры экрана.'],
    ['Mobile traffic outgrew desktop years ago.', 'Мобильный трафик обогнал настольный годы назад.'],
    ['Accessibility labels help screen readers navigate.', 'Подписи доступности помогают экранным дикторам ориентироваться.'],
    ['Alt text describes images for everyone benefit.', 'Альтернативный текст описывает картинки на пользу всем.'],
    ['Dark mode spares eyes at midnight.', 'Тёмная тема бережёт глаза в полночь.'],
    ['Autoplay videos violate fundamental human dignity.', 'Автовоспроизведение видео нарушает базовое человеческое достоинство.'],
    ['Cookie banners outnumber actual cookies.', 'Баннеры про куки outnumberят сами куки.'],
    ['Accept all remains the fastest button on the internet.', '«Принять все» — самая быстрая кнопка интернета.'],
    ['Privacy policies average longer than novels.', 'Политики конфиденциальности в среднем длиннее романов.'],
    ['Data brokers sell profiles assembled from breadcrumbs.', 'Брокеры данных продают профили, собранные из крошек.'],
    ['Location permissions deserve annual audits.', 'Разрешения на геолокацию заслуживают ежегодного аудита.'],
    ['Apps request contacts for reasons unclear.', 'Приложения просят контакты по неясным причинам.'],
    ['Revoking permissions breaks apps entertainingly sometimes.', 'Отзыв разрешений иногда разваливает приложения очень занятно.'],
    ['Bookmarks folders organise chaos approximately.', 'Папки закладок организуют хаос приблизительно.'],
    ['Open tabs reproduce faster than you close them.', 'Открытые вкладки плодятся быстрее, чем вы их закрываете.'],
    ['Four hundred unread tabs is a lifestyle choice.', 'Четыреста непрочитанных вкладок — это выбор образа жизни.'],
    ['Session restore resurrects everything after crashes.', 'Восстановление сессии воскрешает всё после сбоев.'],
    ['Autofill forms save typing and leak surprises.', 'Автозаполнение форм экономит время и иногда удивляет утечками.'],
    ['CAPTCHA tests prove humanity through traffic lights.', 'КАПЧА доказывает человечность через светофоры.'],
    ['Select every image containing a bicycle, apparently none.', 'Выберите все картинки с велосипедами — видимо, ни одной.'],
    ['Dead links litter the web like abandoned buildings.', 'Мёртвые ссылки усеивают сеть как заброшенные здания.'],
    ['Archive services snapshot pages before they vanish.', 'Архивные сервисы снимают страницы, прежде чем они исчезнут.'],
    ['Wayback machines preserve digital history accidentally.', 'Машины времени случайно сохраняют цифровую историю.'],
    ['Domain names appreciate like real estate sometimes.', 'Доменные имена иногда дорожают как недвижимость.'],
    ['Hosting plans renew at painful premium prices.', 'Хостинг продлевается по болезненным премиальным ценам.'],
    ['SSL certificates renew automatically or sites panic.', 'SSL-сертификаты продлеваются автоматически, иначе сайты паникуют.'],
    ['Downtime happens on weekends by universal law.', 'Отбои случаются по выходным согласно вселенскому закону.'],
    ['Status pages update slower than complaints arrive.', 'Страницы статуса обновляются медленнее, чем приходят жалобы.'],
    ['Backups restore everything except yesterday work.', 'Бэкапы восстанавливают всё, кроме вчерашней работы.'],
    ['Test restores, not just backups.', 'Проверяйте восстановление, а не только копирование.'],
    ['Two browsers isolate work from personal browsing.', 'Два браузера разделяют работу и личное.'],
    ['Guest networks quarantine smart gadgets safely.', 'Гостевые сети безопасно изолируют умные гаджеты.'],
    ['Password sharing circles break terms of service.', 'Круги обмена паролями нарушают условия обслуживания.'],
    ['Family plans share subscriptions legitimately.', 'Семейные тарифы легально делят подписки.'],
    ['Cancellation flows hide behind retention offers.', 'Отмена подписки прячется за удерживающими предложениями.'],
    ['Free trials convert into invoices silently.', 'Бесплатные пробные периоды молча превращаются в счета.'],
    ['Calendar reminders cancel trials before charges.', 'Напоминания в календаре отменяют триалы до списаний.'],
    ['Digital minimalism starts with unsubscribing.', 'Цифровой минимализм начинается с отписок.'],
    ['The offline world missed you while you scrolled.', 'Офлайн-мир скучал по вам, пока вы листали ленту.'],
    ['Reader modes strip ads and fonts down to text.', 'Режим чтения снимает рекламу и оставляет чистый текст.'],
    ['Print stylesheets rescue long articles from layout chaos.', 'Стили печати спасают длинные статьи от хаоса вёрстки.'],
    ['Browser extensions request alarming permissions casually.', 'Расширения браузера невзначай просят тревожные разрешения.'],
    ['Audit your extensions twice a year honestly.', 'Честно проверяйте расширения дважды в год.'],
    ['Sync conflicts duplicate bookmarks into confusion.', 'Конфликты синхронизации плодят дубликаты закладок.'],
    ['Profile separation keeps work logins from leaking.', 'Раздельные профили не дают рабочих логинов утечь.'],
    ['The download folder is where files go to be forgotten.', 'Папка загрузок — место, куда файлы приходят забываться.'],
    ['Desktop clutter mirrors browser tab anxiety.', 'Захламлённый рабочий стол отражает тревогу открытых вкладок.'],
    ['Search within page finds what scrolling missed.', 'Поиск по странице находит то, что пропустил скроллинг.'],
    ['Keyboard shortcuts double browsing speed eventually.', 'Горячие клавиши со временем удваивают скорость браузинга.'],
    ['Middle click opens links without losing your place.', 'Средняя кнопка открывает ссылки, не теряя текущую страницу.'],
    ['Reading lists park articles for the weekend.', 'Списки для чтения паркуют статьи до выходных.'],
  ],
};
