// Curated real-speech phrases: restaurant, cafe & bar, supermarket.
export const food = {
  restaurant: {
    file: 'dictionaries/phrasebook-attherestaurant.json',
    emoji: '🍴',
    description: 'Ресторан от начала до конца: столик, заказ, претензии, счёт',
    phrases: [
      ['A table for two, please.', 'Столик на двоих, пожалуйста.'],
      ['Do you have a table for four?', 'У вас есть столик на четверых?'],
      ['I have a reservation for eight o’clock.', 'У меня забронирован столик на восемь.'],
      ['Under what name?', 'На чьё имя?'],
      ['Under the name Petrov.', 'На фамилию Петров.'],
      ['How long is the wait?', 'Сколько ждать свободный столик?'],
      ['Would you like to sit at the bar while you wait?', 'Не хотите подождать за барной стойкой?'],
      ['Could we sit by the window?', 'Можно нам столик у окна?'],
      ['Is this seat free?', 'Это место свободно?'],
      ['Could we have the menu, please?', 'Можно меню, пожалуйста?'],
      ['Here you are.', 'Вот, пожалуйста.'],
      ['Are you ready to order?', 'Вы готовы сделать заказ?'],
      ['What would you recommend?', 'Что вы посоветуете?'],
      ["What's today's special?", 'Какое сегодня блюдо дня?'],
      ['The salmon is very popular here.', 'Лосось здесь очень популярен.'],
      ["I'll have the chicken soup.", 'Я возьму куриный суп.'],
      ['For starters, we’ll share a salad.', 'На закуску мы разделим салат.'],
      ['And for the main course?', 'А на основное блюдо?'],
      ['Steak, medium, please.', 'Стейк средней прожарки, пожалуйста.'],
      ['How would you like your steak?', 'Как прожарить ваш стейк?'],
      ['Medium rare, please.', 'Слабой прожарки, пожалуйста.'],
      ['Well done, please.', 'Полностью прожаренный, пожалуйста.'],
      ['Any sides with that?', 'Что-нибудь на гарнир?'],
      ['French fries, please.', 'Картофель фри, пожалуйста.'],
      ['Hold the onions, please.', 'Без лука, пожалуйста.'],
      ['No ice, please.', 'Без льда, пожалуйста.'],
      ['Are there any nuts in this dish?', 'В этом блюде есть орехи?'],
      ['Does it contain dairy?', 'Там есть молочные продукты?'],
      ['I’m allergic to shellfish.', 'У меня аллергия на морепродукты.'],
      ['I’m a vegetarian.', 'Я вегетарианец.'],
      ['Do you have any vegan options?', 'У вас есть веганские блюда?'],
      ['Do you have a gluten-free menu?', 'Есть у вас безглютеновое меню?'],
      ['Is this dish spicy?', 'Это блюдо острое?'],
      ['Not too spicy, I hope?', 'Не слишком острое, надеюсь?'],
      ['Make it mild, please.', 'Сделайте неострым, пожалуйста.'],
      ['Another round of drinks, please.', 'Ещё по одному напитку, пожалуйста.'],
      ['Same again, please.', 'Повторите заказ, пожалуйста.'],
      ['Excuse me, we’ve been waiting for our order.', 'Извините, мы уже давно ждём наш заказ.'],
      ['This isn’t what I ordered.', 'Это не то, что я заказывал.'],
      ['My soup is cold.', 'Мой суп холодный.'],
      ['The meat is overcooked.', 'Мясо пережарено.'],
      ['There’s a hair in my food!', 'В моей еде волос!'],
      ['I’m so sorry about that. We’ll replace it right away.', 'Мне так жаль. Мы сразу же заменим блюдо.'],
      ['Everything is delicious!', 'Всё очень вкусно!'],
      ['Compliments to the chef!', 'Комплименты шеф-повару!'],
      ['Could we have some more bread?', 'Можно ещё немного хлеба?'],
      ['Can we get this to go?', 'Можно это с собой?'],
      ['Anything for dessert?', 'Что-нибудь на десерт?'],
      ['Just the bill, thank you.', 'Просто счёт, спасибо.'],
      ['Could we get the check, please?', 'Нам можно счёт, пожалуйста?'],
      ['One bill or separate?', 'Один счёт или раздельно?'],
      ['Separate bills, please.', 'Раздельные счета, пожалуйста.'],
      ['It’s on me.', 'Я угощаю. / С меня.'],
      ["Let's split the bill.", 'Давайте разделим счёт.'],
      ['We’d like to pay together.', 'Мы хотим заплатить вместе.'],
      ['Do you accept credit cards?', 'Вы принимаете кредитные карты?'],
      ['Cash only, I’m afraid.', 'К сожалению, только наличные.'],
      ['Keep the change.', 'Сдачи оставьте себе.'],
      ['Was everything all right?', 'Всё ли вам понравилось?'],
      ['Yes, thank you, it was lovely.', 'Да, спасибо, всё было чудесно.'],
      ['Thank you, come again!', 'Спасибо, приходите ещё!'],
      ['Tip is included in the bill.', 'Чаевые включены в счёт.'],
      ['Service charge is not included.', 'Плата за обслуживание не включена.'],
      ['We don’t tip here.', 'Здесь не принято давать чаевые.'],
      ['Enjoy your meal!', 'Приятного аппетита!'],
      ['Bon appétit!', 'Приятного аппетита!'],
      ['That was a wonderful dinner.', 'Это был замечательный ужин.'],
    ],
  },

  cafebar: {
    file: 'dictionaries/phrasebook-cafebar.json',
    emoji: '☕',
    new: true,
    name: 'Café & Bar',
    description: 'Кафе и бар: кофе навынос, перекус, напитки за стойкой',
    phrases: [
      ['Hi, one latte to go, please.', 'Привет, один латте навынос, пожалуйста.'],
      ['Two cappuccinos, please.', 'Два капучино, пожалуйста.'],
      ['An espresso, please.', 'Эспрессо, пожалуйста.'],
      ['Large black coffee, please.', 'Большой чёрный кофе, пожалуйста.'],
      ['Decaf, please.', 'Без кофеина, пожалуйста.'],
      ['With milk and two sugars.', 'С молоком и двумя ложками сахара.'],
      ['No sugar, thanks.', 'Без сахара, спасибо.'],
      ['Soy milk, please.', 'На соевом молоке, пожалуйста.'],
      ['Oat milk works too.', 'Овсяное молоко тоже подойдёт.'],
      ['Extra shot, please.', 'Добавьте двойную порцию эспрессо, пожалуйста.'],
      ['Hot or iced?', 'Горячий или холодный?'],
      ['Iced, please.', 'Холодный, пожалуйста.'],
      ['For here or to go?', 'Здесь будете пить или с собой?'],
      ['To go, please.', 'С собой, пожалуйста.'],
      ['Can I warm up my cup?', 'Можно подогреть мою кружку?'],
      ['Anything to eat with that?', 'Что-нибудь к этому?'],
      ['A croissant and a blueberry muffin.', 'Круассан и маффин с черникой.'],
      ['Is the soup of the day vegetarian?', 'Суп дня вегетарианский?'],
      ['What sandwiches do you have?', 'Какие у вас есть сэндвичи?'],
      ['Toast it, please.', 'Поджарьте его, пожалуйста.'],
      ['Warm it up for me, please.', 'Подогрейте мне, пожалуйста.'],
      ['Could I have a glass of tap water?', 'Можно стакан воды из-под крана?'],
      ['Still or sparkling?', 'Без газа или с газом?'],
      ['Sparkling water, please.', 'Газированную воду, пожалуйста.'],
      ['Fresh orange juice, please.', 'Свежевыжатый апельсиновый сок, пожалуйста.'],
      ['Is there free refill?', 'Есть бесплатная доливка?'],
      ['Table service or counter service?', 'Обслуживание за столиками или у стойки?'],
      ['Order at the counter, please.', 'Заказывайте у стойки, пожалуйста.'],
      ['Your name for the order?', 'Ваше имя для заказа?'],
      ['Number twenty-seven, your order is ready!', 'Номер двадцать семь, заказ готов!'],
      ['What can I get you?', 'Что вам принести?'],
      ['What do you have on tap?', 'Какое у вас разливное пиво?'],
      ['A pint of lager, please.', 'Пинту лагера, пожалуйста.'],
      ['Two beers, please.', 'Два пива, пожалуйста.'],
      ['A glass of red wine, please.', 'Бокал красного вина, пожалуйста.'],
      ['House wine, please.', 'Домашнее (базовое) вино, пожалуйста.'],
      ['Whiskey on the rocks.', 'Виски со льдом.'],
      ['Make it a double.', 'Сделайте двойную порцию.'],
      ['Another one, please.', 'Ещё такой же, пожалуйста.'],
      ['It’s my round.', 'Сегодня моя очередь угощать.'],
      ['Cheers, everyone!', 'Ну, за нас всех!'],
      ['To your health!', 'За ваше здоровье!'],
      ['I’ve had enough, thanks.', 'Спасибо, мне достаточно.'],
      ['Water for me, I’m driving.', 'Мне воду, я за рулём.'],
      ['Last call!', 'Последний заказ!'],
      ['We’re closing soon.', 'Мы скоро закрываемся.'],
      ['Could we sit outside?', 'Можно сесть снаружи?'],
      ['Are dogs allowed here?', 'Можно ли сюда с собаками?'],
    ],
  },

  supermarket: {
    file: 'dictionaries/phrasebook-supermarket.json',
    emoji: '🛒',
    new: true,
    name: 'Supermarket',
    description: 'Продуктовый магазин: поиск товаров, вес, оплата, пакеты',
    phrases: [
      ['Where can I find milk?', 'Где найти молоко?'],
      ['Which aisle is the cereal in?', 'В каком ряду хлопья?'],
      ['Do you sell fresh basil?', 'У вас продается свежий базилик?'],
      ['Where is the bakery section?', 'Где отдел выпечки?'],
      ['Is there a butcher counter here?', 'Здесь есть мясной прилавок?'],
      ['Where’s the checkout?', 'Где касса?'],
      ['Excuse me, is this queue for cash only?', 'Извините, эта очередь только для оплаты наличными?'],
      ['Are these bananas ripe?', 'Эти бананы спелые?'],
      ['How much are the tomatoes?', 'Сколько стоят помидоры?'],
      ['These are on sale, right?', 'Они же по скидке, верно?'],
      ['Is this the sale price?', 'Это цена со скидкой?'],
      ['Buy one, get one free!', 'Два по цене одного — второй бесплатно!'],
      ['Do you have this in stock?', 'Это есть в наличии?'],
      ['When will you restock the eggs?', 'Когда завезут яйца?'],
      ['Half a kilo of cheese, please.', 'Полкило сыра, пожалуйста.'],
      ['Two hundred grams of ham, please.', 'Двести граммов ветчины, пожалуйста.'],
      ['Slice it thin, please.', 'Нарежьте тонко, пожалуйста.'],
      ['A loaf of white bread, please.', 'Батон белого хлеба, пожалуйста.'],
      ['Is this gluten-free?', 'Это без глютена?'],
      ['Does it contain preservatives?', 'Там есть консерванты?'],
      ['What’s the expiration date?', 'Какой срок годности?'],
      ['It expires tomorrow, better take another one.', 'Срок истекает завтра, лучше возьмите другую.'],
      ['Do you have a loyalty card?', 'У вас есть карта лояльности?'],
      ['I don’t have one, sorry.', 'Нет, у меня её нет, извините.'],
      ['Paper or plastic?', 'Бумажный пакет или пластиковый?'],
      ['A bag, please.', 'Пакет, пожалуйста.'],
      ['I brought my own bag.', 'Я принёс свой пакет.'],
      ['Card or cash?', 'Картой или наличными?'],
      ['Pay by card, please.', 'Оплата картой, пожалуйста.'],
      ['Insert your card into the reader.', 'Вставьте карту в терминал.'],
      ['Enter your PIN, please.', 'Введите ваш PIN-код, пожалуйста.'],
      ['Contactless doesn’t work, try inserting it.', 'Бесконтактная оплата не работает, попробуйте вставить карту.'],
      ['Would you like a receipt?', 'Вам нужен чек?'],
      ['Receipt, please.', 'Чек, пожалуйста.'],
      ['Self-checkout is faster.', 'Самообслуживание быстрее.'],
      ['Unexpected item in the bagging area.', 'Неожиданный предмет в зоне упаковки (сообщение кассы самообслуживания).'],
      ['Call an assistant, please!', 'Позовите помощника, пожалуйста!'],
      ['Can I return this without a receipt?', 'Можно вернуть это без чека?'],
      ['I need a refund for this item.', 'Мне нужен возврат денег за этот товар.'],
      ['It’s past the return window, sorry.', 'Срок возврата уже прошёл, извините.'],
      ['Groceries are getting expensive.', 'Продукты дорожают.'],
      ['Prices went up again.', 'Цены снова выросли.'],
    ],
  },
};
