// Curated real-speech phrases: bank, doctor, emergencies, barbershop.
export const services = {
  bank: {
    file: 'dictionaries/phrasebook-atthebank.json',
    emoji: '💳',
    description: 'В банке и у банкомата: счета, переводы, обмен валюты',
    phrases: [
      ['Good morning, I’d like to open an account.', 'Доброе утро, я хотел бы открыть счёт.'],
      ['I’d like to open a savings account.', 'Я хотел бы открыть сберегательный счёт.'],
      ['What documents do I need?', 'Какие документы нужны?'],
      ['Here is my ID and proof of address.', 'Вот мой паспорт и подтверждение адреса.'],
      ['How long does it take to open?', 'Сколько времени занимает открытие?'],
      ['Is there a monthly fee?', 'Есть ли ежемесячная плата?'],
      ['Are there any hidden charges?', 'Есть скрытые комиссии?'],
      ['What’s the interest rate?', 'Какая процентная ставка?'],
      ['I’d like to exchange dollars for euros.', 'Я хотел бы обменять доллары на евро.'],
      ['What’s today’s exchange rate?', 'Какой сегодня курс обмена?'],
      ['The rate is better at the ATM, actually.', 'Курс в банкомате на самом деле лучше.'],
      ['Could you break this into smaller bills?', 'Разменяйте это мелкими купюрами, пожалуйста.'],
      ['I’d like to withdraw some money.', 'Я хотел бы снять немного денег.'],
      ['How much would you like to withdraw?', 'Какую сумму вы хотите снять?'],
      ['Three hundred pounds, please.', 'Триста фунтов, пожалуйста.'],
      ['I’d like to make a transfer.', 'Я хотел бы сделать перевод.'],
      ['Transfer it to this account number.', 'Переведите это на номер этого счёта.'],
      ['When will the money arrive?', 'Когда придут деньги?'],
      ['Transfers usually take one business day.', 'Переводы обычно занимают один рабочий день.'],
      ['There’s a fee for international transfers.', 'За международные переводы есть комиссия.'],
      ['My card was swallowed by the ATM!', 'Банкомат проглотил мою карту!'],
      ['My card got stuck in the machine.', 'Моя карта застряла в банкомате.'],
      ['The ATM is out of order.', 'Банкомат не работает.'],
      ['Your card has expired.', 'Срок действия вашей карты истёк.'],
      ['I’ve been charged twice.', 'С меня списали деньги дважды.'],
      ['I see a charge I don’t recognize.', 'Вижу списание, которое не узнаю.'],
      ['Please block my card immediately.', 'Заблокируйте мою карту немедленно, пожалуйста.'],
      ['Someone used my card without permission.', 'Кто-то воспользовался моей картой без разрешения.'],
      ['I need a statement of my account.', 'Мне нужна выписка по счёту.'],
      ['Take a seat; the manager will be with you shortly.', 'Присядьте; менеджер скоро подойдёт к вам.'],
      ['Your new card will arrive within two weeks.', 'Новая карта прибудет в течение двух недель.'],
      ['Sign here, please.', 'Распишитесь здесь, пожалуйста.'],
      ['Enter your PIN and confirm the amount.', 'Введите PIN-код и подтвердите сумму.'],
      ['Insufficient funds.', 'Недостаточно средств.'],
      ['Payment declined. Try another card.', 'Платёж отклонён. Попробуйте другую карту.'],
    ],
  },

  doctor: {
    file: 'dictionaries/phrasebook-atthedoctor.json',
    emoji: '🩺',
    description: 'У врача: жалобы, симптомы, лечение и рецепты',
    phrases: [
      ['I’d like to make an appointment with a doctor.', 'Я хотел бы записаться на приём к врачу.'],
      ['Can I see a doctor today?', 'Можно попасть к врачу сегодня?'],
      ['It’s not urgent, but soon please.', 'Это не срочно, но как можно скорее, пожалуйста.'],
      ['Please fill out this form.', 'Заполните эту форму, пожалуйста.'],
      ['Do you have medical insurance?', 'У вас есть медицинская страховка?'],
      ['Here is my insurance card.', 'Вот моя страховая карта.'],
      ['What seems to be the problem?', 'Что вас беспокоит?'],
      ['Where does it hurt?', 'Где у вас болит?'],
      ['I have a splitting headache.', 'У меня сильная головная боль.'],
      ['My throat hurts when I swallow.', 'У меня болит горло, когда глотаю.'],
      ['I have a sharp pain in my side.', 'У меня острая боль в боку.'],
      ['It hurts when I press here.', 'Болит, когда нажимаю здесь.'],
      ['The pain comes and goes.', 'Боль то появляется, то проходит.'],
      ['The pain gets worse at night.', 'Ночью боль усиливается.'],
      ['Since when have you had these symptoms?', 'Давно ли у вас эти симптомы?'],
      ['For about three days now.', 'Уже около трёх дней.'],
      ['I feel dizzy.', 'У меня головокружение.'],
      ['I feel nauseous.', 'Меня тошнит.'],
      ['I keep coughing at night.', 'Я постоянно кашляю по ночам.'],
      ['I can’t stop sneezing.', 'Не могу перестать чихать.'],
      ['My nose is stuffed up.', 'У меня заложен нос.'],
      ['I have a runny nose.', 'У меня насморк.'],
      ['I’m running a temperature.', 'У меня повышенная температура.'],
      ['I have a fever of thirty-nine degrees.', 'У меня температура тридцать девять.'],
      ['I feel weak all over.', 'Я чувствую слабость во всём теле.'],
      ['I have no appetite.', 'У меня нет аппетита.'],
      ['I can’t sleep because of the pain.', 'Я не могу спать из-за боли.'],
      ['Have you taken anything for it?', 'Вы что-нибудь принимали от этого?'],
      ['Just painkillers so far.', 'Пока только обезболивающие.'],
      ['Are you allergic to any medication?', 'У вас есть аллергия на какие-либо лекарства?'],
      ['I’m allergic to penicillin.', 'У меня аллергия на пенициллин.'],
      ['Are you taking any other medications?', 'Принимаете ли вы другие лекарства?'],
      ['Let me listen to your lungs.', 'Давайте послушаю ваши лёгкие.'],
      ['Breathe in deeply… and out.', 'Глубоко вдохните... и выдохните.'],
      ['Open your mouth wide, please.', 'Откройте рот пошире, пожалуйста.'],
      ['Say “ahh”.', 'Скажите «а-а-ах».'],
      ['Roll up your sleeve, please.', 'Закатайте рукав, пожалуйста.'],
      ['I’ll check your blood pressure.', 'Я измерю ваше давление.'],
      ['Your blood pressure is a bit high.', 'У вас немного повышено давление.'],
      ['You need a blood test.', 'Вам нужно сдать анализ крови.'],
      ['Nothing serious, just a common cold.', 'Ничего серьёзного, обычная простуда.'],
      ['You have the flu.', 'У вас грипп.'],
      ['It looks like bronchitis.', 'Похоже на бронхит.'],
      ['You’ll need antibiotics.', 'Вам понадобятся антибиотики.'],
      ['I’ll prescribe you something stronger.', 'Я выпишу вам что-то посильнее.'],
      ['Take one tablet twice a day after meals.', 'Принимайте по одной таблетке два раза в день после еды.'],
      ['Take it with plenty of water.', 'Запивайте большим количеством воды.'],
      ['Finish the whole course of antibiotics.', 'Пропейте весь курс антибиотиков.'],
      ['Get plenty of rest and drink fluids.', 'Много отдыхайте и пейте жидкость.'],
      ['Come back if it doesn’t improve.', 'Приходите снова, если не станет лучше.'],
      ['You should stay home from work.', 'Вам стоит остаться дома с работы.'],
      ['Here is your prescription.', 'Вот ваш рецепт.'],
      ['Take this prescription to the pharmacy.', 'Отнесите этот рецепт в аптеку.'],
      ['When can I get the results?', 'Когда будут готовы результаты?'],
      ['Is it contagious?', 'Это заразно?'],
      ['Will I need surgery?', 'Мне понадобится операция?'],
      ['I need a sick note for work.', 'Мне нужна справка для работы о болезни.'],
      ['Thank you, doctor.', 'Спасибо, доктор.'],
    ],
  },

  emergency: {
    file: 'dictionaries/phrasebook-emergencyhealth.json',
    emoji: '🚑',
    description: 'Экстренные ситуации: вызов помощи, пожар, полиция, аптечка',
    phrases: [
      ['Help!', 'На помощь!'],
      ['Fire!', 'Пожар!'],
      ['Thief!', 'Держите вора!'],
      ['Call an ambulance!', 'Вызовите скорую!'],
      ['Call the police!', 'Вызовите полицию!'],
      ['Call nine-one-one!', 'Звоните девять один один!'],
      ['Somebody call 112!', 'Кто-нибудь, звоните 112!'],
      ['It’s an emergency!', 'Это чрезвычайная ситуация!'],
      ['We need help right away!', 'Нам нужна немедленная помощь!'],
      ['He’s not breathing!', 'Он не дышит!'],
      ['She’s unconscious.', 'Она без сознания.'],
      ['He has a pulse but won’t wake up.', 'Пульс есть, но он не просыпается.'],
      ['Start CPR, I know how.', 'Начинайте сердечно-лёгочную реанимацию, я умею.'],
      ['Is anyone here a doctor?', 'Здесь есть кто-нибудь врач?'],
      ['Does anyone know first aid?', 'Кто-нибудь знает первую помощь?'],
      ['Get the first aid kit!', 'Принесите аптечку!'],
      ['Apply pressure to the wound.', 'Прижмите рану (чтобы остановить кровь).'],
      ['Don’t move him, he might have a spinal injury.', 'Не двигайте его, возможно повреждение позвоночника.'],
      ['Keep him calm and still.', 'Успокойте его и не давайте двигаться.'],
      ['She’s bleeding heavily.', 'У неё сильное кровотечение.'],
      ['He’s having trouble breathing.', 'Он с трудом дышит.'],
      ['I think she broke her leg.', 'Кажется, она сломала ногу.'],
      ['My friend collapsed on the street.', 'Мой друг упал в обморок на улице.'],
      ['He fainted all of a sudden.', 'Он внезапно потерял сознание.'],
      ['She’s having an allergic reaction!', 'У неё аллергическая реакция!'],
      ['She needs her EpiPen!', 'Ей нужен её ЭпиПен!'],
      ['His heart condition is serious.', 'У него серьёзная болезнь сердца.'],
      ['He has diabetes.', 'У него диабет.'],
      ['There’s been an accident!', 'Произошла авария!'],
      ['Two cars crashed at the intersection.', 'Две машины столкнулись на перекрёстке.'],
      ['Nobody was seriously hurt.', 'Никто серьёзно не пострадал.'],
      ['Everyone, evacuate the building!', 'Все, покиньте здание!'],
      ['Leave everything and get out!', 'Оставьте всё и выходите!'],
      ['Use the stairs, not the elevator!', 'Используйте лестницу, а не лифт!'],
      ['Where is the fire exit?', 'Где пожарный выход?'],
      ['Smoke is coming from the kitchen.', 'Из кухни идёт дым.'],
      ['There’s a gas smell in the apartment!', 'В квартире пахнет газом!'],
      ['Turn off the gas main!', 'Перекройте газовый вентиль!'],
      ['Water is leaking everywhere!', 'Вода течёт повсюду!'],
      ['The ceiling is about to collapse!', 'Потолок вот-вот обрушится!'],
      ['Stay back, it’s dangerous!', 'Отойдите назад, там опасно!'],
      ['Don’t panic!', 'Не паникуйте!'],
      ['Everything is under control now.', 'Сейчас всё под контролем.'],
      ['The firefighters arrived quickly.', 'Пожарные приехали быстро.'],
      ['Fill in this incident report.', 'Заполните это заявление о происшествии.'],
      ['Give them my contact details.', 'Передайте им мои контактные данные.'],
    ],
  },

  barbershop: {
    file: 'dictionaries/phrasebook-barbershophaircut.json',
    emoji: '💈',
    description: 'Парикмахерская: стрижка, борода, укладка — как объяснить желание',
    phrases: [
      ['Hi, do you take walk-ins?', 'Здравствуйте, можно без записи?'],
      ['Do you have any openings today?', 'Есть свободное время сегодня?'],
      ['I have an appointment at three.', 'У меня запись на три часа.'],
      ['It’ll be about a twenty-minute wait.', 'Ждать придётся минут двадцать.'],
      ['Just a trim, please.', 'Просто подровнять, пожалуйста.'],
      ['Not too short, please.', 'Не слишком коротко, пожалуйста.'],
      ['Shorter on the sides, longer on top.', 'Короче по бокам, подлиннее сверху.'],
      ['Same style as last time.', 'Так же, как в прошлый раз.'],
      ['A bit shorter than usual.', 'Чуть короче обычного.'],
      ['Just clean up the edges.', 'Просто подравняйте края.'],
      ['Fade on the sides, please.', 'Фейд (плавный переход) по бокам, пожалуйста.'],
      ['Skin fade, please.', 'Кожаный фейд, пожалуйста.'],
      ['Buzz cut all over, number two.', 'Машинка по всей голове, насадка номер два.'],
      ['Trim the bangs a little.', 'Подровняйте чёлку немного.'],
      ['Part it on the left, please.', 'Разделите пробор слева, пожалуйста.'],
      ['No parting, thank you.', 'Без пробора, спасибо.'],
      ['Should I wash my hair first?', 'Сначала помыть голову?'],
      ['Wash and cut, please.', 'Помыть и постричь, пожалуйста.'],
      ['Blow-dry it afterwards.', 'И высушите феном после.'],
      ['Some styling product, please.', 'Немного средства для укладки, пожалуйста.'],
      ['Something light, no strong hold.', 'Что-нибудь лёгкое, без сильной фиксации.'],
      ['Would you like a beard trim as well?', 'Подровнять вам ещё бороду?'],
      ['Yes, shape up the beard, please.', 'Да, оформите бороду, пожалуйста.'],
      ['Just tidy up the neckline.', 'Просто приведите в порядок линию шеи.'],
      ['Hot towel shave, please.', 'Бритьё горячим полотенцем, пожалуйста.'],
      ['Careful around the sideburns.', 'Аккуратно возле висков.'],
      ['That length is perfect, thanks.', 'Эта длина идеальна, спасибо.'],
      ['A little more off the top.', 'Чуть больше снимите сверху.'],
      ['That’s exactly what I wanted!', 'Именно то, что я хотел!'],
      ['How much do I owe you?', 'Сколько я должен?'],
      ['Twenty-five dollars even.', 'Ровно двадцать пять долларов.'],
      ['Keep the change.', 'Сдачи оставьте себе.'],
      ['Same time next month, please.', 'Запишите меня на следующей месяц, в то же время.'],
      ['Book me in for next Friday.', 'Запишите меня на следующую пятницу.'],
    ],
  },
};
