// Curated real-speech phrases: shopping & bargaining, clothing store.
export const shopping = {
  shopping: {
    file: 'dictionaries/phrasebook-shoppingmoney.json',
    emoji: '🛍️',
    description: 'Покупки: вопросы к продавцу, оплата, возврат, торг на рынке',
    phrases: [
      ['Excuse me, where can I find…?', 'Извините, где я могу найти...?'],
      ['I’m just looking, thanks.', 'Я просто смотрю, спасибо.'],
      ['Just browsing, thank you.', 'Просто присматриваюсь, спасибо.'],
      ['Let me know if you need help.', 'Дайте знать, если понадобится помощь.'],
      ['Could you help me choose?', 'Помогите мне выбрать?'],
      ['Which one would you recommend?', 'Какой из них вы посоветуете?'],
      ['What’s the difference between these two?', 'В чём разница между этими двумя?'],
      ['How much is this?', 'Сколько это стоит?'],
      ['What’s the price of this one?', 'Сколько стоит этот?'],
      ['That’s a bit over my budget.', 'Это немного выше моего бюджета.'],
      ["That's too expensive for me.", 'Для меня это слишком дорого.'],
      ['Do you have anything cheaper?', 'Есть что-нибудь подешевле?'],
      ['Is there any discount on this?', 'На это есть скидка?'],
      ['Is this on sale?', 'Это по акции?'],
      ['There’s a thirty-percent discount today.', 'Сегодня скидка тридцать процентов.'],
      ['When does the sale end?', 'Когда заканчивается распродажа?'],
      ['Do you give student discounts?', 'Даёте ли скидку студентам?'],
      ['Can you give me a better price?', 'Можете дать цену получше?'],
      ['Come on, make it twenty.', 'Ну же, давайте за двадцать.'],
      ["I'll give you fifteen.", 'Я дам вам пятнадцать.'],
      ['Fifteen is my final offer.', 'Пятнадцать — моё последнее предложение.'],
      ['Deal!', 'По рукам! / Договорились!'],
      ['You drive a hard bargain.', 'Ты жёстко торгуешься.'],
      ['It’s a fair price.', 'Это честная цена.'],
      ['Do you take credit cards?', 'Вы принимаете карты?'],
      ['Cash only.', 'Только наличные.'],
      ['Can I pay in cash?', 'Можно заплатить наличными?'],
      ['Do you accept contactless payment?', 'Принимаете бесконтактную оплату?'],
      ['Here’s your change.', 'Вот ваша сдача.'],
      ['Could I get a receipt?', 'Можно чек?'],
      ['Can I get a gift wrap?', 'Можно упаковать как подарок?'],
      ['Should I put it in a bag?', 'Мне положить это в пакет?'],
      ['Does it come with a warranty?', 'С ним идёт гарантия?'],
      ['The warranty lasts two years.', 'Гарантия действует два года.'],
      ['Where is the fitting room?', 'Где примерочная?'],
      ['Are these returnable?', 'Их можно вернуть?'],
      ['What’s your return policy?', 'Каковы условия возврата?'],
      ['You can return it within fourteen days.', 'Вы можете вернуть в течение четырнадцати дней.'],
      ['I’d like to return this item.', 'Я хотел бы вернуть эту вещь.'],
      ['I’d like to exchange this for a larger size.', 'Хотел бы обменять на размер побольше.'],
      ['Do you have the receipt?', 'У вас есть чек?'],
      ['It stopped working after two days.', 'Он перестал работать через два дня.'],
      ['It doesn’t work properly.', 'Оно работает неправильно.'],
      ['I want a refund, please.', 'Я хотел бы вернуть деньги, пожалуйста.'],
      ['Store credit only, I’m afraid.', 'Боюсь, мы можем вернуть только на счёт магазина.'],
      ['This is defective.', 'Этот товар с дефектом.'],
      ['I’ll take it!', 'Я возьму его!'],
      ['Wrap it up, please.', 'Заверните, пожалуйста.'],
      ['Thank you for your purchase!', 'Спасибо за покупку!'],
      ['Have a nice day!', 'Хорошего дня!'],
    ],
  },

  clothingshop: {
    file: 'dictionaries/phrasebook-clothingshop.json',
    emoji: '👗',
    new: true,
    name: 'Clothing Store',
    description: 'Магазин одежды: размеры, примерка, цвет и фасон',
    phrases: [
      ['Hi! Can I help you find anything?', 'Здравствуйте! Помочь вам что-нибудь найти?'],
      ['I’m looking for a winter coat.', 'Я ищу зимнее пальто.'],
      ['I need a dress for a wedding.', 'Мне нужно платье на свадьбу.'],
      ['Do you sell jeans here?', 'У вас продаются джинсы?'],
      ['Where are the men’s shirts?', 'Где мужские рубашки?'],
      ['Show me that jacket, please.', 'Покажите ту куртку, пожалуйста.'],
      ['Can I see it in black?', 'Можно посмотреть чёрную?'],
      ['Do you have it in blue?', 'Он есть в синем цвете?'],
      ['What size is this?', 'Какой это размер?'],
      ['What size do you wear?', 'Какой у вас размер?'],
      ['I wear medium.', 'Я ношу средний размер (M).'],
      ['Do you have a smaller size?', 'Есть размер поменьше?'],
      ['Do you have this in a large?', 'Есть такой в большом размере (L)?'],
      ['Could I try this on?', 'Можно это примерить?'],
      ['Sure, the fitting room is over there.', 'Конечно, примерочная вон там.'],
      ['Three items max in the fitting room.', 'Не больше трёх вещей в примерочную.'],
      ['How does it fit?', 'Как сидит (по размеру)?'],
      ['It fits perfectly.', 'Сидит идеально.'],
      ["It's too tight.", 'Слишком тесно.'],
      ["It's too loose.", 'Слишком свободно.'],
      ['It’s a bit long in the sleeves.', 'Рукава немного длинноваты.'],
      ['The trousers are too short.', 'Эти брюки слишком короткие.'],
      ['It looks good on you!', 'Тебе это идёт!'],
      ['This color really suits you.', 'Этот цвет вам действительно идёт.'],
      ['Hmm, not really my style.', 'Хм, не совсем мой стиль.'],
      ['Do you have one with longer sleeves?', 'Есть с более длинными рукавами?'],
      ['Do you have something more formal?', 'Есть что-нибудь поформальнее?'],
      ['Something casual for everyday wear.', 'Что-то повседневное.'],
      ['What material is this made of?', 'Из какого материала это сделано?'],
      ['Is it machine washable?', 'Его можно стирать в машинке?'],
      ['Hand wash only.', 'Только ручная стирка.'],
      ['Will it shrink after washing?', 'Он сядет после стирки?'],
      ['It shrinks slightly, wash cold.', 'Немного садится, стирайте в холодной воде.'],
      ['Does it wrinkle easily?', 'Оно легко мнётся?'],
      ['How much does it cost?', 'Сколько это стоит?'],
      ['It’s forty dollars, but it’s on sale now.', 'Сорок долларов, но сейчас скидка.'],
      ['If you buy two, the second is half price.', 'Если купите две, вторая за полцены.'],
      ['I’ll think about it.', 'Я подумаю.'],
      ['Okay, I’ll take both.', 'Ладно, беру обе.'],
      ['Just these shoes, please.', 'Только эти туфли, пожалуйста.'],
      ['Can I try them with thicker socks?', 'Можно примерить их с более толстыми носками?'],
      ['These pinch my toes.', 'Они жмут мне пальцы.'],
      ['They’re half a size too small.', 'Они на полразмера меньше.'],
      ['Do you have these in size forty-two?', 'Есть такие в сорок втором размере?'],
      ['Would you like a box for those?', 'Вам коробку для них?'],
    ],
  },
};
