// Engineer & Mechanic final fill (+~140).
export const topups = {
  motorsportengineermechanic: [
    ['Aero rakes sensor arrays flow field mapping sessions dedicated.', 'Аэро-грабли картографируют потоки в специальных сессиях!'],
    ['Pressure tap tubing routed hundreds channels scanner banks multiplexed.', 'Сотни трубок датчиков давления идут в мультиплексоры!'],
    ['Bib nose assemblies quick change aero configurations swapped between runs.', 'Носовые секции меняют между заездами ради конфигураций!'],
    ['Ride height plates reference plane datum measurements consistency checked.', 'Опорную плоскость клиренса сверяют каждый раз!'],
    ['Starter trolley cart batteries charged jump ready grid.', 'Пусковая тележка заряжена для старта с поля!'],
    ['Fuel cell bladder inspection internal baffles integrity certified periodic.', 'Бак с перегородками сертифицируют периодически!'],
    ['Fire bottle pressure gauges weight checks serviced annually certified tags.', 'Огнетушители обслуживают и вешают бирки ежегодно!'],
    ['Helmet FIA 8860 standard latest homologation sticker verified scrutineering.', 'Шлем последнего стандарта FIA проверяют на техконтроле!'],
    ['Hans anchors tethers shoulder harness routing angles measured spec.', 'Углы крепления Ханса вымерены по спецификации!'],
    ['Roll hoop padding impact foam densities compressible limits replaced compressed.', 'Смятые подушки каркаса заменяют на новые!'],
    ['Mirror glass convex wide angle positioning blind spots eliminated adjustments.', 'Выпуклые зеркала убирают слепые точки регулировками!'],
    ['Rain light LED rear fog intensity regulations visibility tested.', 'Дождевой фонарь проверяют на соответствие видимости!'],
    ['Wheel tethers tensile tested cables frayed replaced preventive.', 'Изношенные тросы колёс меняют превентивно!'],
    ['Upright crack detection magnaflux penetrant inspections suspension pick-ups critical.', 'Критичные узлы подвески проверяют магнитопорошковым методом!'],
    ['Pushrod lengths adjustable turnbuckles locknuts secured alignment set.', 'Штоки регулируются стяжками, контрги зафиксированы!'],
    ['Caster shim stacks geometry altered trial error documented iterations logged.', 'Прокладки кастера: итерации задокументированы!'],
    ['Steering rack ratio quickened turns lock-to-lock reduced feedback tradeoff noted.', 'Быстрый рулевой редуктор: меньше оборотов, меньше обратной связи!'],
    ['Power steering pump pressure relief valve settings driver feel tuned.', 'Клапан ГУР настраивают под «чувство» пилота!'],
    ['Electric power steering maps variable assistance speed sensitive programmed.', 'EPS-карты меняют помощь от скорости программно!'],
    ['Brake disc thickness micrometer measured minimum wear limits enforced strictly.', 'Толщину диска меряют микрометром — лимит строго!'],
    ['Pad wear indicators acoustic sensors wireless telemetry alerts pit wall.', 'Беспроводные датчики колодок сигналят на стену!'],
    ['Fluid lines AN fittings sizes dash numbers confusion avoided charts referenced.', 'Таблицы размеров AN-фитингов спасают от путаницы!'],
    ['Line bending tools kinks avoided flow restrictions prevented smooth radii.', 'Трубки гнут с плавными радиусами без заломов!'],
    ['Flaring tools double flare single bubble types brake fuel specific.', 'Разновидности развальцовок: двойная для тормозов, пузырьковая для топлива!'],
    ['Leak down spray soapy water bubbles bubbles bubbles hunt.', 'Мыльная пена выдаёт утечки пузырями!'],
    ['Vacuum leaks smoke machines diagnostics intake tract post-throttle hunting idle.', 'Дым-машина ищет подсос воздуха за дросселем!'],
    ['Compression test gauge readings cylinder variance percentages logged trended.', 'Компрессию логируют, разброс по цилиндрам трендят!'],
    ['Leak-down tester percentage loss cylinder diagnosis valves rings head gasket differentiated.', 'Тест на утечки различает клапаны, кольца и прокладку!'],
    ['Camshaft lobe wear profile gauge comparisons new specs deviations flagged.', 'Износ кулачков сравнивают с эталонным профилем!'],
    ['Valve guide wear stem play dial indicator wobble measured replaced exceeded.', 'Люфт стеммов клапанов замеряли — превышение, замена!'],
    ['Seat recession depth measurement valve closing geometry altered heads machined resurfaced.', 'Просадку сёдел фрезеруют обратно в геометрию!'],
    ['Head resurfacing mill cuts thousandths precise surface finish RA specified gasket seal.', 'Фрезеровка головы выдерживает шероховатость под прокладку!'],
    ['Block deck decking squaring bore honing torque plate simulation distortion prevention.', 'Гильзовка и хонинг под пластиной имитируют сборку!'],
    ['Piston-to-wall clearance feeler gauges measured expansion rates alloy specific calculated.', 'Зазор поршень-стенка считают по расширению сплава!'],
    ['Ring end gap file fitted positions staggered orientation blow-by minimised assembly.', 'Замки колец разведены по кругу — минимум прорыва газов!'],
    ['Wrist pin fit circlip orientation gaps positioned away cutouts practice.', 'Стопорные кольца ставят замками от выборок!'],
    ['Rod bolt stretch gauge measured yield limits fasteners discarded singles reuse never.', 'Болты шатунов одноразовые: вытяжку меряем, повторно не ставим!'],
    ['Big end bore ovality measurement crank journal polishing microfinishing surfaces restored.', 'Овальность постели правится полировкой шеек!'],
    ['Crank grinding undersize bearings oversize matched sets machined emergency saves races.', 'Шейки шлифуют в ремонтный размер — спасает гоночный уик-энд!'],
    ['Balancing machine bobweights pistons rods matched grams fractions precision obsessive.', 'Балансировочный станок сводит узлы с точностью до долей грамма!'],
    ['Zero balancing rotating assembly harmonics cancellation counterweighted shafts smoothness high rpm reward.', 'Противовесы гасят гармонику — плавность на высоких оборотах!'],
    ['Oil pan capacity extended sumps pickup relocated cornering starvation solved engineering.', 'Углублённый поддон с переносом заборника решил голодание в поворотах!'],
    ['Accusump pre-oiler turbos bearing protection startup shutdown sequences ritual.', 'Аккумулятор масла защищает турбину при старте и остановке!'],
    ['Turbo timer cooldown cycles bearing coking prevention longevity practice disciplined drivers.', 'Дисциплинированные водители гоняют турботаймер против закоксовки!'],
    ['Boost controller manual MBC ball spring versus electronic solenoid duty cycle precision.', 'Механический и электронный буст-контроллер: точность соленоида!'],
    ['Dyno jet inertia versus load-bearing dynos numbers differ calibration wars forums.', 'Споры инерционных и нагрузочных дино-стендов не утихают!'],
    ['Correction factors SAE DIN weather standardised comparison fair numbers published.', 'Поправки SAE/DIN делают цифры сравнимыми честно!'],
    ['Dyno queen garage queen cars trailered shows polished never driven tongue-in-cheek culture.', '«Гаражные королевы» — блестящие, но не езженные (шутка культуры)!'],
    ['Trickle chargers long-term storage battery maintainers winterized fleets prepared springs.', 'Трикл-чейджеры готовят зимующие машины к весне!'],
    ['Fuel stabilisers storage tanks condensation prevention gumming carb jets avoided seasons.', 'Стабилизатор топлива спасает жиклёры от загустения зимой!'],
    ['Fogging oil cylinders internal coating storage corrosion prevention rituals classic collections.', 'Консервация цилиндров маслом — ритуал классических коллекций!'],
    ['Battery disconnect switches parasitic drain eliminated storage periods fire safety garages insurance required.', 'Отключатели массы обязательны по требованиям страховки!'],
    ['Tyre cradles flat spotting prevention storage stacks rotated periodically shapes preserved.', 'Кронштейны под шины сохраняют их форму на хранении!'],
    ['Car covers breathing fabric moisture trapped mildew prevention cotton vs synthetics debates.', 'Дышащие чехлы против плесени: хлопок или синтетика — спорят!'],
    ['Detailing clay bar contaminants paint decontamination ceramic coatings hydrophobic applied professional.', 'Глина для деталей и керамика — профессиональный уход!'],
    ['Paint correction polishing compounds swirl removal machine polisher skills developed patient.', 'Полировка убирает голограммы — навык нарабатывается терпением!'],
    ['Paint depth gauge readings clear coat margins resprays history revealed buyers informed.', 'Толщиномер краски раскрывает историю перекрасов покупателю!'],
    ['VIN chassis number matching originality verification collectors values determined authenticity paramount.', 'Совпадение VIN определяет ценность коллекционной машины!'],
    ['Heritage certificates manufacturers archives build sheets documented provenance authenticated valued premiums.', 'Архивные build sheets подтверждают происхождение и цену!'],
  ],
};
