// Top-up batches: airport, hotel, train & metro, bus & taxi, directions.
export const topups = {
  airport: [
    ['Where is the check-in counter for this airline?', 'Где стойка регистрации этой авиакомпании?'],
    ['Online check-in is faster.', 'Онлайн-регистрация быстрее.'],
    ['Here’s my booking reference.', 'Вот код моего бронирования.'],
    ['Could you print my boarding pass?', 'Распечатайте мой посадочный талон, пожалуйста.'],
    ['Mobile boarding pass will do.', 'Подойдёт посадочный талон в телефоне.'],
    ['Is the flight full today?', 'Рейс сегодня полный?'],
    ['Any chance of an upgrade?', 'Есть шанс на повышение класса?'],
    ['How much for extra legroom?', 'Сколько стоит место с увеличенным пространством для ног?'],
    ['Are there middle seats free?', 'Средние места свободны?'],
    ['Book me an exit row seat.', 'Забронируйте мне место у аварийного выхода.'],
    ['Fragile items in this bag.', 'В этой сумке хрупкие вещи.'],
    ['Handle with care, please.', 'Обращайтесь осторожно, пожалуйста.'],
    ['This suitcase exceeds the weight limit.', 'Этот чемодан превышает лимит веса.'],
    ['Weigh it again, please.', 'Взвесьте ещё раз, пожалуйста.'],
    ['Overweight baggage fee?', 'Сколько доплата за перевес багажа?'],
    ['Move some items to carry-on.', 'Переложите часть вещей в ручную кладь.'],
    ['Where do I drop off my bags?', 'Куда сдать чемоданы?'],
    ['Bags are checked through to Tokyo.', 'Багаж оформлен до Токио.'],
    ['Luggage tag says priority.', 'На багажной бирке пометка «приоритет».'],
    ['Security line moves quickly.', 'Очередь на контроль идёт быстро.'],
    ['Which lane for families?', 'Какая полоса для семей с детьми?'],
    ['Priority lane for business class.', 'Приоритетная полоса для бизнес-класса.'],
    ['Empty your pockets, please.', 'Освободите карманы, пожалуйста.'],
    ['Laptops out of the bag.', 'Достаньте ноутбуки из сумок.'],
    ['Liquids must be under one hundred milliliters.', 'Жидкости должны быть меньше ста миллилитров.'],
    ['This water bottle has to go.', 'Эту бутылку воды придётся оставить.'],
    ['Can I bring an empty bottle through?', 'Можно пронести пустую бутылку?'],
    ['Duty-free purchases are allowed.', 'Покупки из duty-free разрешены.'],
    ['Sealed bag with receipts, please.', 'Держите их в запечатанном пакете с чеками.'],
    ['Random additional screening.', 'Выборочный дополнительный досмотр.'],
    ['Follow me for a pat-down.', 'Пройдите за мной для личного досмотра.'],
    ['Wand check, arms out please.', 'Проход рамкой, руки в стороны, пожалуйста.'],
    ['Am I clear to go?', 'Я могу проходить?'],
    ['You’re all set.', 'Все в порядке, проходите.'],
    ['Where can I fill my water bottle?', 'Где можно наполнить бутылку водой?'],
    ['Smoking area this way.', 'Курительная зона в ту сторону.'],
    ['Prayer room location?', 'Где комната для молитв?'],
    ['Kids play area nearby?', 'Где ближайшая детская игровая зона?'],
    ['Nursing room on level two.', 'Комната матери и ребёнка на втором уровне.'],
    ['Lounges upstairs.', 'Залы ожидания наверху.'],
    ['Day pass for the lounge?', 'Можно разовый пропуск в зал ожидания?'],
    ['Complimentary lounge access with this card.', 'С этой картой вход в зал бесплатно.'],
    ['Last call for boarding!', 'Последнее приглашение на посадку!'],
    ['Gate change announcement.', 'Объявление о смене выхода.'],
    ['Boarding gate moved to C2.', 'Выход перенесён на C2.'],
    ['Delay compensation form, please.', 'Дайте форму на компенсацию за задержку, пожалуйста.'],
    ['Voucher for meals during the delay?', 'Будут ли талоны на питание во время задержки?'],
    ['Hotel provided for overnight delay?', 'Отель положен при ночной задержке?'],
    ['Rebooking desk is to the left.', 'Стойка перебронирования слева.'],
    ['Next available flight tomorrow morning.', 'Следующий рейс завтра утром.'],
    ['Put me on standby, please.', 'Запишите меня в лист ожидания, пожалуйста.'],
    ['Window seat near the wing, ideally.', 'Идеально — место у окна возле крыла.'],
    ['Turbulence expected over the mountains.', 'Над горами ожидается турбулентность.'],
    ['Seatbelt sign is off now.', 'Табло «пристегните ремни» выключено.'],
    ['Cabin crew will serve drinks shortly.', 'Бортпроводники скоро предложат напитки.'],
    ['Headphones in the armrest.', 'Наушники в подлокотнике.'],
    ['In-flight magazine in the seat pocket.', 'Журнал в кармане кресла.'],
    ['Customs form filled out.', 'Таможенную декларацию заполнил.'],
    ['Immigration queue on the right.', 'Очередь на паспортный контроль справа.'],
    ['E-gates accept our passports.', 'Автоматические ворота принимают наши паспорта.'],
    ['Stamp my landing card, please.', 'Штамп в карту прибытия, пожалуйста.'],
  ],

  hotel: [
    ['I’d like a room with a view.', 'Хотел бы номер с видом.'],
    ['Sea view if possible.', 'С видом на море, если возможно.'],
    ['A quiet room away from the elevator.', 'Тихий номер подальше от лифта.'],
    ['High floor preferred.', 'Предпочитаю высокий этаж.'],
    ['Do you have connecting rooms?', 'Есть смежные номера?'],
    ['Cot for the baby, please.', 'Добавьте детскую кроватку, пожалуйста.'],
    ['Hypoallergenic pillows available?', 'Есть гипоаллергенные подушки?'],
    ['Non-smoking room, definitely.', 'Только номер для некурящих.'],
    ['What’s included in the rate?', 'Что входит в стоимость?'],
    ['City tax paid separately?', 'Городской сбор оплачивается отдельно?'],
    ['Tourist tax per night?', 'Туристический налог за ночь?'],
    ['Deposit refunded at checkout?', 'Депозит вернут при выезде?'],
    ['Prepay or pay at the property?', 'Оплата заранее или на месте?'],
    ['Free cancellation until when?', 'До какого момента бесплатная отмена?'],
    ['Late arrival after midnight — hold my room.', 'Приеду после полуночи — сохраните номер.'],
    ['Guaranteed late check-in.', 'Гарантированное позднее заселение.'],
    ['Airport shuttle schedule?', 'Расписание трансфера в аэропорт?'],
    ['Shuttle pickup from terminal two.', 'Трансфер забирает со второго терминала.'],
    ['Breakfast starts at what time?', 'Во сколько начинается завтрак?'],
    ['Continental or full English?', 'Континентальный или полный английский завтрак?'],
    ['Room-only rate, no breakfast.', 'Только номер, без завтрака.'],
    ['Half board includes dinner.', 'Полупансион включает ужин.'],
    ['All-inclusive package details?', 'Детали пакета «всё включено»?'],
    ['Gym opening hours?', 'Часы работы тренажёрного зала?'],
    ['Spa treatments bookable at reception.', 'Спa-процедуры бронируются на ресепшене.'],
    ['Pool towels by the entrance.', 'Полотенца для бассейна у входа.'],
    ['Sauna included in the price?', 'Сауна входит в цену?'],
    ['Business center on the ground floor.', 'Бизнес-центр на первом этаже.'],
    ['Conference room booked for ten.', 'Конференц-зал забронирован на десять часов.'],
    ['Print boarding passes at reception?', 'Можно распечатать посадочные талоны на ресепшене?'],
    ['Scan and email this document, please.', 'Отсканируйте и отправьте этот документ по почте, пожалуйста.'],
    ['Wake-up call plus taxi at seven.', 'Разбудите в семь и закажите такси.'],
    ['Two more nights, same room.', 'Ещё две ночи, тот же номер.'],
    ['Switch to a bigger room?', 'Можно перейти в номер побольше?'],
    ['Rate difference for the upgrade?', 'Какая разница в цене за апгрейд?'],
    ['Complimentary upgrade — lovely surprise!', 'Бесплатное улучшение номера — приятный сюрприз!'],
    ['Minibar charges on final bill.', 'Расходы из мини-бара добавят к итоговому счёту.'],
    ['Didn’t touch the minibar.', 'Мы не трогали мини-бар.'],
    ['Movie rentals charged twice.', 'Фильмы списали дважды.'],
    ['Check the bill before I pay.', 'Проверю счёт перед оплатой.'],
    ['Split the bill between two cards.', 'Разделите счёт на две карты.'],
    ['Cash payment possible?', 'Возможна оплата наличными?'],
    ['Invoice for my company, please.', 'Выставите счёт на компанию, пожалуйста.'],
    ['Receipt with company details.', 'Чек с реквизитами компании.'],
    ['Lost and found kept for thirty days.', 'Найденные вещи хранят тридцать дней.'],
    ['Mail held for guests?', 'Почту для гостей хранят на ресепшене?'],
    ['Postcard stamps sold here?', 'Марки для открыток продаются здесь?'],
    ['Recommend a local restaurant?', 'Посоветуете местный ресторан?'],
    ['Safe neighborhood for evening walks?', 'Район безопасен для вечерних прогулок?'],
    ['Walking distance to old town?', 'До старого города дойти пешком можно?'],
    ['Map of the city center, please.', 'Дайте карту центра города, пожалуйста.'],
    ['Luggage storage after checkout?', 'Можно оставить багаж после выезда?'],
    ['Checkout was smooth, thank you.', 'Выезд прошёл легко, спасибо.'],
    ['Five stars for the staff!', 'Персоналу пять звёзд!'],
    ['Complaint to the manager, please.', 'Позовите менеджера, хочу пожаловаться.'],
    ['This is unacceptable service.', 'Это неприемлемый сервис.'],
    ['Refund the difference, please.', 'Верните разницу, пожалуйста.'],
  ],

  trainmetro: [
    ['Round trip to Boston, please.', 'Билет в Бостон и обратно, пожалуйста.'],
    ['Off-peak tickets are cheaper.', 'Билеты вне часа пик дешевле.'],
    ['Peak fares apply until nine.', 'Тариф часа пик действует до девяти.'],
    ['Group discount for six people?', 'Есть групповая скидка для шести человек?'],
    ['Child ticket half price?', 'Детский билет за полцены?'],
    ['Senior discount available?', 'Скидка для пенсионеров есть?'],
    ['Validate your card at the yellow reader.', 'Приложите карту к жёлтому валидатору.'],
    ['Tap in and tap out.', 'Приложите при входе и при выходе.'],
    ['Insufficient balance on the card.', 'Недостаточно средств на карте.'],
    ['Top up the minimum amount.', 'Пополните на минимальную сумму.'],
    ['Machine only takes coins.', 'Автомат принимает только монеты.'],
    ['Ticket inspector coming through.', 'Контролёр идёт по вагону.'],
    ['Show your ticket, please.', 'Предъявите билет, пожалуйста.'],
    ['Fine for riding without a ticket.', 'Штраф за безбилетный проезд.'],
    ['I’ll buy one right now.', 'Я куплю билет прямо сейчас.'],
    ['Which direction is inbound?', 'В какую сторону в центр (inbound)?'],
    ['Outbound platform across the bridge.', 'Платформа «из города» через мост.'],
    ['Northbound or southbound?', 'На север или на юг?'],
    ['Terminus station, everyone off.', 'Конечная станция, все выходят.'],
    ['End of the line, please exit.', 'Конечная остановка, просим выйти.'],
    ['Service resumes at five a.m.', 'Движение возобновится в пять утра.'],
    ['Night buses replace trains tonight.', 'Сегодня ночью поезда заменят ночными автобусами.'],
    ['Track maintenance this weekend.', 'Ремонт путей в эти выходные.'],
    ['Replacement shuttle running.', 'Ходит заменяющий шаттл.'],
    ['Delays up to twenty minutes.', 'Задержки до двадцати минут.'],
    ['Minor delays on all lines.', 'Небольшие задержки на всех линиях.'],
    ['Good service on all lines.', 'На всех линиях движение штатное.'],
    ['Lifts to street level over there.', 'Лифты на поверхность вон там.'],
    ['Stairs are quicker than waiting.', 'По лестнице быстрее, чем ждать лифт.'],
    ['Watch your head stepping out.', 'Осторожно, не ударитесь головой на выходе.'],
    ['Priority seats for elderly and disabled.', 'Приоритетные места для пожилых и маломобильных.'],
    ['Give up your seat if needed.', 'Уступи место, если требуется.'],
    ['Prams and bicycles at the rear car.', 'Коляски и велосипеды — в задний вагон.'],
    ['No eating on the platform.', 'На платформе нельзя есть.'],
    ['Bin your coffee before boarding.', 'Выбросьте кофе перед посадкой.'],
    ['Quiet carriage ahead of us.', 'Тихий вагон впереди.'],
    ['Phone calls prohibited here.', 'Здесь запрещены телефонные разговоры.'],
    ['Headphones on, volume low.', 'Наушники надел, громкость убавил.'],
    ['Reserved seating sticker on the window.', 'Наклейка о бронировании мест на окне.'],
    ['Unreserved cars fill up fast.', 'Вагоны без брони заполняются быстро.'],
    ['Standing room only.', 'Только стоячие места.'],
    ['Packed like sardines today.', 'Сегодня битком, как селёдка в бочке.'],
    ['Squeeze in, there’s room.', 'Втискивайтесь, есть место.'],
    ['Next stop: Central Station.', 'Следующая станция: Центральный вокзал.'],
    ['Announced stops listed above the door.', 'Список остановок над дверью.'],
    ['Electronic display shows next stop.', 'Электронное табло показывает следующую станцию.'],
    ['Change here for line four.', 'Здесь пересадка на четвёртую линию.'],
    ['Interchange takes about five minutes.', 'Переход занимает около пяти минут.'],
    ['Exit via the main concourse.', 'Выходите через главный зал.'],
    ['Follow the green line overhead.', 'Идите по зелёной линии наверху.'],
  ],

  taxibus: [
    ['Book a cab for four passengers.', 'Закажите такси на четверых пассажиров.'],
    ['Need a child seat, please.', 'Нужно детское кресло, пожалуйста.'],
    ['Pet-friendly car required.', 'Нужна машина, куда можно с животным.'],
    ['Van for luggage space.', 'Нужен минивэн — много багажа.'],
    ['Driver arriving in three minutes.', 'Водитель прибудет через три минуты.'],
    ['License plate ends in seven.', 'Номер машины кончается на семь.'],
    ['Silver sedan, right?', 'Серебристый седан, верно?'],
    ['Confirming my name matches.', 'Сверяю имя водителя с приложением.'],
    ['Not my ride, sorry.', 'Это не моя машина, извините.'],
    ['Shared ride or private?', 'Попутная поездка или индивидуальная?'],
    ['Metered fare or fixed price?', 'По счётчику или фиксированная цена?'],
    ['Roughly what will it cost?', 'Сколько примерно это будет стоить?'],
    ['Estimate around fifteen dollars.', 'Примерно около пятнадцати долларов.'],
    ['Cheaper route through suburbs?', 'Дешевле объехать через окраины?'],
    ['Fastest way, please, money’s no issue.', 'Быстрейшим путём, деньги не проблема.'],
    ['Traffic camera zone ahead.', 'Впереди зона камер.'],
    ['Speed limit here is fifty.', 'Здесь ограничение пятьдесят.'],
    ['Merge left at the junction.', 'На развязке перестройтесь левее.'],
    ['Roundabout, second exit.', 'На круговом движении второй выезд.'],
    ['Drop me at departures level.', 'Высадите меня на уровне вылетов.'],
    ['Arrivals side, please.', 'К стороне прилётов, пожалуйста.'],
    ['Hotel entrance round the corner.', 'Вход в отель за углом.'],
    ['Wait here, I’ll be quick.', 'Подождите здесь, я быстро.'],
    ['Keep the meter running.', 'Пусть счётчик работает.'],
    ['Extra charge for waiting time?', 'Ожидание оплачивается дополнительно?'],
    ['First five minutes free.', 'Первые пять минут бесплатно.'],
    ['Airport surcharge applies.', 'Есть надбавка за поездку в аэропорт.'],
    ['Night tariff after eleven.', 'Ночной тариф после одиннадцати.'],
    ['Toll road adds two dollars.', 'Платная дорога добавит два доллара.'],
    ['Skip the tolls, please.', 'Без платных участков, пожалуйста.'],
    ['Receipt printer broken, sorry.', 'Принтер чеков сломан, извините.'],
    ['Email receipt instead?', 'Могу прислать чек на почту вместо этого.'],
    ['Five-star rating for you!', 'Пять звёзд вам за поездку!'],
    ['Left a good review with tip.', 'Оставил хороший отзыв и чаевые.'],
    ['Bus pass for a week, please.', 'Проездной на неделю, пожалуйста.'],
    ['Single ride fare?', 'Сколько стоит разовая поездка?'],
    ['Exact change appreciated.', 'Желательно без сдачи (точная сумма).'],
    ['Driver doesn’t carry change.', 'У водителя нет сдачи.'],
    ['Front seats empty, sit anywhere.', 'Передние места свободны, садитесь куда хотите.'],
    ['Rear door opens automatically.', 'Задняя дверь открывается автоматически.'],
    ['Push the button to request a stop.', 'Нажмите кнопку, чтобы запросить остановку.'],
    ['Stop requested light is on.', 'Горит табло «остановка по требованию».'],
    ['Missed my stop, one back.', 'Проехал остановку, одну назад.'],
    ['This loop goes downtown first.', 'Этот кольцевой маршрут сначала идёт в центр.'],
    ['Express skips minor stops.', 'Экспресс пропускает второстепенные остановки.'],
    ['Local stops everywhere.', 'Обычный автобус останавливается везде.'],
    ['Timetable posted at the shelter.', 'Расписание висит на остановке.'],
    ['Real-time board says two minutes.', 'Табло показывает: две минуты.'],
    ['Ghost bus disappeared from the app.', 'Автобус-призрак исчез из приложения (шутл.).'],
    ['Three buses came at once.', 'Три автобуса пришли сразу, как всегда.'],
    ['Typical bus bunching.', 'Классика: автобусы идут пачкой.'],
  ],

  directions: [
    ['Sorry to trouble you, quick question.', 'Извините за беспокойство, быстрый вопрос.'],
    ['Point me toward the river, please.', 'Направьте меня к реке, пожалуйста.'],
    ['Lead the way!', 'Веди дорогу! / Показывайте путь!'],
    ['After you.', 'После вас. / Проходите первым.'],
    ['Mind your step here.', 'Осторожно, здесь ступенька.'],
    ['Low ceiling ahead, duck down.', 'Впереди низкий потолок, пригнитесь.'],
    ['Narrow passage, single file.', 'Узкий проход, идёмте по одному.'],
    ['Dead end, we turn back.', 'Тупик, разворачиваемся.'],
    ['No through road here.', 'Здесь сквозного проезда нет.'],
    ['Loop back to the main path.', 'Возвращаемся к главной тропе.'],
    ['Shortcut through the park.', 'Короткий путь через парк.'],
    ['Cut through the alley.', 'Срежем через переулок.'],
    ['Scenic route is longer.', 'Красивый маршрут длиннее.'],
    ['Pedestrian zone starts here.', 'Пешеходная зона начинается здесь.'],
    ['Cars banned beyond this point.', 'Дальше машины запрещены.'],
    ['One-way street, circle around.', 'Улица с односторонним движением, объезжайте.'],
    ['U-turn not allowed here.', 'Здесь разворот запрещён.'],
    ['Underpass beneath the ring road.', 'Подземный переход под кольцевой.'],
    ['Footbridge over the highway.', 'Пешеходный мост над трассой.'],
    ['Crosswalk painted on the road.', 'Зебра нарисована на дороге.'],
    ['Wait for the green man.', 'Ждите зелёный сигнал.'],
    ['Jaywalking fine is steep here.', 'Штраф за переход в неположенном месте большой.'],
    ['Tram tracks in the middle.', 'Трамвайные пути посередине дороги.'],
    ['Cycle lane on your left.', 'Велодорожка слева от вас.'],
    ['Watch for scooters on the sidewalk.', 'Осторожно, самокаты на тротуаре.'],
    ['Bollards block car entry.', 'Столбики не пускают машины.'],
    ['Archway leads to the courtyard.', 'За аркой двор.'],
    ['Passage between the buildings.', 'Проход между домами.'],
    ['Landmark is the big clock tower.', 'Ориентир — большая часовая башня.'],
    ['Golden dome visible from afar.', 'Золотой купол виден издалека.'],
    ['Statue marks the square’s center.', 'Статуя в центре площади.'],
    ['Fountain is the meeting spot.', 'Фонтан — место встречи.'],
    ['Stand by the fountain, I’ll find you.', 'Стой у фонтана, я тебя найду.'],
    ['Look for the red awning.', 'Ищи красный навес.'],
    ['Entrance hidden behind the café.', 'Вход спрятан за кафе.'],
    ['Side door open till eight.', 'Боковая дверь открыта до восьми.'],
    ['Staff entrance around back.', 'Служебный вход сзади.'],
    ['Loading zone, keep moving.', 'Зона погрузки, не задерживайтесь.'],
    ['Driveway, don’t block it.', 'Въезд во двор, не загораживайте.'],
    ['Kerb cut ahead for wheelchairs.', 'Впереди спуск с бордюра для колясок.'],
    ['Ramp instead of steps.', 'Пандус вместо ступенек.'],
    ['Elevator to the platform level.', 'Лифт до уровня платформы.'],
    ['Accessible route clearly marked.', 'Безбарьерный маршрут размечен.'],
    ['Tourist info booth straight ahead.', 'Информационная стойка прямо впереди.'],
    ['Free city maps inside.', 'Внутри бесплатные карты города.'],
    ['Guided walking tour starts here.', 'Пешеходная экскурсия стартует отсюда.'],
    ['Self-guided trail signs along the way.', 'Указатели самостоятельного маршрута вдоль пути.'],
    ['Trail forks at the big oak.', 'Тропа раздваивается у большого дуба.'],
    ['Keep the lake on your right.', 'Держите озеро по правую руку.'],
    ['Summit trail is steep but worth it.', 'Тропа к вершине крутая, но стоит того.'],
    ['Viewpoint ten minutes further.', 'Смотровая площадка ещё в десяти минутах.'],
    ['Photo spot just past the bridge.', 'Лучшее место для фото сразу за мостом.'],
    ['Best angle from the opposite bank.', 'Лучший ракурс с противоположного берега.'],
    ['Panorama opens at the top.', 'Панорама открывается на вершине.'],
    ['Worth every step of the climb.', 'Подъёма стоило каждого шага.'],
    ['Loop trail returns to parking.', 'Кольцевая тропа выводит к парковке.'],
    ['Return the way we came.', 'Вернёмся той же дорогой.'],
    ['Backtrack to the signpost.', 'Возвращаемся к указателю.'],
    ['Signpost points two ways.', 'Указатель показывает в обе стороны.'],
    ['Distance marker says three kilometers.', 'Табличка расстояния: три километра.'],
  ],
};
