// Top-up batches: feelings, dating, social media chat, work, job interview.
export const topups = {
  feelings: [
    ['How did that make you feel?', 'Что ты при этом почувствовал?'],
    ['I’m at a loss for words.', 'Я не нахожу слов.'],
    ['I’m overwhelmed.', 'Меня это переполняет / я не справляюсь с потоком эмоций.'],
    ['I need to process this.', 'Мне нужно это осмыслить.'],
    ['It hasn’t sunk in yet.', 'Это ещё не осозналось до конца.'],
    ['I’m in shock, honestly.', 'Честно, я в шоке.'],
    ['I’m speechless.', 'Я онемел / нет слов.'],
    ['I’m overjoyed!', 'Я вне себя от радости!'],
    ['I’m on cloud nine.', 'Я летаю на облаке счастья.'],
    ['Life is beautiful.', 'Жизнь прекрасна.'],
    ['I wouldn’t change a thing.', 'Я бы ничего не менял.'],
    ['Content and grateful.', 'Доволен и благодарен.'],
    ['Counting my blessings.', 'Считаю свои блага (благодарю за всё).'],
    ['I feel blessed.', 'Я чувствую, что мне повезло в жизни.'],
    ['I couldn’t ask for more.', 'Больше и желать нельзя.'],
    ['Living the dream.', 'Живу мечтой (шутл.).'],
    ['Best day ever!', 'Лучший день в жизни!'],
    ['Made my whole week.', 'Украсил мне всю неделю.'],
    ['I’m buzzing with excitement.', 'Я звеню от восторга.'],
    ['Can’t stop smiling.', 'Не могу перестать улыбаться.'],
    ['Grinning from ear to ear.', 'Улыбаюсь до ушей.'],
    ['My heart is full.', 'У меня сердце переполнено.'],
    ['Touched beyond words.', 'Тронут(а) до глубины души.'],
    ['That means the world to me.', 'Для меня это очень много значит.'],
    ['You warmed my heart.', 'Ты согрел моё сердце.'],
    ['I’m moved to tears.', 'Я растроган(а) до слёз.'],
    ['Bittersweet memories.', 'Горько-сладкие воспоминания.'],
    ['Nostalgia is hitting hard.', 'Ностальгия накрыла с головой.'],
    ['I miss being a kid sometimes.', 'Иногда скучаю по детству.'],
    ['Time heals all wounds.', 'Время лечит любые раны.'],
    ['Grief comes in waves.', 'Горе накатывает волнами.'],
    ['I’m still grieving.', 'Я всё ещё скорблю.'],
    ['My heart goes out to them.', 'Моё сердце им принадлежит (им сочувствую).'],
    ['I feel for you.', 'Мне искренне тебя жаль / понимаю тебя.'],
    ['That must be so hard.', 'Как же это тяжело для тебя.'],
    ['Sending strength.', 'Шлю тебе силы.'],
    ['I’m here for you.', 'Я рядом / я с тобой.'],
    ['Lean on me.', 'Обопрись на меня.'],
    ['You’re not alone in this.', 'Ты не один в этом.'],
    ['It’s okay to not be okay.', 'Нормально быть не в порядке.'],
    ['Feelings are valid.', 'Твои чувства имеют значение.'],
    ['Don’t bottle it up.', 'Не держи всё в себе.'],
    ['Let it all out.', 'Выплесни всё наружу.'],
    ['Have a good cry if you need to.', 'Поплачь, если нужно — поможет.'],
    ['Cry it out, you’ll feel better.', 'Проревись, станет легче.'],
    ['I needed that cry.', 'Мне это было нужно — поплакала.'],
    ['Feeling much lighter now.', 'Сейчас стало легче на душе.'],
    ['Weight lifted off my shoulders.', 'Будто гора с плеч.'],
    ['Like a weight has been lifted.', 'Как будто гирю сняли с плеч.'],
    ['Breathing easier now.', 'Теперь дышится легче.'],
    ['Peace of mind at last.', 'Наконец-то душевный покой.'],
    ['At peace with it now.', 'Теперь я примирился с этим.'],
    ['Made peace with the past.', 'Помирился со своим прошлым.'],
    ['No regrets.', 'Никаких сожалений.'],
    ['Live without regrets.', 'Живи без сожалений.'],
    ['Looking back with fondness.', 'Оглядываюсь назад с теплотой.'],
    ['The good old days.', 'Старые добрые времена.'],
    ['Those were the days!', 'Вот были времена!'],
  ],

  dating: [
    ['Do you come here often?', 'Ты часто сюда заходишь?'],
    ['Can I join you?', 'Можно присоединюсь?'],
    ['Is this seat taken or are you saving it?', 'Это место занято или вы его бережёте?'],
    ['What’s a person like you doing in a place like this?', 'Что человек вроде вас делает в таком месте?'],
    ['Have we met before?', 'Мы раньше встречались?'],
    ['You seem familiar.', 'Ты мне кого-то напоминаешь.'],
    ['Sorry, I had to come say hi.', 'Извини, просто должен был подойти поздороваться.'],
    ['My friends dared me to talk to you.', 'Друзья поспорили, что я подойду к тебе.'],
    ['Can I get your number?', 'Можно твой номер телефона?'],
    ['Give me your number and I’ll text you.', 'Дай номер — я напишу тебе.'],
    ['Here’s my number, text me.', 'Вот мой номер, напиши мне.'],
    ['Are you free this weekend?', 'Ты свободна в эти выходные?'],
    ['Dinner, just the two of us?', 'Ужин, только ты и я?'],
    ['First date jitters?', 'Волнуешься перед первым свиданием?'],
    ['I picked this place specially.', 'Я выбрал это место специально.'],
    ['Hope you like Italian food.', 'Надеюсь, ты любишь итальянскую кухню.'],
    ['You look even better in person.', 'Вживую ты выглядишь ещё лучше.'],
    ['Photos don’t do you justice.', 'Фото тебя не передают.'],
    ['Tell me about your perfect Sunday.', 'Расскажи про своё идеальное воскресенье.'],
    ['Coffee person or tea person?', 'Ты за кофе или за чай?'],
    ['Cat person or dog person?', 'Ты за кошек или за собак?'],
    ['Morning runs or evening walks?', 'Утренние пробежки или вечерние прогулки?'],
    ['Beach holidays or mountains?', 'Отпуск на море или в горах?'],
    ['Sweet tooth?', 'Любишь сладкое?'],
    ['Pineapple on pizza — yes or no?', 'Ананасы на пицце — да или нет?'],
    ['Serious question: how do you take your coffee?', 'Серьёзный вопрос: какой ты любишь кофе?'],
    ['Your playlist says a lot about you.', 'Твой плейлист многое о тебе говорит.'],
    ['What song describes your life?', 'Какая песня описывает твою жизнь?'],
    ['Any hidden talents?', 'Есть скрытые таланты?'],
    ['I bet you were the class clown.', 'Спорю, ты был душой компании в классе.'],
    ['You give off great energy.', 'От тебя исходит отличная энергия.'],
    ['Conversation just flows with you.', 'С тобой разговор льётся сам собой.'],
    ['I could talk to you for hours.', 'Я мог бы говорить с тобой часами.'],
    ['Is it weird that I don’t want tonight to end?', 'Странно, что я не хочу, чтобы вечер заканчивался?'],
    ['Already planning our next date.', 'Уже планирую наше следующее свидание.'],
    ['Next time dinner’s on me.', 'В следующий раз ужин за мой счёт.'],
    ['Text me when you wake up.', 'Напиши, когда проснёшься.'],
    ['Good morning, beautiful.', 'Доброе утро, красавица.'],
    ['Slept well? Dreamed of me?', 'Хорошо спала? Мне снилась? (шутл.)'],
    ['You crossed my mind today.', 'Ты сегодня мне вспомнился.'],
    ['Thinking of you always makes me smile.', 'Мысли о тебе всегда заставляют улыбаться.'],
    ['Every love story is beautiful, but ours is my favorite.', 'Всякая история любви прекрасна, но наша — моя любимая.'],
    ['Home is wherever I’m with you.', 'Дом там, где ты рядом со мной.'],
    ['You complete me.', 'Ты делаешь меня целым.'],
    ['Forever isn’t long enough with you.', 'С тобой даже вечность будет короткой.'],
  ],

  chat: [
    ['Hey stranger, long time!', 'Привет, незнакомец, сколько лет!'],
    ['Alive over there?', 'Ты там живой вообще?'],
    ['Hello?! Anyone home?', 'Аллё?! Ты тут?'],
    ['Earth to Alex!', 'Алекс, выйди на связь!'],
    ['Answer your phone sometime!', 'Возьми иногда трубку!'],
    ['Left you a voicemail.', 'Оставил тебе голосовое.'],
    ['Check your voicemail, please.', 'Проверь голосовые сообщения, пожалуйста.'],
    ['Sent a voice message instead.', 'Отправил голосовое вместо текста.'],
    ['Too lazy to type, listen to it.', 'Лень печатать — послушай.'],
    ['Typing one-handed, feeding the baby.', 'Печатаю одной рукой, кормлю ребёнка.'],
    ['Multitasking master right here.', 'Мастер многозадачности на связи.'],
    ['In line at the store, quick question.', 'Стою в очереди в магазине, есть быстрый вопрос.'],
    ['Walk-and-talk call?', 'Созвонимся на ходу?'],
    ['Calling during lunch break.', 'Позвоню в обеденный перерыв.'],
    ['Free after six?', 'Свободна после шести?'],
    ['After work drinks?', 'Пиво после работы? Кто со мной?'],
    ['Who’s in for Friday?', 'Кто идёт в пятницу?'],
    ['Headcount for Saturday, please.', 'Посчитайтесь на субботу, пожалуйста.'],
    ['Confirming attendance.', 'Подтверждаю участие.'],
    ['Regretfully declining, family stuff.', 'К сожалению, не смогу — семейные дела.'],
    ['Family emergency, be there soon.', 'Семейные обстоятельства, скоро буду.'],
    ['Running ten minutes behind.', 'Опаздываю минут на десять.'],
    ['Parking now, two minutes.', 'Паркуюсь, буду через две минуты.'],
    ['Found parking on the third try.', 'Нашёл парковку с третьего раза.'],
    ['Traffic is brutal today.', 'Пробки сегодня свирепые.'],
    ['Roads are jammed everywhere.', 'Дороги стоят повсюду.'],
    ['Left already, see you there.', 'Уже выехал, увидимся на месте.'],
    ['Almost there!', 'Почти приехал!'],
    ['Five minutes out.', 'Буду через пять минут.'],
    ['Outside, buzz me in.', 'Я снаружи, открой дверь (набери в домофон).'],
    ['Ring the doorbell twice.', 'Позвоните в дверной звонок дважды.'],
    ['We’re in booth seven.', 'Мы в седьмой кабинке.'],
    ['Back corner table by the window.', 'Дальний столик у окна.'],
    ['Grabbing the corner table.', 'Забираю столик в углу.'],
    ['Splitting the bill three ways.', 'Делим счёт на троих.'],
    ['Venmo me later.', 'Переведи мне потом через приложение.'],
    ['Send money to my card.', 'Скинь деньги на карту.'],
    ['I’ll cover it, you get next round.', 'Я заплачу, следующая порция твоя.'],
    ['Thanks again for yesterday!', 'Ещё раз спасибо за вчера!'],
    ['Yesterday was a blast!', 'Вчера было огонь!'],
    ['Same crew next month?', 'Та же компания через месяц?'],
    ['Making this a monthly thing.', 'Делаем это ежемесячной традицией.'],
    ['Calendar invite sent.', 'Приглашение в календарь отправлено.'],
    ['Added it to the group calendar.', 'Добавил в общий календарь.'],
    ['Poll attached, vote please.', 'Прикрепил опрос, проголосуйте.'],
    ['Vote closes at midnight.', 'Голосование закроется в полночь.'],
    ['Majority rules!', 'Большинство решает!'],
    ['Fine by majority vote.', 'Решено большинством.'],
    ['Overruled by popular demand.', 'Отменено общим голосованием (шутл.).'],
    ['Democracy wins again.', 'Демократия снова победила (шутл.).'],
    ['Screenshot this before it disappears.', 'Скриньте, пока не исчезло.'],
    ['This message will self-destruct.', 'Сообщение самоуничтожится (шутл.).'],
    ['Forwarded as received.', 'Пересылаю как есть.'],
    ['Copied from the group chat.', 'Скопировал из группового чата.'],
    ['Bringing this back to the top.', 'Поднимаю это сообщение наверх.'],
    ['Bumping this thread.', 'Поднимаю тему.'],
    ['Pinned message for reference.', 'Закрепил сообщение для справки.'],
    ['Check pinned messages.', 'Гляньте закреплённые сообщения.'],
    ['Scroll up for context.', 'Пролистайте вверх для контекста.'],
    ['TL;DR below.', 'Краткое содержание ниже.'],
    ['Long story short, we won.', 'Короче, мы победили.'],
    ['Details in the doc.', 'Детали в документе.'],
    ['Doc link in bio.', 'Ссылка на документ в профиле.'],
    ['Link in comments.', 'Ссылка в комментариях.'],
    ['Reposting for reach.', 'Репощу для охвата.'],
    ['Sharing to stories.', 'Делю в сторис.'],
    ['Story expires in twenty-four hours.', 'История исчезнет через двадцать четыре часа.'],
    ['Highlight saved.', 'Сохранено в актуальное.'],
    ['Archive is gold.', 'Архив — золото.'],
    ['Digging through old posts.', 'Копаюсь в старых постах.'],
    ['Throwback time!', 'Время ностальгических фото!'],
    ['Flashback Friday!', 'Пятница воспоминаний!'],
    ['Memory popped up today.', 'Сегодня всплыло старое фото из памяти.'],
    ['One year ago today.', 'Ровно год назад.'],
  ],

  work: [
    ['Welcome aboard!', 'Добро пожаловать в команду!'],
    ['Welcome to the team!', 'Добро пожаловать в команду!'],
    ['Meet the new hire.', 'Знакомьтесь, новый сотрудник.'],
    ['Show him the ropes.', 'Познакомь его с работой (научи всему).'],
    ['She’s shadowing me this week.', 'Она в этом неделю проходит стажировку рядом со мной.'],
    ['Onboarding paperwork first.', 'Сначала оформительные бумаги.'],
    ['HR will send the contract.', 'Кадры пришлют договор.'],
    ['Probation period is three months.', 'Испытательный срок — три месяца.'],
    ['Performance review next week.', 'Оценка эффективности на следующей неделе.'],
    ['Annual review coming up.', 'Скоро годовая аттестация.'],
    ['KPIs look solid this quarter.', 'Показатели за квартал крепкие.'],
    ['Numbers are up ten percent.', 'Цифры выросли на десять процентов.'],
    ['Revenue exceeded targets.', 'Выручка превысила план.'],
    ['We blew past our goals.', 'Мы перевыполнили цели.'],
    ['Budget got cut again.', 'Бюджет опять урезали.'],
    ['Hiring freeze until further notice.', 'Заморозка найма до особого распоряжения.'],
    ['Two positions opened up.', 'Открылись две вакансии.'],
    ['Referral bonus for recommendations.', 'Премия за рекомендацию кандидата.'],
    ['Team building event on Thursday.', 'Тимбилдинг в четверг.'],
    ['Offsite next month.', 'Выездной корпоратив в следующем месяце.'],
    ['Retreat agenda attached.', 'Повестка выезда во вложении.'],
    ['Casual dress code on Fridays.', 'По пятницам свободная форма одежды.'],
    ['Kitchen is stocked.', 'На кухне всё есть (запасы пополнены).'],
    ['Coffee machine is broken again.', 'Кофемашина опять сломалась.'],
    ['Someone stole my yogurt from the fridge!', 'Кто-то украл мой йогурт из холодильника!'],
    ['Fridge cleanup at five.', 'Разбор холодильника в пять (уберите свои продукты).'],
    ['Fire drill at noon.', 'Учебная пожарная тревога в полдень.'],
    ['Assembly point is the parking lot.', 'Место сбора — парковка.'],
    ['Badge access only after hours.', 'После рабочего времени вход только по карте.'],
    ['Tailgate behind you, please.', 'Не пускайте хвостом за собой посторонних.'],
    ['Security badge lost again.', 'Опять потерял пропуск.'],
    ['IT reset my password twice today.', 'Айтишники дважды сбрасывали мне пароль.'],
    ['VPN acting up again.', 'VPN опять барахлит.'],
    ['Server maintenance tonight.', 'Техобслуживание сервера сегодня ночью.'],
    ['System downtime expected.', 'Ожидается простой системы.'],
    ['Everything back online.', 'Всё снова работает.'],
    ['Ticket resolved.', 'Заявка закрыта.'],
    ['Escalate it to support.', 'Передай это в поддержку (эскалация).'],
    ['Client feedback attached.', 'Отзыв клиента во вложении.'],
    ['Client wants changes.', 'Клиент просит правки.'],
    ['Revision requested.', 'Запрошена доработка.'],
    ['Final version approved!', 'Финальная версия утверждена!'],
    ['Sign-off from legal pending.', 'Юристы ещё не согласовали.'],
    ['Compliance signed off.', 'Комплаенс согласовал.'],
    ['Contract renewal discussion.', 'Обсуждение продления договора.'],
    ['Negotiations went smoothly.', 'Переговоры прошли гладко.'],
    ['Deal is closed!', 'Сделка закрыта!'],
    ['Invoice sent on the first.', 'Счёт выставлен первого числа.'],
    ['Payment overdue reminder.', 'Напоминание о просроченном платеже.'],
    ['Expenses reimbursed weekly.', 'Расходы возмещают еженедельно.'],
    ['Submit receipts by Friday.', 'Сдайте чеки до пятницы.'],
    ['Payday is the twenty-fifth.', 'Зарплата двадцать пятого.'],
    ['Raise request denied.', 'В просьбе о повышении отказано.'],
    ['Promotion announced today!', 'О повышении объявили сегодня!'],
    ['Well-deserved promotion.', 'Заслуженное повышение.'],
    ['New role starts Monday.', 'Новая должность с понедельника.'],
    ['Handover notes shared.', 'Заметки по передаче дел разослал.'],
    ['Knowledge transfer session booked.', 'Сессия передачи знаний забронирована.'],
    ['Offboarding checklist complete.', 'Чек-лист увольнения заполнен.'],
    ['Farewell party at five!', 'Прощальная вечеринка в пять!'],
    ['Going-away card circulating.', 'Открытка на прощание ходит по рукам.'],
    ['Wishing you success in your new role!', 'Успехов на новом месте!'],
    ['Keep in touch after you leave.', 'Оставайтесь на связи после ухода.'],
    ['LinkedIn connect request sent.', 'Отправил запрос на связь в LinkedIn.'],
  ],

  interview: [
    ['Please have a seat.', 'Присаживайтесь, пожалуйста.'],
    ['Would you like some water?', 'Не хотите воды?'],
    ['Make yourself comfortable.', 'Устраивайтесь поудобнее.'],
    ['Ready to begin?', 'Готовы начать?'],
    ['Walk me through your resume.', 'Проведите меня по вашему резюме.'],
    ['Summarize your experience briefly.', 'Кратко изложите ваш опыт.'],
    ['Highlight your most relevant role.', 'Отметьте самую близкую вам должность.'],
    ['What drew you to this field?', 'Что привело вас в эту сферу?'],
    ['Why this industry specifically?', 'Почему именно эта индустрия?'],
    ['What excites you professionally?', 'Что вас вдохновляет профессионально?'],
    ['Describe your ideal workplace.', 'Опишите ваше идеальное место работы.'],
    ['What environment do you thrive in?', 'В какой обстановке вы расцветаете?'],
    ['Do you prefer structure or autonomy?', 'Вам ближе регламент или самостоятельность?'],
    ['How do you handle ambiguity?', 'Как вы справляетесь с неопределённостью?'],
    ['How do you prioritize tasks?', 'Как вы расставляете приоритеты в задачах?'],
    ['How do you organize your workflow?', 'Как вы организуете рабочий процесс?'],
    ['What tools do you use daily?', 'Какими инструментами вы пользуетесь ежедневно?'],
    ['Rate your proficiency honestly.', 'Честно оцените свой уровень владения.'],
    ['On a scale of one to ten?', 'По шкале от одного до десяти?'],
    ['Intermediate level, working toward advanced.', 'Средний уровень, двигаюсь к продвинутому.'],
    ['Tell me about a project you’re proud of.', 'Расскажите о проекте, которым гордитесь.'],
    ['What was your contribution exactly?', 'Каков был именно ваш вклад?'],
    ['Were you leading or supporting?', 'Вы руководили или помогали?'],
    ['What obstacles did you face?', 'С какими препятствиями столкнулись?'],
    ['How did you measure success?', 'Как вы измеряли успех?'],
    ['What would you do differently?', 'Что бы вы сделали иначе?'],
    ['Lessons learned from that failure?', 'Какие уроки извлекли из той неудачи?'],
    ['Failure taught me resilience.', 'Неудача научила меня стойкости.'],
    ['Tell me about a conflict with a coworker.', 'Расскажите о конфликте с коллегой.'],
    ['How did you resolve the disagreement?', 'Как вы уладили разногласия?'],
    ['We found common ground quickly.', 'Мы быстро нашли общий язык.'],
    ['Disagreement stayed professional.', 'Разногласия остались в рабочих рамках.'],
    ['How do you take criticism?', 'Как вы относитесь к критике?'],
    ['Criticism makes me better.', 'Критика делает меня лучше.'],
    ['Feedback is a gift.', 'Обратная связь — это подарок.'],
    ['Describe your management style.', 'Опишите ваш стиль управления.'],
    ['I delegate and stay involved.', 'Я делегирую, но остаюсь вовлечённым.'],
    ['Lead by example.', 'Я веду за собой личным примером.'],
    ['How big was your team?', 'Насколько большой была ваша команда?'],
    ['Cross-functional collaboration?', 'Работали ли кросс-функционально?'],
    ['Worked closely with designers and QA.', 'Тесно работал с дизайнерами и тестировщиками.'],
    ['Stakeholder management experience?', 'Есть опыт работы с заинтересованными сторонами?'],
    ['Presented findings to executives.', 'Представлял результаты руководству.'],
    ['Comfortable presenting to large groups?', 'Комфортно ли выступать перед большой аудиторией?'],
    ['Public speaking grows on you.', 'К публичным выступлениям привыкаешь.'],
    ['Any certifications or courses?', 'Есть сертификаты или курсы?'],
    ['Currently studying for certification.', 'Сейчас готовлюсь к сертификации.'],
    ['Continuous learner here.', 'Я учусь постоянно.'],
    ['Upskilling every year.', 'Каждый год повышаю квалификацию.'],
    ['Do you freelance on the side?', 'Подрабатываете фрилансом параллельно?'],
    ['Notice period at current job?', 'Срок отработки на текущем месте?'],
    ['References available upon request.', 'Рекомендации предоставлю по запросу.'],
    ['Former manager will vouch for me.', 'Бывший руководитель за меня поручится.'],
    ['Portfolio link in my resume.', 'Ссылка на портфолио есть в резюме.'],
    ['Case studies available on request.', 'Кейсы покажу по запросу.'],
    ['Anything else you’d like us to know?', 'Хотите что-то добавить о себе?'],
    ['I think we covered everything.', 'Кажется, обсудили всё.'],
    ['Thank you for considering my application.', 'Спасибо за рассмотрение моей кандидатуры.'],
    ['Hope to hear good news soon!', 'Надеюсь на хорошие новости!'],
    ['Either way, thanks for the opportunity.', 'В любом случае спасибо за возможность.'],
  ],
};
