// Final precision batches: sized to bring each dictionary to ~500 entries.
export const topups = {
  opinions: [
    ['Debatable.', 'Спорно.'],
  ],
  requests: [
    ['Could you keep this confidential?', 'Держите это в секрете, пожалуйста.'],
    ['Keep it between us.', 'Пусть останется между нами.'],
    ['Off the record, please.', 'Не для протокола, пожалуйста.'],
    ['Could you cover for me briefly?', 'Можешь меня на минутку прикрыть?'],
  ],
  work: [
    ['Desk moved next week.', 'Мой стол перенесут на следующей неделе.'],
    ['Hot-desking every Friday.', 'По пятницам — свободные рабочие места.'],
    ['Printer code changed monthly.', 'Код принтера меняют ежемесячно.'],
    ['Parking permit renewal due.', 'Скоро продление парковочного пропуска.'],
  ],
  invitations: [
    ['Join our book club?', 'Присоединяйтесь к нашему книжному клубу?'],
    ['We gather monthly for board games.', 'Мы собираемся раз в месяц за настолками.'],
    ['Bring your guitar to campfire night.', 'Захвати гитару на вечер у костра.'],
    ['Potluck dinner — bring a dish.', 'Ужин в складчину — принесите блюдо.'],
    ['Housewarming party next Saturday.', 'Новоселье в следующую субботу.'],
    ['Plus-ones welcome at the wedding.', 'На свадьбу можно с плюс-одним.'],
  ],
  advice: [
    ['Start before you feel ready.', 'Начинайте до того, как почувствуете готовность.'],
    ['Done is better than perfect.', 'Лучше сделано, чем идеально.'],
    ['Ask forgiveness, not permission.', 'Иногда проще просить прощения, чем разрешения.'],
    ['Small daily habits compound.', 'Маленькие ежедневные привычки накапливаются.'],
    ['Track progress, not perfection.', 'Отслеживай прогресс, а не идеальность.'],
    ['Rest is part of training.', 'Отдых — часть тренировки.'],
    ['Learn the rules before breaking them.', 'Выучи правила, прежде чем нарушать.'],
    ['When angry, count to ten.', 'Разозлился — посчитай до десяти.'],
  ],
  chat: [
    ['Typing from the checkout line.', 'Пишу прямо из очереди на кассе.'],
    ['Battery at five percent, hurry!', 'Батареи пять процентов, быстрее!'],
    ['Charger lent to a colleague.', 'Одолжил зарядку коллеге.'],
    ['Signal drops in the elevator.', 'В лифте пропадает связь.'],
    ['Basement has zero bars.', 'В подвале ни одного деления.'],
    ['Wi-Fi password changed again?', 'Пароль от Wi-Fi опять сменился?'],
    ['Router restart fixed it.', 'Перезапуск роутера помог.'],
    ['Airplane mode toggled accidentally.', 'Случайно включил авиарежим.'],
    ['Missed notifications flood after reboot.', 'После перезагрузки лавина уведомлений.'],
  ],
  timedates: [
    ['What keeps you so busy lately?', 'Что вас так занимает в последнее время?'],
    ['This week flew by.', 'Неделя пролетела.'],
    ['Dragging on forever today.', 'Сегодня тянется бесконечно.'],
    ['Monday again already?', 'Опять понедельник?!'],
    ['Midweek hump day.', 'Экватор недели — среда.'],
    ['Almost weekend, hang tight.', 'Почти выходные, потерпите.'],
    ['Sunday reset routine.', 'Воскресная перезагрузка (планы на неделю).'],
    ['New Year resolutions fading.', 'Новогодние обещания тают.'],
    ['Spring forward one hour.', 'Переводим часы на час вперёд.'],
    ['Fall back tonight.', 'Ночью переводим часы назад.'],
    ['Daylight saving confusion again.', 'Опять путаница с переводом часов.'],
  ],
  apologies: [
    ['Sorry for the wall of text.', 'Извините за простыню текста.'],
    ['Apologies for the essay-length reply.', 'Простите за ответ длиной с сочинение.'],
    ['Sorry, hit send too early.', 'Извините, рано отправил сообщение.'],
    ['Ignore my previous message.', 'Проигнорируйте моё прошлое сообщение.'],
    ['Correction to my earlier note.', 'Поправка к моему раннему сообщению.'],
    ['My mistake on the dates.', 'Я ошибся с датами.'],
    ['Mixed up two threads, sorry.', 'Перепутал две переписки, извините.'],
    ['Wrong recipient, please delete.', 'Не тому адресату — удалите, пожалуйста.'],
    ['Recall that email immediately!', 'Отзовите то письмо немедленно!'],
    ['Sent before proofreading, oops.', 'Отправил без вычитки — упс.'],
    ['Typos mine, apologies.', 'Опечатки мои, извините.'],
    ['Autocorrect betrayed me again.', 'Автозамена снова меня подвела.'],
    ['Voice message by accident.', 'Голосовое записалось случайно.'],
  ],
  techsupport: [
    ['Cursor freezes randomly.', 'Курсор беспричинно замирает.'],
    ['Touchpad double-typing letters.', 'Тачпад дублирует буквы.'],
    ['Keyboard keys sticking.', 'Клавиши клавиатуры залипают.'],
    ['Spilled coffee on the keyboard!', 'Пролил кофе на клавиатуру!'],
    ['Flip it upside down quickly!', 'Быстро переверните вверх дном!'],
    ['The rice trick is a myth for laptops.', 'Для ноутбуков способ с рисом — миф.'],
    ['Power off and remove battery.', 'Выключите и вытащите батарею.'],
    ['Take it to service immediately.', 'Сразу несите в сервис.'],
    ['Data recovery might be possible.', 'Данные, возможно, восстановят.'],
    ['Backups saved me twice this year.', 'Резервные копии дважды спасли меня за год.'],
    ['Cloud sync finished overnight.', 'Облачная синхронизация закончилась за ночь.'],
    ['Storage almost full warning.', 'Предупреждение: память почти заполнена.'],
    ['Duplicate photos eating space.', 'Повторяющиеся фото съедают место.'],
    ['Deduplication app cleaned gigabytes.', 'Приложение нашло и убрало гигабайты дублей.'],
    ['Cache cleared, speed returned.', 'Очистил кеш — скорость вернулась.'],
    ['Background apps hogging memory.', 'Фоновые приложения забивают память.'],
    ['Task manager reveals culprits.', 'Диспетчер задач показывает виновников.'],
    ['Startup list trimmed drastically.', 'Список автозагрузки сильно сократил.'],
  ],
  interview: [
    ['Traffic made me circle the block twice.', 'Из-за пробок пришлось дважды объехать квартал.'],
    ['Nervous but well-prepared.', 'Волнуюсь, но хорошо подготовился.'],
    ['Prepared answers to classic questions.', 'Подготовил ответы на классические вопросы.'],
    ['Researched your latest product launch.', 'Изучил ваш последний запуск продукта.'],
    ['Read the team blog regularly.', 'Регулярно читаю блог команды.'],
    ['Your mission statement resonates.', 'Ваша миссия мне откликается.'],
    ['Growth opportunity attracts me most.', 'Больше всего привлекает возможность роста.'],
    ['Mentoring juniors excites me.', 'Мне интересно наставничество над новичками.'],
    ['I thrive on challenging problems.', 'Расцветаю на сложных задачах.'],
    ['Routine kills my motivation slowly.', 'Рутина медленно убивает мотивацию.'],
    ['Deadlines focus me naturally.', 'Дедлайны меня естественно собирают.'],
    ['I break big tasks into milestones.', 'Делю крупные задачи на этапы.'],
    ['Estimate first, then add twenty percent buffer.', 'Сначала оценка, затем плюс двадцать процентов запаса.'],
    ['Underpromise and overdeliver.', 'Обещай меньше — сделай больше.'],
    ['Communication avoids surprises.', 'Коммуникация избавляет от сюрпризов.'],
    ['Bad news reaches me first.', 'Плохие новости я узнаю первым.'],
    ['Documentation saves future headaches.', 'Документация избавляет от будущих проблем.'],
    ['Code reviews taught me humility.', 'Ревью кода научили меня скромности.'],
    ['Testing is respect for teammates.', 'Тестирование — уважение к коллегам.'],
    ['Legacy code deserves patience.', 'Старый код требует терпения.'],
    ['Refactoring gradually beats rewriting.', 'Постепенный рефакторинг лучше переписывания.'],
    ['Metrics guided our decisions.', 'Метрики вели наши решения.'],
    ['A/B testing settled the debate.', 'A/B-тест закрыл спор.'],
    ['User feedback beats assumptions.', 'Отзывы пользователей лучше предположений.'],
    ['Accessibility often overlooked.', 'Доступность часто упускают из виду.'],
    ['Performance budget enforced early.', 'Бюджет производительности соблюдали сразу.'],
    ['Security review before launch.', 'Проверка безопасности перед релизом.'],
    ['Postmortems without blame culture.', 'Разборы инцидентов без поиска виновных.'],
  ],
  taxibus: [
    ['Meter seems to jump oddly.', 'Счётчик подозрительно скачет.'],
    ['Check the meter, please.', 'Проверьте счётчик, пожалуйста.'],
    ['Was that detour necessary?', 'Этот объезд был необходим?'],
    ['I know a shorter way.', 'Я знаю дорогу короче.'],
    ['Follow the navigation, please.', 'Следуйте навигатору, пожалуйста.'],
    ['Navigation says left here.', 'Навигатор говорит: здесь налево.'],
    ['Recalculating route constantly.', 'Маршрут пересчитывается постоянно.'],
    ['Road closed for marathon today.', 'Дорога закрыта из-за марафона.'],
    ['Street festival blocking the bridge.', 'Уличный праздник перекрыл мост.'],
    ['Protest march downtown expected.', 'В центре ожидается шествие.'],
    ['Trams diverted via side streets.', 'Трамваи идут в объезд по боковым.'],
    ['Bus lane cameras fine drivers.', 'Камеры в автобусной полосе штрафуют водителей.'],
    ['Taxi rank outside terminal B.', 'Стоянка такси у терминала Б.'],
    ['Marshrutka stops on demand.', 'Маршрутка останавливается по требованию.'],
    ['Fare paid in cash to driver.', 'Оплата водителю наличными.'],
    ['Exact fare box only.', 'Только точная сумма в ящик (без сдачи).'],
    ['Transfer slip from the driver.', 'Пересадочный талон у водителя.'],
    ['Valid for ninety minutes.', 'Действителен девяносто минут.'],
    ['Day pass covers trams too.', 'Дневной проездной включает трамваи.'],
    ['Children under seven ride free.', 'Дети до семи ездят бесплатно.'],
    ['Buggy space at the back door.', 'Место для колясок у задней двери.'],
    ['Priority boarding for seniors.', 'Приоритетная посадка для пожилых.'],
    ['Rear doors open on request.', 'Задние двери открываются по запросу.'],
    ['Driver watching mirrors closely.', 'Водитель внимательно следит в зеркала.'],
    ['Hold the rail while standing.', 'Держитесь за поручень стоя.'],
    ['Braking hard, brace yourself.', 'Резко тормозит, держитесь.'],
    ['Potholes jolt everyone awake.', 'Ямы встряхивают всех пассажиров.'],
    ['Speed bumps ahead in the village.', 'Впереди лежачие полицейские в деревне.'],
    ['Hitchhikers rarely picked up now.', 'Автостопщиков сейчас редко подбирают.'],
    ['Carpool lane needs three people.', 'Полоса карпула требует трёх человек.'],
    ['Rideshare pickup zone painted green.', 'Зону такси выделили зелёным.'],
    ['Surge pricing tripled fares tonight.', 'Динамический тариф сегодня поднял цены втрое.'],
    ['Wait ten minutes, prices drop.', 'Подождите десять минут — цены упадут.'],
    ['Shared ride adds twenty minutes.', 'Попутная поездка добавит двадцать минут.'],
    ['Private hire costs double.', 'Индивидуальное такси стоит вдвое дороже.'],
    ['Airport flat rate negotiated.', 'Договорились о фиксе за поездку в аэропорт.'],
    ['Return trip booked same driver.', 'Обратную поездку забронировали у того же водителя.'],
    ['Lost item hotline called.', 'Позвонил на горячую линию по находкам.'],
    ['Driver found my scarf under seat.', 'Водитель нашёл мой шарф под сиденьем.'],
    ['Couriered wallet next morning.', 'Кошелёк доставили курьером утром.'],
    ['Five stars for honesty!', 'Пять звёзд за честность!'],
    ['Tip doubled for kindness.', 'Чаевые удвоил за доброту.'],
    ['Route through park scenic.', 'Дорога через парк живописна.'],
    ['Shortcut saves five minutes.', 'Короткий путь экономит пять минут.'],
    ['Long way round but calm traffic.', 'Крюк, зато спокойный трафик.'],
    ['Toll booth queue crawling.', 'Очередь на пункте оплаты ползёт.'],
    ['Express toll lane empty.', 'Экспресс-полоса оплаты пустая.'],
    ['Cash lane slower than card.', 'Наличная полоса медленнее карточной.'],
    ['Change machine out of order.', 'Автомат сдачи не работает.'],
    ['Receipt emailed within hour.', 'Чек пришлют в течение часа.'],
  ],
};
