// Engineer & Mechanic final fill (+~140).
export const topups = {
  motorsportengineermechanic: [
    ['Aero rakes map flow fields in dedicated sensor array sessions.', 'Аэро-грабли картографируют потоки в специальных сессиях!'],
    ['Pressure tap tubing routes hundreds of channels into multiplexed scanner banks.', 'Сотни трубок датчиков давления идут в мультиплексоры!'],
    ['Bib nose assemblies swap quick change aero configurations between runs.', 'Носовые секции меняют между заездами ради конфигураций!'],
    ['Ride height plates check reference plane datum measurement consistency.', 'Опорную плоскость клиренса сверяют каждый раз!'],
    ['Starter trolley cart batteries charge jump ready for the grid.', 'Пусковая тележка заряжена для старта с поля!'],
    ['Fuel cell bladder inspections certify internal baffle integrity periodically.', 'Бак с перегородками сертифицируют периодически!'],
    ['Fire bottle pressure gauges get annual weight checks with certified tags.', 'Огнетушители обслуживают и вешают бирки ежегодно!'],
    ['Helmet FIA 8860 homologation stickers verify at scrutineering.', 'Шлем последнего стандарта FIA проверяют на техконтроле!'],
    ['HANS anchors measure shoulder harness routing angles to spec.', 'Углы крепления Ханса вымерены по спецификации!'],
    ['Roll hoop padding replaces compressed impact foam beyond limits.', 'Смятые подушки каркаса заменяют на новые!'],
    ['Convex wide angle mirror glass eliminates blind spots through adjustments.', 'Выпуклые зеркала убирают слепые точки регулировками!'],
    ['Rain light LED rear fog intensity tests against visibility regulations.', 'Дождевой фонарь проверяют на соответствие видимости!'],
    ['Wheel tethers tensile test cables replacing frayed ones preventively.', 'Изношенные тросы колёс меняют превентивно!'],
    ['Upright crack detection magnafluxes critical suspension pick-ups with penetrant inspections.', 'Критичные узлы подвески проверяют магнитопорошковым методом!'],
    ['Pushrod lengths adjust turnbuckles with locknuts secured and alignment set.', 'Штоки регулируются стяжками, контрги зафиксированы!'],
    ['Caster shim stacks document trial error iterations in logged geometry changes.', 'Прокладки кастера: итерации задокументированы!'],
    ['Steering rack quickening reduces turns lock-to-lock trading away feedback.', 'Быстрый рулевой редуктор: меньше оборотов, меньше обратной связи!'],
    ['Power steering pump relief valves tune driver feel settings.', 'Клапан ГУР настраивают под «чувство» пилота!'],
    ['Electric power steering maps program speed sensitive variable assistance.', 'EPS-карты меняют помощь от скорости программно!'],
    ['Brake disc thickness micrometer measurements enforce minimum wear limits strictly.', 'Толщину диска меряют микрометром — лимит строго!'],
    ['Pad wear indicator acoustic sensors send wireless telemetry alerts to the pit wall.', 'Беспроводные датчики колодок сигналят на стену!'],
    ['AN fitting dash number charts avoid fluid line size confusion.', 'Таблицы размеров AN-фитингов спасают от путаницы!'],
    ['Line bending tools prevent kinks keeping smooth radii for flow.', 'Трубки гнут с плавными радиусами без заломов!'],
    ['Flaring tools choose double or bubble types specific to brake fuel lines.', 'Разновидности развальцовок: двойная для тормозов, пузырьковая для топлива!'],
    ['Leak down hunts bubbles with soapy water spray.', 'Мыльная пена выдаёт утечки пузырями!'],
    ['Vacuum leak smoke machines diagnose intake tracts hunting post-throttle idle issues.', 'Дым-машина ищет подсос воздуха за дросселем!'],
    ['Compression test gauges log cylinder variance percentages as trends.', 'Компрессию логируют, разброс по цилиндрам трендят!'],
    ['Leak-down testers differentiate valve ring head gasket losses by cylinder percentage.', 'Тест на утечки различает клапаны, кольца и прокладку!'],
    ['Camshaft lobe wear flags deviations against new spec profile gauges.', 'Износ кулачков сравнивают с эталонным профилем!'],
    ['Valve guide wear measures stem play wobble by dial indicator replacing exceeded ones.', 'Люфт стеммов клапанов замеряли — превышение, замена!'],
    ['Seat recession depth alters valve closing geometry until heads machine resurfaced.', 'Просадку сёдел фрезеруют обратно в геометрию!'],
    ['Head resurfacing mill cuts thousandths specifying surface finish RA for gasket seal.', 'Фрезеровка головы выдерживает шероховатость под прокладку!'],
    ['Block decking squares bores honing under torque plate simulation preventing distortion.', 'Гильзовка и хонинг под пластиной имитируют сборку!'],
    ['Piston-to-wall clearance calculates alloy specific expansion rates measured by feeler gauges.', 'Зазор поршень-стенка считают по расширению сплава!'],
    ['Ring end gaps file fit staggered orientations minimising blow-by on assembly.', 'Замки колец разведены по кругу — минимум прорыва газов!'],
    ['Wrist pin circlips position gaps away from cutouts by practice.', 'Стопорные кольца ставят замками от выборок!'],
    ['Rod bolt stretch gauges discard yielded fasteners — singles never reused.', 'Болты шатунов одноразовые: вытяжку меряем, повторно не ставим!'],
    ['Big end bore ovality restores crank journals through microfinishing polish.', 'Овальность постели правится полировкой шеек!'],
    ['Crank grinding machines undersize bearings matched oversize sets saving race weekends.', 'Шейки шлифуют в ремонтный размер — спасает гоночный уик-энд!'],
    ['Balancing machines match pistons rods bobweights obsessively to gram fractions.', 'Балансировочный станок сводит узлы с точностью до долей грамма!'],
    ['Zero balancing counterweights cancel harmonics rewarding smoothness at high rpm.', 'Противовесы гасят гармонику — плавность на высоких оборотах!'],
    ['Extended sump oil pans relocate pickups engineering away cornering starvation.', 'Углублённый поддон с переносом заборника решил голодание в поворотах!'],
    ['Accusump pre-oilers protect turbo bearings through startup shutdown rituals.', 'Аккумулятор масла защищает турбину при старте и остановке!'],
    ['Turbo timer cooldown cycles prevent bearing coking for disciplined drivers.', 'Дисциплинированные водители гоняют турботаймер против закоксовки!'],
    ['Boost controllers compare manual ball spring against electronic solenoid duty cycle precision.', 'Механический и электронный буст-контроллер: точность соленоида!'],
    ['Inertia versus load-bearing dynos spark calibration wars over differing numbers.', 'Споры инерционных и нагрузочных дино-стендов не утихают!'],
    ['SAE DIN correction factors standardise weather for fair published comparisons.', 'Поправки SAE/DIN делают цифры сравнимыми честно!'],
    ['Dyno queen garage queens trailer to shows polished never driven in tongue-in-cheek culture.', '«Гаражные королевы» — блестящие, но не езженные (шутка культуры)!'],
    ['Trickle chargers maintain batteries winterizing fleets ready for spring.', 'Трикл-чейджеры готовят зимующие машины к весне!'],
    ['Fuel stabilisers prevent tank condensation avoiding gummed carb jets across seasons.', 'Стабилизатор топлива спасает жиклёры от загустения зимой!'],
    ['Fogging oil coats cylinders internally as classic collection storage corrosion rituals.', 'Консервация цилиндров маслом — ритуал классических коллекций!'],
    ['Battery disconnect switches eliminate parasitic drain as garage insurance requires.', 'Отключатели массы обязательны по требованиям страховки!'],
    ['Tyre cradles prevent flat spotting rotating storage stacks periodically preserving shapes.', 'Кронштейны под шины сохраняют их форму на хранении!'],
    ['Breathable car covers debate cotton versus synthetics against trapped moisture mildew.', 'Дышащие чехлы против плесени: хлопок или синтетика — спорят!'],
    ['Detailing clay bars decontaminate paint before professional hydrophobic ceramic coatings apply.', 'Глина для деталей и керамика — профессиональный уход!'],
    ['Paint correction polishing compounds develop patient machine polisher swirl removal skills.', 'Полировка убирает голограммы — навык нарабатывается терпением!'],
    ['Paint depth gauge readings reveal respray histories informing buyers of clear coat margins.', 'Толщиномер краски раскрывает историю перекрасов покупателю!'],
    ['VIN chassis number matching determines collector values where authenticity is paramount.', 'Совпадение VIN определяет ценность коллекционной машины!'],
    ['Heritage certificates authenticate provenance through manufacturer archive build sheets earning premiums.', 'Архивные build sheets подтверждают происхождение и цену!'],
  ],
};
