// Final fills: Spectator +70, Engineer & Mechanic +200.
export const topups = {
  motorsportspectator: [
    ['Grandstand roofs shade prized afternoon sun positions.', 'Трибуны с крышей ценятся в жаркий полдень!'],
    ['Big screen sightlines get checked before booking seats confirmed.', 'Перед бронированием проверяют видимость большого экрана!'],
    ['Camera lenses poke through pit wall fence gaps with careful etiquette.', 'Объективы просовывают в сетку пит-уолла аккуратно!'],
    ['Radio scanner team frequencies get shared generously on forums.', 'Частоты команд для сканеров щедро делят на форумах!'],
    ['Team radio banter reveals personalities in unguarded moments fans love.', 'Радио-шутки команд раскрывают характеры — фанаты обожают!'],
    ['Engineer voices gained recognition and cult followings like celebrities.', 'Голоса инженеров стали культовыми!'],
    ['Armchair strategists second-guess strategy calls in raging online debates.', 'Диванные стратеги бесконечно спорят о вызовах команды!'],
    ['Tyre choice hindsight makes everyone a genius afterwards, jokes self-deprecating.', 'После гонки все гении: «я же говорил про резину!»'],
    ['Weather app radar screenshots share dramatic rain front countdowns.', 'Скрины радара дождя создают драму ожидания!'],
    ['Umbrella etiquette politely requests lowering when views block and glares exchange.', 'Зонты, закрывающие обзор, просят опустить взглядами!'],
    ['Poncho rustle forms a comedic quiet-moment soundtrack in drizzle races.', 'Шорох дождевиков — комичный саундтрек гонки под моросью!'],
    ['Sun cream sharing between strangers shows warm community spirit.', 'Незнакомец делится кремом от солнца — дух сообщества!'],
    ['Water misting fan tents queue blissful relief from heat.', 'Водяные завесы от жары — блаженные очереди облегчения!'],
    ['Free earplug dispensers thank grateful parents of toddler-sensitive ears.', 'Родителям малышей бесплатно выдают беруши — спасение!'],
    ['Stroller friendly routes map ramps and elevators in praised accessibility apps.', 'Маршруты для колясок в приложениях хвалят!'],
    ['Nursing rooms provide mothers infants thoughtful privacy at modern venues.', 'Комнаты матери и ребёнка продуманы современно!'],
    ['Prayer reflection spaces acknowledge multifaith diversity gracefully.', 'Тихие комнаты разных конфессий — уважение к разнообразию!'],
    ['Lost property reunions share miracle stories from relieved owners.', 'Истории возврата паспортов и кошельков — чудеса бюро находок!'],
    ['Multilingual lost children announcements calm panicking parents with reassuring procedures.', 'Многоязычные объявления о потерявшихся детях успокаивают родителей!'],
    ['Meeting point landmarks anchor confused crowds navigating statues and gates.', 'Статуи и ворота — навигационные якоря для толпы!'],
    ['Phone charging station queues play scrolling feed waiting games.', 'Очереди к зарядкам скрашиваются лентой соцсетей!'],
    ['Power bank sharing trades favours with strangers whose batteries die.', 'Пауэрбанк по-соседски: выручают умирающие батареи!'],
    ['Cashless wristband top-ups avoid lunchtime rushes through morning strategies shared as tips.', 'Браслеты пополняют утром, избегая обеденной давки!'],
    ['Receipt tracking totals shock weekend budgets with humorous groans.', 'Итоги трат уик-энда — смешные стоны над чеками!'],
    ['Group cost-splitting apps divide expenses, jokingly resolved by rock-paper-scissors.', 'Расходы делят приложениями, споры — камень-ножницы-бумага!'],
    ['Designated meeting times execute smoothly as battery dead contingencies.', 'План «если телефон сдох» сработал безупречно!'],
    ['Photo tag requests ask consent respectfully as privacy norms shift generationally.', 'Спрашивают разрешение перед публикацией фото — нормы меняются!'],
    ['Drone shows introduce choreographed light pattern finales into night skies.', 'Дрон-шоу светящимися паттернами завершают вечера!'],
    ['Firework regulations negotiate celebration traditions against noise complaints through councils.', 'Салюты согласовывают с жителями через советы!'],
    ['Public holidays align race dates extending city party weekends.', 'Гонки на праздники — город гуляет дольше!'],
    ['Economic boosts fill hotels restaurants bars with measurable local business gratitude.', 'Локальный бизнес благодарит гоночные уик-энды кассой!'],
    ['Volunteer appreciation events hold ceremonies recognising community service hours.', 'Церемонии благодарят волонтёров за часы службы!'],
    ['Marshalling careers started from spectator curiosity discovering training pathways.', 'Карьера маршала началась с любопытства трибун!'],
    ['Officials recruitment drives answered shortage appeals when community stepped up admirably.', 'Призыв волонтёров — сообщество откликнулось восхитительно!'],
    ['Motorsport museum volunteer guides keep history alive with retired mechanic stories firsthand.', 'Отставные механики водят экскурсии — история жива!'],
    ['Archive photo exhibitions journey poignantly through then-now decade transformations.', 'Фото-экспозиции «тогда/сейчас» — пронзительная ностальгия!'],
    ['Time capsule burials seal anniversary messages of hope for future generations.', 'Капсулы времени к юбилеям: послания будущим поколениям!'],
    ['Anniversary legends reunions recreate podium photographs in emotional full-circle moments.', 'Воссоздание легендарных подиумов — эмоции замкнули круг!'],
    ['Championship winning car displays draw town square selfie crowds smiling permanently.', 'Чемпионский болид на площади — селфи и улыбки без конца!'],
    ['Open garage sessions fund charity fundraisers with behind scenes workshop tours.', 'Благотворительные открытые гаражи — доступ за донат!'],
    ['School visits fuel dreams as drivers give inspirational talks to wide-eyed children.', 'Визиты пилотов в школы зажигают детские мечты!'],
    ['Hospital visits bring helmeted superheroes gifts and healing smiles to children wards.', 'Гонщики в детских больницах — супергерои со шлемами!'],
    ['Community karting events collectively fund racing dreams for disadvantaged youth scholarships.', 'Сообщество оплачивает картинг талантливым ребятам из малообеспеченных семей!'],
    ['Diversity inclusion programmes make women engineers racers visible role models.', 'Женщины в паддоке как ролевые модели — видимость важна!'],
    ['LGBTQ inclusive fan groups celebrate pride flags making circuits welcoming safe spaces.', 'Флаги гордости на трибунах — инклюзивный прогресс!'],
    ['Plastic-free zones and green transport discounts introduced.', 'Появились безпластиковые зоны и скидки за эко-транспорт!'],
    ['Environmental responsibility is now openly celebrated.', 'Экологическая ответственность теперь открыто поощряется!'],
    ['Carbon offset programs calculate travel emissions with published transparency reports.', 'Компенсация углеродного следа поездок — отчёты открыты!'],
    ['Solar panels power circuit rooftops advertising sustainability leadership proudly.', 'Солнечные панели питают трассу — лидерство в устойчивости!'],
    ['Electric vehicle test drives convert curious petrolheads through silent torque.', 'Тест-драйвы электрокаров обращают бензофилов в любопытство!'],
    ['Future generations inherit a sport evolved greener safer faster, stewarded responsibly.', 'Будущие поколения получат спорт зеленее, безопаснее, быстрее!'],
  ],

  motorsportengineermechanic: [
    ['Telemetry overlay comparisons colour code laps showing driver differences instantly.', 'Цветные наложения кругов показывают разницу пилотов мгновенно!'],
    ['Brake pressure traces quantify modulation styles smooth versus aggressive.', 'Модуляцию тормозов квантифицируют: плавную против агрессивной!'],
    ['Throttle application gradients analyse corner exit phases correlated with traction.', 'Профили газа на выходе сверяют с тракцией!'],
    ['Steering angle traces measure counter-steer corrections to degree fractions.', 'Углы контрруления меряют с точностью до долей градуса!'],
    ['Gear shift points optimise engine torque band exploitation maximised.', 'Точки переключений выжали максимум из полки момента!'],
    ['Shift durations cut milliseconds seamlessly — invisible to spectators, felt by drivers.', 'Переключение за миллисекунды: зрители не видят, пилоты чувствуют!'],
    ['Launch strategy calibrates wheelspin targets against clutch temperature conditions.', 'Стартовые карты калибруют под температуру сцепления!'],
    ['Clutch temp data proactively avoids overheated launches preventing failures.', 'Данные температуры сцепления предотвращают прогар проактивно!'],
    ['Turbo lag minimises through anti-lag strategies managing combustion instability tradeoffs.', 'Антилаг убирает турбояму ценой нестабильности горения!'],
    ['Wastegate duty cycles map boost curves altitude corrected automatically.', 'Кривые буста автоматически корректируются по высоте!'],
    ['Lambda sensors close the loop on air-fuel ratios across narrowband wideband hybrids.', 'Лямбда-зонды держат смесь в замкнутом контуре!'],
    ['Combustion phasing monitors stability cycle by cycle inside knock window margins.', 'Стабильность горения мониторится цикл за циклом!'],
    ['Cylinder deactivation strategies experiment with fuel economy in endurance cruising modes.', 'Отключение цилиндров экономит топливо в эндурансе!'],
    ['Thermal imaging revealed header design flaws through uneven exhaust distribution.', 'Тепловизор вскрыл неравномерность коллектора!'],
    ['Coolant flow simulations analyse cavitation risks across water pump speeds.', 'Симуляции потока охлаждения нашли кавитацию помпы!'],
    ['Pressure caps adjust boil-over margins with elevation atmospheric corrections.', 'Давление крышки радиатора скорректировали под высоту!'],
    ['Oil starvation gets engineered away with pickup baffling against sustained corner sloshing.', 'Маслозаборник с перегородками не голодает в затяжных поворотах!'],
    ['Dry sump multi-stage scavenging pumps handle vertical g-forces.', 'Сухой каркас с многоступенчатой откачкой держит вертикальные перегрузки!'],
    ['Accumulators pre-charge air buffers against oil pressure dips at corner exits.', 'Аккумулятор давления страхует провалы масла на выходе!'],
    ['Magnetic filter plugs shorten inspection intervals when wear is suspected.', 'Магнитные пробки сокращают интервалы при подозрении на износ!'],
    ['Spectrometric oil analysis schedules trend wear metals for early warnings.', 'Спектрометрия масла предупреждает об износе заранее!'],
    ['Filter clogging monitors differential pressures flagging bypass valve opening.', 'Забитый фильтр видно по перепаду давления до открытия байпаса!'],
    ['Breather systems regulate crankcase vacuum optimising ring seal efficiency.', 'Вакуум в картере оптимизирует кольцевое уплотнение!'],
    ['Windage losses minimise shaping pans against crankshaft oil bath drag.', 'Форма поддона минимизирует потери маховика о масло!'],
    ['Crankcase evacuation vacuum pumps balance horsepower gains against parasitic losses.', 'Вакуумный насос картера балансирует мощность и паразитные потери!'],
    ['Harmonic balancers protect crankshaft resonance critically at high rpm.', 'Демпфер коленвала защищает от резонанса на высоких оборотах!'],
    ['Flywheel lightening trades rotational inertia throttle response gains against stall risk.', 'Облегчённый маховик: отклик плюс, риск глохнущего старта минус!'],
    ['Balancing rotating assemblies smooths blueprinted engine harmonics with precision tolerances.', 'Балансировка узлов сглаживает гармонику собранного мотора!'],
    ['Blueprinting matches hand-selected component sets tighter than production tolerances.', 'Блюпринтинг: компоненты подобраны точнее заводских допусков!'],
    ['Port matching smooths manifold head transitions minimising turbulence.', 'Совмещение каналов впуска и ГБЦ убирает турбулентность!'],
    ['Three-angle valve seat cuts documented flow bench improvement percentages.', 'Трёхугольная обработка сёдел подтверждена на проточном стенде цифрами!'],
    ['Cam timing dials degree wheels setting precise phase relationships at zero lash.', 'Фазы распредвала выставлены по градусному колесу точно!'],
    ['Rocker arm ratios verify achieved lift with dial indicators.', 'Передаточное число рокеров проверено индикатором!'],
    ['Spring pressures check coil bind safety margins measuring installed heights.', 'Проверили пружины клапанов: зазор до витков замерен!'],
    ['Titanium retainers reduce reciprocating mass raising rev ceilings safely.', 'Титановые тарелки подняли безопасные обороты!'],
    ['Valve train harmonics discovered flutter onset rpm limits through destructive sacrifice testing.', 'Флаттер клапанов нашли разрушительными тестами жертвы!'],
    ['Head gaskets specify MLS torque sequences in staged tightening.', 'MLS-прокладка затягивается ступенчатым моментом по схеме!'],
    ['Deck surface flatness verifies straightedge feeler gauges ruling out warping.', 'Плоскость блока повернули линейкой и щупами!'],
    ['Helicoil thread inserts repair stripped holes stronger than original.', 'Helicoil чинит сорванную резьбу прочнее завода!'],
    ['Torque-to-yield bolts are single use with mandatory stretch measured replacement.', 'Болты ТТУ одноразовые: вытяжка измерена, замена обязательна!'],
    ['Fastener lubrication changes friction coefficients so dry oiled specs differ.', 'Смазка крепежа меняет моменты затяжки — читай спецификацию!'],
    ['Wire loom crossings route twisted shielded pairs away from ignition interference.', 'Жгуты дальше зажигания: витые пары против наводок!'],
    ['Star grounding topology eliminated hum silencing electrical noise loops.', 'Звезда заземления убрала фон электросети!'],
    ['CAN termination resistors stabilised the bus preserving message integrity.', 'Терминаторы CAN стабилизировали шину и целостность сообщений!'],
    ['Firmware rollback procedures recover bricked units through bootloader rescue modes.', 'Окирпиченные блоки спасли через режим бутлоадера!'],
    ['Version control changelogs audit parameter diffs hunting regressions systematically.', 'Версионирование параметров помогает ловить регрессии системно!'],
    ['Simulator correlation rigs blend subjective motion cueing tuning with objectivity.', 'Настройка моушн-куинга: субъективные ощущения плюс объективность!'],
    ['Seven-post rigs map pitch heave frequency response simulating aerodynamic loads.', 'Семиштоковый стенд имитирует аэродинамику частотным откликом!'],
    ['Tyre model fitting curve fits Pacejka magic formula coefficients to measured data.', 'Коэффициенты «магической формулы» Пачейки сняли с данных!'],
    ['Slip curve validation runs flat plank testers at controlled surface speeds.', 'Кривые скольжения валидировали плоскими стендами!'],
    ['Thermal models predict tyre compound behaviour improving lap one accuracy.', 'Термомодель предсказывает поведение резины уже на первом круге!'],
    ['Pressure build predictions grow confidence iterating ambient track temperature inputs.', 'Прогноз роста давления уточнялся с каждой итерацией!'],
    ['Machine learning mines setup optimisation datasets for emerging insights.', 'Машинное обучение майнит инсайты из датасетов сетапов!'],
    ['Neural networks generate suspension suggestions human engineers validate sceptically.', 'Нейросети советуют настройки — инженеры проверяют скептично!'],
    ['Digital twins mirror physical fleets fed continuously by telemetry.', 'Цифровые двойники машин питаются телеметрией непрерывно!'],
    ['Predictive maintenance algorithms forecast failures replacing parts preemptively.', 'Предиктивное обслуживание меняет детали до отказа!'],
    ['JIT supply chains balance delivery risks against buffer stock costs.', 'JIT-поставки балансируют риски и складские затраты!'],
    ['Custom fabrication plans around carbon cure cycle schedule constraints.', 'График ремонта карбона строится вокруг циклов автоклава!'],
    ['Quality assurance sign-offs log every component serial number lifetime traceability.', 'Каждая деталь прослеживается по серийнику всю жизнь!'],
    ['Recall campaigns prioritise fleet safety scheduling rectifications after fault clusters identified.', 'Отзывные кампании приоритизируют безопасность парка машин!'],
    ['Internal engineering wikis document tribal wisdom turnover-proof.', 'Внутренняя вики сохраняет племенную мудрость инженеров!'],
    ['Apprenticeship programmes mentor junior wrenchers passing craft generations hands-on.', 'Подмастерья перенимают ремесло у мастеров — ремесло живёт!'],
    ['Quality tool investments justify budgets through calibration certified reliability.', 'Хороший инструмент с сертификатами оправдан надёжностью!'],
    ['Workshop organisation adopts Japanese 5S shadow board efficiency.', '5S из Японии: чистота и порядок цеха!'],
    ['Workstation ergonomics prevents repetitive strain injuries through posture awareness.', 'Эргономика рабочих мест бережёт спины в долгие ночи!'],
    ['Night shift circadian lighting tunes brightness maintaining alertness considerately.', 'Циркадный свет ночным сменам держит бодрость бережно!'],
    ['Late crew catering fuels well minimising fatigue mistakes.', 'Сытые ночные смены ошибаются реже — кормите людей!'],
    ['Psychological safety flattens hierarchy so junior voices catch valuable issues.', 'Джун может остановить выпуск — его голос слышат!'],
  ],
};
