// Final fills: Spectator +70, Engineer & Mechanic +200.
export const topups = {
  motorsportspectator: [
    ['Grandstand roofs shade afternoon sun positions prized.', 'Трибуны с крышей ценятся в жаркий полдень!'],
    ['Big screen sightlines checked before booking seats confirmed.', 'Перед бронированием проверяют видимость большого экрана!'],
    ['Pit wall fence gaps camera lenses poked through carefully etiquette.', 'Объективы просовывают в сетку пит-уолла аккуратно!'],
    ['Radio scanners programmed frequencies teams listed forums shared generously.', 'Частоты команд для сканеров щедро делят на форумах!'],
    ['Team radio banter personalities revealed unguarded moments beloved fans.', 'Радио-шутки команд раскрывают характеры — фанаты обожают!'],
    ['Engineer voices recognised celebrity status cult followings developed.', 'Голоса инженеров стали культовыми!'],
    ['Strategy calls second-guessed armchair strategists debates raging online.', 'Диванные стратеги бесконечно спорят о вызовах команды!'],
    ['Tyre choice hindsight wisdom everyone genius afterwards jokes self-deprecating.', 'После гонки все гении: «я же говорил про резину!»'],
    ['Weather app radar screenshots shared countdown rain front arrivals dramatic.', 'Скрины радара дождя создают драму ожидания!'],
    ['Umbrella etiquette blocking views lowered politely requested glares exchanged.', 'Зонты, закрывающие обзор, просят опустить взглядами!'],
    [' poncho rustle symphony quiet moments comedic soundtrack races drizzle.', 'Шорох дождевиков — комичный саундтрек гонки под моросью!'],
    ['Sun cream sharing strangers kindness community spirit moments warm.', 'Незнакомец делится кремом от солнца — дух сообщества!'],
    ['Water misting fans tent cooling stations queues blissful relief queues.', 'Водяные завесы от жары — блаженные очереди облегчения!'],
    ['Free earplug dispensers families grateful parents especially toddlers sensitive ears.', 'Родителям малышей бесплатно выдают беруши — спасение!'],
    ['Stroller friendly routes ramps elevators mapped apps accessibility features praised.', 'Маршруты для колясок в приложениях хвалят!'],
    ['Nursing rooms privacy mothers infants facilities modern venues provided thoughtfully.', 'Комнаты матери и ребёнка продуманы современно!'],
    ['Prayer reflection quiet spaces multifaith respect diversity acknowledged gracefully.', 'Тихие комнаты разных конфессий — уважение к разнообразию!'],
    ['Lost property reunions wallets passports phones miracle stories shared relieved owners.', 'Истории возврата паспортов и кошельков — чудеса бюро находок!'],
    ['Announcement systems multilingual lost children calm procedures reassuring parents panicking.', 'Многоязычные объявления о потерявшихся детях успокаивают родителей!'],
    ['Meeting point landmarks statues gates designated confused crowds navigational anchors.', 'Статуи и ворота — навигационные якоря для толпы!'],
    ['Phone charging stations queues entertainment scrolling feeds waiting games played.', 'Очереди к зарядкам скрашиваются лентой соцсетей!'],
    ['Power bank sharing kindness strangers batteries dying emergencies traded favors.', 'Пауэрбанк по-соседски: выручают умирающие батареи!'],
    ['Cashless wristband top-ups lunchtime rush avoided morning strategies shared tips.', 'Браслеты пополняют утром, избегая обеденной давки!'],
    ['Receipt tracking spending budgets weekend totals shock realisations humorous groans.', 'Итоги трат уик-энда — смешные стоны над чеками!'],
    ['Group cost-splitting apps expenses divided fairness arguments jokingly resolved rock-paper-scissors.', 'Расходы делят приложениями, споры — камень-ножницы-бумага!'],
    ['Designated meeting times battery dead scenarios planned contingencies executed smoothly.', 'План «если телефон сдох» сработал безупречно!'],
    ['Photo tag requests consent asked respectfully privacy boundaries respected generationally shifting norms.', 'Спрашивают разрешение перед публикацией фото — нормы меняются!'],
    ['Drone shows night sky displays choreographed light patterns spectacular finales introduced.', 'Дрон-шоу светящимися паттернами завершают вечера!'],
    ['Firework regulations noise complaints balanced celebration traditions negotiated councils.', 'Салюты согласовывают с жителями через советы!'],
    ['Public holidays race dates aligned celebrations extended cities party weekends.', 'Гонки на праздники — город гуляет дольше!'],
    ['Economic boost hotels restaurants bars full weekends measurable gratitude local businesses.', 'Локальный бизнес благодарит гоночные уик-энды кассой!'],
    ['Volunteer appreciation events certificates community service hours recognised ceremonies held.', 'Церемонии благодарят волонтёров за часы службы!'],
    ['Marshalling careers started spectator curiosity training pathways discovered life changes directions.', 'Карьера маршала началась с любопытства трибун!'],
    ['Officials recruitment drives shortage appeals responded community stepped up admirable.', 'Призыв волонтёров — сообщество откликнулось восхитительно!'],
    ['Motorsport museum volunteer guides retired mechanics stories firsthand history alive.', 'Отставные механики водят экскурсии — история жива!'],
    ['Archive photo exhibitions decades comparisons then-now transformations poignant nostalgic journeys.', 'Фото-экспозиции «тогда/сейчас» — пронзительная ностальгия!'],
    ['Time capsule burials anniversary celebrations future generations messages sealed hopes.', 'Капсулы времени к юбилеям: послания будущим поколениям!'],
    ['Anniversary legends reunions podium recreations photographs emotional full-circle moments tears.', 'Воссоздание легендарных подиумов — эмоции замкнули круг!'],
    ['Championship winning car display town square crowds selfies permanent smile memories.', 'Чемпионский болид на площади — селфи и улыбки без конца!'],
    ['Open garage sessions charity fundraisers donations workshops tours behind scenes access.', 'Благотворительные открытые гаражи — доступ за донат!'],
    ['School visits drivers inspirational talks dreams fuelled ambitions sparked children eyes wide.', 'Визиты пилотов в школы зажигают детские мечты!'],
    ['Hospital visits children wards superheroes helmets gifts smiles healing moments powerful.', 'Гонщики в детских больницах — супергерои со шлемами!'],
    ['Community karting events scholarships disadvantaged youth opportunities racing dreams funded collectively.', 'Сообщество оплачивает картинг талантливым ребятам из малообеспеченных семей!'],
    ['Diversity inclusion programmes women engineers racers representation role models visibility matters.', 'Женщины в паддоке как ролевые модели — видимость важна!'],
    ['LGBTQ inclusive fan groups safe spaces pride flags circuits welcoming progress celebrated.', 'Флаги гордости на трибунах — инклюзивный прогресс!'],
['Plastic-free zones and green transport discounts introduced.', 'Появились безпластиковые зоны и скидки за эко-транспорт!'],
    ['Environmental responsibility is now openly celebrated.', 'Экологическая ответственность теперь открыто поощряется!'],
    ['Carbon offset programs travel emissions calculated contributions optional encouraged transparency reports published.', 'Компенсация углеродного следа поездок — отчёты открыты!'],
    ['Solar panels circuit rooftops renewable energy powering facilities proudly advertised sustainability leadership.', 'Солнечные панели питают трассу — лидерство в устойчивости!'],
    ['Electric vehicle test drives sponsor activations silent torque conversions converting petrolheads curious.', 'Тест-драйвы электрокаров обращают бензофилов в любопытство!'],
    ['Future generations inherit sport evolved greener safer faster legacies stewarded responsibly.', 'Будущие поколения получат спорт зеленее, безопаснее, быстрее!'],
  ],

  motorsportengineermechanic: [
    ['Telemetry overlay comparison laps colour coded driver differences visible instantly.', 'Цветные наложения кругов показывают разницу пилотов мгновенно!'],
    ['Brake pressure traces modulation style smooth versus aggressive quantified.', 'Модуляцию тормозов квантифицируют: плавную против агрессивной!'],
    ['Throttle application gradients corner exit phases analysed traction correlated.', 'Профили газа на выходе сверяют с тракцией!'],
    ['Steering angle traces counter-steer corrections measured degrees fractions.', 'Углы контрруления меряют с точностью до долей градуса!'],
    ['Gear shift points optimised engine torque band exploitation maximised.', 'Точки переключений выжали максимум из полки момента!'],
    ['Shift duration milliseconds seamless torque cuts invisible spectators felt drivers.', 'Переключение за миллисекунды: зрители не видят, пилоты чувствуют!'],
    ['Launch strategy wheelspin targets clutch temperature management calibrated conditions.', 'Стартовые карты калибруют под температуру сцепления!'],
    ['Clutch temp data overheating launches avoided failures prevented proactive.', 'Данные температуры сцепления предотвращают прогар проактивно!'],
    ['Turbo lag minimised anti-lag strategies combustion instability tradeoffs managed.', 'Антилаг убирает турбояму ценой нестабильности горения!'],
    ['Wastegate duty cycles boost curves mapped altitude corrected automatically.', 'Кривые буста автоматически корректируются по высоте!'],
    ['Air-fuel ratios lambda sensors closed loop control narrowband wideband hybrid.', 'Лямбда-зонды держат смесь в замкнутом контуре!'],
    ['Combustion phasing knock window margins safety combustion stability monitored cycles.', 'Стабильность горения мониторится цикл за циклом!'],
    ['Cylinder deactivation strategies fuel economy cruising modes experimental endurance.', 'Отключение цилиндров экономит топливо в эндурансе!'],
    ['Thermal imaging exhaust headers distribution unevenness header design flaws revealed.', 'Тепловизор вскрыл неравномерность коллектора!'],
    ['Coolant flow simulations cavitation risks water pump speeds analysed.', 'Симуляции потока охлаждения нашли кавитацию помпы!'],
    ['Pressure caps boil-over margins elevation adjusted atmospheric corrections.', 'Давление крышки радиатора скорректировали под высоту!'],
    ['Oil starvation pickup baffling sloshing sustained corners engineered solutions.', 'Маслозаборник с перегородками не голодает в затяжных поворотах!'],
    ['Dry sump scavenging stages multi-stage pumps vertical g-forces handled.', 'Сухой каркас с многоступенчатой откачкой держит вертикальные перегрузки!'],
    ['Accumulator pre-charged air buffer oil pressure dips corner exits.', 'Аккумулятор давления страхует провалы масла на выходе!'],
    ['Filter magnet plugs ferrous debris inspection intervals shortened wear suspected.', 'Магнитные пробки сокращают интервалы при подозрении на износ!'],
    ['Spectrometric oil analysis scheduled trending wear metals early warnings.', 'Спектрометрия масла предупреждает об износе заранее!'],
    ['Filter clogging differential pressures monitored bypass valve opening flagged.', 'Забитый фильтр видно по перепаду давления до открытия байпаса!'],
    ['Breather systems crankcase vacuum regulation ring seal efficiency optimised.', 'Вакуум в картере оптимизирует кольцевое уплотнение!'],
    ['Windage losses crankshaft counterweights oil bath drag minimised shaping pans.', 'Форма поддона минимизирует потери маховика о масло!'],
    ['Crankcase evacuation vacuum pumps horsepower gains parasitic losses balanced.', 'Вакуумный насос картера балансирует мощность и паразитные потери!'],
    ['Harmonic balancer torsional vibration dampener crankshaft resonance protection critical high rpm.', 'Демпфер коленвала защищает от резонанса на высоких оборотах!'],
    ['Flywheel lightening rotational inertia reductions throttle response gains stall risk tradeoffs.', 'Облегчённый маховик: отклик плюс, риск глохнущего старта минус!'],
    ['Balancing rotating assemblies blueprinted engines harmonics smoothed tolerances precision.', 'Балансировка узлов сглаживает гармонику собранного мотора!'],
    ['Blueprinting specifications tighter than production tolerances hand-selected components matched sets.', 'Блюпринтинг: компоненты подобраны точнее заводских допусков!'],
    ['Port matching manifold heads airflow continuity transitions smooth turbulence minimised.', 'Совмещение каналов впуска и ГБЦ убирает турбулентность!'],
    ['Valve seat angles three-angle cuts flow benches validated improvements percentages documented.', 'Трёхугольная обработка сёдел подтверждена на проточном стенде цифрами!'],
    ['Cam timing degree wheel dialed zero lash precise phase relationships set.', 'Фазы распредвала выставлены по градусному колесу точно!'],
    ['Rocker arm ratios geometry leverage multiplication calculated lift achieved verified dial indicator.', 'Передаточное число рокеров проверено индикатором!'],
    ['Spring pressures coil bind margin safety checked installed heights measured.', 'Проверили пружины клапанов: зазор до витков замерен!'],
    ['Retainer titanium lightweight reciprocating mass reduced rev ceiling raised safely.', 'Титановые тарелки подняли безопасные обороты!'],
    ['Valve train harmonics flutter onset rpm limits discovered destructive testing sacrificed.', 'Флаттер клапанов нашли разрушительными тестами жертвы!'],
    ['Head gasket multi-layer steel MLS torque sequences specified stage tightening.', 'MLS-прокладка затягивается ступенчатым моментом по схеме!'],
    ['Deck surfaces flatness straightedge feeler gauges verified warping ruled out.', 'Плоскость блока повернули линейкой и щупами!'],
    ['Thread inserts helicoil stripped holes repaired stronger-than-original fixes common.', 'Helicoil чинит сорванную резьбу прочнее завода!'],
    ['Torque-to-yield bolts single use stretch measured replaced mandatory.', 'Болты ТТУ одноразовые: вытяжка измерена, замена обязательна!'],
    ['Fastener lubrication friction coefficients torque values affected dry oiled spec differences.', 'Смазка крепежа меняет моменты затяжки — читай спецификацию!'],
    ['Wire loom crossings electromagnetic interference twisted shielded routed away ignition.', 'Жгуты дальше зажигания: витые пары против наводок!'],
    ['Ground loops hum elimination star grounding topology implemented electrical noise silenced.', 'Звезда заземления убрала фон электросети!'],
    ['CAN termination resistors bus stability reflections eliminated message integrity preserved.', 'Терминаторы CAN стабилизировали шину и целостность сообщений!'],
    ['Firmware rollback procedures bricked units recovered bootloader rescue modes.', 'Окирпиченные блоки спасли через режим бутлоадера!'],
    ['Version control changelogs parameter diffs audited regression hunting systematic.', 'Версионирование параметров помогает ловить регрессии системно!'],
    ['Simulator correlation rigs actuator fidelity motion cueing tuning subjective objectivity blended.', 'Настройка моушн-куинга: субъективные ощущения плюс объективность!'],
    ['Seven-post rig aerodynamic load simulation pitch heave frequency response mapped.', 'Семиштоковый стенд имитирует аэродинамику частотным откликом!'],
    ['Tyre model fitting Pacejka magic formula coefficients curve fitted measured data.', 'Коэффициенты «магической формулы» Пачейки сняли с данных!'],
    ['Slip curve validation flat plank testers controlled surface speeds.', 'Кривые скольжения валидировали плоскими стендами!'],
    ['Thermal model tyre heat cycles compound behaviour predicted lap one accuracy improved.', 'Термомодель предсказывает поведение резины уже на первом круге!'],
    ['Pressure build prediction ambient track temperature inputs confidence growing iterations.', 'Прогноз роста давления уточнялся с каждой итерацией!'],
    ['Machine learning pattern recognition setup optimisation datasets mined insights emerging.', 'Машинное обучение майнит инсайты из датасетов сетапов!'],
    ['Neural networks suspension tuning suggestions generated human engineers validated sceptically.', 'Нейросети советуют настройки — инженеры проверяют скептично!'],
    ['Digital twins virtual cars physical fleet mirrored telemetry fed continuously.', 'Цифровые двойники машин питаются телеметрией непрерывно!'],
    ['Predictive maintenance algorithms failure forecasting parts replaced preemptively downtime minimised.', 'Предиктивное обслуживание меняет детали до отказа!'],
    ['Supply chain JIT just-in-time delivery risks buffers stock levels balanced costs.', 'JIT-поставки балансируют риски и складские затраты!'],
    ['Custom fabrication lead times carbon parts cure cycles schedule constraints planned around.', 'График ремонта карбона строится вокруг циклов автоклава!'],
    ['Quality assurance sign-offs traceability serial numbers every component logged lifetime.', 'Каждая деталь прослеживается по серийнику всю жизнь!'],
    ['Recall campaigns fault clusters identified fleet-wide notifications rectifications scheduled prioritised safety.', 'Отзывные кампании приоритизируют безопасность парка машин!'],
    ['Knowledge base wiki internal engineering tribal wisdom documented turnover-proof.', 'Внутренняя вики сохраняет племенную мудрость инженеров!'],
    ['Apprenticeship programmes junior wrenchers mentored hands-on skills passed generations craft preserved.', 'Подмастерья перенимают ремесло у мастеров — ремесло живёт!'],
    ['Tool investments quality spanners torque instruments calibration certificates current budgets justified reliability.', 'Хороший инструмент с сертификатами оправдан надёжностью!'],
    ['Workshop organisation shadow boards cleanliness 5S methodologies adopted Japanese efficiency imported.', '5S из Японии: чистота и порядок цеха!'],
    ['Ergonomics workstation heights repetitive strain injuries prevention posture awareness long nights.', 'Эргономика рабочих мест бережёт спины в долгие ночи!'],
    ['Night shift circadian lighting brightness tuned alertness maintained health considered.', 'Циркадный свет ночным сменам держит бодрость бережно!'],
    ['Catering late crews nutrition fuelled mistakes fatigue errors minimised fed well.', 'Сытые ночные смены ошибаются реже — кормите людей!'],
    ['Psychological safety speaking up concerns hierarchy flattened junior voices heard valuable catches.', 'Джун может остановить выпуск — его голос слышат!'],
  ],
};
