// Curated real-speech phrases: taxi & bus, train & metro, lost items, phone calls.
export const travel2 = {
  taxibus: {
    file: 'dictionaries/phrasebook-transportationbustaxi.json',
    emoji: '🚌',
    description: 'Такси и автобус — заказ, маршрут, оплата, остановки',
    phrases: [
      ['Could you call me a taxi, please?', 'Вызовите мне такси, пожалуйста.'],
      ["I'd like to book a taxi for eight a.m.", 'Я хотел бы заказать такси на восемь утра.'],
      ['Taxi!', 'Такси!'],
      ['Where to?', 'Куда едем?'],
      ['To the railway station, please.', 'На железнодорожный вокзал, пожалуйста.'],
      ['Take me to this address, please.', 'Отвезите меня по этому адресу, пожалуйста.'],
      ['Could you take the highway?', 'Поедете по трассе?'],
      ['Please avoid the city center.', 'Пожалуйста, объезжайте центр города.'],
      ['How long will it take to get there?', 'Сколько времени займёт дорога?'],
      ['Is it far? I’m in a hurry.', 'Далеко? Я очень спешу.'],
      ['Could you drive a bit faster?', 'Могли бы вы ехать побыстрее?'],
      ['Could you slow down a little?', 'Не могли бы вы ехать помедленнее?'],
      ['Turn left here, please.', 'Здесь налево, пожалуйста.'],
      ['Stop here, please.', 'Остановитесь здесь, пожалуйста.'],
      ['Pull over here, please.', 'Прижмитесь здесь к обочине, пожалуйста.'],
      ['This is fine, thank you.', 'Здесь отлично, спасибо.'],
      ['You can drop me off at the corner.', 'Можете высадить меня на углу.'],
      ['Keep the change.', 'Сдачи не надо. / Оставьте сдачу себе.'],
      ['Here you go.', 'Вот, держите.'],
      ['Do you take cards?', 'Вы принимаете карты?'],
      ['Card, please.', 'Картой, пожалуйста.'],
      ['Can I get a receipt?', 'Можно квитанцию?'],
      ['Where does this bus go?', 'Куда идёт этот автобус?'],
      ['Does this bus go downtown?', 'Этот автобус идёт в центр?'],
      ['Which bus goes to the museum?', 'Какой автобус идёт к музею?'],
      ['Am I on the right bus?', 'Я в том автобусе?'],
      ['Where is the nearest bus stop?', 'Где ближайшая автобусная остановка?'],
      ['How often do the buses run?', 'Как часто ходят автобусы?'],
      ['When is the next bus?', 'Когда будет следующий автобус?'],
      ['The bus is late again.', 'Автобус снова опаздывает.'],
      ['Let’s take an Uber instead.', 'Давай лучше вызовем такси через приложение.'],
      ['The driver is on his way.', 'Водитель уже едет.'],
      ['Your driver has arrived.', 'Ваш водитель приехал.'],
      ['I’ll be out in a minute.', 'Я выйду через минуту.'],
      ['Two tickets, please.', 'Два билета, пожалуйста.'],
      ['One single and one return, please.', 'Один в одну сторону и один туда-обратно, пожалуйста.'],
      ['Does this ticket include the transfer?', 'Этот билет включает пересадку?'],
      ['Do I need to validate my ticket?', 'Мне нужно прокомпостировать билет?'],
      ['Excuse me, could I squeeze past?', 'Извините, можно пройти?'],
      ['Could you move over a little?', 'Не могли бы вы подвинуться чуть-чуть?'],
      ['Are we there yet?', 'Мы уже приехали?'],
      ['What stop is next?', 'Какая следующая остановка?'],
      ['Please let me through, this is my stop.', 'Пропустите меня, пожалуйста, это моя остановка.'],
      ['Watch your step when getting off.', 'Осторожно выходите из транспорта.'],
    ],
  },

  trainmetro: {
    file: 'dictionaries/phrasebook-transportationtrainsubway.json',
    emoji: '🚆',
    description: 'Поезда и метро — билеты, платформы, расписание, пересадки',
    phrases: [
      ['A ticket to Manchester, please.', 'Один билет до Манчестера, пожалуйста.'],
      ['One return ticket, please.', 'Один билет туда и обратно, пожалуйста.'],
      ['Single or return?', 'В один конец или туда-обратно?'],
      ['Return, please.', 'Туда и обратно, пожалуйста.'],
      ['First or second class?', 'Первый или второй класс?'],
      ['Second class is fine.', 'Второй класс подойдет.'],
      ['Window seat, please.', 'Место у окна, пожалуйста.'],
      ['Is this train direct?', 'Это прямой поезд?'],
      ['Do I need to change trains?', 'Нужна ли пересадка?'],
      ['You need to change at York.', 'Вам нужна пересадка в Йорке.'],
      ['Which platform does the train leave from?', 'С какой платформы отходит поезд?'],
      ['The train leaves from platform three.', 'Поезд отходит с третьей платформы.'],
      ['When does the next train arrive?', 'Когда прибывает следующий поезд?'],
      ['The train is delayed by ten minutes.', 'Поезд задерживается на десять минут.'],
      ['The train has been cancelled.', 'Поезд отменён.'],
      ['Is this train going to the airport?', 'Этот поезд идёт в аэропорт?'],
      ['Does this train stop at Oxford?', 'Этот поезд останавливается в Оксфорде?'],
      ['How long does the journey take?', 'Сколько длится поездка?'],
      ['About two and a half hours.', 'Около двух с половиной часов.'],
      ['Where is the ticket office?', 'Где билетная касса?'],
      ['Where can I buy a metro card?', 'Где можно купить карту метро?'],
      ['How much is a day pass?', 'Сколько стоит проездной на день?'],
      ['Top up my travel card, please.', 'Пополните мою транспортную карту, пожалуйста.'],
      ['Which line goes to the city center?', 'Какая линия идёт в центр города?'],
      ['Take the red line northbound.', 'Поезжайте по красной линии в северном направлении.'],
      ['Change to line two at Central Station.', 'Пересядьте на вторую линию на Центральном вокзале.'],
      ['Which exit for the National Museum?', 'Какой выход к Национальному музею?'],
      ['Mind the gap!', 'Осторожно, зазор между поездом и платформой!'],
      ['Stand behind the yellow line.', 'Стойте за жёлтой линией.'],
      ['Let passengers off first.', 'Дайте сначала выйти пассажирам.'],
      ['Excuse me, what station is this?', 'Извините, какая это станция?'],
      ['Announce my station, please.', 'Объявите мою станцию, пожалуйста.'],
      ['Wake me up when we get to Boston.', 'Разбудите меня, когда мы приедем в Бостон.'],
      ['Is there a dining car on this train?', 'В этом поезде есть вагон-ресторан?'],
      ['Where is car number seven?', 'Где седьмой вагон?'],
      ['This is our carriage.', 'Это наш вагон.'],
      ['These are our seats, I believe.', 'Кажется, это наши места.'],
      ['I think you’re in my seat.', 'Кажется, вы на моём месте.'],
      ['Oh sorry, my mistake.', 'Ой, извините, я ошибся.'],
    ],
  },

  lostitems: {
    file: 'dictionaries/phrasebook-lostitems.json',
    emoji: '🧳',
    new: true,
    name: 'Lost Items & Theft',
    description: 'Что-то потерялось или украли: как сообщить и что говорить',
    phrases: [
      ['Excuse me, I think I lost my wallet.', 'Извините, кажется, я потерял свой кошелёк.'],
      ['I can’t find my passport!', 'Я не могу найти свой паспорт!'],
      ['My bag was stolen!', 'У меня украли сумку!'],
      ['Someone stole my phone on the bus.', 'Кто-то украл мой телефон в автобусе.'],
      ['I left my phone in the taxi.', 'Я забыл телефон в такси.'],
      ['Has anyone turned in a black purse?', 'Кто-нибудь сдавал чёрную сумочку?'],
      ['Did anyone find a set of keys?', 'Никто не находил связку ключей?'],
      ['It’s a small brown leather wallet.', 'Это маленький коричневый кожаный кошелёк.'],
      ['There were documents inside.', 'Внутри были документы.'],
      ['Where is the lost and found?', 'Где находится бюро находок?'],
      ['When did you see it last?', 'Когда вы видели её в последний раз?'],
      ['Describe the item, please.', 'Опишите вещь, пожалуйста.'],
      ['Can you retrace your steps?', 'Можете вспомнить, где вы были?'],
      ['Check with reception, maybe someone found it.', 'Спросите на ресепшене, может, кто-то нашёл.'],
      ['I’d like to report a theft.', 'Я хочу заявить о краже.'],
      ['I want to file a police report.', 'Я хочу написать заявление в полицию.'],
      ['It happened about an hour ago near the market.', 'Это случилось около часа назад возле рынка.'],
      ['He grabbed my bag and ran off.', 'Он выхватил сумку и убежал.'],
      ['I didn’t see his face clearly.', 'Я не разглядел его лицо.'],
      ['He was wearing a grey hoodie.', 'На нём была серая толстовка.'],
      ['Was anyone injured?', 'Кто-нибудь пострадал?'],
      ['No, nobody was hurt.', 'Нет, никто не пострадал.'],
      ['My credit cards were in the wallet.', 'В кошельке были мои кредитные карты.'],
      ['I need to block my cards immediately.', 'Мне нужно немедленно заблокировать карты.'],
      ['Call my bank, please.', 'Позвоните в мой банк, пожалуйста.'],
      ['My phone had all my contacts in it.', 'В телефоне были все мои контакты.'],
      ['Can I use your phone to call the police?', 'Можно воспользоваться вашим телефоном, чтобы вызвать полицию?'],
      ['Is there anything valuable inside?', 'Есть ли что-то ценное внутри?'],
      ['Luckily, the documents are intact.', 'К счастью, документы целы.'],
      ['Thank goodness I found it!', 'Слава богу, я нашёл это!'],
      ['Oh great, it was in my other pocket!', 'Отлично, оно было в другом кармане!'],
      ['Everything is here, nothing missing.', 'Всё на месте, ничего не пропало.'],
      ['Report any suspicious activity.', 'Сообщайте о любых подозрительных действиях.'],
      ['Be careful with your belongings.', 'Следите за своими вещами.'],
      ['Keep an eye on your bags.', 'Присматривайте за сумками.'],
      ['Pickpockets work in crowded places.', 'Карманники работают в людных местах.'],
    ],
  },

  phonecalls: {
    file: 'dictionaries/phrasebook-phonecalls.json',
    emoji: '📞',
    new: true,
    name: 'Phone & Video Calls',
    description: 'Телефонные разговоры и видеозвонки: представление, связь, прощание',
    phrases: [
      ['Hello, this is Mark calling.', 'Алло, это Марк звонит.'],
      ['Hi, it’s Kate.', 'Привет, это Кейт.'],
      ['Who’s calling, please?', 'Кто звонит, скажите, пожалуйста?'],
      ['May I ask who’s calling?', 'Можно узнать, кто звонит?'],
      ['Hold on, please.', 'Подождите минутку, пожалуйста.'],
      ['Just a second, I’ll get him.', 'Одну секунду, сейчас позову его.'],
      ['Hang on a moment, please.', 'Подождите минутку, пожалуйста.'],
      ['I’m putting you through now.', 'Соединяю вас.'],
      ['Sorry, she’s not available right now.', 'Извините, она сейчас не может подойти.'],
      ['She’s on another call.', 'Она разговаривает по другой линии.'],
      ['He stepped out of the office.', 'Он вышел из офиса.'],
      ['Would you like to leave a message?', 'Хотите оставить сообщение?'],
      ['Can I leave a message for her?', 'Можно оставить ей сообщение?'],
      ['Please tell him Alex called.', 'Передайте ему, что звонил Алекс.'],
      ['I’ll call back later.', 'Я перезвоню позже.'],
      ['Ask her to call me back, please.', 'Попросите её перезвонить мне, пожалуйста.'],
      ['Sorry, you’ve got the wrong number.', 'Извините, вы ошиблись номером.'],
      ['What number did you dial?', 'Какой номер вы набрали?'],
      ['Sorry, I must have dialled wrong.', 'Извините, должно быть, я набрал не тот номер.'],
      ['The line is busy.', 'Линия занята.'],
      ['You’re breaking up.', 'Ты прерываешься. / Связь плохая.'],
      ['You’re cutting out.', 'Тебя обрывает.'],
      ['I can barely hear you.', 'Я почти тебя не слышу.'],
      ['Say that again, please.', 'Повторите, пожалуйста.'],
      ['We have a bad connection.', 'У нас плохая связь.'],
      ['Let me call you back on WhatsApp.', 'Я перезвоню тебе через WhatsApp.'],
      ['Switch to video, let me see you!', 'Переключись на видео, дай посмотреть на тебя!'],
      ['Can you hear me now?', 'Теперь вы меня слышите?'],
      ['Loud and clear!', 'Отлично слышно!'],
      ['Your microphone is muted.', 'Ваш микрофон выключен.'],
      ['Unmute yourself, please.', 'Включите микрофон, пожалуйста.'],
      ['You’re frozen again.', 'У вас снова зависло видео.'],
      ['Your camera is off.', 'У вас выключена камера.'],
      ['Share your screen, please.', 'Покажите экран, пожалуйста.'],
      ['I’ll send you the link.', 'Я пришлю вам ссылку.'],
      ['Join the meeting, we’re waiting for you.', 'Заходите в конференцию, вас ждут.'],
      ['Sorry, I have another call coming in.', 'Извините, у меня входящий вызов.'],
      ['Can I call you back in five minutes?', 'Я могу перезвонить через пять минут?'],
      ['Text me instead, it’s noisy here.', 'Лучше напиши сообщение, тут шумно.'],
      ['Sorry, I missed your call.', 'Извините, я пропустил твой звонок.'],
      ['Why didn’t you pick up?', 'Почему ты не взял трубку?'],
      ['My battery is dying.', 'Мой телефон садится.'],
      ['I’m almost out of credit.', 'У меня почти закончились деньги на счёте.'],
      ['Talk soon, bye!', 'Созвонимся, пока!'],
      ['Thanks for calling. Goodbye!', 'Спасибо за звонок. До свидания!'],
      ['Speak to you soon!', 'До связи!'],
    ],
  },
};
