// Curated real-speech phrases: airport, hotel, rental apartment, directions.
export const travel = {
  airport: {
    file: 'dictionaries/phrasebook-attheairport.json',
    emoji: '🛫',
    description: 'Аэропорт: регистрация, контроль, посадка, багаж — живые фразы',
    phrases: [
      ['Excuse me, where is the check-in desk?', 'Извините, где стойка регистрации?'],
      ['Which terminal does my flight leave from?', 'С какого терминала вылетает мой рейс?'],
      ["I'd like a window seat, please.", 'Я бы хотел место у окна, пожалуйста.'],
      ['I’d prefer an aisle seat.', 'Я бы предпочёл место у прохода.'],
      ['Are we taking off on time?', 'Мы взлетаем вовремя?'],
      ['Is the flight on schedule?', 'Рейс по расписанию?'],
      ['The flight has been delayed.', 'Рейс задержали.'],
      ['How long is the delay?', 'Какая длительность задержки?'],
      ['What time does boarding start?', 'Когда начинается посадка?'],
      ['Here are my passport and ticket.', 'Вот мой паспорт и билет.'],
      ['I’m flying to London.', 'Я лечу в Лондон.'],
      ['This is my carry-on bag.', 'Это моя ручная кладь.'],
      ['Can I take this on board?', 'Могу я взять это на борт?'],
      ['Does this fit in the overhead bin?', 'Это поместится на верхнюю полку?'],
      ['How many bags can I check in?', 'Сколько мест багажа можно сдать?'],
      ['I have two suitcases to check in.', 'Мне нужно сдать два чемодана.'],
      ['Could you tag this bag for me?', 'Могли бы вы повесить бирку на этот чемодан?'],
      ['Do you have any liquids in your bag?', 'В вашей сумке есть жидкости?'],
      ['Please put your laptop in the tray.', 'Положите ноутбук в лоток, пожалуйста.'],
      ['Take off your belt and shoes, please.', 'Снимите ремень и обувь, пожалуйста.'],
      ['Please raise your arms.', 'Поднимите руки, пожалуйста.'],
      ['I set off the alarm again.', 'У меня снова сработала рамка.'],
      ['Where can I find gate B7?', 'Где найти выход B7?'],
      ['How do I get to gate twelve?', 'Как пройти к двенадцатому выходу?'],
      ['Is this the right line for boarding?', 'Это правильная очередь на посадку?'],
      ['May I see your boarding pass?', 'Можно посмотреть ваш посадочный талон?'],
      ['We’re now boarding passengers with children.', 'Сейчас идёт посадка пассажиров с детьми.'],
      ['Final call for flight BA204!', 'Последний вызов на рейс BA204!'],
      ['Where is the baggage claim?', 'Где выдача багажа?'],
      ['Which carousel is for flight 512?', 'Какая лента для рейса 512?'],
      ['My suitcase hasn’t arrived.', 'Мой чемодан не приехал.'],
      ['One of my bags is missing.', 'Одна из моих сумок пропала.'],
      ['Where is the lost and found office?', 'Где бюро находок?'],
      ['I’d like to report lost luggage.', 'Я хочу заявить об утере багажа.'],
      ['Here is my baggage claim ticket.', 'Вот мой багажный талон.'],
      ['When will my luggage be delivered?', 'Когда мой багаж доставят?'],
      ['Where is the transfer desk?', 'Где стойка для транзитных пассажиров?'],
      ['I have a connecting flight to Rome.', 'У меня пересадка на рейс до Рима.'],
      ['Will my luggage be transferred automatically?', 'Багаж перенаправят автоматически?'],
      ['How long is the layover?', 'Насколько долгая пересадка?'],
      ['Where is the currency exchange?', 'Где обмен валюты?'],
      ['Where can I get a taxi?', 'Где можно взять такси?'],
      ['Which way to the exit?', 'В какую сторону выход?'],
      ['Is there free Wi-Fi here?', 'Здесь есть бесплатный Wi-Fi?'],
      ['Where are the restrooms?', 'Где туалеты?'],
      ['Where can I charge my phone?', 'Где можно зарядить телефон?'],
      ['Could you watch my luggage for a minute?', 'Присмотрите за моим багажом минуту?'],
      ['What is the purpose of your visit?', 'Какова цель вашей поездки?'],
      ["I'm here on holiday.", 'Я здесь на отдыхе.'],
      ["I'm here on business.", 'Я приехал по работе.'],
      ['How long are you staying?', 'На сколько вы остаётесь?'],
      ['Two weeks, until the twenty-second.', 'Две недели, до двадцать второго.'],
      ['Where will you be staying?', 'Где вы будете останавливаться?'],
      ['At a hotel downtown.', 'В отеле в центре города.'],
      ['Anything to declare?', 'Есть что-нибудь для декларации?'],
      ['Nothing to declare.', 'Мне нечего декларировать.'],
      ['Open your suitcase, please.', 'Откройте чемодан, пожалуйста.'],
      ['These are gifts for friends.', 'Это подарки друзьям.'],
      ['Welcome to our country!', 'Добро пожаловать в нашу страну!'],
      ['Enjoy your stay!', 'Приятного пребывания!'],
      ['Have a nice flight!', 'Хорошего полёта!'],
      ['Can I change my seat?', 'Можно поменять моё место?'],
      ['Is this seat taken?', 'Это место занято?'],
      ['Would you swap seats with me?', 'Не поменяешься со мной местами?'],
      ['Can I have a blanket, please?', 'Можно мне одеяло, пожалуйста?'],
      ['Chicken or pasta?', 'Курица или паста?'],
      ['Chicken, please.', 'Курицу, пожалуйста.'],
      ['Could I have some water?', 'Можно немного воды?'],
      ['When do we land?', 'Когда мы приземлимся?'],
      ['Please fasten your seatbelt.', 'Пристегните ремни, пожалуйста.'],
      ['Please switch your phone to airplane mode.', 'Переведите телефон в авиарежим, пожалуйста.'],
      ['We’re experiencing some turbulence.', 'Мы попадаем в зону турбулентности.'],
    ],
  },

  hotel: {
    file: 'dictionaries/phrasebook-atthehotel.json',
    emoji: '🛏️',
    description: 'В отеле: заселение, услуги, проблемы и выселение',
    phrases: [
      ['Good evening, do you have any rooms available?', 'Добрый вечер, у вас есть свободные номера?'],
      ['I have a reservation under the name Ivanov.', 'У меня забронирован номер на фамилию Иванов.'],
      ['I’d like to book a double room.', 'Я хотел бы забронировать двухместный номер.'],
      ['A single room for three nights, please.', 'Одноместный номер на три ночи, пожалуйста.'],
      ['How much is it per night?', 'Сколько стоит за ночь?'],
      ['Is breakfast included?', 'Завтрак включён?'],
      ['What time is breakfast served?', 'Во сколько подают завтрак?'],
      ['Is there a swimming pool in the hotel?', 'В отеле есть бассейн?'],
      ['Do you have Wi-Fi in the rooms?', 'В номерах есть Wi-Fi?'],
      ["What's the password for the Wi-Fi?", 'Какой пароль от Wi-Fi?'],
      ['Could I see the room first?', 'Можно сначала посмотреть номер?'],
      ['The room is too noisy.', 'В номере слишком шумно.'],
      ['It faces the street. Could we get a quieter room?', 'Он выходит на улицу. Можно номер потише?'],
      ['The air conditioning doesn’t work.', 'Кондиционер не работает.'],
      ['The shower has no hot water.', 'В душе нет горячей воды.'],
      ['There’s no toilet paper in the bathroom.', 'В ванной нет туалетной бумаги.'],
      ['The TV remote doesn’t work.', 'Пульт от телевизора не работает.'],
      ['Could someone clean my room, please?', 'Кто-нибудь мог бы убрать мой номер?'],
      ['Could I get extra towels?', 'Можно дополнительные полотенца?'],
      ['Could I have more pillows, please?', 'Можно ещё подушек, пожалуйста?'],
      ['I left my key card in the room.', 'Я оставил ключ-карту в номере.'],
      ['I’ve locked myself out.', 'Я заперся снаружи.'],
      ['Room service, please.', 'Обслуживание номеров, пожалуйста.'],
      ['I’d like to order room service.', 'Я хотел бы заказать еду в номер.'],
      ['Could you bring it up to room 305?', 'Могли бы вы поднять это в номер 305?'],
      ['Can I have a wake-up call at seven?', 'Разбудите меня в семь, пожалуйста?'],
      ['Please wake me up at six thirty.', 'Разбудите меня в шесть тридцать, пожалуйста.'],
      ['Where is the elevator?', 'Где лифт?'],
      ['Is there a safe in the room?', 'В номере есть сейф?'],
      ['Can I leave my valuables at reception?', 'Могу оставить ценности на ресепшене?'],
      ['Is there parking at the hotel?', 'В отеле есть парковка?'],
      ['What time is check-out?', 'Во сколько выезд?'],
      ['Can we check out a bit later?', 'Можно выехать чуть позже?'],
      ['I’d like to extend my stay for one more night.', 'Я хотел бы продлить пребывание ещё на одну ночь.'],
      ['I’d like to pay by card.', 'Я хотел бы оплатить картой.'],
      ['Could I have the bill, please?', 'Можно счёт, пожалуйста?'],
      ['I’m checking out today.', 'Сегодня я выселяюсь.'],
      ['Here’s your key back.', 'Вот ваш ключ обратно.'],
      ['Was everything all right with your stay?', 'Всё ли было хорошо во время проживания?'],
      ['Yes, everything was perfect, thank you.', 'Да, всё было отлично, спасибо.'],
      ['Could you call a taxi for me?', 'Вы могли бы вызвать мне такси?'],
      ['Could you keep my luggage until evening?', 'Можете подержать мой багаж до вечера?'],
      ['I left my charger in the room.', 'Я забыл зарядку в номере.'],
      ['Did anyone find a black wallet here?', 'Здесь никто не находил чёрный кошелёк?'],
      ['Enjoy your stay with us!', 'Приятного пребывания!'],
    ],
  },

  airbnb: {
    file: 'dictionaries/phrasebook-airbnbrental.json',
    emoji: '🏡',
    new: true,
    name: 'Short-term Rental',
    description: 'Съём жилья: переписка с хозяином, заезд, бытовые вопросы',
    phrases: [
      ['Hi! Is the apartment still available?', 'Здравствуйте! Квартира всё ещё свободна?'],
      ['Is this room available next weekend?', 'Эта комната свободна на следующие выходные?'],
      ['For what dates?', 'На какие даты?'],
      ['From June third to June tenth.', 'С третьего по десятое июня.'],
      ['How many guests does it sleep?', 'Сколько человек может разместиться?'],
      ['Is the price per person or total?', 'Цена за человека или за всех?'],
      ['Does the price include utilities?', 'В цену входят коммунальные услуги?'],
      ['Is there an extra cleaning fee?', 'Есть отдельная плата за уборку?'],
      ['What time is check-in?', 'Во сколько заселение?'],
      ['What time is check-out?', 'Во сколько выезд?'],
      ['Is early check-in possible?', 'Возможно ли раннее заселение?'],
      ['Can we drop our bags off before check-in?', 'Можно оставить сумки до заселения?'],
      ['How do we get the keys?', 'Как мы получим ключи?'],
      ['Someone will meet us at the apartment.', 'Кто-то встретит нас у квартиры.'],
      ['Is there self check-in with a code?', 'Есть самостоятельное заселение по коду?'],
      ['Is there free parking nearby?', 'Есть ли бесплатная парковка рядом?'],
      ['How far is the nearest metro station?', 'Как далеко ближайшая станция метро?'],
      ['Is the area safe at night?', 'Этот район безопасен ночью?'],
      ['Is the building quiet?', 'Дом тихий?'],
      ['Is smoking allowed?', 'Можно курить?'],
      ['Are pets allowed?', 'Можно с животными?'],
      ['Is there air conditioning?', 'Есть кондиционер?'],
      ['Is there a washing machine?', 'Есть стиральная машина?'],
      ['Is there Wi-Fi, and how fast is it?', 'Есть Wi-Fi, и какой скорости?'],
      ['What’s the Wi-Fi password?', 'Какой пароль от Wi-Fi?'],
      ['The hot water isn’t working.', 'Горячая вода не работает.'],
      ['The heater won’t turn on.', 'Обогреватель не включается.'],
      ['The door won’t lock properly.', 'Дверь нормально не запирается.'],
      ['There’s no toilet paper left.', 'Туалетная бумага закончилась.'],
      ['Could you send someone to fix it?', 'Не могли бы вы прислать кого-нибудь починить?'],
      ['We accidentally broke a glass, sorry!', 'Мы случайно разбили стакан, извините!'],
      ['Where should we throw out the trash?', 'Куда выбрасывать мусор?'],
      ['Where can we park?', 'Где нам можно парковаться?'],
      ['Thanks for the recommendations!', 'Спасибо за рекомендации!'],
      ['Any tips for local restaurants?', 'Посоветуете местные рестораны?'],
      ['We’re checking out tomorrow morning.', 'Мы съезжаем завтра утром.'],
      ['Where should we leave the keys?', 'Где нам оставить ключи?'],
      ['Everything was great, thank you!', 'Всё было замечательно, спасибо!'],
      ['We really enjoyed our stay.', 'Нам очень понравилось жить здесь.'],
      ['Would you mind writing us a review?', 'Не могли бы вы написать нам отзыв?'],
      ['Sure, we’ll leave a five-star review!', 'Конечно, оставим пятизвёздочный отзыв!'],
    ],
  },

  directions: {
    file: 'dictionaries/phrasebook-directionsnavigation.json',
    emoji: '🧭',
    description: 'Спросить дорогу и объяснить путь — как это делают носители',
    phrases: [
      ['Excuse me, could you tell me how to get to the station?', 'Извините, не скажете, как добраться до вокзала?'],
      ['How do I get to the city center from here?', 'Как попасть отсюда в центр города?'],
      ['What’s the best way to the museum?', 'Как лучше всего добраться до музея?'],
      ['Is it far from here?', 'Это далеко отсюда?'],
      ['Is it within walking distance?', 'Это можно дойти пешком?'],
      ['It’s about a ten-minute walk.', 'Это минут десять пешком.'],
      ['Go straight ahead.', 'Идите прямо.'],
      ['Go straight until the traffic lights.', 'Идите прямо до светофора.'],
      ['Turn left at the corner.', 'Поверните налево на углу.'],
      ['Turn right at the second crossing.', 'Поверните направо на втором перекрёстке.'],
      ['Cross the street at the crosswalk.', 'Перейдите дорогу по пешеходному переходу.'],
      ['Go past the bank and then turn left.', 'Пройдите мимо банка и поверните налево.'],
      ["It's just around the corner.", 'Это прямо за углом.'],
      ["It's across the street.", 'Это через дорогу.'],
      ["It's next to the pharmacy.", 'Это рядом с аптекой.'],
      ["It's opposite the church.", 'Это напротив церкви.'],
      ["It's between the café and the shop.", 'Это между кафе и магазином.'],
      ['Take the second street on the right.', 'Сверните во вторую улицу справа.'],
      ['Follow this road for about a mile.', 'Идите по этой дороге примерно милю.'],
      ["You can't miss it.", 'Вы его точно не пропустите.'],
      ['Am I going the right way?', 'Я иду в правильном направлении?'],
      ['Did I miss my stop?', 'Я проехал свою остановку?'],
      ['You’re going in the wrong direction.', 'Вы движетесь не в том направлении.'],
      ['You need to go back two blocks.', 'Вам нужно вернуться на два квартала назад.'],
      ['Sorry, I’m not from around here.', 'Извините, я не местный.'],
      ['I’m afraid I don’t know this area.', 'Боюсь, я не знаю этот район.'],
      ['Let me check the map.', 'Дайте посмотрю на карте.'],
      ['Let’s use the GPS.', 'Давай воспользуемся навигатором.'],
      ['Recalculate the route, please.', 'Пересчитайте маршрут, пожалуйста.'],
      ['Where am I on this map?', 'Где я на этой карте?'],
      ['Could you show me on the map where we are?', 'Можете показать на карте, где мы?'],
      ['Is there a shortcut?', 'Есть короткая дорога?'],
      ['Which side of the street is the entrance on?', 'С какой стороны улицы вход?'],
      ['Is this the entrance to the metro?', 'Это вход в метро?'],
      ['How many stops from here?', 'Сколько остановок отсюда?'],
      ['Get off at the third stop.', 'Выйдете на третьей остановке.'],
      ['Is this seat facing forward?', 'Это место по ходу движения?'],
      ['Keep left at the fork.', 'На развилке держитесь левее.'],
      ['Take the escalator down.', 'Спуститесь по эскалатору.'],
      ['The elevator is to your right.', 'Лифт справа от вас.'],
      ['Follow the signs to the exits.', 'Следуйте по указателям к выходам.'],
      ['Lost? Need help finding something?', 'Заблудились? Помочь что-нибудь найти?'],
      ['Yes, please! I’m looking for platform five.', 'Да, пожалуйста! Я ищу пятую платформу.'],
    ],
  },
};
