// Curated real-speech phrases: work & meetings, job interview, email.
export const work = {
  work: {
    file: 'dictionaries/phrasebook-workbusiness.json',
    emoji: '💼',
    description: 'Работа: совещания, дедлайны, обсуждение задач, офисные разговоры',
    phrases: [
      ['Good morning, everyone. Let’s get started.', 'Доброе утро всем. Давайте начинать.'],
      ['Let’s begin the meeting.', 'Начнём собрание.'],
      ['Thanks for joining us today.', 'Спасибо, что присоединились сегодня.'],
      ['Everyone here?', 'Все здесь?'],
      ['Is everyone on the call?', 'Все на связи?'],
      ['Can everyone hear me?', 'Вас всем слышно?'],
      ['You’re on mute.', 'У вас выключен микрофон.'],
      ['Let’s move on to the next item.', 'Перейдём к следующему пункту.'],
      ['Let’s get down to business.', 'Давайте перейдём к делу.'],
      ['We have a lot to cover today.', 'Нам нужно обсудить много вопросов.'],
      ['The main goal of this meeting is…', 'Главная цель этого собрания.'],
      ['Any questions so far?', 'Есть вопросы по ходу?'],
      ['Does that make sense?', 'Это понятно? / Всё логично?'],
      ['Could you clarify what you mean?', 'Не могли бы вы уточнить, что вы имеете в виду?'],
      ['Sorry to interrupt, but I’d like to add something.', 'Извините, что перебиваю, но я бы хотел добавить.'],
      ['Please let me finish my point.', 'Позвольте мне закончить мысль.'],
      ['Back to the topic, please.', 'Вернёмся к теме, пожалуйста.'],
      ['Let’s not get sidetracked.', 'Давайте не будем отвлекаться.'],
      ['What’s your take on this?', 'Каково ваше мнение по этому поводу?'],
      ['From our side, everything is ready.', 'С нашей стороны всё готово.'],
      ['We’re on track with the schedule.', 'Мы идём по графику.'],
      ['We’re behind schedule.', 'Мы отстаём от графика.'],
      ['We need more time for testing.', 'Нам нужно больше времени на тестирование.'],
      ["What's the status of the project?", 'Каков статус проекта?'],
      ['Where are we with the report?', 'На каком этапе отчёт?'],
      ['It’s almost done, just polishing.', 'Почти готово, шлифуем детали.'],
      ['When can you deliver it?', 'Когда вы сможете это сдать?'],
      ['The deadline is next Friday.', 'Крайний срок — следующая пятница.'],
      ['Can we extend the deadline?', 'Можно продлить срок?'],
      ['I’ll send it by end of day.', 'Я отправлю это до конца дня.'],
      ['I’ll follow up on that.', 'Я вернусь к этому вопросу.'],
      ['Let me double-check and get back to you.', 'Я проверю и вернусь с ответом.'],
      ['Keep me posted.', 'Держите меня в курсе.'],
      ['Loop me in when there’s news.', 'Подключайте меня, когда будут новости.'],
      ['Copy me on future emails.', 'Ставьте меня в копию в дальнейшей переписке.'],
      ['Let’s touch base tomorrow.', 'Свяжемся завтра для сверки.'],
      ['Let’s circle back to this later.', 'Вернёмся к этому позже.'],
      ['Table this for now.', 'Отложим это пока.'],
      ['Let’s park that question.', 'Оставим этот вопрос на потом.'],
      ['To sum up, we agreed on three points.', 'Подводя итог, мы согласовали три пункта.'],
      ['Let’s wrap up.', 'Давайте завершать.'],
      ['That’s all from me.', 'Это всё, что я хотел сказать.'],
      ['Thanks for your time, everyone.', 'Спасибо всем за время.'],
      ['Meeting adjourned.', 'Заседание закрыто.'],
      ['See you at the next sync.', 'До встречи на следующем созвоне.'],
      ['How was your weekend? Did you finally rest?', 'Как выходные? Наконец-то отдохнули?'],
      ['Coffee break, anyone?', 'Кофе-брейк, кто со мной?'],
      ['Lunch together?', 'Обедаем вместе?'],
      ['I’m grabbing lunch; want anything?', 'Иду за обедом; тебе что-нибудь взять?'],
      ['TGIF!', 'Ура, пятница!'],
      ['Have a good evening, see you tomorrow.', 'Хорошего вечера, до завтра.'],
      ['Have a great vacation! You deserve it.', 'Хорошего отпуска! Вы его заслужили.'],
      ['Who covers for you while you’re away?', 'Кто вас подменяет, пока вас нет?'],
      ['I’m working remotely today.', 'Я сегодня работаю удалённо.'],
      ['I’ll be out of office tomorrow.', 'Завтра меня не будет на месте.'],
      ['He called in sick today.', 'Он сегодня взял больничный.'],
      ['She’s on maternity leave.', 'Она в декретном отпуске.'],
      ['I need to take a day off.', 'Мне нужно взять выходной.'],
      ['My request for leave got approved.', 'Мой отпуск одобрили.'],
      ['Overtime again tonight.', 'Опять переработка сегодня вечером.'],
      ['Let’s finish this tomorrow with fresh eyes.', 'Давай закончим это завтра на свежую голову.'],
      ['Good job on the presentation!', 'Отличная работа с презентацией!'],
      ['Your report was very thorough.', 'Ваш доклад был очень основательным.'],
    ],
  },

  interview: {
    file: 'dictionaries/phrasebook-jobinterview.json',
    emoji: '🤝',
    description: 'Собеседование: самопрезентация, типичные вопросы и ответы',
    phrases: [
      ['Thanks for coming in today.', 'Спасибо, что пришли сегодня.'],
      ['Thank you for inviting me.', 'Спасибо за приглашение.'],
      ['Nice to meet you in person.', 'Приятно познакомиться лично.'],
      ['Did you find our office okay?', 'Вы легко нашли наш офис?'],
      ['Tell me about yourself.', 'Расскажите о себе.'],
      ['Where do you see yourself in five years?', 'Где вы видите себя через пять лет?'],
      ['Why do you want to work here?', 'Почему вы хотите работать у нас?'],
      ['Why did you leave your last job?', 'Почему вы ушли с прошлой работы?'],
      ['What are your strengths?', 'Каковы ваши сильные стороны?'],
      ['What would you say your weaknesses are?', 'Какие у вас слабые стороны?'],
      ['I tend to be a perfectionist, but I’m working on it.', 'Я склонен к перфекционизму, но работаю над этим.'],
      ['I work well both alone and in a team.', 'Я хорошо работаю и один, и в команде.'],
      ['I’m a fast learner.', 'Я быстро учусь.'],
      ['I pay attention to detail.', 'Я внимателен к деталям.'],
      ['I stay calm under pressure.', 'Я сохраняю спокойствие под давлением.'],
      ['Describe a difficult situation and how you handled it.', 'Опишите сложную ситуацию и то, как вы её решили.'],
      ['Give an example of teamwork from your experience.', 'Приведите пример командной работы из вашего опыта.'],
      ['Have you ever missed a deadline? What happened?', 'Вы когда-нибудь срывали срок? Что произошло?'],
      ['I owned up to the mistake and fixed the process.', 'Я признал ошибку и исправил процесс.'],
      ['What do you know about our company?', 'Что вы знаете о нашей компании?'],
      ['I’ve been following your products for years.', 'Я слежу за вашими продуктами уже много лет.'],
      ['What experience do you have with…', 'Какой у вас опыт работы с.'],
      ['I have three years of experience in this field.', 'У меня трёхлетний опыт в этой сфере.'],
      ['In my previous role, I managed a team of five.', 'На предыдущем месте я руководил командой из пяти человек.'],
      ['I led the migration project last year.', 'В прошлом году я вёл проект по миграции.'],
      ['Are you comfortable working overtime occasionally?', 'Вам окей иногда работать сверхурочно?'],
      ['Are you willing to relocate?', 'Готовы ли вы переехать?'],
      ['Do you have any questions for us?', 'Есть ли у вас вопросы к нам?'],
      ['Yes — how big is the team I’d be joining?', 'Да — насколько большая команда, к которой я присоединюсь?'],
      ['What does a typical day look like here?', 'Как выглядит обычный рабочий день здесь?'],
      ['How do you measure success in this role?', 'Как вы оцениваете успех в этой роли?'],
      ['What are the next steps in the process?', 'Какие следующие шаги в процессе отбора?'],
      ['We’ll get back to you within a week.', 'Мы свяжемся с вами в течение недели.'],
      ['Thank you for your time. I look forward to hearing from you.', 'Спасибо за уделённое время. С нетерпением жду вашего ответа.'],
      ['What salary range are you expecting?', 'На какой диапазон зарплаты вы рассчитываете?'],
      ['Based on market rates, I’m looking at sixty to seventy thousand.', 'По рынку ориентируюсь на шестьдесят-семьдесят тысяч.'],
      ['Salary is negotiable depending on the package.', 'Зарплата обсуждается в зависимости от полного пакета.'],
      ['When could you start?', 'Когда вы можете выйти на работу?'],
      ['I could start in two weeks.', 'Я могу выйти через две недели.'],
      ['Congratulations, we’d like to offer you the position!', 'Поздравляем, мы хотели бы предложить вам эту должность!'],
      ['I accept the offer, thank you!', 'Я принимаю предложение, спасибо!'],
    ],
  },

  email: {
    file: 'dictionaries/phrasebook-emailphrases.json',
    emoji: '✉️',
    new: true,
    name: 'Email & Messages',
    description: 'Электронные письма: приветствия, вежливые формулировки, подпись',
    phrases: [
      ['Dear Sir or Madam,', 'Уважаемый господин или госпожа (официальное начало письма),'],
      ['Dear Mr. Johnson,', 'Уважаемый мистер Джонсон,'],
      ['Dear Ms. Parker,', 'Уважаемая миссис Паркер,'],
      ['Hi John,', 'Привет, Джон,'],
      ['Hello team,', 'Привет, команда,'],
      ['Good afternoon, colleagues.', 'Добрый день, коллеги.'],
      ['I am writing to inquire about…', 'Пишу вам, чтобы узнать о.'],
      ['I am writing regarding your recent order.', 'Пишу по поводу вашего недавнего заказа.'],
      ['With reference to our conversation…', 'Со ссылкой на наш разговор.'],
      ['Further to my previous email…', 'В дополнение к моему предыдущему письму.'],
      ['As discussed, I am sending you the files.', 'Как договаривались, отправляю вам файлы.'],
      ['Please find attached the report.', 'Во вложении вы найдёте отчёт.'],
      ['Attached you will find the invoice.', 'Во вложении счёт-фактура.'],
      ['I have attached my resume for your review.', 'Прилагаю моё резюме на рассмотрение.'],
      ['Could you please confirm receipt of this message?', 'Не могли бы вы подтвердить получение этого сообщения?'],
      ['I would appreciate a prompt reply.', 'Буду признателен за оперативный ответ.'],
      ['Looking forward to hearing from you.', 'Жду вашего ответа.'],
      ['Awaiting your feedback.', 'Ожидаю вашей обратной связи.'],
      ['Please respond at your earliest convenience.', 'Ответьте, пожалуйста, как будет удобно.'],
      ['No rush — whenever you get a chance.', 'Без спешки — когда будет возможность.'],
      ['Just a quick reminder about tomorrow’s meeting.', 'Небольшое напоминание о завтрашней встрече.'],
      ['This is a gentle nudge about the pending payment.', 'Мягко напоминаю об ожидающемся платеже.'],
      ['Apologies for the late reply.', 'Прошу прощения за поздний ответ.'],
      ['Sorry for the delayed response, I was on vacation.', 'Извините за задержку с ответом, я был в отпуске.'],
      ['Thanks for getting back to me.', 'Спасибо, что ответили.'],
      ['Thank you for your quick reply.', 'Спасибо за быстрый ответ.'],
      ['I appreciate your help with this matter.', 'Ценю вашу помощь в этом вопросе.'],
      ['Unfortunately, we cannot accept the offer.', 'К сожалению, мы не можем принять предложение.'],
      ['Regretfully, I must decline.', 'К сожалению, вынужден отказаться.'],
      ['We regret to inform you that…', 'С сожалением сообщаем, что.'],
      ['Please keep me informed of any changes.', 'Информируйте меня о любых изменениях.'],
      ['Let me know if anything is unclear.', 'Сообщите, если что-то непонятно.'],
      ['Feel free to reach out if you have questions.', 'Обращайтесь, если возникнут вопросы.'],
      ['Don’t hesitate to contact me.', 'Не стесняйтесь связаться со мной.'],
      ['If you have any questions, just ask.', 'Если есть вопросы, просто спросите.'],
      ['Could you resend the file? It didn’t open.', 'Могли бы вы прислать файл заново? Он не открылся.'],
      ['I might have misunderstood — could you clarify?', 'Возможно, я неправильно понял — могли бы уточнить?'],
      ['Just to confirm: the meeting is at three, right?', 'Чтобы уточнить: встреча в три, верно?'],
      ['CC’ing Anna for visibility.', 'Ставлю Анну в копию для информации.'],
      ['Moving this thread offline.', 'Продолжим обсуждение вне цепочки писем.'],
      ['Best regards,', 'С наилучшими пожеланиями,'],
      ['Kind regards,', 'С уважением,'],
      ['Sincerely,', 'Искренне ваш,'],
      ['All the best,', 'Всего доброго,'],
      ['Cheers,', 'Пока (неформальное завершение письма),'],
      ['Talk soon,', 'До связи,'],
      ['Sent from my iPhone.', 'Отправлено с iPhone.'],
    ],
  },
};
