export type EmojiCategory = 
  | 'All'
  | 'Favorites'
  | 'Recent'
  | 'Smileys & Emotion'
  | 'People'
  | 'Animals'
  | 'Nature'
  | 'Food & Drink'
  | 'Travel'
  | 'Transport'
  | 'Sports'
  | 'Games'
  | 'Music'
  | 'Movies & Media'
  | 'Art'
  | 'Books & Learning'
  | 'Work'
  | 'Business'
  | 'Finance'
  | 'Technology'
  | 'Programming'
  | 'Linux / DevOps'
  | 'AI'
  | 'Science'
  | 'Medicine'
  | 'Tools'
  | 'Security'
  | 'Communication'
  | 'Shopping'
  | 'Home'
  | 'Time'
  | 'Weather'
  | 'Space'
  | 'Symbols'
  | 'Awards'
  | 'Misc';

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
  category: EmojiCategory;
}

export const CATEGORIES: EmojiCategory[] = [
  'All',
  'Favorites',
  'Recent',
  'Smileys & Emotion',
  'People',
  'Animals',
  'Nature',
  'Food & Drink',
  'Travel',
  'Transport',
  'Sports',
  'Games',
  'Music',
  'Movies & Media',
  'Art',
  'Books & Learning',
  'Work',
  'Business',
  'Finance',
  'Technology',
  'Programming',
  'Linux / DevOps',
  'AI',
  'Science',
  'Medicine',
  'Tools',
  'Security',
  'Communication',
  'Shopping',
  'Home',
  'Time',
  'Weather',
  'Space',
  'Symbols',
  'Awards',
  'Misc'
];

// Mapped icons for category tabs
export const CATEGORY_ICONS: Record<EmojiCategory, string> = {
  'All': '🌍',
  'Favorites': '⭐',
  'Recent': '🕒',
  'Smileys & Emotion': '😀',
  'People': '👋',
  'Animals': '🐶',
  'Nature': '🌿',
  'Food & Drink': '🍔',
  'Travel': '✈️',
  'Transport': '🚗',
  'Sports': '⚽',
  'Games': '🎮',
  'Music': '🎵',
  'Movies & Media': '🎬',
  'Art': '🎨',
  'Books & Learning': '📚',
  'Work': '💼',
  'Business': '📈',
  'Finance': '💰',
  'Technology': '💻',
  'Programming': '👨‍💻',
  'Linux / DevOps': '🐧',
  'AI': '🤖',
  'Science': '🔬',
  'Medicine': '💊',
  'Tools': '🛠️',
  'Security': '🔒',
  'Communication': '💬',
  'Shopping': '🛒',
  'Home': '🏠',
  'Time': '⏰',
  'Weather': '☀️',
  'Space': '🚀',
  'Symbols': '🔣',
  'Awards': '🏆',
  'Misc': '✨'
};

export const EMOJI_DATABASE: EmojiItem[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'Grinning Face', keywords: ['smile', 'happy', 'joy'], category: 'Smileys & Emotion' },
  { emoji: '😂', name: 'Face with Tears of Joy', keywords: ['smile', 'happy', 'joy', 'laugh', 'tears', 'lmao'], category: 'Smileys & Emotion' },
  { emoji: '🤣', name: 'Rolling on the Floor Laughing', keywords: ['smile', 'happy', 'joy', 'laugh', 'rofl'], category: 'Smileys & Emotion' },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', keywords: ['smile', 'happy', 'blush', 'proud'], category: 'Smileys & Emotion' },
  { emoji: '🥰', name: 'Smiling Face with Hearts', keywords: ['love', 'happy', 'affection'], category: 'Smileys & Emotion' },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', keywords: ['cool', 'sun', 'swag'], category: 'Smileys & Emotion' },
  { emoji: '🤔', name: 'Thinking Face', keywords: ['think', 'wonder', 'hmm'], category: 'Smileys & Emotion' },
  { emoji: '😭', name: 'Loudly Crying Face', keywords: ['cry', 'sad', 'tears', 'sob'], category: 'Smileys & Emotion' },
  { emoji: '😡', name: 'Pouting Face', keywords: ['mad', 'angry', 'red'], category: 'Smileys & Emotion' },
  { emoji: '🤯', name: 'Exploding Head', keywords: ['mind blown', 'shock', 'wow'], category: 'Smileys & Emotion' },
  { emoji: '🥳', name: 'Partying Face', keywords: ['party', 'celebrate', 'fun'], category: 'Smileys & Emotion' },
  { emoji: '🫠', name: 'Melting Face', keywords: ['hot', 'melt', 'sarcasm', 'dread'], category: 'Smileys & Emotion' },
  { emoji: '💀', name: 'Skull', keywords: ['dead', 'skeleton', 'creepy'], category: 'Smileys & Emotion' },
  { emoji: '🤡', name: 'Clown Face', keywords: ['clown', 'joke', 'silly'], category: 'Smileys & Emotion' },
  { emoji: '👻', name: 'Ghost', keywords: ['scary', 'spooky', 'boo'], category: 'Smileys & Emotion' },
  { emoji: '💩', name: 'Pile of Poo', keywords: ['poop', 'crap', 'shit'], category: 'Smileys & Emotion' },
  
  // People
  { emoji: '👋', name: 'Waving Hand', keywords: ['hello', 'hi', 'bye', 'greet'], category: 'People' },
  { emoji: '👌', name: 'OK Hand', keywords: ['okay', 'perfect', 'good'], category: 'People' },
  { emoji: '✌️', name: 'Victory Hand', keywords: ['peace', 'two', 'win'], category: 'People' },
  { emoji: '🤞', name: 'Crossed Fingers', keywords: ['luck', 'hope', 'wish'], category: 'People' },
  { emoji: '👍', name: 'Thumbs Up', keywords: ['yes', 'good', 'approve'], category: 'People' },
  { emoji: '👎', name: 'Thumbs Down', keywords: ['no', 'bad', 'disapprove'], category: 'People' },
  { emoji: '👏', name: 'Clapping Hands', keywords: ['applause', 'bravo', 'good job'], category: 'People' },
  { emoji: '🙌', name: 'Raising Hands', keywords: ['hooray', 'celebrate', 'praise'], category: 'People' },
  { emoji: '🤝', name: 'Handshake', keywords: ['deal', 'agree', 'meet'], category: 'People' },
  { emoji: '🙏', name: 'Folded Hands', keywords: ['pray', 'please', 'thanks', 'namaste'], category: 'People' },
  { emoji: '💪', name: 'Flexed Biceps', keywords: ['strong', 'muscle', 'workout'], category: 'People' },
  { emoji: '🧠', name: 'Brain', keywords: ['smart', 'think', 'mind'], category: 'People' },
  { emoji: '👀', name: 'Eyes', keywords: ['look', 'see', 'watch'], category: 'People' },
  { emoji: '🤷', name: 'Person Shrugging', keywords: ['dont know', 'whatever', 'ignorant'], category: 'People' },
  { emoji: '🤦', name: 'Person Facepalming', keywords: ['disappointment', 'frustration', 'doh'], category: 'People' },
  { emoji: '🦸', name: 'Superhero', keywords: ['hero', 'marvel', 'dc'], category: 'People' },
  { emoji: '🥷', name: 'Ninja', keywords: ['stealth', 'assassin', 'hide'], category: 'People' },
  
  // Animals
  { emoji: '🐶', name: 'Dog Face', keywords: ['pet', 'puppy', 'animal'], category: 'Animals' },
  { emoji: '🐱', name: 'Cat Face', keywords: ['pet', 'kitten', 'animal'], category: 'Animals' },
  { emoji: '🐭', name: 'Mouse Face', keywords: ['animal', 'rodent', 'cheese'], category: 'Animals' },
  { emoji: '🦊', name: 'Fox', keywords: ['animal', 'wild', 'orange'], category: 'Animals' },
  { emoji: '🐻', name: 'Bear', keywords: ['animal', 'wild', 'brown'], category: 'Animals' },
  { emoji: '🐼', name: 'Panda', keywords: ['animal', 'wild', 'bamboo'], category: 'Animals' },
  { emoji: '🦁', name: 'Lion', keywords: ['animal', 'wild', 'king'], category: 'Animals' },
  { emoji: '🐸', name: 'Frog', keywords: ['animal', 'amphibian', 'ribbit'], category: 'Animals' },
  { emoji: '🐧', name: 'Penguin', keywords: ['animal', 'bird', 'cold'], category: 'Animals' },
  { emoji: '🦄', name: 'Unicorn', keywords: ['animal', 'magic', 'horse'], category: 'Animals' },
  { emoji: '🦋', name: 'Butterfly', keywords: ['insect', 'bug', 'fly'], category: 'Animals' },
  { emoji: '🐢', name: 'Turtle', keywords: ['animal', 'reptile', 'slow'], category: 'Animals' },
  { emoji: '🐍', name: 'Snake', keywords: ['animal', 'reptile', 'slither'], category: 'Animals' },
  { emoji: '🐙', name: 'Octopus', keywords: ['animal', 'ocean', 'sea'], category: 'Animals' },
  { emoji: '🦈', name: 'Shark', keywords: ['animal', 'ocean', 'sea', 'fish'], category: 'Animals' },
  { emoji: '🐉', name: 'Dragon', keywords: ['animal', 'myth', 'fantasy'], category: 'Animals' },

  // Nature
  { emoji: '🌍', name: 'Globe Showing Europe-Africa', keywords: ['earth', 'world', 'planet'], category: 'Nature' },
  { emoji: '🌲', name: 'Evergreen Tree', keywords: ['plant', 'wood', 'forest'], category: 'Nature' },
  { emoji: '🌳', name: 'Deciduous Tree', keywords: ['plant', 'wood', 'forest'], category: 'Nature' },
  { emoji: '🌴', name: 'Palm Tree', keywords: ['plant', 'tropical', 'beach'], category: 'Nature' },
  { emoji: '🌵', name: 'Cactus', keywords: ['plant', 'desert', 'spike'], category: 'Nature' },
  { emoji: '🌷', name: 'Tulip', keywords: ['flower', 'spring', 'plant'], category: 'Nature' },
  { emoji: '🌹', name: 'Rose', keywords: ['flower', 'love', 'romance'], category: 'Nature' },
  { emoji: '🌻', name: 'Sunflower', keywords: ['flower', 'sun', 'plant'], category: 'Nature' },
  { emoji: '🍁', name: 'Maple Leaf', keywords: ['plant', 'leaf', 'autumn', 'fall', 'canada'], category: 'Nature' },
  { emoji: '🌊', name: 'Water Wave', keywords: ['water', 'ocean', 'sea', 'surf'], category: 'Nature' },
  { emoji: '🔥', name: 'Fire', keywords: ['hot', 'flame', 'burn', 'lit'], category: 'Nature' },
  { emoji: '⛰️', name: 'Mountain', keywords: ['nature', 'rock', 'climb'], category: 'Nature' },
  { emoji: '🏔️', name: 'Snow-Capped Mountain', keywords: ['nature', 'snow', 'cold', 'winter'], category: 'Nature' },

  // Food & Drink
  { emoji: '🍔', name: 'Hamburger', keywords: ['food', 'meat', 'fast food', 'beef'], category: 'Food & Drink' },
  { emoji: '🍕', name: 'Pizza', keywords: ['food', 'cheese', 'slice'], category: 'Food & Drink' },
  { emoji: '🌭', name: 'Hot Dog', keywords: ['food', 'meat', 'sausage', 'frankfurter'], category: 'Food & Drink' },
  { emoji: '🥪', name: 'Sandwich', keywords: ['food', 'bread', 'lunch'], category: 'Food & Drink' },
  { emoji: '🍜', name: 'Steaming Bowl', keywords: ['food', 'ramen', 'noodle', 'soup'], category: 'Food & Drink' },
  { emoji: '🍣', name: 'Sushi', keywords: ['food', 'japanese', 'fish', 'rice'], category: 'Food & Drink' },
  { emoji: '🍱', name: 'Bento Box', keywords: ['food', 'japanese', 'lunch'], category: 'Food & Drink' },
  { emoji: '🥟', name: 'Dumpling', keywords: ['food', 'chinese', 'potsticker'], category: 'Food & Drink' },
  { emoji: '🌮', name: 'Taco', keywords: ['food', 'mexican'], category: 'Food & Drink' },
  { emoji: '🍩', name: 'Doughnut', keywords: ['food', 'dessert', 'sweet', 'donut'], category: 'Food & Drink' },
  { emoji: '🍪', name: 'Cookie', keywords: ['food', 'dessert', 'sweet', 'chocolate'], category: 'Food & Drink' },
  { emoji: '☕', name: 'Hot Beverage', keywords: ['drink', 'coffee', 'tea', 'cafe'], category: 'Food & Drink' },
  { emoji: '🫖', name: 'Teapot', keywords: ['drink', 'tea', 'pot'], category: 'Food & Drink' },
  { emoji: '🥤', name: 'Cup with Straw', keywords: ['drink', 'soda', 'juice', 'fast food'], category: 'Food & Drink' },
  { emoji: '🍺', name: 'Beer Mug', keywords: ['drink', 'alcohol', 'pub', 'bar'], category: 'Food & Drink' },
  { emoji: '🍷', name: 'Wine Glass', keywords: ['drink', 'alcohol', 'red'], category: 'Food & Drink' },
  { emoji: '🥑', name: 'Avocado', keywords: ['fruit', 'food', 'guacamole'], category: 'Food & Drink' },
  { emoji: '🍎', name: 'Red Apple', keywords: ['fruit', 'food', 'mac'], category: 'Food & Drink' },
  { emoji: '🍌', name: 'Banana', keywords: ['fruit', 'food', 'monkey'], category: 'Food & Drink' },

  // Travel
  { emoji: '✈️', name: 'Airplane', keywords: ['travel', 'air', 'fly', 'flight', 'plane'], category: 'Travel' },
  { emoji: '🚗', name: 'Automobile', keywords: ['travel', 'car', 'drive', 'vehicle'], category: 'Travel' },
  { emoji: '🚕', name: 'Taxi', keywords: ['travel', 'car', 'drive', 'vehicle', 'cab'], category: 'Travel' },
  { emoji: '🚙', name: 'Sport Utility Vehicle', keywords: ['travel', 'car', 'drive', 'vehicle', 'suv'], category: 'Travel' },
  { emoji: '🏎️', name: 'Racing Car', keywords: ['travel', 'car', 'drive', 'vehicle', 'fast', 'f1'], category: 'Travel' },
  { emoji: '🚲', name: 'Bicycle', keywords: ['travel', 'drive', 'vehicle', 'bike', 'cycle'], category: 'Travel' },
  { emoji: '🚆', name: 'Train', keywords: ['travel', 'drive', 'vehicle', 'rail', 'subway'], category: 'Travel' },
  { emoji: '🚄', name: 'High-Speed Train', keywords: ['travel', 'drive', 'vehicle', 'rail', 'bullet'], category: 'Travel' },
  { emoji: '🚇', name: 'Metro', keywords: ['travel', 'drive', 'vehicle', 'rail', 'subway'], category: 'Travel' },
  { emoji: '🚢', name: 'Ship', keywords: ['travel', 'water', 'boat', 'ocean', 'sea', 'cruise'], category: 'Travel' },
  { emoji: '⛵', name: 'Sailboat', keywords: ['travel', 'water', 'boat', 'ocean', 'sea'], category: 'Travel' },
  { emoji: '🧳', name: 'Luggage', keywords: ['travel', 'bag', 'suitcase', 'pack', 'trip'], category: 'Travel' },
  { emoji: '🗺️', name: 'World Map', keywords: ['travel', 'map', 'earth', 'world', 'globe', 'location'], category: 'Travel' },
  { emoji: '🧭', name: 'Compass', keywords: ['travel', 'map', 'direction', 'north', 'south', 'east', 'west'], category: 'Travel' },
  { emoji: '📍', name: 'Round Pushpin', keywords: ['travel', 'work', 'office', 'pin', 'tack', 'location'], category: 'Travel' },

  // Weather
  { emoji: '☀️', name: 'Sun', keywords: ['sky', 'day', 'weather', 'hot'], category: 'Weather' },
  { emoji: '🌤️', name: 'Sun Behind Small Cloud', keywords: ['sky', 'weather', 'cloudy'], category: 'Weather' },
  { emoji: '⛅', name: 'Sun Behind Cloud', keywords: ['sky', 'weather', 'cloudy'], category: 'Weather' },
  { emoji: '☁️', name: 'Cloud', keywords: ['sky', 'weather', 'rain'], category: 'Weather' },
  { emoji: '🌧️', name: 'Cloud with Rain', keywords: ['sky', 'weather', 'rain'], category: 'Weather' },
  { emoji: '⛈️', name: 'Cloud with Lightning and Rain', keywords: ['sky', 'weather', 'storm'], category: 'Weather' },
  { emoji: '⚡', name: 'High Voltage', keywords: ['weather', 'storm', 'lightning', 'electric'], category: 'Weather' },
  { emoji: '❄️', name: 'Snowflake', keywords: ['weather', 'snow', 'cold', 'ice'], category: 'Weather' },
  { emoji: '☃️', name: 'Snowman', keywords: ['weather', 'snow', 'cold', 'winter'], category: 'Weather' },
  { emoji: '🌈', name: 'Rainbow', keywords: ['sky', 'weather', 'color', 'pride'], category: 'Weather' },

  // Time
  { emoji: '⏰', name: 'Alarm Clock', keywords: ['time', 'clock', 'wake', 'bell'], category: 'Time' },
  { emoji: '⏱️', name: 'Stopwatch', keywords: ['time', 'clock', 'race', 'timer'], category: 'Time' },
  { emoji: '⏳', name: 'Hourglass Not Done', keywords: ['time', 'sand', 'wait'], category: 'Time' },
  { emoji: '🕰️', name: 'Mantelpiece Clock', keywords: ['time', 'clock', 'antique'], category: 'Time' },
  { emoji: '📅', name: 'Calendar', keywords: ['time', 'business', 'office', 'date', 'schedule'], category: 'Time' },
  { emoji: '🗓️', name: 'Spiral Calendar', keywords: ['time', 'business', 'office', 'date', 'schedule'], category: 'Time' },

  // Transport
  { emoji: '🚗', name: 'Automobile', keywords: ['transport', 'car', 'drive', 'vehicle'], category: 'Transport' },
  { emoji: '🚕', name: 'Taxi', keywords: ['transport', 'car', 'drive', 'vehicle', 'cab'], category: 'Transport' },
  { emoji: '🚙', name: 'Sport Utility Vehicle', keywords: ['transport', 'car', 'drive', 'vehicle', 'suv'], category: 'Transport' },
  { emoji: '🚌', name: 'Bus', keywords: ['transport', 'drive', 'vehicle', 'public'], category: 'Transport' },
  { emoji: '🏎️', name: 'Racing Car', keywords: ['transport', 'car', 'drive', 'vehicle', 'fast', 'f1'], category: 'Transport' },
  { emoji: '🚓', name: 'Police Car', keywords: ['transport', 'car', 'drive', 'vehicle', 'cop', 'law'], category: 'Transport' },
  { emoji: '🚑', name: 'Ambulance', keywords: ['transport', 'car', 'drive', 'vehicle', 'medical', 'hospital'], category: 'Transport' },
  { emoji: '🚒', name: 'Fire Engine', keywords: ['transport', 'car', 'drive', 'vehicle', 'fire', 'water'], category: 'Transport' },
  { emoji: '🚚', name: 'Delivery Truck', keywords: ['transport', 'car', 'drive', 'vehicle', 'truck', 'shipping'], category: 'Transport' },
  { emoji: '🚜', name: 'Tractor', keywords: ['transport', 'car', 'drive', 'vehicle', 'farm', 'agriculture'], category: 'Transport' },
  { emoji: '🚲', name: 'Bicycle', keywords: ['transport', 'drive', 'vehicle', 'bike', 'cycle'], category: 'Transport' },
  { emoji: '🛴', name: 'Kick Scooter', keywords: ['transport', 'drive', 'vehicle', 'bike', 'electric'], category: 'Transport' },
  { emoji: '🛵', name: 'Motor Scooter', keywords: ['transport', 'drive', 'vehicle', 'bike', 'motorcycle'], category: 'Transport' },
  { emoji: '🚁', name: 'Helicopter', keywords: ['transport', 'air', 'fly', 'flight', 'chopper'], category: 'Transport' },

  // Sports
  { emoji: '⚽', name: 'Soccer Ball', keywords: ['sports', 'ball', 'football', 'play', 'game'], category: 'Sports' },
  { emoji: '🏀', name: 'Basketball', keywords: ['sports', 'ball', 'play', 'game'], category: 'Sports' },
  { emoji: '🏈', name: 'American Football', keywords: ['sports', 'ball', 'play', 'game'], category: 'Sports' },
  { emoji: '⚾', name: 'Baseball', keywords: ['sports', 'ball', 'play', 'game'], category: 'Sports' },
  { emoji: '🎾', name: 'Tennis', keywords: ['sports', 'ball', 'play', 'game'], category: 'Sports' },
  { emoji: '🏐', name: 'Volleyball', keywords: ['sports', 'ball', 'play', 'game'], category: 'Sports' },
  { emoji: '🏉', name: 'Rugby Football', keywords: ['sports', 'ball', 'play', 'game'], category: 'Sports' },
  { emoji: '🥊', name: 'Boxing Glove', keywords: ['sports', 'fight', 'punch'], category: 'Sports' },
  { emoji: '🏓', name: 'Ping Pong', keywords: ['sports', 'ball', 'play', 'game', 'table tennis'], category: 'Sports' },
  { emoji: '🏸', name: 'Badminton', keywords: ['sports', 'birdie', 'play', 'game'], category: 'Sports' },
  { emoji: '⛳', name: 'Flag in Hole', keywords: ['sports', 'golf', 'play', 'game'], category: 'Sports' },
  { emoji: '🏋️', name: 'Person Lifting Weights', keywords: ['gym', 'workout', 'muscle'], category: 'Sports' },
  { emoji: '🤸', name: 'Person Cartwheeling', keywords: ['gymnastics', 'flip', 'sport'], category: 'Sports' },
  { emoji: '🏃', name: 'Person Running', keywords: ['run', 'jog', 'sprint'], category: 'Sports' },
  { emoji: '🚴', name: 'Person Biking', keywords: ['bike', 'cycle', 'ride'], category: 'Sports' },
  { emoji: '🏊', name: 'Person Swimming', keywords: ['water', 'pool', 'sport'], category: 'Sports' },

  // Games
  { emoji: '🎮', name: 'Video Game', keywords: ['games', 'play', 'controller', 'console'], category: 'Games' },
  { emoji: '🕹️', name: 'Joystick', keywords: ['games', 'play', 'arcade', 'retro'], category: 'Games' },
  { emoji: '🎲', name: 'Game Die', keywords: ['games', 'play', 'dice', 'random', 'luck'], category: 'Games' },
  { emoji: '♟️', name: 'Chess Pawn', keywords: ['games', 'play', 'board', 'strategy'], category: 'Games' },
  { emoji: '🧩', name: 'Puzzle Piece', keywords: ['games', 'play', 'jigsaw', 'solve'], category: 'Games' },
  { emoji: '🎳', name: 'Bowling', keywords: ['games', 'play', 'ball', 'strike'], category: 'Games' },
  { emoji: '🎯', name: 'Bullseye', keywords: ['games', 'play', 'darts', 'target', 'goal'], category: 'Games' },
  { emoji: '🎰', name: 'Slot Machine', keywords: ['games', 'play', 'casino', 'gamble', 'luck'], category: 'Games' },

  // Music
  { emoji: '🎵', name: 'Musical Note', keywords: ['music', 'song', 'sing', 'sound'], category: 'Music' },
  { emoji: '🎶', name: 'Musical Notes', keywords: ['music', 'song', 'sing', 'sound'], category: 'Music' },
  { emoji: '🎤', name: 'Microphone', keywords: ['music', 'song', 'sing', 'sound', 'karaoke'], category: 'Music' },
  { emoji: '🎧', name: 'Headphone', keywords: ['music', 'song', 'sing', 'sound', 'listen'], category: 'Music' },
  { emoji: '🎼', name: 'Musical Score', keywords: ['music', 'song', 'sing', 'sound', 'clef'], category: 'Music' },
  { emoji: '🎸', name: 'Guitar', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'rock'], category: 'Music' },
  { emoji: '🎹', name: 'Musical Keyboard', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'piano'], category: 'Music' },
  { emoji: '🥁', name: 'Drum', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'beat'], category: 'Music' },
  { emoji: '🎷', name: 'Saxophone', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'jazz'], category: 'Music' },
  { emoji: '🎺', name: 'Trumpet', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'brass'], category: 'Music' },
  { emoji: '🎻', name: 'Violin', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'string'], category: 'Music' },
  { emoji: '🪕', name: 'Banjo', keywords: ['music', 'song', 'sing', 'sound', 'instrument', 'string'], category: 'Music' },

  // Movies & Media
  { emoji: '🎬', name: 'Clapper Board', keywords: ['movies & media', 'film', 'movie', 'record', 'action'], category: 'Movies & Media' },
  { emoji: '🎥', name: 'Movie Camera', keywords: ['movies & media', 'film', 'movie', 'record', 'video'], category: 'Movies & Media' },
  { emoji: '🎞️', name: 'Film Frames', keywords: ['movies & media', 'film', 'movie', 'record', 'cinema'], category: 'Movies & Media' },
  { emoji: '📽️', name: 'Film Projector', keywords: ['movies & media', 'film', 'movie', 'record', 'cinema'], category: 'Movies & Media' },
  { emoji: '📺', name: 'Television', keywords: ['movies & media', 'tv', 'show', 'screen'], category: 'Movies & Media' },
  { emoji: '📷', name: 'Camera', keywords: ['movies & media', 'photo', 'picture', 'take'], category: 'Movies & Media' },
  { emoji: '📸', name: 'Camera with Flash', keywords: ['movies & media', 'photo', 'picture', 'take', 'flash'], category: 'Movies & Media' },
  { emoji: '📹', name: 'Video Camera', keywords: ['movies & media', 'film', 'movie', 'record', 'video'], category: 'Movies & Media' },
  { emoji: '📼', name: 'Videocassette', keywords: ['movies & media', 'film', 'movie', 'record', 'video', 'vhs'], category: 'Movies & Media' },
  { emoji: '🎟️', name: 'Admission Tickets', keywords: ['movies & media', 'ticket', 'event', 'show'], category: 'Movies & Media' },

  // Art
  { emoji: '🎨', name: 'Artist Palette', keywords: ['art', 'paint', 'draw', 'color', 'brush'], category: 'Art' },
  { emoji: '🖌️', name: 'Paintbrush', keywords: ['art', 'paint', 'draw', 'color', 'brush'], category: 'Art' },
  { emoji: '🖍️', name: 'Crayon', keywords: ['art', 'paint', 'draw', 'color'], category: 'Art' },
  { emoji: '🖼️', name: 'Framed Picture', keywords: ['art', 'photo', 'painting', 'gallery', 'museum'], category: 'Art' },
  { emoji: '🎭', name: 'Performing Arts', keywords: ['art', 'theater', 'drama', 'mask', 'act'], category: 'Art' },
  { emoji: '🧵', name: 'Thread', keywords: ['art', 'sew', 'needle', 'string', 'spool'], category: 'Art' },
  { emoji: '🧶', name: 'Yarn', keywords: ['art', 'sew', 'knit', 'string', 'ball'], category: 'Art' },

  // Books & Learning
  { emoji: '📚', name: 'Books', keywords: ['books & learning', 'read', 'study', 'school', 'library'], category: 'Books & Learning' },
  { emoji: '📖', name: 'Open Book', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'page'], category: 'Books & Learning' },
  { emoji: '📗', name: 'Green Book', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'green'], category: 'Books & Learning' },
  { emoji: '📘', name: 'Blue Book', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'blue'], category: 'Books & Learning' },
  { emoji: '📙', name: 'Orange Book', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'orange'], category: 'Books & Learning' },
  { emoji: '📕', name: 'Closed Book', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'red'], category: 'Books & Learning' },
  { emoji: '📓', name: 'Notebook', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'note'], category: 'Books & Learning' },
  { emoji: '📔', name: 'Notebook with Decorative Cover', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'note'], category: 'Books & Learning' },
  { emoji: '📒', name: 'Ledger', keywords: ['books & learning', 'read', 'study', 'school', 'library', 'note'], category: 'Books & Learning' },
  { emoji: '🎓', name: 'Graduation Cap', keywords: ['books & learning', 'win', 'prize', 'champion', 'school', 'university'], category: 'Books & Learning' },
  { emoji: '🏫', name: 'School', keywords: ['books & learning', 'building', 'education', 'learn'], category: 'Books & Learning' },
  { emoji: '✏️', name: 'Pencil', keywords: ['books & learning', 'write', 'draw', 'school'], category: 'Books & Learning' },

  // Work
  { emoji: '💼', name: 'Briefcase', keywords: ['work', 'business', 'office', 'job'], category: 'Work' },
  { emoji: '🏢', name: 'Office Building', keywords: ['work', 'business', 'office', 'building', 'city'], category: 'Work' },
  { emoji: '📁', name: 'File Folder', keywords: ['work', 'business', 'office', 'document'], category: 'Work' },
  { emoji: '📂', name: 'Open File Folder', keywords: ['work', 'business', 'office', 'document'], category: 'Work' },
  { emoji: '🗂️', name: 'Card Index Dividers', keywords: ['work', 'business', 'office', 'document', 'organize'], category: 'Work' },
  { emoji: '🗃️', name: 'Card File Box', keywords: ['work', 'business', 'office', 'document', 'organize'], category: 'Work' },
  { emoji: '🗄️', name: 'File Cabinet', keywords: ['work', 'business', 'office', 'document', 'organize'], category: 'Work' },
  { emoji: '📅', name: 'Calendar', keywords: ['work', 'business', 'office', 'date', 'schedule'], category: 'Work' },
  { emoji: '🗓️', name: 'Spiral Calendar', keywords: ['work', 'business', 'office', 'date', 'schedule'], category: 'Work' },
  { emoji: '🗒️', name: 'Spiral Notepad', keywords: ['work', 'business', 'office', 'note', 'document'], category: 'Work' },
  { emoji: '📋', name: 'Clipboard', keywords: ['work', 'business', 'office', 'document', 'note'], category: 'Work' },
  { emoji: '📌', name: 'Pushpin', keywords: ['work', 'business', 'office', 'pin', 'tack'], category: 'Work' },
  { emoji: '📍', name: 'Round Pushpin', keywords: ['work', 'business', 'office', 'pin', 'tack', 'location'], category: 'Work' },

  // Business
  { emoji: '📈', name: 'Chart Increasing', keywords: ['business', 'finance', 'graph', 'growth', 'up'], category: 'Business' },
  { emoji: '📉', name: 'Chart Decreasing', keywords: ['business', 'finance', 'graph', 'down'], category: 'Business' },
  { emoji: '📊', name: 'Bar Chart', keywords: ['business', 'finance', 'graph', 'stats'], category: 'Business' },
  { emoji: '🤝', name: 'Handshake', keywords: ['business', 'deal', 'agree', 'meet'], category: 'Business' },
  { emoji: '📣', name: 'Megaphone', keywords: ['business', 'announce', 'shout', 'loud'], category: 'Business' },
  { emoji: '📢', name: 'Loudspeaker', keywords: ['business', 'announce', 'shout', 'loud', 'public'], category: 'Business' },
  { emoji: '📬', name: 'Open Mailbox with Raised Flag', keywords: ['business', 'mail', 'post', 'delivery'], category: 'Business' },

  // Finance
  { emoji: '💰', name: 'Money Bag', keywords: ['finance', 'money', 'cash', 'wealth'], category: 'Finance' },
  { emoji: '💸', name: 'Money with Wings', keywords: ['finance', 'money', 'cash'], category: 'Finance' },
  { emoji: '💵', name: 'Dollar Banknote', keywords: ['finance', 'money', 'cash', 'usd'], category: 'Finance' },
  { emoji: '💶', name: 'Euro Banknote', keywords: ['finance', 'money', 'cash', 'eur'], category: 'Finance' },
  { emoji: '💷', name: 'Pound Banknote', keywords: ['finance', 'money', 'cash', 'gbp'], category: 'Finance' },
  { emoji: '💴', name: 'Yen Banknote', keywords: ['finance', 'money', 'cash', 'jpy'], category: 'Finance' },
  { emoji: '💳', name: 'Credit Card', keywords: ['finance', 'money', 'pay', 'bank'], category: 'Finance' },
  { emoji: '🏦', name: 'Bank', keywords: ['finance', 'money', 'building', 'save'], category: 'Finance' },
  { emoji: '🪙', name: 'Coin', keywords: ['finance', 'money', 'gold', 'silver'], category: 'Finance' },

  // Technology
  { emoji: '💻', name: 'Laptop', keywords: ['tech', 'computer', 'pc', 'mac'], category: 'Technology' },
  { emoji: '🖥️', name: 'Desktop Computer', keywords: ['tech', 'computer', 'pc', 'mac'], category: 'Technology' },
  { emoji: '⌨️', name: 'Keyboard', keywords: ['tech', 'type', 'input'], category: 'Technology' },
  { emoji: '🖱️', name: 'Computer Mouse', keywords: ['tech', 'click', 'input'], category: 'Technology' },
  { emoji: '🖨️', name: 'Printer', keywords: ['tech', 'paper', 'ink'], category: 'Technology' },
  { emoji: '📱', name: 'Mobile Phone', keywords: ['tech', 'cell', 'smartphone', 'iphone'], category: 'Technology' },
  { emoji: '⌚', name: 'Watch', keywords: ['tech', 'clock', 'wearable', 'apple watch'], category: 'Technology' },
  { emoji: '📡', name: 'Satellite Antenna', keywords: ['tech', 'space', 'communication', 'dish'], category: 'Technology' },
  { emoji: '🔌', name: 'Electric Plug', keywords: ['tech', 'power', 'energy', 'cable'], category: 'Technology' },
  { emoji: '💾', name: 'Floppy Disk', keywords: ['tech', 'storage', 'save'], category: 'Technology' },
  { emoji: '💿', name: 'Optical Disk', keywords: ['tech', 'storage', 'cd', 'dvd'], category: 'Technology' },
  { emoji: '📀', name: 'DVD', keywords: ['tech', 'storage', 'cd', 'dvd'], category: 'Technology' },
  { emoji: '🔋', name: 'Battery', keywords: ['tech', 'power', 'energy'], category: 'Technology' },
  { emoji: '🔦', name: 'Flashlight', keywords: ['tech', 'light', 'dark'], category: 'Technology' },

  // Programming
  { emoji: '👨‍💻', name: 'Man Technologist', keywords: ['programming', 'coder', 'developer', 'hacker', 'software', 'engineer'], category: 'Programming' },
  { emoji: '👩‍💻', name: 'Woman Technologist', keywords: ['programming', 'coder', 'developer', 'hacker', 'software', 'engineer'], category: 'Programming' },
  { emoji: '🤖', name: 'Robot', keywords: ['programming', 'bot', 'ai', 'tech'], category: 'Programming' },
  { emoji: '🦾', name: 'Mechanical Arm', keywords: ['programming', 'robot', 'prosthetic', 'cyborg'], category: 'Programming' },
  { emoji: '🧬', name: 'DNA', keywords: ['programming', 'biology', 'genetics'], category: 'Programming' },
  { emoji: '🔬', name: 'Microscope', keywords: ['programming', 'biology', 'lab', 'magnify'], category: 'Programming' },
  { emoji: '🔭', name: 'Telescope', keywords: ['programming', 'space', 'stars', 'astronomy'], category: 'Programming' },
  { emoji: '📟', name: 'Pager', keywords: ['programming', 'message', 'beep'], category: 'Programming' },
  { emoji: '📠', name: 'Fax Machine', keywords: ['programming', 'document', 'send'], category: 'Programming' },
  { emoji: '📜', name: 'Scroll', keywords: ['programming', 'paper', 'document', 'ancient'], category: 'Programming' },
  { emoji: '🧾', name: 'Receipt', keywords: ['programming', 'paper', 'document', 'buy'], category: 'Programming' },
  { emoji: '🏗️', name: 'Building Construction', keywords: ['programming', 'build', 'crane', 'work', 'infrastructure'], category: 'Programming' },
  { emoji: '🕸️', name: 'Spider Web', keywords: ['programming', 'insect', 'bug', 'spider', 'internet'], category: 'Programming' },
  { emoji: '🌐', name: 'Globe with Meridians', keywords: ['programming', 'earth', 'world', 'planet', 'internet'], category: 'Programming' },
  { emoji: '🗃️', name: 'Card File Box', keywords: ['programming', 'work', 'office', 'document', 'organize', 'database'], category: 'Programming' },

  // AI
  { emoji: '🤖', name: 'Robot', keywords: ['ai', 'bot', 'tech', 'machine learning', 'artificial intelligence'], category: 'AI' },
  { emoji: '🧠', name: 'Brain', keywords: ['ai', 'smart', 'think', 'mind', 'neural network', 'deep learning'], category: 'AI' },
  { emoji: '📊', name: 'Bar Chart', keywords: ['ai', 'finance', 'graph', 'stats', 'data'], category: 'AI' },
  { emoji: '📈', name: 'Chart Increasing', keywords: ['ai', 'finance', 'graph', 'growth', 'up', 'data'], category: 'AI' },
  { emoji: '📉', name: 'Chart Decreasing', keywords: ['ai', 'finance', 'graph', 'down', 'data'], category: 'AI' },
  { emoji: '🗄️', name: 'File Cabinet', keywords: ['ai', 'work', 'office', 'document', 'organize', 'database'], category: 'AI' },
  { emoji: '💾', name: 'Floppy Disk', keywords: ['ai', 'storage', 'save', 'data'], category: 'AI' },
  { emoji: '🔍', name: 'Magnifying Glass Pointed Left', keywords: ['ai', 'search', 'find', 'zoom', 'data'], category: 'AI' },
  { emoji: '🛰️', name: 'Satellite', keywords: ['ai', 'space', 'communication', 'orbit', 'science', 'data'], category: 'AI' },
  { emoji: '📡', name: 'Satellite Antenna', keywords: ['ai', 'space', 'communication', 'dish', 'data'], category: 'AI' },
  { emoji: '🧪', name: 'Test Tube', keywords: ['ai', 'chemistry', 'lab', 'experiment', 'data'], category: 'AI' },
  { emoji: '⚗️', name: 'Alembic', keywords: ['ai', 'chemistry', 'lab', 'experiment', 'data'], category: 'AI' },
  { emoji: '🔬', name: 'Microscope', keywords: ['ai', 'biology', 'lab', 'magnify', 'data'], category: 'AI' },
  { emoji: '🧮', name: 'Abacus', keywords: ['ai', 'math', 'calculate', 'count', 'school', 'data'], category: 'AI' },

  // Linux / DevOps
  { emoji: '🐧', name: 'Penguin', keywords: ['linux / devops', 'animal', 'bird', 'cold', 'linux', 'tux'], category: 'Linux / DevOps' },
  { emoji: '☁️', name: 'Cloud', keywords: ['linux / devops', 'sky', 'weather', 'rain', 'cloud', 'aws', 'azure', 'gcp'], category: 'Linux / DevOps' },
  { emoji: '🌩️', name: 'Cloud with Lightning', keywords: ['linux / devops', 'sky', 'weather', 'storm', 'cloud', 'aws', 'azure', 'gcp'], category: 'Linux / DevOps' },
  { emoji: '🔥', name: 'Fire', keywords: ['linux / devops', 'hot', 'flame', 'burn', 'lit', 'incident', 'outage'], category: 'Linux / DevOps' },
  { emoji: '🐳', name: 'Spouting Whale', keywords: ['linux / devops', 'animal', 'ocean', 'sea', 'mammal', 'docker', 'container'], category: 'Linux / DevOps' },
  { emoji: '📦', name: 'Package', keywords: ['linux / devops', 'mail', 'box', 'shipping', 'delivery', 'container', 'deploy'], category: 'Linux / DevOps' },
  { emoji: '🚢', name: 'Ship', keywords: ['linux / devops', 'transport', 'water', 'boat', 'ocean', 'docker', 'kubernetes'], category: 'Linux / DevOps' },
  { emoji: '🏗️', name: 'Building Construction', keywords: ['linux / devops', 'build', 'crane', 'work', 'infrastructure'], category: 'Linux / DevOps' },
  { emoji: '⚡', name: 'High Voltage', keywords: ['linux / devops', 'weather', 'storm', 'lightning', 'electric', 'fast', 'performance'], category: 'Linux / DevOps' },
  { emoji: '🛡️', name: 'Shield', keywords: ['linux / devops', 'security', 'protect', 'defend', 'firewall'], category: 'Linux / DevOps' },
  { emoji: '🔐', name: 'Locked with Key', keywords: ['linux / devops', 'lock', 'padlock', 'password', 'key', 'security'], category: 'Linux / DevOps' },
  { emoji: '🔑', name: 'Key', keywords: ['linux / devops', 'lock', 'door', 'password', 'security'], category: 'Linux / DevOps' },
  { emoji: '🗝️', name: 'Old Key', keywords: ['linux / devops', 'lock', 'door', 'password', 'antique', 'security'], category: 'Linux / DevOps' },

  // Science
  { emoji: '🔬', name: 'Microscope', keywords: ['science', 'biology', 'lab', 'magnify'], category: 'Science' },
  { emoji: '🔭', name: 'Telescope', keywords: ['science', 'space', 'stars', 'astronomy'], category: 'Science' },
  { emoji: '🧪', name: 'Test Tube', keywords: ['science', 'chemistry', 'lab', 'experiment'], category: 'Science' },
  { emoji: '⚗️', name: 'Alembic', keywords: ['science', 'chemistry', 'lab', 'experiment'], category: 'Science' },
  { emoji: '🧬', name: 'DNA', keywords: ['science', 'biology', 'genetics'], category: 'Science' },
  { emoji: '🧫', name: 'Petri Dish', keywords: ['science', 'biology', 'lab', 'bacteria'], category: 'Science' },
  { emoji: '🌡️', name: 'Thermometer', keywords: ['science', 'weather', 'hot', 'cold', 'temperature'], category: 'Science' },
  { emoji: '🛰️', name: 'Satellite', keywords: ['science', 'space', 'communication', 'orbit'], category: 'Science' },
  { emoji: '⚖️', name: 'Balance Scale', keywords: ['science', 'law', 'justice', 'weight', 'mass'], category: 'Science' },
  { emoji: '🧲', name: 'Magnet', keywords: ['science', 'tools', 'attract', 'metal', 'physics'], category: 'Science' },

  // Medicine
  { emoji: '💊', name: 'Pill', keywords: ['medicine', 'drug', 'doctor', 'sick'], category: 'Medicine' },
  { emoji: '🩺', name: 'Stethoscope', keywords: ['medicine', 'doctor', 'heart', 'listen'], category: 'Medicine' },
  { emoji: '🩹', name: 'Adhesive Bandage', keywords: ['medicine', 'heal', 'hurt', 'bandaid'], category: 'Medicine' },
  { emoji: '💉', name: 'Syringe', keywords: ['medicine', 'doctor', 'shot', 'needle'], category: 'Medicine' },
  { emoji: '🩸', name: 'Drop of Blood', keywords: ['medicine', 'red', 'donate'], category: 'Medicine' },
  { emoji: '🏥', name: 'Hospital', keywords: ['medicine', 'building', 'doctor', 'sick', 'emergency'], category: 'Medicine' },
  { emoji: '🚑', name: 'Ambulance', keywords: ['medicine', 'transport', 'car', 'drive', 'vehicle', 'emergency'], category: 'Medicine' },
  { emoji: '⚕️', name: 'Medical Symbol', keywords: ['medicine', 'doctor', 'sick', 'health'], category: 'Medicine' },

  // Tools
  { emoji: '🛠️', name: 'Hammer and Wrench', keywords: ['tools', 'fix', 'repair', 'build'], category: 'Tools' },
  { emoji: '🔨', name: 'Hammer', keywords: ['tools', 'fix', 'repair', 'build'], category: 'Tools' },
  { emoji: '🔧', name: 'Wrench', keywords: ['tools', 'fix', 'repair', 'spanner'], category: 'Tools' },
  { emoji: '🪛', name: 'Screwdriver', keywords: ['tools', 'fix', 'repair', 'screw'], category: 'Tools' },
  { emoji: '🔩', name: 'Nut and Bolt', keywords: ['tools', 'fix', 'repair', 'screw'], category: 'Tools' },
  { emoji: '⚙️', name: 'Gear', keywords: ['tools', 'cog', 'settings'], category: 'Tools' },
  { emoji: '🪚', name: 'Carpentry Saw', keywords: ['tools', 'cut', 'wood'], category: 'Tools' },
  { emoji: '🪓', name: 'Axe', keywords: ['tools', 'chop', 'wood'], category: 'Tools' },
  { emoji: '⛏️', name: 'Pick', keywords: ['tools', 'mine', 'dig'], category: 'Tools' },
  { emoji: '⚒️', name: 'Hammer and Pick', keywords: ['tools', 'mine', 'dig', 'build'], category: 'Tools' },
  { emoji: '🪜', name: 'Ladder', keywords: ['tools', 'climb', 'step'], category: 'Tools' },
  { emoji: '🪝', name: 'Hook', keywords: ['tools', 'catch', 'metal'], category: 'Tools' },
  { emoji: '⛓️', name: 'Chains', keywords: ['tools', 'link', 'metal'], category: 'Tools' },

  // Security
  { emoji: '🔒', name: 'Locked', keywords: ['security', 'lock', 'padlock', 'password'], category: 'Security' },
  { emoji: '🔓', name: 'Unlocked', keywords: ['security', 'unlock', 'padlock', 'password'], category: 'Security' },
  { emoji: '🔐', name: 'Locked with Key', keywords: ['security', 'lock', 'padlock', 'password', 'key'], category: 'Security' },
  { emoji: '🔏', name: 'Locked with Pen', keywords: ['security', 'lock', 'padlock', 'password', 'key'], category: 'Security' },
  { emoji: '🔑', name: 'Key', keywords: ['security', 'lock', 'door', 'password'], category: 'Security' },
  { emoji: '🗝️', name: 'Old Key', keywords: ['security', 'lock', 'door', 'password', 'antique'], category: 'Security' },
  { emoji: '🛡️', name: 'Shield', keywords: ['security', 'protect', 'defend', 'firewall'], category: 'Security' },
  { emoji: '⚔️', name: 'Crossed Swords', keywords: ['security', 'fight', 'battle', 'weapon'], category: 'Security' },

  // Communication
  { emoji: '💬', name: 'Speech Balloon', keywords: ['communication', 'talk', 'speak', 'chat', 'message'], category: 'Communication' },
  { emoji: '🗨️', name: 'Left Speech Bubble', keywords: ['communication', 'talk', 'speak', 'chat', 'message'], category: 'Communication' },
  { emoji: '🗯️', name: 'Right Anger Bubble', keywords: ['communication', 'talk', 'speak', 'chat', 'message', 'mad'], category: 'Communication' },
  { emoji: '💭', name: 'Thought Balloon', keywords: ['communication', 'think', 'dream', 'cloud'], category: 'Communication' },
  { emoji: '📧', name: 'E-Mail', keywords: ['communication', 'mail', 'letter', 'email'], category: 'Communication' },
  { emoji: '✉️', name: 'Envelope', keywords: ['communication', 'mail', 'letter', 'email'], category: 'Communication' },
  { emoji: '📨', name: 'Incoming Envelope', keywords: ['communication', 'mail', 'letter', 'email', 'receive'], category: 'Communication' },
  { emoji: '📩', name: 'Envelope with Arrow', keywords: ['communication', 'mail', 'letter', 'email', 'send'], category: 'Communication' },
  { emoji: '📤', name: 'Outbox Tray', keywords: ['communication', 'mail', 'letter', 'email', 'send'], category: 'Communication' },
  { emoji: '📥', name: 'Inbox Tray', keywords: ['communication', 'mail', 'letter', 'email', 'receive'], category: 'Communication' },
  { emoji: '📦', name: 'Package', keywords: ['communication', 'mail', 'box', 'shipping', 'delivery'], category: 'Communication' },
  { emoji: '📫', name: 'Closed Mailbox with Raised Flag', keywords: ['communication', 'mail', 'post', 'delivery'], category: 'Communication' },
  { emoji: '📪', name: 'Closed Mailbox with Lowered Flag', keywords: ['communication', 'mail', 'post', 'delivery'], category: 'Communication' },
  { emoji: '📬', name: 'Open Mailbox with Raised Flag', keywords: ['communication', 'mail', 'post', 'delivery'], category: 'Communication' },
  { emoji: '📭', name: 'Open Mailbox with Lowered Flag', keywords: ['communication', 'mail', 'post', 'delivery'], category: 'Communication' },
  { emoji: '📮', name: 'Postbox', keywords: ['communication', 'mail', 'post', 'delivery', 'letter'], category: 'Communication' },
  { emoji: '📞', name: 'Telephone Receiver', keywords: ['communication', 'phone', 'call', 'tech'], category: 'Communication' },
  { emoji: '☎️', name: 'Telephone', keywords: ['communication', 'phone', 'call', 'tech'], category: 'Communication' },
  { emoji: '📱', name: 'Mobile Phone', keywords: ['communication', 'cell', 'smartphone', 'iphone', 'tech'], category: 'Communication' },
  { emoji: '📲', name: 'Mobile Phone with Arrow', keywords: ['communication', 'cell', 'call', 'receive', 'tech'], category: 'Communication' },
  { emoji: '📢', name: 'Loudspeaker', keywords: ['communication', 'announce', 'shout', 'loud', 'public'], category: 'Communication' },
  { emoji: '📣', name: 'Megaphone', keywords: ['communication', 'announce', 'shout', 'loud'], category: 'Communication' },

  // Shopping
  { emoji: '🛒', name: 'Shopping Cart', keywords: ['shopping', 'buy', 'purchase', 'store', 'trolley'], category: 'Shopping' },
  { emoji: '🛍️', name: 'Shopping Bags', keywords: ['shopping', 'buy', 'purchase', 'store'], category: 'Shopping' },
  { emoji: '🎁', name: 'Wrapped Gift', keywords: ['shopping', 'present', 'birthday', 'christmas'], category: 'Shopping' },
  { emoji: '🎈', name: 'Balloon', keywords: ['shopping', 'party', 'celebrate', 'birthday'], category: 'Shopping' },
  { emoji: '🎀', name: 'Ribbon', keywords: ['shopping', 'party', 'celebrate', 'gift'], category: 'Shopping' },
  { emoji: '🏷️', name: 'Label', keywords: ['shopping', 'tag', 'price', 'sale'], category: 'Shopping' },
  { emoji: '🧾', name: 'Receipt', keywords: ['shopping', 'paper', 'document', 'buy'], category: 'Shopping' },

  // Home
  { emoji: '🏠', name: 'House', keywords: ['home', 'building', 'residence', 'family'], category: 'Home' },
  { emoji: '🏡', name: 'House with Garden', keywords: ['home', 'building', 'residence', 'family', 'tree'], category: 'Home' },
  { emoji: '🚪', name: 'Door', keywords: ['home', 'entry', 'exit'], category: 'Home' },
  { emoji: '🪑', name: 'Chair', keywords: ['home', 'seat', 'sit', 'furniture'], category: 'Home' },
  { emoji: '🛋️', name: 'Couch and Lamp', keywords: ['home', 'seat', 'sit', 'furniture', 'living room'], category: 'Home' },
  { emoji: '🛏️', name: 'Bed', keywords: ['home', 'sleep', 'rest', 'furniture', 'bedroom'], category: 'Home' },
  { emoji: '🪞', name: 'Mirror', keywords: ['home', 'reflection', 'glass', 'look'], category: 'Home' },
  { emoji: '🪟', name: 'Window', keywords: ['home', 'glass', 'view', 'look'], category: 'Home' },
  { emoji: '🚽', name: 'Toilet', keywords: ['home', 'bathroom', 'washroom', 'restroom'], category: 'Home' },
  { emoji: '🚿', name: 'Shower', keywords: ['home', 'bathroom', 'wash', 'clean'], category: 'Home' },
  { emoji: '🛁', name: 'Bathtub', keywords: ['home', 'bathroom', 'wash', 'clean'], category: 'Home' },
  { emoji: '🧼', name: 'Soap', keywords: ['home', 'bathroom', 'wash', 'clean'], category: 'Home' },
  { emoji: '🧽', name: 'Sponge', keywords: ['home', 'clean', 'wash'], category: 'Home' },
  { emoji: '🧹', name: 'Broom', keywords: ['home', 'clean', 'sweep', 'witch'], category: 'Home' },
  { emoji: '🧺', name: 'Basket', keywords: ['home', 'laundry', 'picnic'], category: 'Home' },

  // Space
  { emoji: '🚀', name: 'Rocket', keywords: ['space', 'sky', 'ship', 'launch'], category: 'Space' },
  { emoji: '🛸', name: 'Flying Saucer', keywords: ['space', 'ufo', 'alien', 'ship'], category: 'Space' },
  { emoji: '🛰️', name: 'Satellite', keywords: ['space', 'communication', 'orbit', 'science'], category: 'Space' },
  { emoji: '🌌', name: 'Milky Way', keywords: ['space', 'sky', 'stars', 'galaxy'], category: 'Space' },
  { emoji: '🪐', name: 'Ringed Planet', keywords: ['space', 'sky', 'planet', 'saturn'], category: 'Space' },
  { emoji: '🌎', name: 'Globe Showing Americas', keywords: ['space', 'earth', 'world', 'planet'], category: 'Space' },
  { emoji: '🌍', name: 'Globe Showing Europe-Africa', keywords: ['space', 'earth', 'world', 'planet'], category: 'Space' },
  { emoji: '🌏', name: 'Globe Showing Asia-Australia', keywords: ['space', 'earth', 'world', 'planet'], category: 'Space' },
  { emoji: '🌕', name: 'Full Moon', keywords: ['space', 'sky', 'night'], category: 'Space' },
  { emoji: '🌙', name: 'Crescent Moon', keywords: ['space', 'sky', 'night'], category: 'Space' },
  { emoji: '⭐', name: 'Star', keywords: ['space', 'sky', 'night'], category: 'Space' },
  { emoji: '🌟', name: 'Glowing Star', keywords: ['space', 'sky', 'night', 'shine'], category: 'Space' },
  { emoji: '🌠', name: 'Shooting Star', keywords: ['space', 'sky', 'night', 'wish'], category: 'Space' },
  { emoji: '☄️', name: 'Comet', keywords: ['space', 'sky', 'star'], category: 'Space' },
  { emoji: '👨‍🚀', name: 'Man Astronaut', keywords: ['space', 'explore', 'moon'], category: 'Space' },
  { emoji: '👩‍🚀', name: 'Woman Astronaut', keywords: ['space', 'explore', 'moon'], category: 'Space' },

  // Symbols
  { emoji: '✅', name: 'Check Mark Button', keywords: ['symbols', 'yes', 'ok', 'tick', 'approve'], category: 'Symbols' },
  { emoji: '☑️', name: 'Check Box with Check', keywords: ['symbols', 'yes', 'ok', 'tick', 'approve', 'box'], category: 'Symbols' },
  { emoji: '✔️', name: 'Check Mark', keywords: ['symbols', 'yes', 'ok', 'tick', 'approve'], category: 'Symbols' },
  { emoji: '❌', name: 'Cross Mark', keywords: ['symbols', 'no', 'cancel', 'wrong', 'x'], category: 'Symbols' },
  { emoji: '❎', name: 'Cross Mark Button', keywords: ['symbols', 'no', 'cancel', 'wrong', 'x', 'box'], category: 'Symbols' },
  { emoji: '➕', name: 'Plus', keywords: ['symbols', 'add', 'math', 'positive'], category: 'Symbols' },
  { emoji: '➖', name: 'Minus', keywords: ['symbols', 'subtract', 'math', 'negative'], category: 'Symbols' },
  { emoji: '➗', name: 'Divide', keywords: ['symbols', 'math', 'split'], category: 'Symbols' },
  { emoji: '✖️', name: 'Multiply', keywords: ['symbols', 'math', 'times', 'x'], category: 'Symbols' },
  { emoji: '❓', name: 'Question Mark', keywords: ['symbols', 'ask', 'confused', 'help'], category: 'Symbols' },
  { emoji: '❕', name: 'White Exclamation Mark', keywords: ['symbols', 'surprise', 'warning', 'wow'], category: 'Symbols' },
  { emoji: '❗', name: 'Exclamation Mark', keywords: ['symbols', 'surprise', 'warning', 'wow'], category: 'Symbols' },
  { emoji: '💯', name: 'Hundred Points', keywords: ['symbols', 'score', 'perfect', '100'], category: 'Symbols' },
  { emoji: '⭕', name: 'Hollow Red Circle', keywords: ['symbols', 'circle', 'round', 'o'], category: 'Symbols' },
  { emoji: '🛑', name: 'Stop Sign', keywords: ['symbols', 'stop', 'warning', 'danger'], category: 'Symbols' },
  { emoji: '⛔', name: 'No Entry', keywords: ['symbols', 'stop', 'warning', 'danger', 'block'], category: 'Symbols' },
  { emoji: '🚷', name: 'No Pedestrians', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'walk'], category: 'Symbols' },
  { emoji: '🚯', name: 'No Littering', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'trash'], category: 'Symbols' },
  { emoji: '🚳', name: 'No Bicycles', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'bike'], category: 'Symbols' },
  { emoji: '🚱', name: 'Non-Potable Water', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'drink'], category: 'Symbols' },
  { emoji: '🔞', name: 'No One Under Eighteen', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'age'], category: 'Symbols' },
  { emoji: '📵', name: 'No Mobile Phones', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'phone'], category: 'Symbols' },
  { emoji: '🚭', name: 'No Smoking', keywords: ['symbols', 'stop', 'warning', 'danger', 'block', 'smoke'], category: 'Symbols' },
  { emoji: '🔄', name: 'Counterclockwise Arrows Button', keywords: ['symbols', 'refresh', 'reload', 'sync'], category: 'Symbols' },
  { emoji: '♻️', name: 'Recycling Symbol', keywords: ['symbols', 'recycle', 'green', 'environment'], category: 'Symbols' },

  // Awards
  { emoji: '🏆', name: 'Trophy', keywords: ['awards', 'win', 'prize', 'champion'], category: 'Awards' },
  { emoji: '🏅', name: 'Sports Medal', keywords: ['awards', 'win', 'prize', 'champion', 'gold'], category: 'Awards' },
  { emoji: '🥇', name: '1st Place Medal', keywords: ['awards', 'win', 'prize', 'champion', 'gold'], category: 'Awards' },
  { emoji: '🥈', name: '2nd Place Medal', keywords: ['awards', 'win', 'prize', 'champion', 'silver'], category: 'Awards' },
  { emoji: '🥉', name: '3rd Place Medal', keywords: ['awards', 'win', 'prize', 'champion', 'bronze'], category: 'Awards' },
  { emoji: '🎖️', name: 'Military Medal', keywords: ['awards', 'win', 'prize', 'champion', 'army'], category: 'Awards' },
  { emoji: '🏵️', name: 'Rosette', keywords: ['awards', 'win', 'prize', 'champion', 'flower'], category: 'Awards' },
  { emoji: '🎗️', name: 'Reminder Ribbon', keywords: ['awards', 'win', 'prize', 'champion', 'ribbon'], category: 'Awards' },
  { emoji: '👑', name: 'Crown', keywords: ['awards', 'win', 'prize', 'champion', 'king', 'queen'], category: 'Awards' },
  { emoji: '🌟', name: 'Glowing Star', keywords: ['awards', 'win', 'prize', 'champion', 'shine'], category: 'Awards' },
  { emoji: '✨', name: 'Sparkles', keywords: ['awards', 'win', 'prize', 'champion', 'shine', 'magic'], category: 'Awards' },

  // Misc
  { emoji: '✨', name: 'Sparkles', keywords: ['misc', 'shine', 'magic', 'clean', 'new'], category: 'Misc' },
  { emoji: '💎', name: 'Gem Stone', keywords: ['misc', 'jewel', 'diamond', 'rich'], category: 'Misc' },
  { emoji: '🔮', name: 'Crystal Ball', keywords: ['misc', 'magic', 'fortune', 'future'], category: 'Misc' },
  { emoji: '🧿', name: 'Nazar Amulet', keywords: ['misc', 'evil eye', 'charm', 'protect'], category: 'Misc' },
  { emoji: '🪄', name: 'Magic Wand', keywords: ['misc', 'magic', 'witch', 'wizard'], category: 'Misc' },
  { emoji: '🎈', name: 'Balloon', keywords: ['misc', 'party', 'celebrate', 'birthday'], category: 'Misc' },
  { emoji: '🎉', name: 'Party Popper', keywords: ['misc', 'party', 'celebrate', 'birthday'], category: 'Misc' },
  { emoji: '🎊', name: 'Confetti Ball', keywords: ['misc', 'party', 'celebrate', 'birthday'], category: 'Misc' },
  { emoji: '🧨', name: 'Piñata', keywords: ['misc', 'party', 'celebrate', 'mexico'], category: 'Misc' },
  { emoji: '🪅', name: 'Piñata', keywords: ['misc', 'party', 'celebrate', 'mexico'], category: 'Misc' },
  { emoji: '🧸', name: 'Teddy Bear', keywords: ['misc', 'toy', 'play', 'stuffed animal'], category: 'Misc' },
  { emoji: '🪆', name: 'Nesting Dolls', keywords: ['misc', 'toy', 'play', 'matryoshka', 'russia'], category: 'Misc' },
  { emoji: '🪩', name: 'Mirror Ball', keywords: ['misc', 'party', 'dance', 'disco'], category: 'Misc' },
  { emoji: '🗿', name: 'Moai', keywords: ['misc', 'stone', 'statue', 'easter island'], category: 'Misc' },
  { emoji: '🗽', name: 'Statue of Liberty', keywords: ['misc', 'statue', 'new york', 'usa'], category: 'Misc' },
  { emoji: '🗼', name: 'Tokyo Tower', keywords: ['misc', 'tower', 'japan', 'tokyo'], category: 'Misc' },
  { emoji: '🏰', name: 'Castle', keywords: ['misc', 'building', 'fortress', 'king', 'queen'], category: 'Misc' },
];
