import type { KeyboardLayout } from './model';

export const standard: KeyboardLayout = {
  id: 'standard',
  name: 'Standard',
  type: 'standard',
  rows: [
    // Row 1: Numbers
    [
      { id: '`', label: '`', ruId: 'ё', ruLabel: 'Ё', finger: 'left-pinky' },
      { id: '1', label: '1', finger: 'left-pinky' },
      { id: '2', label: '2', finger: 'left-ring' },
      { id: '3', label: '3', finger: 'left-middle' },
      { id: '4', label: '4', finger: 'left-index' },
      { id: '5', label: '5', finger: 'left-index' },
      { id: '6', label: '6', finger: 'right-index' },
      { id: '7', label: '7', finger: 'right-index' },
      { id: '8', label: '8', finger: 'right-middle' },
      { id: '9', label: '9', finger: 'right-ring' },
      { id: '0', label: '0', finger: 'right-pinky' },
      { id: '-', label: '-', finger: 'right-pinky' },
      { id: '=', label: '=', finger: 'right-pinky' },
      { id: 'Backspace', label: 'Backspace', finger: 'right-pinky', width: 2 },
    ],
    // Row 2: QWERTY
    [
      { id: 'Tab', label: 'Tab', finger: 'left-pinky', width: 1.5 },
      { id: 'q', label: 'Q', ruId: 'й', ruLabel: 'Й', finger: 'left-pinky' },
      { id: 'w', label: 'W', ruId: 'ц', ruLabel: 'Ц', finger: 'left-ring' },
      { id: 'e', label: 'E', ruId: 'у', ruLabel: 'У', finger: 'left-middle' },
      { id: 'r', label: 'R', ruId: 'к', ruLabel: 'К', finger: 'left-index' },
      { id: 't', label: 'T', ruId: 'е', ruLabel: 'Е', finger: 'left-index' },
      { id: 'y', label: 'Y', ruId: 'н', ruLabel: 'Н', finger: 'right-index' },
      { id: 'u', label: 'U', ruId: 'г', ruLabel: 'Г', finger: 'right-index' },
      { id: 'i', label: 'I', ruId: 'ш', ruLabel: 'Ш', finger: 'right-middle' },
      { id: 'o', label: 'O', ruId: 'щ', ruLabel: 'Щ', finger: 'right-ring' },
      { id: 'p', label: 'P', ruId: 'з', ruLabel: 'З', finger: 'right-pinky' },
      { id: '[', label: '[', ruId: 'х', ruLabel: 'Х', finger: 'right-pinky' },
      { id: ']', label: ']', ruId: 'ъ', ruLabel: 'Ъ', finger: 'right-pinky' },
      { id: '\\', label: '\\', finger: 'right-pinky', width: 1.5 },
    ],
    // Row 3: ASDF
    [
      { id: 'CapsLock', label: 'Caps Lock', finger: 'left-pinky', width: 1.75 },
      { id: 'a', label: 'A', ruId: 'ф', ruLabel: 'Ф', finger: 'left-pinky' },
      { id: 's', label: 'S', ruId: 'ы', ruLabel: 'Ы', finger: 'left-ring' },
      { id: 'd', label: 'D', ruId: 'в', ruLabel: 'В', finger: 'left-middle' },
      { id: 'f', label: 'F', ruId: 'а', ruLabel: 'А', finger: 'left-index' },
      { id: 'g', label: 'G', ruId: 'п', ruLabel: 'П', finger: 'left-index' },
      { id: 'h', label: 'H', ruId: 'р', ruLabel: 'Р', finger: 'right-index' },
      { id: 'j', label: 'J', ruId: 'о', ruLabel: 'О', finger: 'right-index' },
      { id: 'k', label: 'K', ruId: 'л', ruLabel: 'Л', finger: 'right-middle' },
      { id: 'l', label: 'L', ruId: 'д', ruLabel: 'Д', finger: 'right-ring' },
      { id: ';', label: ';', ruId: 'ж', ruLabel: 'Ж', finger: 'right-pinky' },
      { id: '\'', label: '\'', ruId: 'э', ruLabel: 'Э', finger: 'right-pinky' },
      { id: 'Enter', label: 'Enter', finger: 'right-pinky', width: 2.25 },
    ],
    // Row 4: ZXCV
    [
      { id: 'ShiftLeft', label: 'Shift', finger: 'left-pinky', width: 2.25 },
      { id: 'z', label: 'Z', ruId: 'я', ruLabel: 'Я', finger: 'left-pinky' },
      { id: 'x', label: 'X', ruId: 'ч', ruLabel: 'Ч', finger: 'left-ring' },
      { id: 'c', label: 'C', ruId: 'с', ruLabel: 'С', finger: 'left-middle' },
      { id: 'v', label: 'V', ruId: 'м', ruLabel: 'М', finger: 'left-index' },
      { id: 'b', label: 'B', ruId: 'и', ruLabel: 'И', finger: 'left-index' },
      { id: 'n', label: 'N', ruId: 'т', ruLabel: 'Т', finger: 'right-index' },
      { id: 'm', label: 'M', ruId: 'ь', ruLabel: 'Ь', finger: 'right-index' },
      { id: ',', label: ',', ruId: 'б', ruLabel: 'Б', finger: 'right-middle' },
      { id: '.', label: '.', ruId: 'ю', ruLabel: 'Ю', finger: 'right-ring' },
      { id: '/', label: '/', ruId: '.', ruLabel: '.', finger: 'right-pinky' },
      { id: 'ShiftRight', label: 'Shift', finger: 'right-pinky', width: 2.75 },
    ],
    // Row 5: Space
    [
      { id: 'ControlLeft', label: 'Ctrl', finger: 'left-pinky', width: 1.25 },
      { id: 'MetaLeft', label: 'Win', finger: 'left-thumb', width: 1.25 },
      { id: 'AltLeft', label: 'Alt', finger: 'left-thumb', width: 1.25 },
      { id: ' ', label: 'Space', finger: 'left-thumb', width: 6.25 },
      { id: 'AltRight', label: 'Alt', finger: 'right-thumb', width: 1.25 },
      { id: 'MetaRight', label: 'Win', finger: 'right-thumb', width: 1.25 },
      { id: 'ContextMenu', label: 'Menu', finger: 'right-pinky', width: 1.25 },
      { id: 'ControlRight', label: 'Ctrl', finger: 'right-pinky', width: 1.25 },
    ],
  ],
};
